### ISSUE TITLE
iOS build stopping after "Preparing Firebase on iOS"

### ISSUE THREAD

**Issue by 0x6C77** [dpa99c/cordova-plugin-firebasex#101]
Cordova exits after console log "Preparing Firebase on iOS" when building for iOS. Android builds are completing successfully.

Moving [this line](https://github.com/dpa99c/cordova-plugin-firebasex/blob/e47439927d88e9639eda5cb5ee6346c37123d936/scripts/after_prepare.js#L113) outside the IF seems to have fixed the issue. Builds are now completing and functioning as expected.

Is this going to break something further down the line? Is there a reason to now resolve if `IOS_STRIP_DEBUG` is not set?

**Comment by globules-io** [comment]
I have the same issue with 6.0.7 + iOS
Will downgrade to 6.0.6 and report here

**Comment by svzi** [comment]
I'm probably having the same issue. When I try to build for iOS, this is my console output (please keep an eye on the line breaks!):

```
> cordova prepare ios
Generating initial manifest for Ionic Deploy...
Ionic Deploy initial manifest successfully generated.
Preparing Firebase on iOS
ENOENT: no such file or directory, open '/Users/svzi/development/_own/ProjectName/app/platforms/ios/
		ProjectName
	.xcodeproj/project.pbxproj'
```
The file exists, but I guess it should be a one liner like:
```
/Users/svzi/development/_own/ProjectName/app/platforms/ios/ProjectName.xcodeproj/project.pbxproj
```

**Comment by globules-io** [comment]
I have downgraded to 6.0.6 but I had to update Catalina (b5) & Xcode (11b6). 
So with 6.0.6 I can't build from the shell as well. 
I can open the workspace and build the app right after I add the iOS platform (without running cordova build ios) and it builds the app properly (after setting dev team) and archive properly.

**Comment by svzi** [comment]
Using the XCode build is something I don't like and want to avoid. I usually build via CLI to improve the app performance (using AOT, optimizing, uglifying, ...).

**Comment by consciousimages** [comment]
@svzi I think your issue is different, Sven -- literally when building iOS, in this case Cordova outputs 

`Preparing Firebase on iOS`

Then quits silently, even when building with the `--verbose` flag.  

As stated above, Android builds fine.

Are you maybe seeing [this issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/114)?

**Comment by peterpeterparker** [comment]
Same here, tried to upgrade to v6.0.7 and the build stop/skip when reaching "Preparing Firebase on iOS"

Same, downgrading to v6.0.6 as workaround was ok

**Comment by svzi** [comment]
@consciousimages You were right, I really had another issue. The fix provided in the very first post here, let me build via cli again. So big thanks @0x6C77 !

**Comment by HendryZheng** [comment]
Have anyone found solution yet? I am facing similar issue.

**Comment by TdoubleG** [comment]
Same here...

**Comment by HendryZheng** [comment]
Seems need to downgrade like v6.0.6
Downgrade to v6.0.6 (ionic cordova plugin add cordova-plugin-firebasex@6.0.6)
works for me

**Comment by sun34133** [comment]
I have got the same issue i.e. cordova exits after console log "Preparing Firebase on iOS" when building for iOS. Android builds are working successfully.

Here is the output from the cordova output:

cordova-custom-config: Wrote file /../../xxxx-Info.plist
cordova-custom-config: Finished applying platform config
Executing script found in plugin cordova-plugin-firebasex for hook "after_prepare": plugins/cordova-plugin-firebasex/scripts/after_prepare.js
Preparing Firebase on iOS

Plugins versions etc:
<pre>Cordova version: 9.0.0 (cordova-lib@9.0.1)</pre>
<pre>cordova-ios@5.0.1</pre>

I have used cordova-plugin-androidx and cordova-plugin-androidx-adapter along with the  cordova-plugin-firebasex

**Comment by dpa99c** [comment]
Fixed by #121 which will be released shortly in v6.0.8

**Comment by mahnuh** [comment]
@dpa99c wondering when shortly will be? I am desperately waiting for some fixes from the master.

**Comment by dpa99c** [comment]
shortly is when I get around to it - I'm busy with other stuff
though donations might motivate me to do it faster 😛 
until then, you can install it directly from master
that's the nature of free open-source software

**Comment by mahnuh** [comment]
That's totally fine! Just wanted to know if I could wait for a npm package update or use the master. Thanks!

**Comment by JunyaoC** [comment]
I'm getting this issue also with version 9.1.1
Wondering is there any solution?

**Comment by mahnuh** [comment]
@JunyaoC not quite sure if it is the exact same problem, but I found that removing and reinstallig the plugin works for me. I also wrote a script to automate this task.
You can find it here: https://manuel-heidrich.dev/blog/a-fix-for-firebasecore-firebasecore-h-file-not-found-when-using-cordova-plugin-firebasex
Hope this helps you as well!

**Comment by JunyaoC** [comment]
Well I tried reinstalling the plugins too, even tried removing the iOS platform. The get around for me is to build using the cordova and then using the xcode workspace to distribute the app. The building process is pretty slow this way....

**Comment by salmanhasni** [comment]
> I'm getting this issue also with version 9.1.1 Wondering is there any solution?

@JunyaoC are you able to resolve this issue with 9.1.1 plugin ?

**Comment by Wolf00Bomber** [comment]
I am facing this issue in 16.0.0, anyone facing the same?
```
<plugin name="cordova-plugin-firebasex" spec="16.0.0">
        <variable name="FIREBASE_ANALYTICS_COLLECTION_ENABLED" value="false" />
        <variable name="FIREBASE_PERFORMANCE_COLLECTION_ENABLED" value="false" />
        <variable name="FIREBASE_CRASHLYTICS_COLLECTION_ENABLED" value="false" />
</plugin>
```
