### ISSUE TITLE
Cannot install plugin - Failed to install 'cordova-plugin-firebasex': undefined

### ISSUE THREAD

**Issue by Theunodb** [dpa99c/cordova-plugin-firebasex#106]
# Bug report

**Current behavior:**
Fails on installation

**Expected behavior:**
Should install sucsessfully 

**Steps to reproduce:**
cordova plugin add cordova-plugin-firebasex@6.0.6

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `ios 5.0.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-chooser 1.2.5 "Chooser"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filepath 1.5.6 "cordova-plugin-filepath"
cordova-plugin-firebasex 6.0.6 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"`
- Dev machine OS and version, e.g.
    - OSX
        - `ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87`

**Console output**
<details>
<summary>Installing "cordova-plugin-firebasex" for ios
Installing "cordova-plugin-androidx" for ios
Installing "cordova-plugin-androidx-adapter" for ios
Failed to install 'cordova-plugin-firebasex': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.</summary>

```

**Comment by Theunodb** [comment]
When i run platform add --verbose i get this:

`Install start for "cordova-plugin-firebasex" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `sources` - `https://github.com/CocoaPods/Specs.git`
Added source line for `https://github.com/CocoaPods/Specs.git`
Set pods.json for `libraries` - `Firebase/Core`
Added pod line for `Firebase/Core`
Set pods.json for `libraries` - `Firebase/Auth`
Added pod line for `Firebase/Auth`
Set pods.json for `libraries` - `Firebase/Messaging`
Added pod line for `Firebase/Messaging`
Set pods.json for `libraries` - `Firebase/Performance`
Added pod line for `Firebase/Performance`
Set pods.json for `libraries` - `Firebase/RemoteConfig`
Added pod line for `Firebase/RemoteConfig`
Set pods.json for `libraries` - `Fabric`
Added pod line for `Fabric`
Set pods.json for `libraries` - `Crashlytics`
Added pod line for `Crashlytics`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Failed to install 'cordova-plugin-firebasex': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.
        
        cordova platform add ios --verbose exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +24ms`

**Comment by Theunodb** [comment]
When downgrading to pods 1.7.5 the issue disappears

**Comment by dpa99c** [comment]
What version of cocoapods caused you the issue?
I want to find the first version which causes it so I can document a maximum version requirement of cocoapods until this is properly resolved...

**Comment by mesqueeb** [comment]
I just want to chip in, I have this error:
```
Install start for "cordova-plugin-firebasex" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `sources` - `https://github.com/CocoaPods/Specs.git`
Added source line for `https://github.com/CocoaPods/Specs.git`
Set pods.json for `libraries` - `Firebase/Core`
Added pod line for `Firebase/Core`
Set pods.json for `libraries` - `Firebase/Auth`
Added pod line for `Firebase/Auth`
Set pods.json for `libraries` - `Firebase/Messaging`
Added pod line for `Firebase/Messaging`
Set pods.json for `libraries` - `Firebase/Performance`
Added pod line for `Firebase/Performance`
Set pods.json for `libraries` - `Firebase/RemoteConfig`
Added pod line for `Firebase/RemoteConfig`
Set pods.json for `libraries` - `Fabric`
Added pod line for `Fabric`
Set pods.json for `libraries` - `Crashlytics`
Added pod line for `Crashlytics`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Failed to install 'cordova-plugin-firebasex': undefined
CordovaError: Promise rejected with non-error: 'The CocoaPods repo has not been synced yet, this will take a long time (approximately 500MB as of Sept 2016). Please run `pod setup` first to sync the repo.'
    at /usr/local/lib/node_modules/cordova/bin/cordova:29:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by andysousa** [comment]
Remove both the plugin and the iOS platform. Add the plugin, then add iOS platform back

**Comment by dpa99c** [comment]
The Cocoapods version issue appears to have been resolved by PR https://github.com/dpa99c/cordova-plugin-firebasex/pull/173.
Using `cordova-plugin-firebasex@7.0.0` and `cocoapods@1.8.4`, the Pods are installed successfully without error.

**Comment by swpaek77** [comment]
Try installing without using the sudo command
