### ISSUE TITLE
viable solution for older versions of cordova?  cordova-android@8 and cordova@8 possibly?

### ISSUE THREAD

**Issue by josh-m-sharpe** [dpa99c/cordova-plugin-firebasex#112]
Is there any viable solution for versions < cordova@9 and possibly even < cordova-andrioid@8 ?

I see there was a lot of work done over here as well, specifically to support several versions of cordova-android (7 8 and 9): 
https://github.com/wizpanda/cordova-plugin-firebase-lib/commit/154596ab8545dd1df7e241b3313ecadc026c7afc

i'm trying to install some older versions of cordova-plugin-firebase-lib to see if that ends getting anywhere, but there seems to be *so* much change with these androidx plugins as well.

Is there any advise for folks that can't wholesale adopt cordova@9 at this point?

Thanks!

**Comment by sagrawal31** [comment]
Latest version does not support the old versions of `cordova` and `cordova-android`. By the way, you can always use it's old version but you are not going to get the latest fixes & improvements.

And you can also use the Wizpanda's repo but please note **that repo is no longer maintained**.

**Comment by dpa99c** [comment]
There are no plans to support older versions of Cordova components
