### ISSUE TITLE
Data collection is enabled during plugin initialization in Android

### ISSUE THREAD

**Issue by msimkunas** [dpa99c/cordova-plugin-firebasex#116]
# Bug report

**Current behavior:**

The `android` version of the plugin seems to call the `setAnalyticsCollectionEnabled` method during plugin initialization: https://github.com/dpa99c/cordova-plugin-firebasex/blob/f3f223dea4ef65256cb1e2f77a246280f866219a/src/android/FirebasePlugin.java#L94

Is this really necessary? This makes data collection opt-out by default which may not be desired in certain contexts.

**Expected behavior:**
The collection of analytics data should not be enabled during the initialization of the plugin.

**Steps to reproduce:**
Simply run the plugin on an Android device.

**Screenshots**
N/A.

**Environment information**
N/A.

**Other information:**
The iOS version of the plugin doesn't seem to call this method during its initialization.

**Comment by consciousimages** [comment]
Here's the way you can turn it off:

https://github.com/dpa99c/cordova-plugin-firebasex/issues/79[https://github.com/dpa99c/cordova-plugin-firebasex/issues/79](url)

**Comment by msimkunas** [comment]
I'm aware of these settings. They don't solve the problem, however.

Setting `firebase_analytics_collection_enabled` to `false` only disables the data collection temporarily which means that it is only disabled until the very first run of `setAnalyticsCollectionEnabled` with `true` as its first argument.

For some reason, this particular method call is hard-coded in the initialization code of this plugin, thus forcing the collection of analytics data before I can even obtain the necessary consent from the user.

To prevent the introduction of a breaking change the issue can be solved by enabling the data collection based on the existence of a `firebase_analytics_collection_enabled` key in the Android manifest.

If the key exists and its value is set to `false`, the data collection should be disabled in the plugin initialization code by either passing `false` to `setAnalyticsCollectionEnabled` or skipping the method call altogether.

Otherwise, if the key doesn't exist or its value is set to `true` the current functionality should be preserved which is to enable the data collection right away.
