### ISSUE TITLE
iOS App store rejection due to permissions issues

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#117]
converting to `cordova-plugin-firebasex` and the use of Cocoapods (at least the current upgraded version) added a Pods-myAPP-Info.plist file that shows the use of 8 new permissions.  Do I need to keep these in place or can I remove them?  What in Pods or Firebase requires the use of these permissions?  My app doesn't actually require them but they are causing my app to be rejected from the iOS App store for the following reasons:

> ITMS-90683: Missing Purpose String in Info.plist
> 
> Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more 

My app is being rejected for 6 of these, specifically:

> NSContactsUsageDescription 
> NSCalendarsUsageDescription 
> NSPhotoLibraryUsageDescription 
> NSBluetoothPeripheralUsageDescription 
> NSMicrophoneUsageDescription 
> NSMotionUsageDescription 

If these are needed then maybe the Firebasex documentation can make a note about these iOS permissions in the `pods` section about why they are needed and what users must do to avoid the conflict.  

I know simply adding the key/string values to my main Info.plist file should resolve the issue, however I am more concerned about suddenly my app has references to all these permission services  when my app doesn't actually need or use them at all.

**Comment by rolinger** [comment]
Well, never ran into this before, but found all the correct documentation regarding Cocaopods - wish I knew all this before installing Pods so I could set the Permissions config file before implementing.  

https://cocoapods.org/pods/Permission

**Comment by consciousimages** [comment]
I'm somewhat surprised to read about this, my app is nearing submission and I would have been shocked as well. I have seen dialogs in Android about permissions I didn't need, but didn't know which plugin was the culprit and disregarded as I thought it was an Android thing.

So even though your iOS app got rejected, the excessive permissions are also present in Android is what I'd guess and therefore both platforms need to be addressed.

**Comment by rolinger** [comment]
The problem I have now is getting rid of these permissions.  According to cocoapods you need to add the `PermissionsConfiguration.xcconfig` to the root of your project and in that config file comment out the permissions you don't want to be implemented into your project.  By default they should turn all of them off and force you go to only turn on the ones you need.  I can't find any solid documentation on how to remove them from an existing project though without having to wipe things out and start over again.

**Comment by consciousimages** [comment]
I checked my Pods-myAPP-Info.plist file, I'm using 6.0.6 (couldn't build using 6.0.7) but I don't see any of these permissions in that file.  Might it be another plugin requesting them?

**Comment by rolinger** [comment]
@consciousimages - in Xcode `myApp.xcworkspace`, under workspace Pods/Targets Support Files/Pods-myApp/Pods-myApp-Info.plist

Which looks like it translates to physical path of:

`/path/myApp/platforms/ios/Pods/Target Support Files/Pods-myApp/Pods-myApp-Info.plist`

You are on Pods 6.0.6?  I just did the most recent update and it says I am on 1.7.5 - thats wwaayy off.  I just followed the pods install directions in this plugin and did all the updates...so don't understand why mine would be off.

**Comment by rolinger** [comment]
@consciousimages - not certain what you are looking at, but I just checked cocoapods main repository, and my version is correct as v1.8 is in beta now.

**Comment by rolinger** [comment]
@consciousimages - so all those plugins were not coming from cocoapods, it took me a while to find where they were coming from.  And ironically, they were coming from another one of @dpa99c plugins - `cordova.plugins.diagnostic` .  My previous builds of my app were using an older version of the `diagnostics` plugin but the most recent build of my app uses the latest version of the `diagnostics` plugin - which now auto-includes all of the above permissions unless you specify BEFORE that plugin install the specific iOS permissions NOT to include.   this is a big change from previous versions of the `diagnostic` plugin.

I assumed they were coming from pods because 1) changing to `cordova-plugin-firebasex` was the only plugin change I made between older version of app and new version - and `firebasex` requires the cocoapods installation and 2) all the iOS permissions were only existing in the `Pods-myApp-Info.plist` file - so those two things combined made me think pods was adding those iOS permissions.
