### ISSUE TITLE
Crashlytics for ios is missing stacktrace

### ISSUE THREAD

**Issue by kirilmicev** [dpa99c/cordova-plugin-firebasex#118]
In FirebasePlugin.m file when generating userInfo with stack trace you are using entry[@"source"] but it doesn't have value and nothing is sent to crashlytics.

I experimented and if you are using something like this will get a full stack trace

[entry[@"functionName"] stringByAppendingFormat:@" %@ %@", entry[@"fileName"], entry[@"lineNumber"]];

**Comment by dpa99c** [comment]
@sagrawal31 Any ideas on this?
I believe this code was brought across from your fork in https://github.com/dpa99c/cordova-plugin-firebasex/commit/e2e32fe9ef445bfb4e13b3e4e50f223f05c634d7 to resolve #57

**Comment by sagrawal31** [comment]
Yes, @dpa99c I copied from our fork and it should work. I'll cross-check it by EOD.

**Comment by dpa99c** [comment]
Thanks, much appreciated 👍

**Comment by dpa99c** [comment]
@sagrawal31 could you take a look at this when you get a moment?

**Comment by sagrawal31** [comment]
Yes @dpa99c I didn't get time last week. I'll debug this by tomorrow.

**Comment by sagrawal31** [comment]
Sorry, this is past a month 😄. But I did try this and seems it's working for me.

**Comment by dpa99c** [comment]
I can confirm the current implementation works correctly after debugging in Xcode

![Screenshot 2019-10-24 at 11 10 07](https://user-images.githubusercontent.com/2345062/67476213-7a869380-f64f-11e9-9840-03c59dbb7cc9.png)

**Comment by dpa99c** [comment]
Note: the above commit resolves this by ensuring the stacktrace appears in the "Stack trace" area of the Crashlytics console instead of in the "Keys" section.
<br/><img src="https://user-images.githubusercontent.com/2345062/68040833-09865200-fcc7-11e9-8c4a-18c9485c4186.png"/>
