### ISSUE TITLE
Unable to install firebasex pods error

### ISSUE THREAD

**Issue by abomadi** [dpa99c/cordova-plugin-firebasex#120]
Installing firebasex on ios gives a broken pods:

``` 
Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-firebasex on ios platform only.
No scripts found for hook "before_plugin_install".
Install start for "cordova-plugin-firebasex" on ios.
Beginning processing of action stack for ios project...
Action stack processing complete.
pods.json found in platforms/ios
Podfile found in platforms/ios
Adding pods since the plugin contained <podspecs>
Set pods.json for `declarations` - `use_frameworks!`
Added declaration line for `use_frameworks!`
Set pods.json for `libraries` - `Firebase/Core`
Added pod line for `Firebase/Core`
Set pods.json for `libraries` - `Firebase/Auth`
Added pod line for `Firebase/Auth`
Set pods.json for `libraries` - `Firebase/Messaging`
Added pod line for `Firebase/Messaging`
Set pods.json for `libraries` - `Firebase/Performance`
Added pod line for `Firebase/Performance`
Set pods.json for `libraries` - `Firebase/RemoteConfig`
Added pod line for `Firebase/RemoteConfig`
Set pods.json for `libraries` - `Fabric`
Added pod line for `Fabric`
Set pods.json for `libraries` - `Crashlytics`
Added pod line for `Crashlytics`
Wrote to pods.json.
Wrote to Podfile.
Running `pod install` (to install plugins)
Running command: pod install --verbose
==== pod install start ====

  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TransformMe`: (``)

Finding Podfile changes
  A Crashlytics
  A Fabric
  A Firebase
  - Firebase

Resolving dependencies of `Podfile`

[!] CocoaPods could not find compatible versions for pod "Firebase/Analytics":
  In snapshot (Podfile.lock):
    Firebase/Analytics (= 6.1.0, ~> 6.1.0)

  In Podfile:
    Firebase/Analytics (~> 6.1.0)

None of your spec sources contain a spec satisfying the dependencies: `Firebase/Analytics (~> 6.1.0), Firebase/Analytics (= 6.1.0, ~> 6.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

Command finished with error code 31: pod install,--verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
pod: Command failed with exit code 31
Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

```
Ionic:

   Ionic CLI          : 5.0.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.1, (and 27 other plugins)

Utility:

   cordova-res : 0.5.2
   native-run  : 0.2.5

System:

   Android SDK Tools : 26.1.1 (/Users/me/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v12.4.0 (/usr/local/Cellar/node/12.4.0/bin/node)
   npm               : 6.9.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8
```

Update ==================== >
it looks the plugin conflicts in somehow with 

- cordova-support-google-services

- cordova-plugin-firebase-inappmessaging

- cordova-plugin-google-analytics

when i remove the above plugins and then installed firebasex again, the build finished but with errors in pods, however i opened the xcode and build it from there it did work. not sure what shall i do next to build the project using cordova cmd line

**Comment by abomadi** [comment]
@dpa99c any idea mate ?

**Comment by sagrawal31** [comment]
Can you first remove other 3 plugins and then try building it again.

**Comment by abomadi** [comment]
@sagrawal31 now i have this 
`> cordova build ios
Overwriting existing resource file at platforms/ios/TransformMe/Resources/GoogleService-Info.plist
Preparing Firebase on iOS`
and it stops building

**Comment by abomadi** [comment]
@sagrawal31 Installed Plugins
`branch-cordova-sdk 3.2.0 "branch-cordova-sdk"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 5.0.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 6.0.7 "Google Firebase Plugin"
cordova-plugin-freshchat 1.2.0 "Freshchat plugin for Phonegap"
cordova-plugin-geolocation 3.0.0 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-purchase 8.1.1 "Purchase"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.5 "SocialSharing"
cordova-plugin-youtube-video-player 2.3.0 "CordovaYoutubeVideoPlayer"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
onesignal-cordova-plugin 2.5.2 "OneSignal Push Notifications"`

**Comment by dpa99c** [comment]
@abomadi have you ([as documented](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods)) run `pod repo update` in `platforms/ios`?

**Comment by abomadi** [comment]
@dpa99c Yes Sir, without any success, however when it reaches **Preparing Firebase on iOS** i still can build the app after that from xcode correctly

**Comment by dpa99c** [comment]
I've published a new version of the plugin - v6.1.0 - please regression test with that version.

If you still encounter problems in your project, please try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) to validate your build environment and rule out other causes in your project such as conflict with other plugins.

**Comment by abomadi** [comment]
@dpa99c Many thanks for the huge time and support you are giving here, i confirm the newer version is working with the phone being attached or not.

But for the record i have found a detailed error coming now from **cordova-plugin-youtube-video-player** along side with firebasex that breaks the build. below is the error details just for reference

`/Users/me/Desktop/Projects/transformme-2.1/platforms/ios/app/Plugins/cordova-plugin-youtube-video-player/YoutubeVideoPlayer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Command finished with error code 65: xcodebuild -workspace,app.xcworkspace,-scheme,TransformMe,-configuration,Debug,-destination,generic/platform=iOS,-archivePath,app.xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/me/Desktop/Projects/app-2.1/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/me/Desktop/Projects/app-2.1/platforms/ios/build/sharedpch
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
    at ChildProcess.whenDone (/Users/me/Desktop/Projects/app-2.1/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

**Comment by coreyroth** [comment]
I've been running into this error today as well with 6.1.0 in one one my projects.  The sample project does install and build iOS for me ok though.  That means it's something specific to my project but I have no idea what.  I've removed my platforms, tried the pod commands and I've removed every plugin I have to see if there is a conflict.  Looking at my versions, they are very similar to the example up there.  I'm building from Catalina but like I said the sample project works fine.  I'm not sure what to try next.

**Comment by Crypt0Graphic** [comment]
I had this error when i had installed cordova-plugin-firebase-dynamiclinks. Then i found a workaround and updated pplatforms/ios/podfiles as:

	pod 'Firebase/Analytics', '~> 6.13.0'
	pod 'Firebase/DynamicLinks', '~> 6.13.0'

Then it's ok. I could install and build FirebaseX. Be careful about versions in podfile.

**Comment by dd-stoyanova** [comment]
go to **platforms/ios** directory
run the command
**pod install --repo-update**

**Comment by shrihans** [comment]
Hi,

I have tried above solutions but I am still getting this error.

I am using following version:
"cordova-plugin-firebasex": "^9.1.1",

When I try:
pod install --repo-update

I get following errors:

`[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In Podfile:
    Firebase/Firestore (= 6.23.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Firestore (= 6.23.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by anubhavkamath** [comment]
Same issues here. Going around in circles with the errors. For each of the "solutions" posted here I get different errors including the one for the repo updated posted above.

**Comment by reinaldoborin** [comment]
> go to **platforms/ios** directory run the command **pod install --repo-update**

This work with a problem.

All plugins after cordova-plugin-firebase-x doenst install.

I am doing:

```
cordova platform rm ios
cordova platform add ios@6.0.0
```
Get the same error of this issue.
```
cd platforms/ios
pod deintegrate
rm Podlock.file
pod install --repo-update
ionic cordova prepare ios
```

I can build, but all plugins after firebase-x doenst work anymore.

**Comment by YRafalsky** [comment]
Btirise project. Same issue.
update <engine name="ios" spec="5.1.1" /> to <engine name="ios" spec="6.2.0" /> helped with firebasex 15.0.0 installation failure.
offtopic: After that i removed cordova-plugin-wkwebview-engine because you don't need it in cordova-ios 6.2.0 (and it spawns errors if you leave it in project)
