### ISSUE TITLE
Not getting any analytics data in firebase

### ISSUE THREAD

**Issue by Ross-Rawlins** [dpa99c/cordova-plugin-firebasex#122]
# Bug report

**Current behavior:**
I have the plugin installed with all the steps followed and enabled. I have setAnalyticsCollectionEnabled set to true but I dont see any data in firebase.

I dont see any issues in the console and I am note sure how I can try log these to make sure the calls are actually being made. It doesnt show screens or events.

**Expected behavior:**

I should be seeing any/some data in firebase including current active users which comes up as 0.
**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	  android 8.0.0
  ios 5.0.1
- Plugins & versions installed in project (including this plugin)
   cc.fovea.cordova.purchase 8.1.1 "Purchase"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 6.0.7 "Google Firebase Plugin"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-multidex 1.0.0 "Multidex"
- Dev machine OS and version, e.g.
OS - Mojave
_Runtime issue_
- Device details
    - _e.g. Running on Samsung S8
- OS details
    - _e.g. Android 9.0_	

**Related code:**
```
this.platform.ready().then(() => {
            if (this.platform.is('cordova')) {
                this.firebase.setAnalyticsCollectionEnabled(true)
}
})
 this.firebase.setScreenName('test')

```

**Console output**
<details>
<summary>console output</summary>

```

No issues are logged

```

</details><br/><br/>

**Other information:**

**Comment by microsmsm** [comment]
I have the same problem

**Comment by JoseGeorges8** [comment]
This issue was close, yet I don't see a solution for it. I'm having the same issue atm

**Comment by hanslbua** [comment]
Same here. There is no data in the Streamview on Firebase / Realtime on Analytics.
