### ISSUE TITLE
setBadgeNumber not working

### ISSUE THREAD

**Issue by michelsondan** [dpa99c/cordova-plugin-firebasex#124]
I am trying to set badge with my app logic, and it is not working. it's reseting the current badge.

` window.FirebasePlugin.setBadgeNumber(myCount, function () {
              alert('success')
            },
            function (err) {
              alert(err)
            })

the function is running and display the alert 'success' on done event, but the badge is not set to my request number.

**Comment by dpa99c** [comment]
Please try building & running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate the cause of issue being in your own code.

If you are able to reproduce the issue in the example project, please complete the issue template to provide full details of the issue such as affected platform/version, etc.

**Comment by michelsondan** [comment]
I have tested it also with example project.
I see in log, that it is increment, but no badge number on app icon. 
after sending push notification, I see the badge number set by system, 
but after click on the button "Increment badge number", the badge is disappeared.

![Screenshot_2019-08-30-15-52-52-166_il homely mls app](https://user-images.githubusercontent.com/22793811/64022537-24114300-cb3f-11e9-9725-cffb459ba448.png)
![IMG_20190830_155449](https://user-images.githubusercontent.com/22793811/64022550-2d021480-cb3f-11e9-92a8-5d6672951993.jpg)

Tested on Android Redmi Note 4
Android system NRD9OM 7.0

Thank You!

**Comment by dpa99c** [comment]
OK, thanks for the info, I will add to list for investigation

**Comment by dpa99c** [comment]
Upon investigation, the [library](https://github.com/leolin310148/ShortcutBadger) used by this plugin to set the badge number on Android will not work on Android 8 and above.
[As stated here](https://stackoverflow.com/a/52037647/777265), there's no way to programmatically set the badge number on Android 8+ without sending/displaying a notification. 

Therefore I'm going to remove `setBadgeNumber()` and `getBadgeNumber()` from the Android implementation and make them iOS-only methods.

**Comment by michelsondan** [comment]
What is the logic of this? lot of time users entering to app by ignoring the popup notification, and the app should have the way to change the badge icon by internal logic that depend on user action.
this is bad.
must be a way.
Are all plugins not supporting badge?

**Comment by dpa99c** [comment]
As [the StackOverflow post I've referenced makes clear](https://stackoverflow.com/q/52036912/777265), there is no way to modify the badge icon count on Android 8 and above without displaying a notification. 
However if you think there's a way to do this, please feel free to implement it and make a pull request to add the functionality to this plugin.

**Comment by michelsondan** [comment]
This StackOverflow post don't seem to be Official answer.
