### ISSUE TITLE
iOS wont build

### ISSUE THREAD

**Issue by AidanDaniel97** [dpa99c/cordova-plugin-firebasex#128]
I have just come from uninstalling the original firebase Cordova plugin to replace it with this one. I have installed it via the command: 
`cordova plugin add cordova-plugin-firebasex`
and I have run:
```
cordova platfrom add ios 
cordova platform add android 
```

and all is fine when i build android but on ios it just gives me one line 'Preparing Firebase on iOS' and then cancels out of the build. even in --debug it says the same. 

I also tried running through these commands to remove everything and add it back in 

```
rm -Rf platforms/android
cordova plugin rm cordova-plugin-firebasex
cordova plugin rm cordova-plugin-firebase
rm -Rf plugins/ node_modules/
npm install
cordova plugin add cordova-plugin-firebasex
cordova platform add android
```

**Comment by mitconcept** [comment]
I have the same issue. Can anyone help? I have tried cleaning the project(removing plugins and node_modules), reinstalling. I previously had the cordova-plugin-firebase-lib and it broke.
I have an Ionic build.
ionic info:
   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.3

Cordova:
   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1

System:
   Android SDK Tools : 26.1.1 (/Users/nikoschrysis/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.11.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8

**Comment by dpa99c** [comment]
See #101. 
This is fixed on master so install direct from there until v6.0.8 is released to npm.

**Comment by AidanDaniel97** [comment]
> See #101.
> This is fixed on master so install direct from there until v6.0.8 is released to npm.

Ah, sorry I did try finding this issue but nothing came up - I will give that a go thanks very much

**Comment by TheSegfault** [comment]
Thanks for the rapid answer, much appreciated !

**Comment by TheSegfault** [comment]
I now get stuck during ProcessPCH phase of ios build, I am just writing it down here if you guys get stuck here too, but It might just be me and some other code not related to firebasex

**Comment by dpa99c** [comment]
If you're building with ionic, try `ionic cordova prepare ios && cordova build ios` instead of `ionic cordova build ios` - when I encountered build freezes, it was only via Ionic CLI, not Cordova CLI.

**Comment by guigons** [comment]
> I now get stuck during ProcessPCH phase of ios build, I am just writing it down here if you guys get stuck here too, but It might just be me and some other code not related to firebasex

Same Here! I'm using de latest version.

**Comment by guigons** [comment]
> If you're building with ionic, try `ionic cordova prepare ios && cordova build ios` instead of `ionic cordova build ios` - when I encountered build freezes, it was only via Ionic CLI, not Cordova CLI.

Thanks a lot! Works perfectly!
