### ISSUE TITLE
[FEATURE] Background data notification with background handler on iOS

### ISSUE THREAD

**Issue by jeancaffou** [dpa99c/cordova-plugin-firebasex#129]
Sending `content-available: 1` in `apn` data field supposedly invokes a background callback handler. As described in: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

In this plugin documentation it says:

> iOS data message notifications
> On iOS:
> ...
> **Data messages that arrive while your app is not running will NOT be received by your app!**

With the `content-available: 1` they should be received.

Having this feature would be great for running background tasks without displaying system notification on iOS (on Android this already works)

**Comment by joel-caton** [comment]
I've been testing this.. This worked for me only after switching from the legacy api to fcm v1...  Have been able to get data from the notification in background as well.  Will see how this works in the long run but so far great work @dpa99c

**Comment by giladrom** [comment]
@joel-caton Can you show a sample FCM payload? I've been trying the following but doesn't seem to trigger the app callback: 

```
const message = {
      notification: {
        title: 'Test Title',
        body: 'Test Body'
      },
      token: dest,
      "apns": {
        "payload": {
          "aps": {
            "sound": "default",
            "badge": 1,
            "content-available": 1
          }
        }
      }
    };

 admin
      .messaging()
      .send(message, false)
      .then(function (response) {
        console.log('Successfully sent message:', JSON.stringify(response));
        resolve(response);
      })
      .catch(function (error) {
        console.log('Error sending message:', JSON.stringify(error));
        reject(error);
      });
```

**Comment by joel-caton** [comment]
@giladrom Sorry for the slow response.. I've been slammed on another project.. Just now getting back into this one.  
1st be sure you can send a regular push notification and receive it with your app in the foreground.  2nd Replace content-available with content_available.
3rd Remove everything extra aside from the content_available and if it works build from there.  You'll really need to read close on the documentation here, on firebase, and at apple.  
It's a bit more to juggle then just sending through apple but should be easier to manage in the long run.

**Comment by trung-pham** [comment]
> @giladrom Sorry for the slow response.. I've been slammed on another project.. Just now getting back into this one.
> 1st be sure you can send a regular push notification and receive it with your app in the foreground. 2nd Replace content-available with content_available.
> 3rd Remove everything extra aside from the content_available and if it works build from there. You'll really need to read close on the documentation here, on firebase, and at apple.
> It's a bit more to juggle then just sending through apple but should be easier to manage in the long run.

i tried to send a notification via test project with payload like the image below. The problem is i saw my app log the message and it showed up on notification center but no callback is received on the js side. Have you encounter this problem?

![image](https://user-images.githubusercontent.com/41943021/95494663-72427800-09c8-11eb-8b99-42e5caaef911.png)
