### ISSUE TITLE
iOS push capabilities

### ISSUE THREAD

**Issue by luboslav** [dpa99c/cordova-plugin-firebasex#130]
I have successfully installed plugin but the notification does not work until I enable Push Notification capabilities via Xcode. Is it possible to configure this during plugin installation ?

<details>
<summary>Setup</summary>  
Platform: iOS

Plugin version: 6.1.0
</details>

**Comment by dpa99c** [comment]
No, it's not possible to change Xcode project capability settings programmatically.

**Comment by luboslav** [comment]
I found that cordova-plugin-googleplus does it via custom cordova [hook](https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/hooks/ios/install_entitlements.js).

**Comment by dpa99c** [comment]
That hook doesn't modify the Xcode project capabilities, it just adds the keychain sharing entitlements - this plugin adds the APNS entitlements [directly via the plugin.xml](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L100) without need of a hook script.

**Comment by luboslav** [comment]
Thanks for clarification.

**Comment by stefano24** [comment]
> That hook doesn't modify the Xcode project capabilities, it just adds the keychain sharing entitlements - this plugin adds the APNS entitlements [directly via the plugin.xml](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L100) without need of a hook script.

Hi, i've the same problem, push capability is not enabled.
On iOS platform output i can see both .plist that you refer to ("platforms/ios/APP_NAME/Entitlements-Debug.plist" and "platforms/ios/APP_NAME/Entitlements-Release.plist") with aps-environment setting.
If i enabled push capability from XCode it set aps-environment setting into "platforms/ios/APP_NAME/Resources/APP_NAME.entitlements" and push notifications is working.
I've also cordova deep-link plugin (maybe create conflict) that set associated-domains setting into that file.
How can i force the aps setting into the entitlements file?

**Comment by alesrosina** [comment]
Any other suggestion how we could build the app without manually checking that option in Xcode? 

Especially interested since we are using ionicframework's applflow builds, where access to xcode is not an option.
