### ISSUE TITLE
Not receiving notifications on iphone

### ISSUE THREAD

**Issue by mishkeTz** [dpa99c/cordova-plugin-firebasex#133]
Hi guys,
I have been trying for several hours to make this working but without success.

Cordova
`9.0.0 (cordova-lib@9.0.1)`

IOS Platform
`ios@5.0.1`

I installed cordova-plugin-firebase, added ios platform and then inside platforms/ios I ran `pod install` it seems it installed all necessary dependencies:

    Analyzing dependencies
    Downloading dependencies
    Using Crashlytics (3.12.0)
    Using Fabric (1.9.0)
    Using Firebase (6.3.0)
    Using FirebaseABTesting (3.0.0)
    Using FirebaseAnalytics (6.0.2)
    Using FirebaseAnalyticsInterop (1.4.0)
    Using FirebaseAuth (6.1.2)
    Using FirebaseAuthInterop (1.0.0)
    Using FirebaseCore (6.0.3)
    Using FirebaseInstanceID (4.2.4)
    Using FirebaseMessaging (4.1.1)
    Using FirebasePerformance (3.1.0)
    Using FirebaseRemoteConfig (4.1.0)
    Using GTMSessionFetcher (1.2.2)
    Using GoogleAppMeasurement (6.0.2)
    Using GoogleToolboxForMac (2.2.1)
    Using GoogleUtilities (6.2.5)
    Using Protobuf (3.9.0)
    Using nanopb (0.3.901)
    Generating Pods project
    Integrating client project
    Sending stats
    Pod installation complete! There are 7 dependencies from the Podfile and 19 total pods installed.

Then I opened platforms/ios/*.xcworkspace file and the project opened correctly. Then I ran the build on my iphone and I opened the application and allowed the notifications but then when I tried to send notification to my token or to that ios application using firebase I never received any.
I don't know why it doesn't work nor how to debug it, because I don't know where the error might be.

Also when adding a platform this was in the console as a output and might mean something:
`Installing "cordova-plugin-androidx-adapter" for ios
Running command: pod install --verbose

`[!] The T and T kids [Debug] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-T and T kids/Pods-T and T kids.debug.xcconfig'. This can lead to problems with the CocoaPods installation`

`[!] The T and T kids [Release] target overrides the LD_RUNPATH_SEARCH_PATHS build setting defined in Pods/Target Support Files/Pods-T and T kids/Pods-T and T kids.release.xcconfig'. This can lead to problems with the CocoaPods installation`

I uploaded the cert to firebase ios project, it's not the first time I am making an app that uses firebase and cordova, but right now I don't know what to do here.

**Comment by dpa99c** [comment]
Try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and set its package ID to the one for your own app so the provisioning profile is correct and use the `GoogleService-Info.plist` for your own project. Then use the built-in FCM API client in the test project or the Firebase Console to send test messages. That should help validate your APNS configuration independently of your codebase.

**Comment by mishkeTz** [comment]
Thanks to the error message I received in terminal when I tried to send a notification using the example project I figure out that I had the wrong cert/Key ID uploaded to my firebase project. Great.
