### ISSUE TITLE
Receive Notification when app is closed

### ISSUE THREAD

**Issue by pilz97** [dpa99c/cordova-plugin-firebasex#134]
Hello,

first of all the plugin works fine , as long my is not closed.
I am receiving the notification when app is in background as well when app is in foreground!

But when i kill the app and send a notification it does not show the notification.

Does anyone have an idea what could be the problem?

The problem occurs on android.
Cordova 9.0.0
plugin version: 6.1.0
cordova-android: 8.0.0

**Comment by dpa99c** [comment]
Please build and run the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex) to verify the problem is not in your implementation.

**Comment by martysaxton** [comment]
I am seeing something similar:  the app receives notifications in the foreground.  While backgrounded, notifications do not trigger the the popup in the Notification Center.  When I manually foreground the app, my callback will then get called with the queued up notification.

I tried the example project app and it does function correctly.  The thing that's missing is the plugin isn't setting the Push Notification capability correctly in my app. When I open my app in XCode and manually enable push notifications, everything works perfectly.  I noticed that this plugin is setting the 'aps-environment' setting in Entitlements-Debug.plist and Entitlements-Release.plist.  For my project, when I manually set the Push Notifications capability in XCode, it adds the aps-environment in a different file:  ( resources/<ProjectName>.entitlements).

I'm still not sure why the iOS project generated in cordova-plugin-firebasex-test works fine (uses Entitlements-*.plist) but the iOS project genererated for my app  uses a different file for entitlements.

**Comment by dpa99c** [comment]
@martysaxton this issue relates to Android whereas yours relates to iOS.
As to why your project does not work and the example project does, I cannot say but I advise comparing one against the other.

**Comment by dpa99c** [comment]
Closing as no response from OP

**Comment by ardabeyazoglu** [comment]
Hello @dpa99c, I have the same issue and reproduced it in the example app. I can only test it on android for now. It works normally except when the app is completely killed. Tried sending notification message from firebase console and by using fcm v1 api, same results.

My payload is as follows:
```json
"notification" => [
                "title" => $data["title"],
                "body" => $data["body"],
],
"data" => [
                "key" => "value"
]

**Comment by dpa99c** [comment]
@ardabeyazoglu it seem this is dependent on which device you are testing and is down to the behaviour of the Firebase SDK on Android - this plugin has no influence on that.
Please see [this thread](https://github.com/firebase/quickstart-android/issues/368) for further details.

**Comment by ardabeyazoglu** [comment]
@dpa99c thanks for quick response. I just switched from phonegap-push-plugin and it used to work before. Can't find a logical reason for this problem.
