### ISSUE TITLE
Ionic compatible plugin

### ISSUE THREAD

**Issue by millerf** [dpa99c/cordova-plugin-firebasex#135]
Last time I checked the ionic-plugin-firebase wasn't compatible with this librairy. The API is slightly different from `cordova-plugin-firebase` if I remember well...

Is there by any chance anyone working on one?

**Comment by RobinGiel** [comment]
@millerf this plugin as an updated version forked from the cordova-plugin-firebase. Use this plugin instead of the cordova-plugin-firebase. cheers

**Comment by millerf** [comment]
@robingiel I was talking about the `ionic` wrapper. 

`ionic-native/firebase`

I am not sure `firebasex` is a "plug and play" replacement...

**Comment by millerf** [comment]
Nevermind. I just read that and it answers my question:

[Ionic 4 and firebasex](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/README.md#ionic-4)
