### ISSUE TITLE
Application doesn't open when the Push Notification is clicked

### ISSUE THREAD

**Issue by alexandreguertin** [dpa99c/cordova-plugin-firebasex#136]
# Bug report

**Current behavior:**

Application doesn't open when the Push Notification is clicked.

**Expected behavior:**

The application should open when the Push Notification is clicked.

**Steps to reproduce:**

1. Send a Push Notification via Firebase.
2. Click on the Push Notification.

**Environment information**

- Cordova CLI version 
	9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	Android

**Comment by josegomez** [comment]
I concur with this bug, have the same issue.

**Comment by dpa99c** [comment]
As demonstrated by [this screencapture](https://www.youtube.com/watch?v=qLPhan9YUhQ&feature=youtu.be) using the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test), tapping an Android system notification while the app is not running/in the background should launch the app.

Please build and run the example project app and confirm this works correctly for you.

Note that when a system notification is tapped, the Android OS is responsible for launching the application - no application (i.e. plugin) code is executed at this point - the payload of the notification is simply forwarded to the application as a launch intent either [at app startup](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L86) if the app wasn't running when the notification arrived or [as a new intent](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L358) if it was running.

**Comment by josegomez** [comment]
I built the test app as shown. Same issue, notifications are received fine when the app is opened. 
When the app is in the background, notification is also received, however nothing happens when it is tapped.
![FireBase](https://user-images.githubusercontent.com/420837/64534244-1d26c500-d2e3-11e9-8a4c-f203ddeb7baf.gif)

**Comment by josegomez** [comment]
Figured it out, my notification was coming in with a click_action once I removed the click_action it worked fine.
Is there any way around this? I need these notifications to work for both android and other devices (which do require a click action)

**Comment by dpa99c** [comment]
As outlined above, the behaviour of system notifications is part of the Android OS where the core Firebase service handles the notification behaviour. The plugin has no influence of how `click_action` or other FCM notification properties influence this, since at this point the app (and therefore plugin code) is not running. 
For this reason, I'm closing this as it's beyond the control of this plugin.

**Comment by alexandreguertin** [comment]
I'm confused.

When I use this [plugin] (https://www.npmjs.com/package/cordova-plugin-fcm), the application opens when I click on the Push Notification!

If only the Android OS handles the behavior, would not it be supposed to behave exactly like the firebasex plugin?

**Comment by dpa99c** [comment]
Please feel free to debug in Android Studio - adding native breakpoints will confirm my assertions

**Comment by vchabal** [comment]
for anyone still having this issue, android 12 or higher can’t start activities from services or broadcast receivers (notification trampolines). you can read more at google.com/search?q=android+12+notification+trampolines

**Comment by dpa99c** [comment]
@vchabal Android 12+ notification trampoline is captured by #763 and should be resolved by the merging of PR #765 which was released in `cordova-plugin-firebasex@15.0.0 `
