### ISSUE TITLE
[iOS] Image attached to the notification does not displayed

### ISSUE THREAD

**Issue by Gidemin** [dpa99c/cordova-plugin-firebasex#138]
# Bug report

**Current behavior:**
Png-image, attached to the notification doe not displayed at iOS-app

**Expected behavior:**
Image, attached to the notification displayed

**Steps to reproduce:**
1. Build an app like described at instructions
2. Install and open [test app](https://github.com/dpa99c/cordova-plugin-firebasex-test) at iOS device
3. Open Firebase Console for my project
4. Fill data for test notification
5. Send notification

**Screenshots**
![mKwlOJZwQkeEj6mLzlRY6Q_thumb_5](https://user-images.githubusercontent.com/43244964/64532490-49aa0380-d31a-11e9-92ce-3787c113a855.jpg)
![UNADJUSTEDNONRAW_thumb_7](https://user-images.githubusercontent.com/43244964/64532492-49aa0380-d31a-11e9-8e21-f0f32cfac123.jpg)
![UNADJUSTEDNONRAW_thumb_8](https://user-images.githubusercontent.com/43244964/64532493-49aa0380-d31a-11e9-8444-716c4d6c2f89.jpg)

**Environment information**

**Cordova CLI version**
9.0.0 (cordova-lib@9.0.1)

**Cordova platform version**
1. android 8.0.0
2. ios 5.0.1

**Plugins & versions installed in project (including this plugin)**
1. cordova-custom-config 5.1.0 "cordova-custom-config"
2. cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
3. cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
4. cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
5. cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
6. cordova-plugin-whitelist 1.3.4 "Whitelist"

**Dev machine OS and version, e.g.**
Mac Mini (Late 2014), OS X 10.14.6

**Device details**
iPhone X (iOS 12.4.1)

**Node JS version**
v10.16.2

**XCode version**
v10.16.2

**Other information:**
Image, that attached to the notification has *.png format and has 70KB size

**Comment by dpa99c** [comment]
To display an image in an iOS system notification, you need to implement a [Notification Service Extension](https://developer.apple.com/documentation/usernotifications/unnotificationserviceextension) as [outlined in the Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/send-image).

Implementing a Notification Service Extension in the context of a Cordova-based iOS app is not trivial as the extension much have its own package ID and provisioning profile (see [this guide](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/ios-push-notifications/ios-rich-notifications-integration)). This does not fit well with the Cordova project structure where the Xcode project is autogenerated when the iOS platform is added.

Therefore displaying images in system notifications on iOS is currently beyond the scope of this plugin but is captured as a feature request in #45.
