### ISSUE TITLE
ionic cordova build ios freezing prefix.pch.dia

### ISSUE THREAD

**Issue by auron105** [dpa99c/cordova-plugin-firebasex#143]
# Bug report

**Current behavior:**

i have own plugin and will install SSZipArchive.
my own plugin.xml i add podspec and pod name="SSZipArchive" to auto install.
but if i install my own plugin with cordova-plugin-firebasex will freezing 
but Separate installation is OK.
please help~~

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : none
   Cordova Plugins       : cordova-plugin-firebasex 6.1.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1,  (and 8 other plugins)

System:

   ios-deploy : 1.9.2
   NodeJS     : v10.16.1 (/usr/local/bin/node)
   npm        : 6.10.2
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8``

**Comment by dpa99c** [comment]
As outlined in #5, this is an issue with the Ionic CLI that [has been fixed](https://github.com/ionic-team/ionic-cli/commit/44697cf4ebc77c656ac664c2ee08bcba052892af) in `ionic-cli@5.4.1` so please update your Ionic CLI version.
