### ISSUE TITLE
iOS app getting crash on launch

### ISSUE THREAD

**Issue by girishk55** [dpa99c/cordova-plugin-firebasex#144]
I am using this plugin in my Cordova app and followed all the instruction but when I launch the app on iOS platform I get below error and app getting crash:

 [] nw_coretls_read_one_record tls_handshake_process: [-9802]
 [] nw_coretls_read_one_record tls_handshake_process: [-9802]
 NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

What wrong I am doing?

**Comment by consciousimages** [comment]
I'm not an expert but I don't think those errors have anything to do with Firebase...

**Comment by dpa99c** [comment]
These errors are unrelated to this plugin
