### ISSUE TITLE
Ionicv3 IOS Not granting permission

### ISSUE THREAD

**Issue by Padapam** [dpa99c/cordova-plugin-firebasex#145]
Hello,

we got a problem with ionic 3 and this plugin. on android its working fine and the firebase notifications are working but on ios the popup from grantpermission is not showing up. 
we tried different approaches without success. we implemented it like this :

`(<any>window).FirebasePlugin.getToken(token => console.log(`token: ${token}`))`
`(<any>window).FirebasePlugin.grantPermission(function(hasPermission){`
` console.log("Permission was " + (hasPermission ? "granted" : "denied"));`
`});`

can someone help ? or can you make it work for ionic 3 with the native plugin 

import { Firebase } from "@ionic-native/firebase"

that would make things easier because we would not have to change code.

thanks for listening and trying.

**Comment by dpa99c** [comment]
> we got a problem with ionic 3 and this plugin. on android its working fine and the firebase notifications are working but on ios the popup from grantpermission is not showing up.
we tried different approaches without success.

Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) on iOS as a known working example to validate your APNS configuration and dev environment.

> can you make it work for ionic 3 with the native plugin

This is a Cordova plugin and so the API is pure JS - not Typescript (Ionic).
The [Typescript wrapper](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts) is maintained by Ionic so you should raise Ionic 3 support as [an issue against Ionic Native](https://github.com/ionic-team/ionic-native/issues/new)
