### ISSUE TITLE
Phonegap not supported

### ISSUE THREAD

**Issue by canado** [dpa99c/cordova-plugin-firebasex#148]
Hello,

I was using firebase for phonegap, and now that I am switching to CLi 9.0.0 I can't make it work.
I understand that you are not supporting phonegap, but this other library ( which is now archived )

https://github.com/wizpanda/cordova-plugin-firebase-lib

is asking people from phonegap to turns to this repo.

Do you know any other repo that is working with firebase and also CLI 9.0.0 ?
Regards

**Comment by dpa99c** [comment]
This issue is out of scope of this repo

**Comment by canado** [comment]
From the phonegap repo
wizpanda/cordova-plugin-firebase-lib

"Requesting all the developers to start using dpa99c/cordova-plugin-firebasex instead of this repository."

**Comment by dpa99c** [comment]
I misread that as "Phonegap Build" - are you talking about local builds with Phonegap CLI?

**Comment by canado** [comment]
Both repo are coming from amesson/cordova-plugin-firebase and it was compatible with Phonegap Build, using private fork

_PhoneGap Build
Hooks do not work with PhoneGap Build. This means you will have to manually make sure the configuration files are included. One way to do that is to make a private fork of this plugin and replace the placeholder config files (see src/ios and src/android) with your actual ones, as well as hard coding your app id and api key in plugin.xml._

The updated and compatible repo
https://github.com/wizpanda/cordova-plugin-firebase-lib is not dead and archived but it is mentioning to all phonegap build user to user yours instead.

But yours has ended the phonegap build compatibility, so do you know any other repo still up-to-date and still compatible with phonegap build ?

Thanks

**Comment by dpa99c** [comment]
No, I don't know of any other maintained Firebase plugin which works with Phonegap Build. The hook scripts in this plugin are essential to customise the underlying native projects and make full use of the Firebase SDK. From experience, I would highly recommend moving away from a cloud build environment to a local environment in order to have full control of the development cycle
