### ISSUE TITLE
[FEATURE] Add type definitions

### ISSUE THREAD

**Issue by dakotaJang** [dpa99c/cordova-plugin-firebasex#149]
I use typescript for my projects and it would be really great if there is a type definitions defined directly in the project.

It would make much better development experience as it would reduce the amount of going back and forth looking at the documentation if the descriptions and types were to show up in the IDE.

**Comment by dpa99c** [comment]
Added by #166

**Comment by lcaprini** [comment]
Hi @dpa99c @dakotaJang, actually I inserted a 
`declare const FirebasePlugin: FirebasePlugin;`
at top of my Angular Service, but I have the following error:
`'FirebasePlugin' refers to a value, but is being used as a type here.`
How can I use the types in may Ionic project?

Thanks,
--Luca
