### ISSUE TITLE
iOS 13 APNS Token Problem

### ISSUE THREAD

**Issue by Akz47** [dpa99c/cordova-plugin-firebasex#151]
Cordova CLI: 9.0.0
Cordova iOS platform: 5.0.1
Cordova-plugin-firebasex: 6.1.0
Firebase SDK: 6.3.0

There appears to be a format problem when retrieving iOS 13 device tokens via `getAPNSToken()` method. It returns a format like the following, instead of a device token:

`{length = 32, bytes = 0xd3d997af 967d1f43 b405374a 13394d2f ... 28f10282 14af515f }`

This appears to be an iOS 13 push token format change highlighted at various articles:
[https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/)
[https://forums.developer.apple.com/thread/117545](https://forums.developer.apple.com/thread/117545)

Can someone please advise on the above? Thank you.

**Comment by pghoratiu** [comment]
phonegap-plugin-push has a similar workaround implemented here
https://github.com/phonegap/phonegap-plugin-push/commit/84781fd926f09089a3626ae396bdad78f22772bf

**Comment by dpa99c** [comment]
Fixed by #177
