### ISSUE TITLE
[FEATURE] Support for remote config v2

### ISSUE THREAD

**Issue by remisture** [dpa99c/cordova-plugin-firebasex#155]
Firebase has released version 2 of remote config. Will this plugin support this?

https://firebase.googleblog.com/2019/08/remote-config-v2-sdk-update.html

Thank you.

**Comment by marcelonnunes** [comment]
Hello people. I'm having trouble using Firebase's Remote Config. Would anyone have an example to help me? I would like to take a value from a key defined in my firebase but I know how to correctly build a function to perform this action. I am in doubt of the order that each method should be called: fetch, activateFetched, getValue, setConfigSettings, setDefaults, etc.
