### ISSUE TITLE
FirebaseX getting error when using VerifyPhoneNumber method

### ISSUE THREAD

**Issue by hamzahalvanaa** [dpa99c/cordova-plugin-firebasex#156]
# Bug report

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `android 8.1.0`
- Plugins & versions installed in project (including this plugin)
`
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-brightness 0.1.5 "Brightness"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
`
- Dev machine OS and version, e.g.
    - Windows 10
        - `Windows 10 version 1903`
        
_Runtime issue_
- Device details
    - _Realme 3_
- OS details
    - _Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `v10.14.2`
- Gradle version
	- `4.10.3 and 5.1.1`

I Am using Ionic 3. Getting error when using method verifyPhoneNumber here is the information.

**Related code:**
```
  async PhoneLoginNative() {
    // console.log(this.extension + this.phone)
    if (this.phone) {
      const loader = this.loadingCtrl.create({
        content: "Mengirim kode...",
        spinner: 'crescent',
        duration: 10000
      });
      loader.present();
      this.dataPhone = this.extension + this.phone;
      this.firebase.verifyPhoneNumber(this.dataPhone, 60)
        .then((credential) => {
          this.verificationId = credential.verificationId;
          loader.dismissAll();
          this.isDisabled = true;
          this.showCodeInput = true;
          // countdown for OTP sending
          this.countdown();
        }).catch((_error) => {
          this.serverProvider.handleError('Gagal mengambil data dari server. Silahkan coba lagi.');
          loader.dismissAll();
          console.error('Gagal mengambil data dari server. Silahkan coba lagi.');
        });
    }
    else this.serverProvider.handleError("Kolom nomor telepon tidak boleh kosong.");
  }

```

**Console output**
<details>
<summary>console output</summary>

```
ion-dev.js?v=3.2.2:157 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function
    at FirebaseX.verifyPhoneNumber (index.js:54)
    at LoginPage.<anonymous> (login.ts:158)
    at step (7.js:57)
    at Object.next (7.js:38)
    at 7.js:32
    at new t (polyfills.js:3)
    at webpackJsonp.1103.__awaiter (7.js:28)
    at LoginPage.webpackJsonp.1103.LoginPage.PhoneLoginNative (login.ts:148)
    at Object.eval [as handleEvent] (LoginPage.ngfactory.js:309)
    at Object.handleEvent (core.js:13589)
    at c (polyfills.js:3)
    at new t (polyfills.js:3)
    at webpackJsonp.1103.__awaiter (7.js:28)
    at LoginPage.webpackJsonp.1103.LoginPage.PhoneLoginNative (login.ts:148)
    at Object.eval [as handleEvent] (LoginPage.ngfactory.js:309)
    at Object.handleEvent (core.js:13589)
    at Object.handleEvent (core.js:14321)
    at dispatchEvent (core.js:10004)
    at core.js:10629
    at HTMLButtonElement.<anonymous> (platform-browser.js:2628)

```
</details><br/><br/>

If someone experienced on this issue please help me. Thank you.

**Comment by dpa99c** [comment]
It looks like you are trying to use the [Ionic Native Typescript wrapper](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts) for this plugin within Ionic 3.

[As documented](https://github.com/dpa99c/cordova-plugin-firebasex#ionic-3), the Ionic Native Typescript wrapper only works with Ionic 4 - not Ionic 3.

Therefore you need to use the JS plugin API directly in Ionic 3, something like:

	(<any>window).FirebasePlugin.verifyPhoneNumber(this.dataPhone, 60, (credential) => {
          this.verificationId = credential.verificationId;
          loader.dismissAll();
          this.isDisabled = true;
          this.showCodeInput = true;
          // countdown for OTP sending
          this.countdown();
        }, (_error) => {
          this.serverProvider.handleError('Gagal mengambil data dari server. Silahkan coba lagi.');
          loader.dismissAll();
          console.error('Gagal mengambil data dari server. Silahkan coba lagi.');
        });
