### ISSUE TITLE
Crashlytics Android issue

### ISSUE THREAD

**Issue by jorisbertomeu** [dpa99c/cordova-plugin-firebasex#159]
When I try to build my app ``cordova build android --prod --release --verbose``, an error is thrown: ``ERROR: Cannot add extension with name 'crashlytics', as there is an extension already registered with that name.``

I already done ``cordova platform rm android && cordova platform add android `` without success. iOS build works well

- MacOS 10.14.6
- Cordova FirebaseX v6.1.0
- Node v12.2.0
- Gradle v5.4.1
- Target SDK 28

Thanks

**Comment by torrolt** [comment]
I observed the same issue today too. My findings:
App builds using 6.0.7 and starts throwing this error using 6.1.0.
In my case, it conflicts with cordova-fabric-plugin - removing it or cordova-plugin-firebasex makes build successful.

**Comment by dpa99c** [comment]
@jorisbertomeu The error indicates you have included another version of the Crashlytics SDK (presumably via another plugin - e.g. `cordova-fabric-plugin`) in your Android build.
This is not something supported by this plugin and if you wish to continue to do so, you'll need to manually resolve the conflict yourself.
