### ISSUE TITLE
Android Notification Sound

### ISSUE THREAD

**Issue by omeriko** [dpa99c/cordova-plugin-firebasex#161]
I created followed the documentation on this issue but the sound did't show up: 
I manually created a folder named "raw" in the path: app/src/main/res/ 
I added a sound file called : bark.mp3 to the raw directory.
I added a  sound: "bark" key-value pair to the notification object (on the server side).
I triggered a notification to test the sound  
And...nothing. 
What am i missing here ?

**Comment by dpa99c** [comment]
Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a working example, including how to set custom sounds in notifications.
See the [pre-defined messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages) for examples of how to structure the notification message to specify sounds
