### ISSUE TITLE
Problems compiling ios 13, 13.1

### ISSUE THREAD

**Issue by paulovargatt** [dpa99c/cordova-plugin-firebasex#162]
I'm having a lot of difficulties building for the new version of ios, anyone managed to solve?

I even updated the pod from 6.3.0 to 6.9.0, the build worked but the push notification broke, "Failed to retrieve default FCM token after 0 retries" error

**Comment by gitdisrupt** [comment]
How did you go about updating the pod?

**Comment by pghoratiu** [comment]
I managed to build successfully using latest XCode and plugin versions.

Do you use FCM or APNS for communication? APNS has an issue with token format.

**Comment by dpa99c** [comment]
This is resolved by #157
