### ISSUE TITLE
ANDROID_ICON_ACCENT not work

### ISSUE THREAD

**Issue by vagsa2** [dpa99c/cordova-plugin-firebasex#164]
# Bug report

**Current behavior:**

Due this https://github.com/dpa99c/cordova-plugin-firebasex#android-notification-color instruction I'm set color, re-add platfrom, but it is not changed in app. 

**Other information:**

I fixed it by adding
```xml
<config-file parent="application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />
</config-file>
```
in `config.xml` (https://firebase.google.com/docs/cloud-messaging/android/topic-messaging#edit-the-app-manifest)

**Comment by dpa99c** [comment]
To change the default notification colour, you'll need to remove the plugin and re-add it to specify the `ANDROID_ICON_ACCENT` plugin variable in order for the change to take effect.

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) and send a test notification for validation that this feature is working properly.

**Comment by spacesuitdiver** [comment]
@dpa99c can this be specified in config.xml somehow if the plugin is already added?

```
  <plugin name="cordova-plugin-firebasex" spec="10.2.0-cli">
    <preference name="ANDROID_ICON_ACCENT" value="#1f69f2ff" />
  </plugin>
```

**Comment by spacesuitdiver** [comment]
I'm an idiot and was using RGBA not ARGB in this scenario the above should work, it writes to the colors.xml and the plugin itself sources from that xml into the AndroidManifest.xml on it's own, @AlexanderVagner's code shouldn't be necessary and will probably lead to an error building during merging the AndroidManifest.xml as the value will be specified twice.

**Comment by tiagotrigger** [comment]
Weird, I'm trying what you said @spacesuitdiver but it is not working, the icon is always black.

**Comment by spacesuitdiver** [comment]
@tiagotrigger you sure it’s not just the icon that’d not properly transparent?

**Comment by tiagotrigger** [comment]
No, the icon is fine.
It works when the ANDROID_ICON_ACCENT is set while adding the plugin and it works when set in the package.json.
But when I added the preference in the config.xml did not work.

The only thing that I did not test was adding the ANDROID_ICON_ACCENT in the config.xml and remove in the package.json, maybe it had some conflict when is set in both.

**Comment by AlexanderVagner** [comment]
Tested `ANDROID_ICON_ACCENT` setting in ARGB format (`"ANDROID_ICON_ACCENT": "#FFE96187"`) in `package.json` in current version of plugin, and its works without any workarounds in `config.xml`
