### ISSUE TITLE
Not receiving any notification sent from the Firebase Console

### ISSUE THREAD

**Issue by Zerokk** [dpa99c/cordova-plugin-firebasex#170]
# Bug report

**Current behavior:**
After so many problems installing Firebase and getting the cloud messaging to work, this plugin finally worked: it correctly got installed, and got me the token, which I was struggling for more than a week already. But even though the methods in the plugin work well, the app never receives any notification.

**Expected behavior:**
I was expecting to receive the OS notification with the app in background/closed, or at least get the alert() that I have inside the handler at onMessageReceived(), fired. None of these things happened, even after many tests.

**Steps to reproduce:**
1. Pre-install: removed all Firebase plugins and stuff like that, even updated some packages and performed a "clean build" that seemed to work well.
2. Installed cordova-plugin-firebasex.
3. Put the google-services.json in my root Ionic Cordova project.
3. Removed the `platforms/android` folder, then I created it again.
4. Built the APK, which gave no errors after all.
5. Installed it in my device.
6. Ran it, had several alerts to check everything was going fine. It was!
7. Went to the Firebase Cloud Messaging console, and tried to send several notifications. None of them ever arrived: they neither showed up as an "alert" with the app open (as it was set up to), nor showed an OS notification message. 

(repeated these steps twice more, with no different results)

**Environment information**

- Cordova CLI version 
	ionic cordova -v gives me: `5.2.5`
- Cordova platform version
	9.0.0 (cordova-lib@9.0.1)

- Plugins & versions installed in project (including this plugin)
```
    cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-filepath 1.5.1 "cordova-plugin-filepath"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.4 "ImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
phonegap-plugin-multidex 1.0.0 "Multidex"
```
- Dev machine OS and version, e.g.
Windows 10
        
_Runtime issue_
- Device: Xiaomi Pocophone
- Android v.: 9.0
	
_Android build issue:_	
- Node JS version
    12.11.1
- Gradle version
	- got both 4.6 and 4.10.3
- Target Android SDK version
	actually, I can't find this in my Android manifest
- Android SDK details
	How can I get this info dump in W10?
	

**Related code:**

I import the plugin and put it in the providers array in the main module (mind that I'm working in an Ionic Angular app). Afterwards, in a service that I have that manages certain initializations (everything stable and been working for long), I call the following method:

```
  async getToken() {

    
    this.platform.ready().then(async () => {

      alert("1. Platform ready; checking permissions")
      const perm = await this.firebase.hasPermission();
      alert("2. Perm. status: "+ perm)

      this.firebase.grantPermission().then(async () => {
        alert("3. Perm granted")
        let token;

        if (this.platform.is('android')) {
          alert("4. Platform is Android")
          token = await this.firebase.getToken();
        }


        if (this.platform.is('ios')) {
          token = await this.firebase.getToken();
          await this.firebase.grantPermission();
        }

        alert("5. Token: "+ token)
        //this.saveToken(token);

        this.firebase.onMessageReceived().subscribe(data => {
          alert("Notif. received")
          data.wasTapped ? alert("Notif tapped, data: "+data) : alert("Notif not tapped")
        });

        this.firebase.onTokenRefresh().subscribe( t => alert("token refreshed: "+t))

      })
    })
    
  }
```
I am totally sure that the problem isn't elsewhere in the rest of the code; either something is wrong in this piece of code, or something of the plugin is failing to install/work with my current set up. 

Also **tried testing your example app, but it won't ever compile**, since I get the following error (doesn't appear in my project). This was after: 1. setting my own google-services in the folder, 2. changing the app id in config.xml for mine, 3. npm install, 4. trying to build for android:

```
> Configure project :app
WARNING: Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: Configuration 'releaseCompile' is obsolete and has been replaced with 'releaseImplementation' and 'releaseApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Dev\test-cordova-firebasex\platforms\android\app\build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'cdvCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
D:\Dev\test-cordova-firebasex\platforms\android\gradlew: Command failed with exit code 1 Error output:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Dev\test-cordova-firebasex\platforms\android\app\build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'cdvCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```
- - - - - 
 

Even with these problems, I am sincerely very thankful for this plugin, since it's the one that got me furthest with this issue. I am going to donate a little amount if it ends up working, because you really deserve it for the great work done, but first, I have to get this working. 

Maybe I'm doing something wrong, but hopefuly you can point the error out.

Thank you a lot!

**Comment by dpa99c** [comment]
The build error with the example project suggests a problem with either your build environment or the changes you made to customise it: the example project builds and runs fine for me and my team and numerous other devs using this plugin.

Once you have the example project built and running, you can use it as a working reference to diagnose your own project.

**Comment by dpa99c** [comment]
Closed due to no response
