### ISSUE TITLE
firebase.h not found

### ISSUE THREAD

**Issue by hengvenchang** [dpa99c/cordova-plugin-firebasex#172]
got this error when build for ios (cordova cli 9 & cordova-ios 5 & ionic 3)
<img width="271" alt="Screenshot 2019-10-04 at 3 31 29 PM" src="https://user-images.githubusercontent.com/17307495/66199338-950cc300-e6c8-11e9-9c39-bb6e294fc7cd.png">

here's my ionic info 
<img width="1222" alt="Screenshot 2019-10-04 at 5 00 49 PM" src="https://user-images.githubusercontent.com/17307495/66199409-bb326300-e6c8-11e9-86cb-1728609961c4.png">

**Comment by dpa99c** [comment]
Please don't open more issues - I've already responded to this in #171
