### ISSUE TITLE
unknown error verifying number Error instance: com.google.firebase.auth.FirebaseAuthException

### ISSUE THREAD

**Issue by DacostaDesarrollo** [dpa99c/cordova-plugin-firebasex#178]
# Bug report

**Current behavior:**
al momento de intentar autenticarme en un dispositivo sale este error en el devolución de llamada de la función:

```javascript
window.FirebasePlugin.verifyPhoneNumber(number, timeOutDuration, function(credential) {
    console.log(credential);

    if(typeof credential === 'object'){
        // if instant verification is true use the code that we received from the firebase endpoint, otherwise ask user to input verificationCode:
        var code = credential.instantVerification ? credential.code : inputField.value.toString();
    
        var verificationId = credential.verificationId;
    
        credential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);
    }
    // sign in with the credential
    firebase.auth().signInWithCredential(credential);

    // OR link to an account
    firebase.auth().currentUser.linkWithCredential(credential)
}, function(error) {
    console.error(error);
});
```
ya configure el sha1 en la plataforma de firebase y adicione el archivo google-services.json, que puede estar pasando?, lo inico extraño es que estoy usando un proyecto de la versión 1 de ionic y anteriormente usaba el plugin cordova-plugin-firebase

**Expected behavior:**

Deberia ingresar con normalidad ya que todo esta configurado a la función de verifyPhoneNumber()

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `android 8.1.0`
- Plugins & versions installed in project (including this plugin)
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-image-picker 1.1.1 "ImagePicker"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-toast 2.6.2 "Toast"
ionic-plugin-keyboard 2.2.1 "Keyboard"

- Dev machine OS and version, e.g.
    - Linux
        - `Ubuntu`
        
_Runtime issue_
- Device details
    - Huawei
- OS details
    - Android 5.1	
	
_Android build issue:_	
- Node JS version
    - `10.16.0`
- Gradle version
	- `4.10.3  5.3.1  buildOutputCleanup  vcs-1`
- Target Android SDK version
	- `android:targetSdkMinVersion = 19`

**Console output**
<details>
<summary>console output</summary>

```

unknown error verifying number Error instance: com.google.firebase.auth.FirebaseAuthException

```

</details><br/><br/>

**Comment by dpa99c** [comment]
`verifyPhoneNumber()` has been reworked in v7.0.0 of this plugin which should resolve your issue.
Please retest using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex).

If you still encounter issues, please respond here (in English) and I will reopen the issue to investigate.

**Comment by mshanak** [comment]
i have the same problem, iam using the version ```"cordova-plugin-firebasex": "^10.1.2",```

**Comment by shiningbless** [comment]
hello. I have same problem, too. The version on plugin is "cordova-plugin-firebasex": "13.0.0-cli",
Help me, please.
