### ISSUE TITLE
Adding push notification icons/configs to config.xml crashes app

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#184]
I followed all the directions for adding the push notification icons to the appropriate folders and the necessary configs.   After adding it all, and doing a `cordova run android` the app starts launch and then immediately crashes.  When it crashes, the last command prompt never returns - have to `<ctrl>-C` out of the batch.

Now I am trying to go through my project to find all the configs that were added to remove them and see which one is causing the issue.

The push notification icons I added to all the drawable folders (notification_icon.png) are all color icons - just mini versions (properly sized) of my actual app icon.  Could an incorrectly formatted `notification_icon.png` cause something like this?

My suspicion is it has to do with the meta-data config.xml edits.  Where does `<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />` get edited/copied to?  I have looked in the `/platforms/android/app/src/main/AndroidManifest.xml` file and its not in there.  I removed it from the main config.xml file but its still crashing.

**Comment by rolinger** [comment]
I had to delete all icon references from config.xml, remove/add android platform and rebuild.  To get it app to work again.  Now trying to figure out exactly what specifically is breaking it.

1.  Just added `drawable-XYpi` folders and icons to `/projects/resources/android/` - did not add any icon `<resource-file ...>` configs to config.xml - recompiled and still worked.
2. Then added all the `<resource-file ...>` lines to the config.xml, recompiled and still worked.
3. Then added the following to the config.xml file (under android), recompiled and then the app crashes again.  
```
        <config-file parent="application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>
```

What could be causing this?

**Comment by rolinger** [comment]
Found the issue, the `<config-file ..>` parent path is wrong in the documentation.

`<config-file parent="application" target="AndroidManifest.xml">`

Should be:

`<config-file parent="/manifest/application" target="AndroidManifest.xml">`

The docs should be updated.

**Comment by rolinger** [comment]
I have real app icon (with colors) showing up in Android test phones running 5.1.1 and 6.0.1...but in the other test phones running 7.0, 8.0 and 9.0, the icons are just white outlines of my icon (which is a hexagonal shape).  I have read in many locations that colored icons are not possible above Lollipop (5.0) but since I do have real color app icons showing up as push notification icons for 5.1.1 and 6.0.1 I need to ask if it is actually possible to do the same for the 7.0 - 9.0 OSs?

**Comment by dpa99c** [comment]
Resolved by #174

**Comment by 50l3r** [comment]
I try to follow the https://github.com/dpa99c/cordova-plugin-firebasex/pull/174 instructions but when i try to open the app it crashes:

![](https://i.gyazo.com/91e9ac617240813df9d117c208b8b028.png)

I have multiple config instructions. Maybe its cause the problem?

    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
        <application android:networkSecurityConfig="@xml/network_security_config" />
        <application android:layout_width="match_parent" />
        <application android:layout_height="match_parent" />
    </edit-config>
    <config-file mode="merge" parent="/*" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
        <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    </config-file>
    <config-file parent="/manifest/application" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
    </config-file>
    <icon background="resources/android/icon/ldpi-background.png" density="ldpi" foreground="resources/android/icon/ldpi-foreground.png" src="resources/android/icon/drawable-ldpi-icon.png" />
    <icon background="resources/android/icon/mdpi-background.png" density="mdpi" foreground="resources/android/icon/mdpi-foreground.png" src="resources/android/icon/drawable-mdpi-icon.png" />
    <icon background="resources/android/icon/hdpi-background.png" density="hdpi" foreground="resources/android/icon/hdpi-foreground.png" src="resources/android/icon/drawable-hdpi-icon.png" />
    <icon background="resources/android/icon/xhdpi-background.png" density="xhdpi" foreground="resources/android/icon/xhdpi-foreground.png" src="resources/android/icon/drawable-xhdpi-icon.png" />
    <icon background="resources/android/icon/xxhdpi-background.png" density="xxhdpi" foreground="resources/android/icon/xxhdpi-foreground.png" src="resources/android/icon/drawable-xxhdpi-icon.png" />
    <icon background="resources/android/icon/xxxhdpi-background.png" density="xxxhdpi" foreground="resources/android/icon/xxxhdpi-foreground.png" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
    <resource-file src="resources/android/icon/drawable-mdpi-icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-hdpi-icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xhdpi-icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xxhdpi-icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xxxhdpi-icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />

**Comment by rolinger** [comment]
@50l3r - make certain your paths to all the files are correct.  I had the same issue and my config file had `/res/android....` and should have been `resources/android/....` - and it was causing my app to crash too.  Double check your other config paths too.

**Comment by 50l3r** [comment]
My resource-file exists:

    <resource-file src="resources/android/icon/drawable-mdpi-icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-hdpi-icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xhdpi-icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xxhdpi-icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
    <resource-file src="resources/android/icon/drawable-xxxhdpi-icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
