### ISSUE TITLE
(<any>window).FirebasePlugin is undefined

### ISSUE THREAD

**Issue by yaozuwang** [dpa99c/cordova-plugin-firebasex#187]
# Bug report

**Current behavior:**

When i run firebase push notification with ionic 3, the following functions are undefined, upon further inspection, (<any>window).FirebasePlugin is undefined.

Error:

Cannot read property 'onMessageReceived' of undefined

and 

Uncaught (in promise): TypeError: Cannot read property 'getToken' of undefined

**Expected behavior:**

Should receive token and start listening for messages

**Steps to reproduce:**

Following document and implementation with ionic 3:

(<any>window).FirebasePlugin.getToken(token => console.log(`token: ${token}`))

(<any>window).FirebasePlugin.onMessageReceived((message) => {
    if (message.tap) { console.log(`Notification was tapped in the ${message.tap}`); }
})

**Screenshots**

![Capture1](https://user-images.githubusercontent.com/7391734/66980984-313dbd80-f0fe-11e9-8fce-908314bdcf28.PNG)

**Environment information**

- Cordova CLI version:  9.0.0 (cordova-lib@9.0.1)
	- `cordova -v`
- Cordova platform version:  android 8.1.0
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`

cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.1.0 "CropPlugin"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by Kiran-addweb** [comment]
> # Bug report
> **Current behavior:**
> 
> When i run firebase push notification with ionic 3, the following functions are undefined, upon further inspection, (window).FirebasePlugin is undefined.
> 
> Error:
> 
> Cannot read property 'onMessageReceived' of undefined
> 
> and
> 
> Uncaught (in promise): TypeError: Cannot read property 'getToken' of undefined
> 
> **Expected behavior:**
> 
> Should receive token and start listening for messages
> 
> **Steps to reproduce:**
> 
> Following document and implementation with ionic 3:
> 
> (window).FirebasePlugin.getToken(token => console.log(`token: ${token}`))
> 
> (window).FirebasePlugin.onMessageReceived((message) => {
> if (message.tap) { console.log(`Notification was tapped in the ${message.tap}`); }
> })
> 
> **Screenshots**
> 
> ![Capture1](https://user-images.githubusercontent.com/7391734/66980984-313dbd80-f0fe-11e9-8fce-908314bdcf28.PNG)
> 
> **Environment information**
> 
> * Cordova CLI version:  9.0.0 (cordova-lib@9.0.1)
>   
>   * `cordova -v`
> * Cordova platform version:  android 8.1.0
>   
>   * `cordova platform ls`
> * Plugins & versions installed in project (including this plugin)
>   
>   * `cordova plugin ls`
> 
> cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
> cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
> cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
> cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
> cordova-plugin-camera 2.4.1 "Camera"
> cordova-plugin-compat 1.2.0 "Compat"
> cordova-plugin-crop 0.1.0 "CropPlugin"
> cordova-plugin-datepicker 0.9.3 "DatePicker"
> cordova-plugin-device 1.1.7 "Device"
> cordova-plugin-file 6.0.2 "File"
> cordova-plugin-file-transfer 1.7.1 "File Transfer"
> cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
> cordova-plugin-geolocation 2.4.3 "Geolocation"
> cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
> cordova-plugin-splashscreen 5.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.4.3 "StatusBar"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
> es6-promise-plugin 4.2.2 "Promise"
> 
> * Dev machine OS and version, e.g.
>   
>   * OSX
>     
>     * `sw_vers`
>   * Windows 10
>     
>     * `winver`
> 
> _Runtime issue_
> 
> * Device details
>   
>   * _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
> * OS details
>   
>   * _e.g. iOS 12.2, Android 9.0_
> 
> _Android build issue:_
> 
> * Node JS version
>   
>   * `node -v`
> * Gradle version
>   
>   * `ls platforms/android/.gradle`
> * Target Android SDK version
>   
>   * `android:targetSdkVersion` in `AndroidManifest.xml`
> * Android SDK details
>   
>   * `sdkmanager --list | sed -e '/Available Packages/q'`
> 
> _iOS build issue:_
> 
> * Node JS version
>   
>   * `node -v`
> * XCode version
> 
> **Related code:**
> 
> ```
> insert any relevant code here such as plugin API calls / input parameters
> ```
> 
> **Console output**
> 
> console output
> 
> 
> **Other information:**

Did you get any solution ?

**Comment by dpa99c** [comment]
This plugin works fine with Ionic 3 if used as outlined in [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#ionic-3).

Please see the [cordova-plugin-firebasex-ionic3-test](https://github.com/dpa99c/cordova-plugin-firebasex-ionic3-test) example project for a working example.

**Comment by brassier** [comment]
I'm running into a similar issue with Ionic 3 and Cordova CLI 8 (cordova-plugin-firebasex@6.1.0).  @Kiran-addweb or @yaozuwang  - did you ever find a root cause?

**Comment by dpa99c** [comment]
@brassier 
> I'm running into a similar issue with Ionic 3 and Cordova CLI 8

The minimum support Cordova CLI version is `cordova@9` [as documented](https://github.com/dpa99c/cordova-plugin-firebasex#supported-cordova-versions)

**Comment by brassier** [comment]
Thanks @dpa99c .  I was hoping I could grab an old version of the plugin (6.1.0) and have it work with Cordova 8.

**Comment by Sagarkhenat** [comment]
@brassier Did it work with upgrading Cordova to 9? I wanted to make use of this plugin for our ionic3 project

**Comment by AndersonTruckingServiceDev** [comment]
Yup, running on Cordova 9 worked well with Ionic 3.  You just need to make your own wrapper since there's no Ionic Native wrapper for it.

If you need to use Cordova 8 I believe you have to go further back in the plugin history (earlier than 6.1.0).  Probably not worth it if you can help it.

**Comment by brassier** [comment]
Yup, running on Cordova 9 worked well with Ionic 3. You just need to make your own wrapper since there's no Ionic Native wrapper for it.

If you need to use Cordova 8 I believe you have to go further back in the plugin history (earlier than 6.1.0). Probably not worth it if you can help it.

**Comment by Sagarkhenat** [comment]
@brassier What happened was I created a demo project and used the same code as of demo test firebasex shared here. Still, I got the error for (<any>window).FirebasePlugin is undefined. It will be really helpful if you share your code.

**Comment by brassier** [comment]
There's not much to the code.  Cordova 9 seemed to be the thing that resolved this for me.  A simple sample of accessing the plugin for me is below.

      firebasePlugin: any;

    ...<other code>

      private WRAPPER_getToken(): Promise<string> {
        return new Promise<string>((resolve, reject) => {
          (<any>window).FirebasePlugin.getToken((token) => {
            resolve(token);
          },
            (error) => {
              reject(error);
            })
        });
      }

**Comment by Sagarkhenat** [comment]
@brassier Thanks for your help, will try and check for this.

**Comment by Sagarkhenat** [comment]
@brassier I did try to follow the changes for my ionic 3 project. But I am still receiving the 'Uncaught (in promise): TypeError: Cannot read property 'getToken' of undefined' message: Below is my code :
In my login.ts file:

if ( this.accessToken ) {
this.fireBaseService.getFirebaseXToken();
}

In my firebase-service.ts file===**====*****======

export class FireBaseService {
protected token:any;
public firebasePlugin;

async getFirebaseXToken() {
   let token;
  this.firebasePlugin = (window).FirebasePlugin;
  token = await this.firebasePlugin.getToken(token => {
  console.log('Response from getToken===>>>>',token);
  });
}
}

These are the specs for my ionic3 project: "cordova": "^9.0.0", "cordova-android": "8.1.0", "cordova-plugin-firebasex": "^8.1.1", "cordova-android-play-services-gradle-release": "3.0.0", "cordova-android-support-gradle-release": "^3.0.0", "cordova-plugin-androidx": "^1.0.2", "cordova-plugin-androidx-adapter": "1.1.0",

"devDependencies": { "@ionic/app-scripts": "^3.2.2", "typescript": "~2.6.2" }

If there are any changes to be done in my code, am I missing something, any kind of help will be helpful. Thanks.

**Comment by brassier** [comment]
I had trouble trying to set things like `this.firebasePlugin = (window).FirebasePlugin;`.  It worked well for me to just use the plugin off the window object any time I needed the plugin.  An example is below.  Similar promise-based wrappers could be made for other plugin methods (since there is no Ionic 3 wrapper available).


     private FBX_getToken(): Promise<string> {
       return new Promise<string>((resolve, reject) => {
         (<any>window).FirebasePlugin.getToken((token) => {
           resolve(token);
         },
           (error) => {
             reject(error);
           })
       });
     }

**Comment by danielvalenciaz** [comment]
Thanks everyone, all your solutions are valid, push notification come alive again. Great support !

**Comment by adrianjguerrero** [comment]
how do you make the library to be avaliable on window?

**Comment by pdoreau** [comment]
@adrianjguerrero did you manage to make the library to be avaliable on window ?
