### ISSUE TITLE
How to add only the necessary pods, not all of them

### ISSUE THREAD

**Issue by deliverymanager** [dpa99c/cordova-plugin-firebasex#188]
In case I am only going to use Analytics, how can I choose not to add all the rest of the libraries?
The reason is obvious.
It ads too much libraries that I do not use inside the bundle.

**Comment by dpa99c** [comment]
This fork is inherited from [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) as a monolithic implementation of all Firebase functionality. If I were to implement this plugin from scratch, I would have made it modular in the same way I have done with [cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin) however to do so for this plugin is big piece of work which I have neither the time nor inclination for.
Therefore this will not be implemented on this fork.

You should use [cordova-plugin-firebase-analytics](https://github.com/chemerisuk/cordova-plugin-firebase-analytics) if you only want to use Firebase Analytics.
