### ISSUE TITLE
Android push icons not working properly

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#189]
I have been testing push notification icons and realize the `notification_icon` in the drawables folders is not being used.  I created a new transparent icon that has some transparent items in the middle of the icon (kind of looks like a smiley face inside a hexagon) but the icon still comes across as a solid white hexagon icon in the status bar.  When I set the color it changes the color of the icon from white to whatever that color is but only when I pull down on the notifications.  On Android 5.1.1 and 6.0.1 the full color app icon arrives in the system tray, but in Android test phones 7, 8 and 9 it shows up as the white icon.  My preference is to have the full color version of my icon in all OS versions - but I don't think this is possible.  I didn't think it was possible beyond Lollipop but I do have them working in the two 5.1.1 and 6.0.1 test phones - everyone says its not supposed to be that way.

I followed all the docs and added all the icons to the appropriate drawable folders:

```
        <config-file parent="/manifest/application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>
        <resource-file src="resources/android/drawable-mdpi/notification_icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
        <resource-file src="resources/android/drawable-hdpi/notification_icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
        <resource-file src="resources/android/drawable-xhdpi/notification_icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
        <resource-file src="resources/android/drawable-xxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
        <resource-file src="resources/android/drawable-xxxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
        <resource-file src="resources/android/drawable-xxxhdpi/notification_icon_large.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon_large.png" />
```

As well, I tried sending a data payload with the `notification_icon_large.png` set and it doesn't show up anywhere.  PHP from my server - the message shows up with the  solid white hexagon icon:

```
    $client = new \Fcm\FcmClient($serverKey,$senderID) ;
    $notification = new \Fcm\Push\Notification();
    
    // 'action','dataTile','dataMsg' are needed for pre 0.2.87 versions.  Can prob be removed after 0.2.9
    $fcmData = array(
      'action' => 2,
      'dataTitle' => $sub,
      'dataMsg' => $msg,
      'pushAction' => 2,
      'pushSub' => $sub,
      'pushMsg' => $msg,
      'icon' => "notification_icon_large"
    ); 
    if ($adID !== 0 && $adID != "0") {
      $fcmData['pushPage'] = "tab.clubs" ;
      $fcmData['pushCode'] = $adID ;
    }

    $wOrange = "#f5aa07" ;    // main Orange: #f5aa07
    $wPaleOrange = "#f8d294" ;// pale Orange: #f8d294
    $wBlue = "#192a67" ;      // blue: #192a67
    $wGrey = "#cdced1" ;      // light grey
    $notification
        ->addRecipient('/topics/' .$topicID)
        ->setTitle($sub)
        ->setBody($msg)
        ->setSound("default")
        ->setColor($wGrey)
        ->setIcon("notification_icon.png")  
        ->addDataArray($fcmData);

    $response = $client->send($notification);
```

I changed the setIcon to 'notfication_icon' and 'notification_icon_large' and the icon that showed up was still the same white icon in the system tray and when I pull down on notifications the icon is grey.

**Comment by rolinger** [comment]
well, I finally got the transparent icons to work, but not via the config.xml settings.  It only works if I set the icon in the message to `setIcon('notification_icon')`.  if I don't use setIcon in the message, the app is not using the transparent icon in the drawable folders, its using the app (colored) icon - and in Android 5/6 it shows up as the real app icon, in Android 7-9 it shows up as a fully white version of the app icon.

**Comment by heidji** [comment]
try if setting your config.xml like so helps:

```xml
<platform name="android">
<resource-file src="resources/android/notification/drawable-hdpi-icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
        <resource-file src="resources/android/notification/drawable-mdpi-icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
        <resource-file src="resources/android/notification/drawable-xhdpi-icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
        <resource-file src="resources/android/notification/drawable-xxhdpi-icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
        <resource-file src="resources/android/notification/drawable-xxxhdpi-icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
<config-file parent="./application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>
</platform>

```

**Comment by dpa99c** [comment]
This plugin works within the limitations of what Android allows: on Android 7+ it's not possible to set a colour accent for the notification icon displayed in the status bar - only for the icon displayed in the system tray area.
The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) illustrates usage of custom icons both in the [project configuration](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/config.xml) and the [pre-defined message examples](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages).
