### ISSUE TITLE
did getAPNSToken get deprecared?

### ISSUE THREAD

**Issue by andysousa** [dpa99c/cordova-plugin-firebasex#193]
Howdy,

I just came across your plugin and THANK YOU!! I was trying to use phonegap's push plugin and the support and issues were just becoming to much.

At any rate... I am integrating with Azure Notification Hub to handle my push and installations.  I was going to still use APNS with them so i can keep installations clean across google (FCM) and apple (APNS).

I just tested out your plugin in google and got my token fine.  Got it and tested FCM with ios and that worked nicely too.  

When I went to call getAPNSToken() so i could register it with Azure, it just wasn't found.  I see it in issues here but not sure why i can't find it.  I am using typescript if that makes any difference.  

Any help would be apreciated

**Comment by andysousa** [comment]
on further investigation, it looks like the typescript wrapper just doesn't have that method in it

**Comment by dpa99c** [comment]
The type definition within this plugin [contains `getAPNSToken()`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L16)

**Comment by andysousa** [comment]
hmmm, so i have a n00b question then.  It isn't in the ionic native wrapper that you mention for those of us using ionic 4, so how would I be able to call it from the within the plugin?

**Comment by dpa99c** [comment]
You can call the JS plugin API directly:

    (<any>window).FirebasePlugin.getAPNSToken(token => console.log(`token: ${token}`))

You could also make PR to Ionic Native to add it to their wrapper based on the [`getToken()` definition](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts#L113)

**Comment by andysousa** [comment]
got it thanks... unfortunately its not working correctly with ios 13.  It's not returning the full handle.  Looks like they fixed this in phonegap-plugin-push recently

**Comment by andysousa** [comment]
https://github.com/phonegap/phonegap-plugin-push/pull/2808/files

**Comment by andysousa** [comment]
my bad, i see the fix is already there... just not released yet.  Things are working perfectly.. thanks so much for this project

**Comment by andysousa** [comment]
I am still trying to debug this... but i don't think the APNS token is working correctly in iOS13.  iOS 12, no issues at all but when I try to push to the token received in 13... never works.

**Comment by dpa99c** [comment]
I tested using APNS token on iOS 13 using [this site](https://www.apnstester.com/apns/) and it worked correctly

**Comment by andysousa** [comment]
I don't understand why I am struggling with ios13 so much...

Here is my payload from Azure Notification Hub

`{
    "aps":  { 
        "alert":"Notification Hub test notification",
        "sound":"default"
    },
    "data" : {
        "notification_foreground": "true",
    "notification_body" : "Notification body",
    "notification_title": "Notification title",
    "notification_ios_sound": "default",
  }
}
`

Here is the console output in the app

`willPresentNotification: {
    aps =     {
        alert = "Notification Hub test notification";
        sound = default;
    };
    data =     {
        "notification_body" = "Notification body";
        "notification_foreground" = true;
        "notification_ios_sound" = default;
        "notification_title" = "Notification title";
    };
    messageType = notification;
}
willPresentNotification: foreground notification not set
`

See anything glaring that I am missing!

**Comment by andysousa** [comment]
ugh, i got it... stepped through the code and that foreground flag needed to be outside data.  I was looking at the example in your README and i am guessing that is for FCM and not APS.  Oh well, I think its working..

Thanks again

**Comment by dpa99c** [comment]
yeah, all the examples in the README are based on using the FCM API, not directly via APNS
though I should probably add a few APNS examples to make the difference clear
