### ISSUE TITLE
image in push notification

### ISSUE THREAD

**Issue by urlexnilz** [dpa99c/cordova-plugin-firebasex#194]
Hey all,

is it possible to send an image in a push notifications like this:

![image](https://user-images.githubusercontent.com/43754601/67511000-4b474500-f696-11e9-8a2a-1a2505101021.png)

OR how twitter is doing it: display a small profile icon on the right side of a received push notification?

![image](https://user-images.githubusercontent.com/43754601/67511197-a2e5b080-f696-11e9-9e40-e3e357ff8b95.png)

**Comment by dpa99c** [comment]
See #45
