### ISSUE TITLE
Error log event Firebase

### ISSUE THREAD

**Issue by marangonijunior** [dpa99c/cordova-plugin-firebasex#195]
Does someone get this error?

Error in Success callbackId: FirebasePlugin730703293 : ReferenceError: log is not defined
vendor.js:215156 ReferenceError: log is not defined
    at main.js:1474
    at Object.callbackFromNative (cordova.js:287)
    at <anonymous>:1:9

My code:
 `
(window as any).FirebasePlugin.logEvent(type, params, function (item) {
        log("Logged event >>> ", item);
      }, function (error) {
        log("Failed to log event: " + error);
      });
`

**Comment by dpa99c** [comment]
The error message is clear: "log is not defined"

You're are calling a function called `log()` which doesn't exist - do you mean to call `console.log()`?

    console.log("Logged event >>> ", item);
