### ISSUE TITLE
[iOS] Update Firebase iOS libraries

### ISSUE THREAD

**Issue by Gidemin** [dpa99c/cordova-plugin-firebasex#196]
### What about updating Firebase iOS libraries?
As I know, at the current plugin version used 6.3 Firebase library version, but since iOS 13 and 13.1 released there a lot of important changes, which may cause bugs. Also, Firebase library [6.11 version](https://firebase.google.com/support/release-notes/ios) with a number of fixes and improvements was released at 22.10.19.

Also, big thanks for your work.

**Comment by dpa99c** [comment]
This is already [done on the dev branch](https://github.com/dpa99c/cordova-plugin-firebasex/commit/651e06ffbc75dcde0a3049137a4905dddb635418). This will be merged to master and released to npm shortly. In the meantime, you can install this plugin directly off the dev branch if you wish.

**Comment by Gidemin** [comment]
Got it. Thanks.
