### ISSUE TITLE
iOS Build - Navigation not working

### ISSUE THREAD

**Issue by mobileDev2020** [dpa99c/cordova-plugin-firebasex#198]
Hi,
 I am trying to use analytics in my phonegap built app in iOS. The build is successful, app navigation is not working. I do have the whitelist plugin, does it interfere with the cordova plugin in anyway? I allow all access origins in my config.

TIA.

**Comment by dpa99c** [comment]
As stated in [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#phonegap-build), this plugin will not work with Phonegap Build because it does not support Cordova hook scripts

**Comment by mobileDev2020** [comment]
Appreciate the prompt response.
Does it not work even if the resource files are manually placed in the source folder and google-services plugin is also added ?

**Comment by dpa99c** [comment]
No, the native Xcode project files need to be modified by the [hook scripts](https://github.com/dpa99c/cordova-plugin-firebasex/tree/master/scripts) to make the Firebase SDK work properly.
