### ISSUE TITLE
Release to NPM

### ISSUE THREAD

**Issue by andysousa** [dpa99c/cordova-plugin-firebasex#200]
Hi @dpa99c, when do you think we could get a release to NPM.  I need the APNS changes for iOS and our build pipeline is not happy with pulling directly from github (as in it just won't work).. has to pull sources from the registry.

I would be happen to help if you need it.

**Comment by dakotaJang** [comment]
This has plugin has already been in the NPM for some time.
https://www.npmjs.com/package/cordova-plugin-firebasex

**Comment by andysousa** [comment]
there hasn't been a release since 9/3, lots of fixes have gone into the dev branch

**Comment by dpa99c** [comment]
v7.0.0 has just been released to npm. Please see CHANGELOG for details.
