### ISSUE TITLE
APNS Token Refresh Callback?

### ISSUE THREAD

**Issue by andysousa** [dpa99c/cordova-plugin-firebasex#201]
Good day,

I am seeing a race condition of sorts.  I am calling the grant permission and then immediately registering for the APNS token.  As soon as that happens, the token is null.  I then see this line a few seconds later

`didRegisterForRemoteNotificationsWithDeviceToken: {length = 32, bytes = 0x5ea7634d abffead7 92515b06 e16f387d ... 604bbc82 xxxxxxxxx }`

If I try to get APNS token again after that, no issue as I would expect.  Is there a callback I can register for when the APNS token is ready?  I tried `this.firebase.onTokenRefresh()` but that only seems to get called with the FCM token.

Any thought would be appreciated

**Comment by dpa99c** [comment]
I've implemented a plugin API function for this on the dev branch.
This will be merged to master and pushed out in the next npm release.
