### ISSUE TITLE
[FEATURE] ANDROID Rich push notification image payload in foreground

### ISSUE THREAD

**Issue by msfs1992** [dpa99c/cordova-plugin-firebasex#202]
It is a very small issue: If an image is attached in the payload and the app is in foreground, the image doesn't show.

:)

**Comment by dpa99c** [comment]
When the app is in the foreground, by default a system notification is not displayed when a push notification arrives. This plugin adds support for foreground notifications by displaying a local notification when the FCM notification message arrives. As such, any additions to this local notification - e.g. an image in the payload - are a feature request rather than a bug.

**Comment by dpa99c** [comment]
It should be possible to add support for this by extracting the image URL from the APNS payload and inserting it into the local notification as a `UNNotificationAttachment` as [outlined here](https://www.ioscreator.com/tutorials/local-notification-ios-tutorial)

**Comment by msfs1992** [comment]
> When the app is in the foreground, by default a system notification is not displayed when a push notification arrives. This plugin adds support for foreground notifications by displaying a local notification when the FCM notification message arrives. As such, any additions to this local notification - e.g. an image in the payload - are a feature request rather than a bug.

I receive push notifications with maximun priority level even when the app is in foreground, but if the app is in background and payloads have an image attached, the image is shown perfectly (but not in foreground)
I have android 9 One UI 1.1

**Comment by msfs1992** [comment]
> It should be possible to add support for this by extracting the image URL from the APNS payload and inserting it into the local notification as a `UNNotificationAttachment` as [outlined here](https://www.ioscreator.com/tutorials/local-notification-ios-tutorial)

Request feature is for Android not IOS, was my mistake. Title updated
