### ISSUE TITLE
[FEATURE] Support more Firebase Authentication operations

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-plugin-firebasex#208]
Currently the plugin only exposes phone auth functionality for [iOS](https://firebase.google.com/docs/auth/ios/phone-auth) & [Android](https://firebase.google.com/docs/auth/android/phone-auth) via [`verifyPhoneNumber()`](https://github.com/dpa99c/cordova-plugin-firebasex#verifyphonenumber) however there are multiple other useful [Firebase SDK auth API](https://firebase.google.com/docs/auth) functions to manage users and sign in users in other ways.

So we should expose these, which will make `verifyPhoneNumber()` in itself more useful

**Comment by mfkenson** [comment]
@dpa99c any chance verifyPhoneNumber will be available on cordova browser platform?

**Comment by dpa99c** [comment]
@mfkenson there is no plan to add browser platform support to this plugin

**Comment by svzi** [comment]
What about my closed issue regarding the Apple Authentication provider? It's mandatory for all new iOS apps, that implement other auth providers. And it will be mandatory for existing apps, in the spring of 2020 as far as I know.

I'm currently working for a client who will release his app on iOS very soon. He already has auth via Facebook and Google implemented. Because this is a new app, the chance are heigh that Apple will reject App Store submission, because of missing auth with Apple.

Do you have any plans to add Apple in the very near future?

**Comment by svzi** [comment]
The first apps got already rejected because of a missing "Login with Apple" button:
https://github.com/firebase/firebase-ios-sdk/issues/3145#issuecomment-557243321

**Comment by dpa99c** [comment]
When I have time, I will update the Firebase SDK and implement Apple Sign In, though I can't promise that will be soon as I'm busy with other stuff and I don't use this functionality myself.
I will also accept a PR that implements it and push that out in a patch release.

**Comment by svzi** [comment]
@dpa99c Any update here?

**Comment by dpa99c** [comment]
@svzi please see the [dev branch of this repo](https://github.com/dpa99c/cordova-plugin-firebasex/tree/dev) where I have been working on this time-permitting and the corresponding [dev branch of the example project](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/dev).
I have many other commitments (I have spread myself across to many open source projects) so I will get around to doing more on this as and when I have time.

**Comment by dpa99c** [comment]
The new authentication functionality has now been released in `cordova-plugin-firebasex@8.0.0`.
Please test using the master branch of the [example project](https://github.com/dpa99c/cordova-plugin-firebasex).

**Comment by dpa99c** [comment]
Example of new auth functionality: Sign In with Apple in the example app on [iOS](http://ge.tt/3lLbBM13) and [Android](http://ge.tt/1uhNBM13)

**Comment by marcosricardo** [comment]
Do you have a example with ionic 4?

This method authenticateUserWithApple not exist in @ionic-native/firebase-x, you can help me in this problem?

I have to deliver this as soon as possible :(

<img width="337" alt="Screen Shot 2020-03-10 at 11 54 44" src="https://user-images.githubusercontent.com/27781419/76325758-74bfe080-62c6-11ea-9515-bcce716e6b39.png">
<img width="443" alt="Screen Shot 2020-03-10 at 11 54 48" src="https://user-images.githubusercontent.com/27781419/76325765-79849480-62c6-11ea-971b-d61e5239539f.png">
<img width="522" alt="Screen Shot 2020-03-10 at 11 54 55" src="https://user-images.githubusercontent.com/27781419/76325768-7ab5c180-62c6-11ea-89ea-5cac7b74061b.png">

**Comment by svzi** [comment]
@marcosricardo My advize: get rid of `@ionic-native/firebase-x` and just use this plugin. I didn't check, but it looks like the Ionic-Wrapper isn't up to date with the latest version of this plugin.

**Comment by dpa99c** [comment]
@marcosricardo The ionic-native/firebase-x wrapper is maintained by Ionic so raise an issue or make a PR to the [ionic-native repo](https://github.com/ionic-team/ionic-native/) to add support for any missing API functions.

or call the plugin's JS API directly, e.g.:

	(<any>window).FirebasePlugin.authenticateUserWithApple(credential => console.dir(credential), error => console.error(error))

**Comment by marcosricardo** [comment]
Ok, I'm almost there.

Log in XCODE.

<img width="594" alt="Screen Shot 2020-03-10 at 17 21 05" src="https://user-images.githubusercontent.com/27781419/76356947-88367000-62f5-11ea-903d-7f46c3b8618e.png">

<img width="393" alt="Screen Shot 2020-03-10 at 17 21 10" src="https://user-images.githubusercontent.com/27781419/76356952-8cfb2400-62f5-11ea-868f-33a9f012c6aa.png">

I have only one problem now.

signInWithCredential return null.

I activated sign with apple in firebase and APP ID but not working.

Thanks.

**Comment by dpa99c** [comment]
@marcosricardo please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working example.

**Comment by vdias38** [comment]
I've submitted a PR ionic-team/ionic-native#3458 to add all missing plugin functions, incl. `authenticateUserWithApple`
