### ISSUE TITLE
Not receiving notifications on iOS device

### ISSUE THREAD

**Issue by EstevesHERE** [dpa99c/cordova-plugin-firebasex#210]
Hey guys, I am trying to use FirebaseX Plugin, but I am only receiving notifications on android.
On iOS version it's the same code, but I am getting the notifications only on Xcode console with this message from FCM console:

`2019-11-05 11:06:46.989556-0300 name[587:69682] didReceiveMessage: {
    "collapse_key" = "key";
    from = XXXXXXXXXX;
    notification =     {
        body = Version;
        e = 1;
        tag = "campaign_collapse_key";
        title = iOS;
    };`

What am I doing wrong ?

**Comment by dpa99c** [comment]
Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your iOS development environment and ensure you've followed the [Firebase guide to configure APNs with Firebase](https://firebase.google.com/docs/cloud-messaging/ios/certs)
