### ISSUE TITLE
Supported Cordova Android 7.x

### ISSUE THREAD

**Issue by nguyenhaduchieu** [dpa99c/cordova-plugin-firebasex#212]
I used last version meteor 1.8 and Cordova Android 7.x. Does your library support?
![image](https://user-images.githubusercontent.com/25113093/68381237-dbe84f80-0183-11ea-8541-f46cceb3ce48.png)

Thanks @dpa99c

**Comment by dpa99c** [comment]
`cordova@9` and `cordova-android@8` are required by this plugin
