### ISSUE TITLE
this.FirebaseAuth.singInWithCredential() is not a function

### ISSUE THREAD

**Issue by sadiss** [dpa99c/cordova-plugin-firebasex#214]
# Bug report

this.FirebaseAuth.singInWithCredential() is not a function

import { FirebaseX } from '@ionic-native/firebase-x/ngx';
constructor(
    private FirebaseAuth: FirebaseX 
  ){}
singInWithCode(){
    this.loading.show();
    this.FirebaseAuth.singInWithCredential(this.phoneNumber, this.verificationId).then( (user)=>{
      console.log(user);
    }, (error)=>{
      alert('Cannot login right now.');
    });
  }
I know its my understanding issue, But i couldn't find any soultion online. I have successfully received code on my phone but now cannot verify it please help.

**Comment by MattGould1** [comment]
hey @sadiss not sure if you've copied your code correctly but you've written `singInWithCredential` it should be `signInWithCredential`

Also, you're passing `this.phoneNumber` as an argument. It should be `signInWithCredential(this.verificationId, this.smsCode)`

**Comment by SnaiCrys** [comment]
same problem

```
main.4b4e9bd446c9989e7280.js:1 ERROR Error: Uncaught (in promise): TypeError: e.firebaseAuthentication.signInWithCredential is not a function
TypeError: e.firebaseAuthentication.signInWithCredential is not a function
    at main.4b4e9bd446c9989e7280.js:1
    at new t (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at t.signInWithVerificationId (main.4b4e9bd446c9989e7280.js:1)
    at n.<anonymous> (16.88b207efc950318007d6.js:1)
    at 16.88b207efc950318007d6.js:1
    at Object.next (16.88b207efc950318007d6.js:1)
    at 16.88b207efc950318007d6.js:1
    at new t (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at s (16.88b207efc950318007d6.js:1)
    at n.onSubmit (16.88b207efc950318007d6.js:1)
    at P (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at polyfills.9d2f6fd8d1d1c89a3f0c.js:1
    at i (16.88b207efc950318007d6.js:1)
    at e.invoke (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at Object.onInvoke (main.4b4e9bd446c9989e7280.js:1)
    at e.invoke (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at t.run (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at polyfills.9d2f6fd8d1d1c89a3f0c.js:1
    at e.invokeTask (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
    at Object.onInvokeTask (main.4b4e9bd446c9989e7280.js:1)
```

**Comment by dpa99c** [comment]
`signInWithCredential()` and `linkUserWithCredential()` are new plugin API functions so haven't yet been added to the Ionic Native Typescript wrapper - you can open an issue/PR against Ionic Native to add them or use them directly via the JS plugin API, for example: 

	(<any>window).FirebasePlugin.signInWithCredential(
		verificationId,
		code, 
		() => console.log('Sign in successful'),
		(error) => console.error('Sign in failed: '+error)
	);

**Comment by sadiss** [comment]
> same problem
> 
> ```
> main.4b4e9bd446c9989e7280.js:1 ERROR Error: Uncaught (in promise): TypeError: e.firebaseAuthentication.signInWithCredential is not a function
> TypeError: e.firebaseAuthentication.signInWithCredential is not a function
>     at main.4b4e9bd446c9989e7280.js:1
>     at new t (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at t.signInWithVerificationId (main.4b4e9bd446c9989e7280.js:1)
>     at n.<anonymous> (16.88b207efc950318007d6.js:1)
>     at 16.88b207efc950318007d6.js:1
>     at Object.next (16.88b207efc950318007d6.js:1)
>     at 16.88b207efc950318007d6.js:1
>     at new t (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at s (16.88b207efc950318007d6.js:1)
>     at n.onSubmit (16.88b207efc950318007d6.js:1)
>     at P (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at polyfills.9d2f6fd8d1d1c89a3f0c.js:1
>     at i (16.88b207efc950318007d6.js:1)
>     at e.invoke (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at Object.onInvoke (main.4b4e9bd446c9989e7280.js:1)
>     at e.invoke (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at t.run (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at polyfills.9d2f6fd8d1d1c89a3f0c.js:1
>     at e.invokeTask (polyfills.9d2f6fd8d1d1c89a3f0c.js:1)
>     at Object.onInvokeTask (main.4b4e9bd446c9989e7280.js:1)
> ```

You must include cordova-plugin-firebase-authentication plugin that's how i make it work
