### ISSUE TITLE
Improve onMessageReceived type

### ISSUE THREAD

**Issue by Birowsky** [dpa99c/cordova-plugin-firebasex#215]
Currently the success payload is not typed:

https://github.com/dpa99c/cordova-plugin-firebasex/blob/2bc2d85ade6cd8feae095c3c7cdeb0f2af25a2d8/types/index.d.ts#L17

I however find it to be the most crucial piece of information in this plugin :}

Could you, in meantime, let me know whether I inferred the correct type based on the docs?
```typescript
type Notification //the payload, currently object
  = FirebaseNotifIos
  | FirebaseNotifAndroid

type FirebaseNotifIos = MessageType & {
  aps: { alert: { title: string, body: string } }
  payload: string
}

type FirebaseNotifAndroid = MessageType & {
  title?: string
  body?: string
  payload: string
}

type MessageType
  = { messageType: 'data' }
  | { messageType: 'notification', tap: 'background' | 'foreground' };
```

Thanx!

**Comment by Birowsky** [comment]
If, however, typescript is not part of your tool-belt, then just jot down examples of all possible versions of the payload, I'll type it out.

**Comment by tsimbalar** [comment]
@Birowsky if/when confirmed that those types are correct, you may want to open a PR in https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts which is where the types are defined, I believe 🤔
