### ISSUE TITLE
Notification evan after app uninstall

### ISSUE THREAD

**Issue by andysousa** [dpa99c/cordova-plugin-firebasex#216]
This might not be a plugin issue and I apologize, but this group seems to be the most informative I have been a part of so I will ask here. 

I have users reporting that they are getting push notification on their apple device even after they have disabled plugins on their device and even after an app uninstall. I am using the apns token for all my apple devices. Am I missing something, I assumed the os with take care of this for me.

**Comment by dpa99c** [comment]
My understanding is that uninstalling the app causes Apple to disassociate the APNS token with your app therefore push notifications should not be received after uninstall the app - [see here](https://stackoverflow.com/questions/14858224/ios-push-notifications-behavior-when-app-is-deleted-and-then-reinstalled).
However, this is out-of-scope of this plugin hence closing.
