### ISSUE TITLE
Android build error after update the plugin to 7.0.0

### ISSUE THREAD

**Issue by wenj5335** [dpa99c/cordova-plugin-firebasex#218]
# Bug report

**Current behavior:**
After upgrade from v6.1.0 to v7.0.0, when I run command `cordova run android` it show the error

**Expected behavior:**
The build process should be success without issue.

**Steps to reproduce:**

**Screenshots**
![image](https://user-images.githubusercontent.com/50609315/68569847-2296bc00-049a-11ea-86ba-20fd0b4417a7.png)

**Environment information**

- Cordova CLI version 
	- `cordova -v9.0.0`
- Cordova platform version
	- `cordova platform android v8.1.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin cordova-plugin-firebasex v7.0.0`

**Related code:**
![image](https://user-images.githubusercontent.com/50609315/68569711-c5026f80-0499-11ea-9a10-cbda813919f8.png)

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
Please post the contents of your `AndroidManifest.xml` so the problematic `<meta-data>` element can be identified.
Also try removing/re-adding the Android platform to see if this resolves the issue.

**Comment by Starofall** [comment]
I had the same issue. Might have been an undefined @colors/accent variable.
I got this issue fixed by reinstalling with ANDROID_ICON_ACCENT.

`cordova plugin add cordova-plugin-firebasex --variable ANDROID_ICON_ACCENT=#FF123456`

```
  "cordova": {
    "plugins": {
   ...
      "cordova-plugin-firebasex": {
        "ANDROID_ICON_ACCENT": "#FF123456", // ADD THIS
```

**Comment by dpa99c** [comment]
I'm guessing this is related to commit https://github.com/dpa99c/cordova-plugin-firebasex/commit/bda54cb59293cf0ca8f72e0b3263a4890a228f55 and that it happens if you don't specify a custom accent colour during plugin installation. 
This change was an attempt to fix #132 but it probably now needs a custom fallback in the hook script to read the default value from `plugin.xml` if there's not a custom value in `config.xml` or `package.json`.

**Comment by wenj5335** [comment]
@Starofall actually i have define the ANDROID_ICON_ACCENT in colors.xml and this is working in previous version of firebasex
![image](https://user-images.githubusercontent.com/50609315/68641770-ce95e100-0546-11ea-94ec-3ddab15d822c.png)

**Comment by wenj5335** [comment]
![image](https://user-images.githubusercontent.com/50609315/68641857-2cc2c400-0547-11ea-9ed7-2e33c19cdb6f.png)
This is the result after `cordova platform add android`

**Comment by wenj5335** [comment]
> I had the same issue. Might have been an undefined @colors/accent variable.
> I got this issue fixed by reinstalling with ANDROID_ICON_ACCENT.
> 
> `cordova plugin add cordova-plugin-firebasex --variable ANDROID_ICON_ACCENT=#FF123456`
> 
> ```
>   "cordova": {
>     "plugins": {
>    ...
>       "cordova-plugin-firebasex": {
>         "ANDROID_ICON_ACCENT": "#FF123456", // ADD THIS
> ```

@Starofall Thanks, your solution is working
