### ISSUE TITLE
(ionic-native) verifyPhoneNumber and signInWithCredential

### ISSUE THREAD

**Issue by SnaiCrys** [dpa99c/cordova-plugin-firebasex#220]
Changes in version 7 do not allow building an ionic project due to ionic-native version d.ts types

**Comment by dpa99c** [comment]
I suggest opening an issue/PR with [Ionic Native](https://github.com/ionic-team/ionic-native/) to add support for these new plugin API functions. In the meantime they can be called directly via the JS plugin API (see #214)

**Comment by vdias38** [comment]
I've submitted a PR ionic-team/ionic-native#3457 to fix these functions
