### ISSUE TITLE
iOS startup crash after updating to 7.0.0

### ISSUE THREAD

**Issue by Birowsky** [dpa99c/cordova-plugin-firebasex#221]
# Bug report

**Current behavior:**
Ios app crashes on startup. [This seems](https://github.com/fechanique/cordova-plugin-fcm/issues/308#issuecomment-302067844) to capture the issue nicely. More specifically, the `platforms/ios/{app name}/Resources/GoogleService-Info.plist` is the one that gets screwed up.

Rolling back to v6.0.1 fixed it.

**Expected behavior:**

App doesn't crash.

**Steps to reproduce:**

- Prepare the fresh clone of a project with v7.0.0 of this plugin with `cordova prepare`.
- Start the app.
- Expect it to crash on startup.

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `ios 5.0.1`
- Plugins & versions installed in project (including this plugin)

```
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-appminimize 1.0.1 "AppMinimize"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-facebook4 6.2.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googleplus 8.2.0 "Google SignIn"
cordova-plugin-headercolor 1.0 "HeaderColor"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-localization-strings 3.2.1 "Localization"
cordova-plugin-secure-storage 3.0.2 "SecureStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.2 "SocialSharing"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
```

- Dev machine OS and version, e.g.
    - OSX
```
ProductName:    Mac OS X
ProductVersion: 10.15.1
BuildVersion:   19B88
```

_Runtime issue_
- Device details
    - any iPhone

_iOS build issue:_
- Node JS version
    - `10.17.0`
- XCode version
    - `Version 11.2.1 (11B53)`

</details><br/><br/>

**Other information:**

Issue doesn't happen if project is being prepared with `cordova platform add ios`.

**Comment by driiftkiing** [comment]
I'm getting the following error after upgrading from v6.1.0 to 7.0.0:
```bash
The following build commands failed:
        CompileC /Users/tharmarajah/Library/Developer/Xcode/DerivedData/Swiss_Economic-ecjhahrgcwyqxhbmnhyigyyqbxof/Build/Intermediates.noindex/ArchiveIntermediates/Swiss\ Economic/IntermediateBuildFilesPath/Swiss\ Economic.build/Debug-iphoneos/Swiss\ Economic.build/Objects-normal/armv7/FirebasePlugin.o /Users/tharmarajah/php-storm-projects/swiss-economic-app/cordova/platforms/ios/Swiss\ Economic/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by driiftkiing** [comment]
I'm getting following error after upgrading:
```bash
The following build commands failed:
        CompileC /Users/USER_NAME/Library/Developer/Xcode/DerivedData/CORDOVA_PROJECT-ecjhahrgcwyqxhbmnhyigyyqbxof/Build/Intermediates.noindex/ArchiveIntermediates/CORDOVA_PROJECT/IntermediateBuildFilesPath/CORDOVA_PROJECT.build/Debug-iphoneos/CORDOVA_PROJECT.build/Objects-normal/armv7/FirebasePlugin.o /Users/USER_NAME/projects/angular-app/cordova/platforms/ios/CORDOVA_PROJECT/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
``

**Comment by asimon91** [comment]
It's happening to me too. I've created an XCode project from an IONIC app that uses this plugin, and it's not compiling because it cannot find the "Firebase.h" file.

`'Firebase.h' file not found
AppDelegate + FirebasePlugin.m`

**Comment by kelpie278** [comment]
This was happening to me due to an incompatibility _cordova-plugin-googleplus_ which I've seen you have on your config, I was capable of sorting it setting up the pods version manually, which is suboptimal but it works.

**Comment by dayaki** [comment]
@asimon91  @driiftkiing Please how are you able to solve this? Am having exact problem and v7.0.1 didn't solve it for me.

**Comment by driiftkiing** [comment]
@dayaki: In my case I had to install the plugin `cordova-plugin-ionic-webview` as last. Otherwise this plugin gets f*cked up.

Also running pod install inside a `after_platform_add` hook, but I dont think this will solve the problem.
```bash
pod repo update
pod install --project-directory='./platforms/ios/'
```

**Comment by DCGoD** [comment]
How does this issue keep arising? This is the same issue I've battled for years and it makes integrating Firebase into an ionic app using continuous integration, a total nightmare. Builds locally, doesn't from CI.

**Comment by markterrill** [comment]
How are folk successfully building?

@kelpie278 what files did you specify a pod version, and what did you set? I'm also using googleplus (git)

**Comment by markterrill** [comment]
Ok. solved the missing firebase.h

The podfile was missing Firebase libraries:
```
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'
use_frameworks!
target 'MyApp' do
	project 'MyApp.xcodeproj'
	pod 'GoogleSignIn', '4.4.0'
	pod 'GoogleUtilities', '6.2.3'
	pod 'Firebase/Core', '6.11.0'
	pod 'Firebase/Auth', '6.11.0'
	pod 'Firebase/Messaging', '6.11.0'
	pod 'Firebase/Performance', '6.11.0'
	pod 'Firebase/RemoteConfig', '6.11.0'
	pod 'Fabric', '1.10.2'
	pod 'Crashlytics', '3.14.0'
end
```

I ignored the warning about auto generation and simply copy/pasted the firebase entries..

Then make sure to ```cd platforms/ios; pod install;``` so it'll install the libraries.

Compiling again showed errors with "'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.2.99."

So using Xcode i clicked on each of the pods and manually updated the ios target version to 10. (as I'm setting my minimum build target to be 10)

**Comment by rip3rs** [comment]
I have this issue to. dont't get what I did, because it was working Oo
