### ISSUE TITLE
FR: Login with Apple

### ISSUE THREAD

**Issue by svzi** [dpa99c/cordova-plugin-firebasex#226]
Anyone who has implemented Firebase Auth (with auth providers like Facebook or Google), have to add the Apple login provider (at least for iOS apps) in the very near future.

Do you have any plans to integrate the Apple auth provider into this plugin? It has been officially released by the Firebase team in the last week:
https://firebase.googleblog.com/2019/11/sign-in-with-apple-auth.html

Best,
Sven

**Comment by dpa99c** [comment]
This will be covered in #208.
Currently only phone number auth (as inherited from `cordova-plugin-firebase`) is supported.
