### ISSUE TITLE
Receiving push on old token

### ISSUE THREAD

**Issue by archigo** [dpa99c/cordova-plugin-firebasex#227]
# Bug report

**Current behavior:**

Receiving system push message when no push is expected.

I'm not sure if this is a firebase issue or an issue with this plugin.

**Expected behavior:**

Push should only be received if we have subscribed to push messages.

**Steps to reproduce:**

This is on android only.

If you install your app and activate push, then everything works as expected.

However, if you uninstall your app, and then install it again (getting a new token) and do not activate push, even calling unregister, the phone will still show system push messages (even with the app in foreground). I assume this is because the token from the previous installation is still active on Firebase and it is somehow not detected that no app with that token exists anymore.

install -> activate push -> uninstall -> install -> don't activate push -> still receive push (as if the app is in the background)

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- android 8.1.0
- Plugins & versions installed in project (including this plugin)
    cordova-disable-http-cache 1.0.0 "Cordova HTTP cache disabler"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.4.0 "AppRate"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-device-name 1.3.5 "Device-Name"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-firebasex 6.1.0 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-keychain-touch-id 3.3.0 "TouchID and Keychain"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-sslcertificatechecker 6.0.0 "SSL Certificate Checker"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
        
_Runtime issue_
- Device details
    - Samsung Galaxy S7
- OS details
    - Android 8.0

**Comment by dpa99c** [comment]
Token management is entirely part of the Firebase SDK - this plugin merely observes and reacts to token changes made by the SDK and therefore there's no way the plugin can influence the behaviour of the Firebase SDK in relation to its internal handling of tokens.

**Comment by mctdev-marius** [comment]
Hello,
i have the same problem.
From what i can see the correct Firebase method to call is "deleteToken" of com.google.firebase.messaging.FirebaseMessaging witch is not present in your service.
Can you please add it and merge.
I already tried it on a different bundle and it works and it worked

**Comment by dpa99c** [comment]
@mctdev-marius the plugin code has [been updated](https://github.com/dpa99c/cordova-plugin-firebasex/blob/dev/src/android/FirebasePlugin.java#L663) to replace the deprecated Firebase IID methods with the replacement Firebase Messaging methods so will resolve this issue with newer versions of the Firebase SDK.
This is currently on the dev branch but will be merged to master and released in a new major version of this plugin.
Hopefully this will happen today, if not sometime this week.

**Comment by mctdev-marius** [comment]
Grate,
thanks it works on android now but ios is having the same problem.
