### ISSUE TITLE
Channel null when app not active.

### ISSUE THREAD

**Issue by svenboogaarthotraco** [dpa99c/cordova-plugin-firebasex#228]
Im trying to get notifications working by copying the example and editing it.
Testing is done on an emulator with the help of android studio, 
Android 10, nexus 4, api 29
running

> cordova platform version android

Returns:

> Installed platforms:
>   android 8.1.0

running 
> cordova --version

returns
>9.0.0 (cordova-lib@9.0.1)

I appended to www/index.js onDeviceReady method:

```
  var channel = {
        id: "my_default_channel",
        name: "My Default Name",
        description: "My Default Description",
        sound: "ringtone",
        vibration: [500, 200, 500],
        light: true,
        lightColor: parseInt("FF0000FF", 16).toString(),
        importance: 4,
        badge: false,
        visibility: -1
    };

    window.FirebasePlugin.setDefaultChannel(channel,
        function () {
            console.log('Default channel set');
        },
        function (error) {
            console.log('Set default channel error: ' + error);
        });
```

Default channel set is logged.

The app works fine when the app is running (background and foreground).
When the app is not active and I send a message I get another message.
Developer warning for package "io.cordova.hellocordova"
Failed to post notifcation on channel "null" See log for more details.
![Screenshot_1574080710](https://user-images.githubusercontent.com/57902158/69053950-d3590a00-0a0a-11ea-9ffe-ff55af706049.png)

My log contains:

 Data message received: {"notification_title":"Test tit2le","messageType":"data","notification_foreground":"true","id":"10","ttl":"2419200","code":"500","from":"753087898340","title":"Test tit2le","sent_time":"1574081636335","show_notification":"true"}
2019-11-18 13:53:55.534 16748-16748/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(12)] "Data message received: {"notification_title":"Test tit2le","messageType":"data","notification_foreground":"true","id":"10","ttl":"2419200","code":"500","from":"753087898340","title":"Test tit2le","sent_time":"1574081636335","show_notification":"true"}",

Did I miss something? If I can help in anyway by providing more info please let me know.

I uploaded my code here:
https://github.com/svenboogaarthotraco/firebasetest2

**Comment by svenboogaarthotraco** [comment]
close #228

**Comment by hungtranpg** [comment]
Hi @svenboogaarthotraco,
how can you fix it? I also face the same problem. it happens on android version >= 8.0
