### ISSUE TITLE
Can't add the plugin - FirebasePlugin.java already exists

### ISSUE THREAD

**Issue by JerryBels** [dpa99c/cordova-plugin-firebasex#231]
Hello :)

So, tonight my project suddenly stopped being able to build. The changes that occured were that I changed firebase-lib to firebasex, and updated facebook4 and googleplus to their latest versions.

# Bug report

**Current behavior:**

Can't add platform Android with the plugin, or add the plugin if Android platform is already added.

When trying any way, an error message appears :

```
Failed to install 'cordova-plugin-firebasex': CordovaError: Uh oh!
"path\to\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java" already exists!
```

**Expected behavior:**

The plugin should be able to be added without issue

**Environment information**

- Cordova CLI version : 9.0.0 (cordova-lib@9.0.1)

- Cordova platform version :   android 8.1.0

- Plugins & versions installed in project (including this plugin)
```
com-sarriaroman-photoviewer 1.1.18 "PhotoViewer"
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebase-lib 4.0.1 "Google Firebase Plugin"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-googleplus 7.0.2 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.0 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.19 "Ionic Deeplink Plugin"
uk.co.workingedge.phonegap.plugin.istablet 1.2.0 "Is Tablet"
```

- Dev machine OS and version, e.g.
Windows 7
	
_Android build issue:_	
- Node JS version : v10.15.1

**Console output**
```
cordova plugin add cordova-plugin-firebasex
Installing "cordova-plugin-firebasex" for android
Installing "cordova-plugin-androidx" for android
Installing "cordova-plugin-androidx-adapter" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebasex': CordovaError: Uh oh!
"path\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java" already exists!
    at copyNewFile (path\platforms\android\cordova\lib\pluginHandlers.js:234:45)
    at install (path\platforms\android\cordova\lib\pluginHandlers.js:34:17)
    at ActionStack.process (path\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (path\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (path\node_modules\cordova-common\src\PluginManager.js:144:17)
    at path\platforms\android\cordova\Api.js:210:74
    at _fulfilled (path\node_modules\q\q.js:854:54)
    at path\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (path\node_modules\q\q.js:816:13)
    at path\node_modules\q\q.js:877:14
Uh oh!
"path\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java" already exists!
```

**Other information:**

ionic -v : 5.4.6

ionic info : 
```
Ionic:

   Ionic CLI                     : 5.4.6 (C:\Users\JB\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.1.1
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 18 other plugins)

Utility:

   cordova-res : 0.3.0
   native-run  : 0.2.6

System:

   NodeJS : v10.15.1 (C:\Program Files\nodejs\node.exe)
   npm    : 6.4.1
   OS     : Windows 7
```

Thanks a lot ahead for your help.

**Comment by JerryBels** [comment]
Oh god that's embarrassing...

I still had cordova-plugin-firebase-lib in my repo, although it was removed from my `package.json` file. Of course it would conflict...

Thanks for the great work :)

**Comment by CarlosPFuentealba** [comment]
Hello! Could you solve this problem?

**Comment by txeto90** [comment]
It indicates Cordova has failed to deploy the plugin source files to the Android platform project since a file with that filepath already exists.
One possible explanation is you have both `cordova-plugin-firebase` and `cordova-plugin-firebasex` present in your project - that would cause such an error. You need to uninstall one, and I recommend you uninstall `cordova-plugin-firebase`. 

In my case, it works.
Hope it helps you.

**Comment by txeto90** [comment]
> Hello! Could you solve this problem?

It indicates Cordova has failed to deploy the plugin source files to the Android platform project since a file with that filepath already exists.
One possible explanation is you have both `cordova-plugin-firebase` and `cordova-plugin-firebasex` present in your project - that would cause such an error. You need to uninstall one, and I recommend you uninstall `cordova-plugin-firebase`.

In my case, it works.
Hope it helps you.
