### ISSUE TITLE
Crashes on iOS v11 with firebase SDK v6.11

### ISSUE THREAD

**Issue by Edmu** [dpa99c/cordova-plugin-firebasex#232]
# Bug report

**Current behavior:**

Crashes on start or shorty after start then calling plugin methods

**Expected behavior:**
Not to crash

**Steps to reproduce:**
Install plugin version v7.0.1
Call various plugin method like: logEvent, fetch, fetchActivated, getValue ...

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- android 8.0.0 &  ios 5.0.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
- Dev machine OS and version, e.g.
    - OSX
        - 10.14.6
        
_Runtime issue_
- Device details
    - iPhone 6
- OS details
    - 11.3	

**Other information:**

I think the issue comes from Firebase SDK v6.11 - downgrading helped (to version which does not use Firebase SDK v6.11). Also xCode debugger catches BAD_MEMORY_ACCESS inside firebase SDK files.

https://github.com/firebase/firebase-ios-sdk/issues/4265
https://firebase.google.com/support/release-notes/ios#6.13.0

It seems v6.11 were having issues on lower iOS versions (v12 and lower) and v6.13 were pushed quite quickly.

**Comment by albertopq** [comment]
I'm having the same issues. Even manually upgrading the pod to 6.13.0 doesn't fix it, so not sure what's the solution here. In the meantime, manually downgraded the pod to 6.9.0

**Comment by dpa99c** [comment]
Cordova currently doesn't support the use of plugin variables in plugin podspecs (as it does for Gradle dependencies for Android) otherwise you could override the versions pinned by the plugin using plugin variables at plugin install time. However, I may be able to implement this using hook scripts.
In the meantime, I will update the pinned versions to the latest v6.13.0 shortly.

**Comment by IonicDeveloper12** [comment]
I am having the same issue, any solution please?
