### ISSUE TITLE
TypeError: Cannot read property 'onMessageReceived' of undefined

### ISSUE THREAD

**Issue by denamielleonardo** [dpa99c/cordova-plugin-firebasex#240]
TypeError: Cannot read property 'onMessageReceived' of undefined

**Comment by dpa99c** [comment]
This is insufficient information for an issue - the issue template exists in order that all necessary information is supplied.
Most likely the plugin or Typescript wrapper is not installed properly in your project. Please see the example project for an example of how to use this plugin.
