### ISSUE TITLE
Success callback of window.FirebasePlugin.grantPermission - hasPermission returns null on iOS device

### ISSUE THREAD

**Issue by IonicDeveloper12** [dpa99c/cordova-plugin-firebasex#242]
I am using this plugin, Android is everything working fine. iOS it is not working.

When I try to call:

```
window.FirebasePlugin.grantPermission(function(hasPermission) {
})
```

`hasPermission` returns `null`

Could you help in resolving it?
Thanks

**Comment by sagrawal31** [comment]
Are you calling `window.FirebasePlugin.grantPermission` or `hasPermission` in Cordova `deviceready` event?

**Comment by IonicDeveloper12** [comment]
window.FirebasePlugin.grantPermission

**Comment by sagrawal31** [comment]
You didn't understood my question @IonicDeveloper12 

```jabascript
document.addEventListener("deviceready", function() {
    // your ios code
}, false);
```

I'm asking that if your code (which you posted above) is being called/executed inside the above similar code of `deviceready` event?

**Comment by IonicDeveloper12** [comment]
I am calling like this

this.platform.ready().then(() => {
if(this.platform.is('ios')){
//My above code here
}
}

**Comment by IonicDeveloper12** [comment]
window.FirebasePlugin.setScreenName()
window.FirebasePlugin.setUserId()
these functions are not working in IOS
it says can not read the property setScreenName of undefined

**Comment by dpa99c** [comment]
> window.FirebasePlugin.grantPermission
> 
> below is my code inside deviceready event.
> 
> ```js
> if (this.platform.is('ios')) {
>     this.firebase.grantPermission(function (hasPermission) {
>         alert('has permission ; ' + hasPermission);
>         if (hasPermission) {
>             this.firebase.getToken(token => {
>                 if (token && gotToken == false) {
>                     gotToken = true;
>                     this.auth.sendPushNotificationInfo(token, 'New');
>                     alert(token + 'New');
>                 }
>             }).catch(error => console.log('Error getting token', error));
> 
>             this.firebase.onTokenRefresh(function (token) {
>                 if (token && gotToken == false) {
>                     gotToken = true;
>                     this.auth.sendPushNotificationInfo(token, 'Refresh');
>                     alert(token + 'Refresh');
>                 }
>             });
>         }
>     });
> }
> ```


You can only call `grantPermission()` if `hasPermission()` returns `false`:

    window.FirebasePlugin.hasPermission(function(hasPermission){
        if(!hasPermission){
            window.FirebasePlugin.grantPermission(function(permissionGranted){
                if(permissionGranted){
                    console.log("Permission granted");
                }else{
                    console.warn("Permission denied");
                }
            });
        }else{
            console.log("Permission already granted");
        }
    });

Please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a [working code example](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L189).

**Comment by dpa99c** [comment]
> window.FirebasePlugin.setScreenName()
> window.FirebasePlugin.setUserId()
> these functions are not working in IOS
> it says can not read the property setScreenName of undefined

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to verify that [the usage](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L422) of these functions work fine on iOS

**Comment by mattprado21** [comment]
@dpa99c Is it possible to call hasPermission and grantPermission outside the device ready. 
I already call it on the device ready. I was wondering what if the user click the "Don't Allow" on the first prompt.
I was planning to call it upon clicking a certain button on the app like a toggle button that on and off the permission

Thank you so much in advance!
