### ISSUE TITLE
Plugin not installed

### ISSUE THREAD

**Issue by Hexa-IT** [dpa99c/cordova-plugin-firebasex#243]
When I try to run the app on my android phone I keep getting this error.
And yes I did do:

`ionic cordova plugin add cordova-plugin-firebasex`
`npm install @ionic-native/firebase-x`

Down here is the exact error that I am getting.
![Error](https://imgur.com/PDoCUXf.png)

**Comment by sagrawal31** [comment]
Can you post info with `ionic info` and also versions of `@ionic-native/*` plugins?

**Comment by Hexa-IT** [comment]
### **Ionic info:** 
Ionic:

   Ionic CLI                     : 5.4.9 (C:\Users\RickbigDick\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.11.5
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 8 other plugins)

Utility:

   cordova-res : 0.8.1
   native-run  : 0.2.9

System:

   Android SDK Tools : 26.1.1 (C:\Users\RickbigDick\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.13.1
   OS                : Windows 10`

### **Versions:**
`"@ionic-native/core": "^5.17.1",`
`"@ionic-native/firebase-x": "^5.17.1",`
`"@ionic-native/globalization": "^5.17.1",`
`"@ionic-native/native-storage": "^5.17.1",`
`"@ionic-native/splash-screen": "^5.17.1",`
`"@ionic-native/status-bar": "^5.17.1",`

**Comment by sprengerst** [comment]
For me it is the same. But only for iOS not for Android:
```

2019-12-02 22:32:04.123696+0000 Together[50232:617028] WARN: Native: tried calling FirebaseX.grantPermission, but the FirebaseX plugin is not installed.
2019-12-02 22:32:04.123847+0000 Together[50232:617028] WARN: Install the FirebaseX plugin: 'ionic cordova plugin add cordova-plugin-firebasex'
2019-12-02 22:32:04.123994+0000 Together[50232:617028] Enabled mobile notifications
2019-12-02 22:32:04.124180+0000 Together[50232:617028] WARN: Native: tried calling FirebaseX.onMessageReceived, but the FirebaseX plugin is not installed.
2019-12-02 22:32:04.124534+0000 Together[50232:617028] WARN: Install the FirebaseX plugin: 'ionic cordova plugin add cordova-plugin-firebasex'
2019-12-02 22:32:04.125337+0000 Together[50232:617028] WARN: Native: tried calling FirebaseX.onTokenRefresh, but the FirebaseX plugin is not installed.
2019-12-02 22:32:04.125992+0000 Together[50232:617028] WARN: Install the FirebaseX plugin: 'ionic cordova plugin add cordova-plugin-firebasex'
```



    "@ionic-native/core": "^5.0.0",
    "@ionic-native/firebase-x": "^5.16.0",

**Comment by dpa99c** [comment]
This is an Ionic support issue, Please raise an issue against Ionic Native or seek support on the Ionic Forum. 
You can verify that the plugin itself functions properly by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test/).

**Comment by moblizeit** [comment]
i have the same issue

**Comment by leitonet** [comment]
I have the same issue after updating the firebasex plugin to v7.0.1

**Comment by ryanlaclair** [comment]
This can be solved by wrapping your firebaseX usage in the success handler from a `platform.ready()` guard: https://github.com/ionic-team/ionic-native/issues/438

**Comment by dupiesdupreez** [comment]
Luckily there is a Wrapper, to wrap a plugin that we needed a fix for a few months ago that is a substitute for the broken firebase plugin. My next project will NOT be in Ionic I can tell you that much

**Comment by RicardoElSabio** [comment]
I have the same issue. Any solution?

**Comment by leolio86400** [comment]
We do have the same issue too, some iOS device somehow don't have the plugin some other with EXACTLY the same configuration (iOS version, iPhone model) have the plugin working perfectly fine.

I would expect the plugin to always register properly in the window object regardless of the errors.

It seems really random and is somehow fixed by itself after couple of days (but not ideal to tell customers to wait couple of days before being able to use their push notifications...).

Anyone came with a solution ?

**Comment by shanthan25** [comment]
Supported Cordova Versions
cordova: >= 9
cordova-android: >= 8
cordova-ios: >= 5

**Comment by leolio86400** [comment]
> Supported Cordova Versions
> cordova: >= 9
> cordova-android: >= 8
> cordova-ios: >= 5
> 
> and need to install cocoapods.

Thanks for copy pasting the readme, really useful... 

In production (Apple store/Google play store) it seems the issue is not as big as test environment, we have only few cases out of thousands. But definitely a weird thing.

**Comment by cyrilfr** [comment]
Same issue with Cordova 11, Cordova iOS 6.2, FirebaseX 14. Any solution?

**Comment by rahulsw99** [comment]
It doesn't work when using live reload, i.e. when I use` ionic cordova run android`, but it does work when I use `ionic cordova build android` and get the apk file transferred on the phone. The apk file should be in /platforms/android/app/build/outputs/apk/debug.

You can then use adb install to transfer the file to your phone.
