### ISSUE TITLE
Styling the notifications

### ISSUE THREAD

**Issue by Amaury-T** [dpa99c/cordova-plugin-firebasex#244]
Hello @dpa99c 

I was wondering if it is possible to style the notifications received from FCM (like whatsapp or other app)

Example:
![notification](https://user-images.githubusercontent.com/45353849/69862101-036d9c00-129a-11ea-95c6-49dc14c78a4b.jpg)

If yes how :)
If no, how can we achieve the same?

I don't find any clue in the documentation.

I was thinking passing the notification received to the cordova-plugin-local-notifications which seems to be able to style the notification, but i read on an issue that both plugins are incompatible.

Thanks in advance for your time and answer ! :)

**Comment by dpa99c** [comment]
By styling like "like whatsapp or other app" do you mean including an image in the notification?
If so, see #45.

> I was thinking passing the notification received to the cordova-plugin-local-notifications which seems to be able to style the notification, but i read on an issue that both plugins are incompatible.

This will not work: when you app is in the background or not running, the OS will display a system notification hence no code in your app will be executed and therefore you can't use cordova-plugin-local-notifications to customise the styling - you must work within the constraints of the platform-specific system notification specifications which Firebase abstracts for you and this plugin abstracts from Firebase.

**Comment by Amaury-T** [comment]
Thanks for the really quick answer!

> By styling like "like whatsapp or other app" do you mean including an image in the notification?
If so, see #45.
Yes, I mean including an image, choosing it's position, choosing text color, ...

From your link i see that it is not possible directly within this plugin and require some native code to handle that on both ios and android platform.
Does it mean that for cordova applications it is not possible to do so? How is it possible to include native code ?

in the PR#45 you mentionned:
`However,` it may be feasible to construct a foreground (local) notification using an FCM notification/data message and augment this to display the rich content (see here).
How can we achieve that?

Thanks !

**Comment by dpa99c** [comment]
This is beyond the current scope of this plugin's functionality.
