### ISSUE TITLE
NullInjectorError: No provider for FirebaseX!

### ISSUE THREAD

**Issue by gold100** [dpa99c/cordova-plugin-firebasex#245]
Hi,
I'm working with FirebaseX in an Angular project and i get this error.
How do I load this service in the appModule.ts?

If i just put FirebaseX in the provider section i get this error

`Invalid provider for the NgModule 'AppModule'`

Please help

**Comment by dpa99c** [comment]
Please only open issues to report bugs or request features,
For support, please use forums such as Stackoverflow and Ionic Forum.
