### ISSUE TITLE
How can I get this to work with Ionic v1?

### ISSUE THREAD

**Issue by aquinn637** [dpa99c/cordova-plugin-firebasex#247]
I'm writing an app with Cordova, Ionic v1 and AngularJS.

I want to implement push notifications in my app and I have considered using this plugin. I see the documentation for Ionic 3 & 4.

I was able to get this working on a plain JS project with cordova but not yet with the Ionic 1 & AngularJS integration.

I get undefined from the window object.

How can I access this plugin from within the AngularJS context?

```
  console.log(window);

  //do the push notifications here
  console.log(window.FirebasePlugin); //undefined

  console.log($window.FirebasePlugin); //undefined

  // window.FirebasePlugin.getToken(function(fcmToken) { //undefined
  //     console.log(fcmToken);
  // }, function(error) {
  //     console.error(error);
  // });

  // $window.FirebasePlugin.getToken(function(fcmToken) { //undefined
  //     console.log(fcmToken);
  // }, function(error) {
  //     console.error(error);
  // });
```

**Comment by dpa99c** [comment]
You should use the JS API (`window.FirebasePlugin`) of the plugin with Ionic 1.
If `window.FirebasePlugin` is not defined, then it's most likely the plugin is not present in the build.
Be sure to test on an actual supported platform (Android or iOS) and not in the browser (e.g. `ionic serve`).
You can check if `window.FirebasePlugin` is defined in the webview by connecting a remote debugger to the device/simulator webview (Safari Web Inspector for iOS / Chrome Dev Tools for Android).

For further support, please ask on Stackoverflow or the Ionic Forum.

**Comment by aquinn637** [comment]
Here is my code: https://github.com/aquinn637/IonicPushTest

No luck with Stackoverflow.
