### ISSUE TITLE
set defaults.

### ISSUE THREAD

**Issue by svenboogaarthotraco** [dpa99c/cordova-plugin-firebasex#249]
Im receiving notifications from a company that uses cordova firebase, i try to handle them from my app. I do not control the messages that are send but still want to use some features.
 
In the FirebasePluginMessagingService I try to set some default behaviour. e.g. to set the android color in the onMessageReceived method:
I set   

            String color = "#c20606";

instead of the original line 96 
           
            String color = null; 

at https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePluginMessagingService.java

However the default behaviour is not changed, when notification_android_color  is not set i want to show my color '#c20606' but the original blueish color is still shown. Is it possible to set default values?

p.s. this is more of a question than an issue, but i did not know where to post the question.

**Comment by dpa99c** [comment]
To change the notification accent color on Android, rather than hacking the plugin source code, set the `ANDROID_ICON_ACCENT` plugin variable as outlined in [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#android-notification-color).

See the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working example of this.

**Comment by svenboogaarthotraco** [comment]
@dpa99c thanks a lot for the reply, just out of technical interest, why does it not work from within the FirebasePluginMessagingService.java file, I thought that if the wanted value was set there it would be used by sendMessage. The main reason im asking is that i prefer a set value in case the server side that i dont manage changes and they do set a color i still prefer my own color.

**Comment by dpa99c** [comment]
The color value you set at [line 96](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePluginMessagingService.java#L96) is immediately overridden by the value in the remote notification at [line L117](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePluginMessagingService.java#L117) (even if that is null). 
The color value is actually used at [line 307](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePluginMessagingService.java#L307) so defining a hard-coded value for color anywhere before here will work, but I don't recommend it as it means you are on a forked version of this plugin and will need to manually merge in your changes if you wish to update to a new version.

**Comment by svenboogaarthotraco** [comment]
@dpa99c thanks for the reply ah i overlooked line 117 i was looking at line 136 and thought it would pick null if not set. We are using a custom variant because we want do do some translations of the incoming message. we receive an error code and based on the phone settings we show an alarm based on the code in the user language. 
When i look in the log for vibrate its saying: Vibrate: 100,30,100,30,100,200,200,30,200,30,200,200,100,30,100,30,100 but its only vibrating three times like the default (i assume).
