### ISSUE TITLE
Ionic 3, Android 9, opening application delay after reboot

### ISSUE THREAD

**Issue by zhyjiuk** [dpa99c/cordova-plugin-firebasex#250]
# Bug report

**Current behavior:**
I try to send a notification while restarting the phone.
Immediately after starting, notification is displayed on screen (it's so quickly, good job).
But if I try to open it (immediately tap), then my application **opens for around 2-3 minutes**!

I'm not sure if this is related to the code of this plugin.

**Expected behavior:**
I think that the application should open immediately after tapping on notification. 

**Steps to reproduce:**
1) restart the phone
2) send notification from firebase console while phone is restarting
3) tap immediately on notification after phone restart

**Environment information**

- Cordova CLI version 
	- 8.1.2 (cordova-lib@8.1.1)
- Cordova platform version
	- android 8.1.0
- Plugins & versions installed in project (including this plugin)
    - "cordova-plugin-firebasex": "^7.0.1"

            "cordova-plugin-firebasex": {
                "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
                "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.0.0",
                "ANDROID_FIREBASE_MESSAGING_VERSION": "19.0.0",
                "ANDROID_FIREBASE_CONFIG_VERSION": "18.0.0",
                "ANDROID_FIREBASE_PERF_VERSION": "18.0.0",
                "ANDROID_FIREBASE_AUTH_VERSION": "18.0.0",
                "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
                "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.0",
                "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "true",
                "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "true",
                "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "true",
                "ANDROID_ICON_ACCENT": "#FF00FFFF"
            }

- Dev machine OS and version, e.g.
    - ubuntu 

- Device details
    - Samsung Galaxy S8
- OS details
    - Android 9

- Node JS version
    - v8.16.2
- Gradle version
	- 4.10.3  4.4.1  buildOutputCleanup  vcs-1
- Target Android SDK version
	- name="android-targetSdkVersion" value="28"

**Related code:**
```
export class NotificationsProvider {
  private win: any = window;
  firebase: any = this.win.FirebasePlugin;

  constructor() {}


  initFirebaseNotifications(): Promise<boolean> {
    var that = this;

    return new Promise(function(resolve, reject) {

      that.firebase.getToken(
        (data) => {
          console.log('getToken success', data);

          that.subscribeFirebaseNotifications();

          // ios anly
          that.permissionFirebaseNotifications();

          resolve();

        },
        (error) => {
          console.error('Error getting token', error);
          reject();
        }
      );

    }); // promise
  
  }


  subscribeFirebaseNotifications() {
    this.firebase.onMessageReceived(
      (data) => {
        console.log('onMessageReceived success', data);
      },
      (error) => {
        console.log('onMessageReceived error', error);
      }
    );
  }


  permissionFirebaseNotifications() {
    if (this.platform.is('ios')) {
      this.firebase.hasPermission(
        (data) => {
          console.log('hasPermission success', data);

          if(!data.isEnabled){
            this.firebase.grantPermission(
              (data) => {
                console.log('grantPermission success', data);
              },
              (error) => {
                console.log('grantPermission error', error);
              }
            );
          }
      
        },
        (error) => {
          console.log('hasPermission error', error);
        }
      );
    }
  }

}
```

Thanks for your help!

**Comment by dpa99c** [comment]
Please test the same scenario using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate the possible cause as plugins or code within your own project.

However, if the example project shows the same result, there is nothing this plugin can do about it: when you tap a system notification, it invokes an intent which launches the app and this is part of the core Android operating system - the plugin code is not being executed at this time.

It's also possible that the delay is because the device CPU is heavily under load during the OS startup and this is causing the delay in execution of the launch intent.

Either way, there's nothing that this plugin can do about it from a code perspective, therefore I'm closing this issue.

**Comment by zhyjiuk** [comment]
Thanks for your help, Dave! I tried to check my app on an older phone this evening.
And delay is not modeled on meizu m3 note (android 5.1).

I apologize for the fuss.
Have a nice time!
