### ISSUE TITLE
error: cannot access FirebaseAuthException

### ISSUE THREAD

**Issue by adriatomas** [dpa99c/cordova-plugin-firebasex#252]
Hello guys when i upload my ionic app to bitrise i get the following error on bitrise, any ideas?
![Screenshot 2019-12-10 at 10 24 39](https://user-images.githubusercontent.com/22915551/70516442-50256280-1b37-11ea-88f9-587b7dfa7edc.png)

Here its my project info:

![Screenshot 2019-12-10 at 10 25 24](https://user-images.githubusercontent.com/22915551/70516513-6b906d80-1b37-11ea-9304-20cb14447519.png)

**Comment by dpa99c** [comment]
I would speculate that bitrise - being a cloud build environment - is not satisfying the Gradle dependency for the Firebase SDK components and therefore they are not present in the build.

This plugin is intended to be used in a local build environment where the native mobile platform projects are under your direct control, therefore this is out-of-scope of the plugin and you will need to resolve this yourself e.g. asking on StackOverflow or ask Bitrise for support.

You can validate that this plugin works correctly in a local build environment by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).
