### ISSUE TITLE
iOS Example Background not working.

### ISSUE THREAD

**Issue by sprengerst** [dpa99c/cordova-plugin-firebasex#253]
With the most actual version Android is working as expected, iOS is working if the app is in foreground.

If the app is in background or killed it is not working with iOS, so there is no banner shown.

If I add the "apns" from your example, the android version is not working anymore and the iOS also not working anymore, even in foreground.

Can you maybe have a look at the message data, I think the issue lies in the construction of the message:

            'notification': {
                'title': titleText,
                'body': bodyText,
            },
            'data': {
                "forceStart": "1",
                "priority": "high",
                'type': JSON.stringify(type),
                'payload': JSON.stringify(rawPayload),
                'title': titleText,
                'body': bodyText,
            }

I am sending through firebase admin console.

Could it be that I am missing APS configuration, but why would it work in foreground then?

Best regards,
Stefan

**Comment by dpa99c** [comment]
If testing use the example project, please use the built-in messaging client to send the [pre-defined test messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages) to validate the plugin functionality as outlined in the [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client).

**Comment by sprengerst** [comment]
Ok thanks I will try. But could you tell me, if I need the APS service linked in Firebase for this to work, or should this also work without the entries. Because, the foreground notification seems to work without APS entry.

**Comment by dpa99c** [comment]
> Ok thanks I will try. But could you tell me, if I need the APS service linked in Firebase for this to work, or should this also work without the entries. Because, the foreground notification seems to work without APS entry.

Yes APNS setup is required for background notifications as outlined in the example project; the mechanism for foreground notifications is entirely different but background notifications are displayed by the iOS operating system code which is reliant on APNS.
Please follow the README instructions of the example project exactly.

**Comment by svenboogaarthotraco** [comment]
I had problems with ios to, I never got a message in onMessageReceive while it was working in android. I did a few rebuilds etc but it didnt solve it.
What did the trick for me was running `pod repo update` and rebuilding it after.

**Comment by sprengerst** [comment]
Did you also had to enable aps?

**Comment by svenboogaarthotraco** [comment]
> Did you also had to enable aps?

Yes, aps is the layer of apple that actually sends the notification, without that layer no notification will be send.

**Comment by dpa99c** [comment]
As [this screencapture](https://www.youtube.com/watch?v=35feCmGYSR4) shows, background notifications work correctly in the example app on iOS when configured correctly.
