### ISSUE TITLE
Minimum ios version?

### ISSUE THREAD

**Issue by svenboogaarthotraco** [dpa99c/cordova-plugin-firebasex#255]
What is the lowest ios version that is supported?
I tried my app on an old ipad (ios 9.3.5 cant be updated anymore) and it crashes, it works fine on my iphone. Im not sure if 9.3.5 is not supported or if there is a bug in my app.

**Comment by svenboogaarthotraco** [comment]
I tried it on a device with ios 10.0.0 and it worked fine, ios 13.3 works fineto. it

**Comment by bryplano** [comment]
Are you certain that the crash you experienced is related to this plugin and not something else in your configuration?

iOS 9 (and honestly, in most situations - I'd argue - iOS 10) should really not be developed for any more, considering there are four major versions ahead of it :)

**Comment by svenboogaarthotraco** [comment]
> Are you certain that the crash you experienced is related to this plugin and not something else in your configuration?
> 
> iOS 9 (and honestly, in most situations - I'd argue - iOS 10) should really not be developed for any more, considering there are four major versions ahead of it :)

im not sure if it is because of the plugin tbh.
currently we have the minimum version at 10, so it's not a problem for us if 9.* is not supported.

**Comment by bryplano** [comment]
It looks like `cordova-ios` [5.0.0](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#500-feb-07-2019) still technically supports iOS 9, so iOS9 should also be supported by this plugin based on the README's min requirements: https://github.com/dpa99c/cordova-plugin-firebasex#breaking-api-changes

That assumes you're using `cordova-ios 5.0.0` of course.

Still a fair question to ask just to be clear, but it's also probably worth checking into the crash on iOS 9 to see if this plugin is actually the cause of the problem or not :)

**Comment by svenboogaarthotraco** [comment]
> It looks like `cordova-ios` [5.0.0](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#500-feb-07-2019) still technically supports iOS 9, so iOS9 should also be supported by this plugin based on the README's min requirements: https://github.com/dpa99c/cordova-plugin-firebasex#breaking-api-changes
> 
> That assumes you're using `cordova-ios 5.0.0` of course.
> 
> Still a fair question to ask just to be clear, but it's also probably worth checking into the crash on iOS 9 to see if this plugin is actually the cause of the problem or not :)

unfortunately I dont have the ios9 device anymore for testing. It crashed when receiving a push notification,

I agree it's better to support later versions only we have set our minimum at 10 but I tried to test it on an old ipad that was laying around just for testing purposes

**Comment by dpa99c** [comment]
Recent version of the Firebase SDK appear to crash on iOS 9 so this plugin will support only iOS 10+.

AFAIK it's currently not possible for a Cordova plugin to impose a minimum platform version so this will be done via documentation.

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#supported-mobile-platform-versions
