### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int com.android.okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by 50l3r** [dpa99c/cordova-plugin-firebasex#257]
Hi,

Since i installed this plugin and enable crashlytics, i recieve this errors in firebase panel:

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference at com.android.okhttp.okio.Buffer.write(Buffer.java:1182) at com.android.okhttp.okio.Buffer.read(Buffer.java:1221) at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:55) at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393) at com.android.okhttp.internal.Util.skipAll(Util.java:159) at com.android.okhttp.internal.Util.discard(Util.java:141) at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:410) at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396) at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384) at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@20.0.0:4) at com.google.firebase.messaging.zzj.close(com.google.firebase:firebase-messaging@@20.0.0:38) at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.0:51) at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.0:60) at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.0:2) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at com.google.android.gms.common.util.concurrent.zza.run(:6) at java.lang.Thread.run(Thread.java:764)`

There's a post related bug here: https://github.com/firebase/firebase-android-sdk/issues/1006

Maybe it's a firebase problem?

**Comment by dpa99c** [comment]
The error is arising in the OKHTTP library used by Firebase - it could be due to another plugin in your project referencing a different version of the OKHTTP library - you'll need to check the `plugin.xml` of each plugin in your project to confirm this and/or check the entries in `platforms/android/app/build.gradle`. 

You can confirm this plugin works fine in isolation by build and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex).

**Comment by 50l3r** [comment]
Great! Much thanks for your help. I just wanted to know if it could be a bug by the plugin.

**Comment by 50l3r** [comment]
Recently firebase-messaging has released a new version who correct this error: https://github.com/firebase/firebase-android-sdk/issues/1006#issuecomment-566152818

He says updating firebase-messaging to 20.1.0 solves problem.

**Comment by dpa99c** [comment]
you can override the default version used by the plugin by setting the `ANDROID_FIREBASE_MESSAGING_VERSION` plugin variable at plugin install time:

    --variable ANDROID_FIREBASE_MESSAGING_VERSION=20.1.0
