### ISSUE TITLE
Question about screenName Analytics report

### ISSUE THREAD

**Issue by 50l3r** [dpa99c/cordova-plugin-firebasex#258]
Hi all,

My app use Vue with Cordova, and with every page changes i call the setScreenName method:

`window.FirebasePlugin.setScreenName("PAGE_NAME");`

But in Firebase Analytics i recieve this:

![](https://i.gyazo.com/3cfdab33149187938c7b218e8d99da23.png)

According with firebase (https://firebase.google.com/docs/analytics/screenviews?hl=es), i need to pass second param to specify the className. In PWA app it's always MainActivity or MainViewController

`Analytics.setScreenName(screenName, screenClass: screenClass)`

Why can set my custom Screen Name?

**Comment by flolovebit** [comment]
same problem: it's not possibile see any screen name passed even the lodgement parameters, what's wrong?

**Comment by dpa99c** [comment]
This plugin provides the facility to set the "screen name" parameter on the "screen_view" event ("screen class" is not set as it's not relevant in the Javascript context of a Cordova app so defaults to the native class name).

You can see how this is done in the plugin source code for [Android](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L606) and [iOS](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L616).

These native implementations are called by the [`setScreenName()`](https://github.com/dpa99c/cordova-plugin-firebasex#setscreenname) JS plugin API function.

The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) contains [an example usage](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L422) and the resulting output can be seen in the Firebase Analytics console:

![screen](https://user-images.githubusercontent.com/2345062/71251188-82924500-2319-11ea-9138-a479d0faf153.jpg)
