### ISSUE TITLE
plugin_not_installed

### ISSUE THREAD

**Issue by rhanesoghlyan** [dpa99c/cordova-plugin-firebasex#259]
I've added plugin to my project but it showing error `plugin_not_installed`.

`Install the FirebaseX plugin: 'ionic cordova plugin add cordova-plugin-firebasex`

**Comment by dpa99c** [comment]
This is an Ionic error, not an error specific to this Cordova plugin. 
You have not provided enough detail to diagnose further the cause.
Please raise an issue with Ionic Native.
