### ISSUE TITLE
I can't put a notification icon

### ISSUE THREAD

**Issue by taruk-tataruk** [dpa99c/cordova-plugin-firebasex#260]
i tried all the described methods in the documentation, none of them work. android version - 6. 

the notification icon looks just like a gray circle and in the middle is a w

**Comment by dpa99c** [comment]
Please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working example of custom notification icons.
Note that Android only supports monochrome images in the statusbar - polychromatic images are not supported.
