### ISSUE TITLE
Notifications do not appear on the lock screen

### ISSUE THREAD

**Issue by taruk-tataruk** [dpa99c/cordova-plugin-firebasex#262]
This time I searched before writing :)

I tested on two phones:

1. Android 6
2. Android 8

none of them have a lock screen message. Android 6 sounds, but the screen is dark

which option should you specify to show messages on the lock screen?

**Comment by taruk-tataruk** [comment]
why did you close?

**Comment by dpa99c** [comment]
This is the default behaviour of of Android.
This plugin cannot change what is the default behavior of Android.

**Comment by taruk-tataruk** [comment]
are there any plugins to change this behavior? I will be grateful for any help

**Comment by dpa99c** [comment]
No
