### ISSUE TITLE
OnMessageReceived does not work on iOS

### ISSUE THREAD

**Issue by taruk-tataruk** [dpa99c/cordova-plugin-firebasex#263]
I beg you not to delete this. I could not solve the problem myself.

the onMessageReceived event does not work for me. Neither with tap nor when the application is running. Your application, which you posted as a test, works. What could be the problem? if you need to attach any files - write, attach

**Comment by dpa99c** [comment]
I cannot speculate what the problem could be within your app - there are so many possible causes.
I am not able to provide you with support - my role as an open source author is to provide a robust software library as a building block for your application - this is validated by the example app.

You will either need to ask on stackoverflow or elsewhere for help or else pay someone to fix the issue for you.

Please do not open additional issues requesting support- these issues should either be used to report genuine bugs in the plugin or to request specific features that are not already supported.

**Comment by SandroMoretti** [comment]
Maybe platform version is different in test and your project @taruk-tataruk ?
