### ISSUE TITLE
Xcode build for iOS 9.3 doesn't build if app name contains spaces

### ISSUE THREAD

**Issue by ulver2812** [dpa99c/cordova-plugin-firebasex#264]
# Bug report

**Current behavior:**

Xcode build for iOS 9.3 doesn't build if app name contains spaces

**Expected behavior:**
Xcode build for iOS 9.3 build if app name contains spaces

**Steps to reproduce:**
In your config.xml set the name tag with app name contains spaces
`<name>My App Name</name>`
instead of 
`<name>MyAppName</name>`
then run
```
cordova platform add ios
cordova build ios
```
open the .xcworkspace generated in platforms/ios folder.
Then in xcode set deployment target to 9.3 and run build.

**Screenshots**
![Screenshot-2020-01-03-at-13 26 14](https://user-images.githubusercontent.com/25301598/71725036-d0876c80-2e32-11ea-9ad1-d79e6236015f.jpg)

**Environment information**

- Cordova CLI version 
	- 9.0.0 cordova-lib@9.0.1
- Cordova platform version
	- ios 5.1.1
- Plugins & versions installed in project (including this plugin)
   - cordova-plugin-whitelist 1.3.3
   - cordova-plugin-statusbar 2.4.2
   - cordova-plugin-device 2.0.2
   - cordova-plugin-splashscreen 5.0.2
   - cordova-plugin-ionic-webview 4.1.3
   - cordova-plugin-ionic-keyboard 2.2.0 
   - cordova-plugin-firebasex 7.0.1
   - cordova-plugin-androidx 1.0.2
   - cordova-plugin-androidx-adapter 1.1.0

- Dev machine OS and version, e.g.
    - OSX
        - Mac OS X 10.14.3
	
_iOS build issue:_
- Node JS version
    - node 10.11.0
- XCode version
    - xcode 10.2.1

**Comment by dpa99c** [comment]
iOS 9 will no longer be supported due to recent versions of the Firebase SDK crashing on iOS 9 - see #255.
