### ISSUE TITLE
Build failed for android in ionic4 after updating the plugin to latest

### ISSUE THREAD

**Issue by bhargavas12** [dpa99c/cordova-plugin-firebasex#267]
Getting the following error while running the below command:

ionic cordova build android

Error:

C:\Users\user\Downloads\ionic-v4\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:849: error: cannot access FirebaseAuthException
                            if (e instanceof FirebaseAuthInvalidCredentialsException) {
                                  ^
  class file for com.google.firebase.auth.FirebaseAuthException not found
C:\Users\user\Downloads\ionic-v4\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:887: error: cannot access InternalTokenProvider
                        FirebaseAuth.getInstance().getFirebaseAuthSettings().setAutoRetrievedSmsCodeForPhoneNumber(number, smsCode);
                                    ^
  class file for com.google.firebase.internal.InternalTokenProvider not found
C:\Users\user\Downloads\ionic-v4\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:925: error: incompatible types: Exception cannot be converted to FirebaseAuthInvalidCredentialsException
                                        if (task.getException() instanceof FirebaseAuthInvalidCredentialsException) {
                                                             ^
C:\Users\user\Downloads\ionic-v4\platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:957: error: incompatible types: Exception cannot be converted to FirebaseAuthInvalidCredentialsException
                                        if (task.getException() instanceof FirebaseAuthInvalidCredentialsException) {
                                                             ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd build android exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

Have these versions in "adroid/app/build.gradle"

// SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.appcompat:appcompat:1.0.0"
    implementation "androidx.annotation:annotation:1.0.0"
    implementation "com.squareup.okhttp3:okhttp-urlconnection:3.10.0"
    implementation "com.google.android.gms:play-services-tagmanager:17.0.0"
    implementation "com.google.firebase:firebase-core:17.0.0"
    implementation "com.google.firebase:firebase-messaging:19.0.0"
    implementation "com.google.firebase:firebase-config:18.0.0"
    implementation "com.google.firebase:firebase-perf:18.0.0"
    implementation "com.google.firebase:firebase-auth:19.2.0"
    implementation "com.crashlytics.sdk.android:crashlytics:2.10.1"
    implementation "com.crashlytics.sdk.android:crashlytics-ndk:2.1.0"
    implementation "me.leolin:ShortcutBadger:1.1.22"
    implementation "androidx.legacy:legacy-support-core-utils:1.0.0"
    // SUB-PROJECT DEPENDENCIES END

**Comment by dpa99c** [comment]
> class file for com.google.firebase.auth.FirebaseAuthException not found

It appears that this Firebase Auth class - part of the the Firebase SDK - was not found during the build.

Please try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) to rule out possible causes in your own project and to validate your build environment.

**Comment by dpa99c** [comment]
Closed due to no response from OP
