### ISSUE TITLE
IOS not tracking open analytics

### ISSUE THREAD

**Issue by ThatAbstractWolf** [dpa99c/cordova-plugin-firebasex#268]
# Bug report

**Current behavior:**

The bug seems to be that when you open a push notification, the notification only reports to Firebase that it has been opened on Android, IOS seems to not report the relevant data.

There is no code associated with the example projects to log the data, meaning it is done in the API.

**Expected behavior:**

The push notification should track the open analytic to the dashboard correctly. 

**Steps to reproduce:**

Send a push notification
Open it on the device (IOS & Android)
The data will not track when opening on IOS.

**Screenshots**

Total data:
![image](https://user-images.githubusercontent.com/19803119/72086692-42fabf80-32ff-11ea-8e35-faad1fdc1b9b.png)

IOS data:
![image](https://user-images.githubusercontent.com/19803119/72086699-47bf7380-32ff-11ea-9161-b843ae1edce4.png)

Android data:
![image](https://user-images.githubusercontent.com/19803119/72086706-4a21cd80-32ff-11ea-8274-33c94cbf62fc.png)

**Environment information**

**- Cordova CLI version**: latest version
**- Cordova platform version**: latest version

**Comment by dpa99c** [comment]
According to the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/understand-delivery#message-delivery-reports) Received and Impressions counts are only available on Android.

The open count is automatically incremented on Android but according to [this SO answer](https://stackoverflow.com/a/51316025/777265), it needs to manually call `appDidReceiveMessage` on the Firebase SDK so this will need to be added to the [`didReceiveRemoteNotification` function](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L144) for iOS

**Comment by remisture** [comment]
> The open count is automatically incremented on Android but according to [this SO answer](https://stackoverflow.com/a/51316025/777265), it needs to manually call `appDidReceiveMessage` on the Firebase SDK so this will need to be added to the [`didReceiveRemoteNotification` function](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L144) for iOS

@dpa99c dpa99cWill this plugin address this in a future release?
