### ISSUE TITLE
Custom Sound not working in Android 8+ devices

### ISSUE THREAD

**Issue by yugandhargangu** [dpa99c/cordova-plugin-firebasex#27]
Custom sound not working in Android 8+ devices.
It was working fine below Android 8 devices with below structure.

{
"registration_ids":<registration_ids>,
"data":{
  "title":<title>,
  "text":<text>,
  "icon":"notification_icon", // Already in resources
  "sound":"notification_sound" // Already in resources raw durectory
}
}

**Comment by dpa99c** [comment]
This should be fixed by merging PR [cordova-plugin-firebase#1035](https://github.com/arnesson/cordova-plugin-firebase/pull/1035) into this fork.

**Comment by yugandhargangu** [comment]
When it is going to merge with the code as, https://github.com/arnesson/cordova-plugin-firebase is not responding.

**Comment by dpa99c** [comment]
I've just published `cordova-plugin-firebasex@5.0.0`.
This is a major version that reworks the cloud messaging code and so will resolve this issue.
Please regression test using v5.0.0 of this plugin to confirm.

Note: v5.0.0 makes breaking changes to the plugin API - see the [CHANGELOG](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md#version-500) for details.

You may find it useful to test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which has a built-in FCM messaging client with test messages.

**Comment by dpa99c** [comment]
Fixed in v5.0.0

**Comment by Bobisback** [comment]
Any idea how to use this in ionic?
