### ISSUE TITLE
Ios Stuck on splash screen 

### ISSUE THREAD

**Issue by LincolnTx** [dpa99c/cordova-plugin-firebasex#271]
# Bug report

**Current behavior:**

On IOS after adding cocoapods on my project and got builds succeed, it's get stuck on splash screen forever, if it matters the console still showing all stuff

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
     9.0.0
	
- Cordova platform version
    IOS 5.0.1
- Plugins & versions installed in project (including this plugin)

cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.5.3 "cordova-plugin-ionic-webview"
cordova-plugin-keychain-touch-id 3.2.1 "TouchID and Keychain"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"

**Comment by dpa99c** [comment]
The issue is likely specific to your project and not caused specifically by this plugin - you'll need to debug using the JS and Xcode native consoles to look for an error.

You can confirm that this plugin works correctly in isolation by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

**Comment by LincolnTx** [comment]
I am looking on it right now, hope you're right

**Comment by LincolnTx** [comment]
Man i was able to solve this, but now i receive the notifications when app is open, but not the push when app is in background

**Comment by dpa99c** [comment]
>  but not the push when app is in background
If this happens with the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) also then a likely cause is your APNS is not setup correctly with Firebase - see the docs for instructions.

**Comment by LincolnTx** [comment]
Thank you bro! I'm closing this really appreciate the help.

**Comment by Siva021** [comment]
@LincolnTx  Man now i am stuck on same issue. Tried many thing didn't workout. How did you solve the issue?

**Comment by LincolnTx** [comment]
@Siva021 so, for me was a unsolved plugin that made the splashscreen stuck, if you have other branchs try to build your app in some of those, so you can understand which plugin is causing you the issue, High change that is not even the firebase plugin
