### ISSUE TITLE
setting for clear push notifications and force show

### ISSUE THREAD

**Issue by urlexnilz** [dpa99c/cordova-plugin-firebasex#272]
Hi all,

two questions, as I saw those features in the [phonegap plugin push](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushnotificationinitoptions) plugin

1.) clearNotifications: Is there a setting to stop the standard behavior of the firebaseX plugin: all push notifications will be cleared when app is opened?

2.) forceShow: when app is foreground you wont see them in statusbar / systembar. 

Thx

**Comment by dpa99c** [comment]
> 1.) clearNotifications: Is there a setting to stop the standard behavior of the firebaseX plugin: all push notifications will be cleared when app is opened?

There is no specific code in this plugin which clears notifications when the app is opened (although it does have a [clearAllNotifications()](https://github.com/dpa99c/cordova-plugin-firebasex#clearallnotifications) function you can call do manually clear them when the app is already open). You haven't specified whether it's Android or iOS you're referring to, but it's possible that the Firebase SDK itself does this.

> 2.) forceShow: when app is foreground you wont see them in statusbar / systembar.

When the app is in the foreground, by default this plugin will not display a notification in the system tray unless the notification message contains the key `"notification_foreground": "true"` - see [Foreground notifications](https://github.com/dpa99c/cordova-plugin-firebasex#foreground-notifications)

**Comment by yesyo** [comment]
Hi all,

I'm experiencing something like this, but I'm actually not sure if it's a bug or a feature. 
All push notifications all removed from the drawer when app is opened from destroyed(killed) state. If the app is resumed from background, then it's working fine.

I'm running the example app on Android 9 and 10. 
Built the app with the following:
- Cordova CLI version: 10
- Cordova platform version: android 9.1.0

iOS is behaving correctly.

Any thoughts?
Thanks.

**Comment by yesyo** [comment]
I think I've found the cause. The plugin [recreates the default channel](https://github.com/dpa99c/cordova-plugin-firebasex/blob/21aae9e9c50f2c8b2bd41ac9f9164da76e5237b7/src/android/FirebasePlugin.java#L211) every time when it's initializing. So the notifications got wiped out after deleting the previous created channel.
