### ISSUE TITLE
IOS null token error

### ISSUE THREAD

**Issue by mtnoronha** [dpa99c/cordova-plugin-firebasex#273]
Hi, 

I'm only opening this issue because I tried everything else I could find.  So, it works normally for Android, but not for IOS.

1) Already have the Firebase configuration OK for IOS (tried both: APN certificate and Auth Key).
2) Using code to getToken from the docs:

```
  async getToken() {
    let token;

    if (this.platform.is('android')) {
      token = await this.firebase.getToken();
    }

    if (this.platform.is('ios')) {
      token = await this.firebase.getToken();
      await this.firebase.grantPermission();
    }

    this.saveToken(token);
  }

```
3) Tried the "cordova-plugin-firebase-analytics" fix. 
4) My specs:
    Ionic 5.2.3
    Cordova 9.0.0 (cordova-lib@9.0.1)
    "cordova-plugin-firebase-analytics": "^4.0.1",
    "cordova-plugin-firebasex": "^7.0.1",
     "cordova-ios": "^5.1.1"

Another problem I have is that I dont have a MAC, so I use an online tool to build and deploy. So basically I need to debug this on production basically=/ 

Thank you in advance =]

**Comment by dpa99c** [comment]
As stated in [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#phonegap-build), this plugin will not work with online cloud build environments such as Phonegap Build because these are limited in their functionality, specifically most do not support Cordova hook scripts which are required by this plugin.
As such only local build environments - which are under the direct control of the plugin user - are supported.

**Comment by mtnoronha** [comment]
Thank you for your kind and quick answer.

**Comment by mtnoronha** [comment]
It turns out that I can run custom cordova hooks on the online build environment, I just need to specify them. Could you please guide me to which hooks I need to execute?

Thank you sir.

**Comment by dpa99c** [comment]
You can find the hook scripts used by this plugin in the `plugin.xml`

**Comment by vohrahul** [comment]
First of all @dpa99c, great work on this plugin mate. I would like to buy you a beer (please tell me how).
Now, I have tried everything, but still getting null on ios. I am not sure if this was closed correctly? I am using mac to build with cocoa pods, but still getToken is null.
Did everything that this issue states. Still null. Works on android.

Any reference would be great!

**Comment by dalybouba** [comment]
@mtnoronha  did you found a solution ??
