### ISSUE TITLE
Channel_Id reporting as null when sending push notification for Android task killed apps

### ISSUE THREAD

**Issue by Cancos** [dpa99c/cordova-plugin-firebasex#274]
# Bug report

**Current behavior:**

Our application currently faces issues receiving any push notifications against backgrounded, task-killed Android applications. It turns out that after debugging, I was able to identify the issue found at:

https://github.com/dpa99c/cordova-plugin-firebasex/blob/74064ec68b907a24244e8f1242a836ea3f580f3d/src/android/FirebasePluginMessagingService.java#L201

Code:
`// Channel
            if(channelId == null || FirebasePlugin.channelExists(channelId)){
                channelId = FirebasePlugin.defaultChannelId;
            }`

Not sure why this is the case, but when my channelId is set to "some_channel_id", for example, in the first clause it will result to false. However, in the second clause, it will result to true and set my chanelId to whatever FirebasePlugin.defaultChannelId is (e.g. "fcm_default_channel"). For some reason though, when I debugged the code, FirebasePlugin.defaultChannelId is setting channelId to null. This in turn causes the push to fail as it cannot find a channel id of null...

Flipping the code logic to the following for the second clause fixes the issue for me:

`// Channel
            if(channelId == null || !FirebasePlugin.channelExists(channelId)){
                channelId = FirebasePlugin.defaultChannelId;
            }`

**Expected behavior:**
Should receive push notification for backgrounded applications on Android when they are task killed.

**Steps to reproduce:**
Please refer to current behavior

**Environment information**

- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - Mac OS X
        - 10.14.6
        
_Runtime issue_
- Device details
    - Google Pixel
- OS details
    - Android 10.0
	
_Android build issue:_	
- Node JS version
    - 10.15.3
- Gradle version
	- 5.4.1
- Target Android SDK version
	- 28

**Related code:**
```
Current code experiencing issue
`// Channel
            if(channelId == null || FirebasePlugin.channelExists(channelId)){
                channelId = FirebasePlugin.defaultChannelId;
            }`

Added changes with fix

`// Channel
            if(channelId == null || !FirebasePlugin.channelExists(channelId)){
                channelId = FirebasePlugin.defaultChannelId;
            }`
```

**Console output**

**Other information:**

**Comment by dpa99c** [comment]
> However, in the second clause, it will result to true and set my chanelId to whatever FirebasePlugin.defaultChannelId is 

yes looks like a logic error from a missing `!` - thanks for point it out - will push a fix.

> For some reason though, when I debugged the code, FirebasePlugin.defaultChannelId is setting channelId to null

it should be set to the default Firebase channel ID as defined in the `AndroidManifest.xml`:

* https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L111
* https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L48
* https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/cordova-plugin-firebase-strings.xml#L3
