### ISSUE TITLE
Failed to install 'cordova-plugin-firebasex': Error: Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by neuronas** [dpa99c/cordova-plugin-firebasex#275]
# Bug report

**Current behavior:**

when i ran cordova platform add ios get the error : 
Failed to install 'cordova-plugin-firebasex': Error: Cannot find module 'xml2js'

it seems that a dependency is lost

 I'm just updated from cordova-plugin-firebasex version  6.0.7 to 7.0.1 and it start to happens

**Expected behavior:**
It should add ios platform successful 

**Steps to reproduce:**
rm -rf platforms/ios && rm -rf node_modules
npm i
npm run build
cordova platform add ios

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- Installed platforms:
           ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
       cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
       cordova-plugin-firebasex 6.0.7 "Google Firebase Plugin"
       cordova-plugin-whitelist 1.3.4 "Whitelist"
- Dev machine OS and version, e.g.
    - OSX
        - 10.15.2 (19C57)
    - XCode version
        - 11.3 (15712)
	
_iOS build issue:_
- Node JS version
    -  v12.14.0
- XCode version
   -  11.3 (15712)

**Related code:**
```
cordova platform add ios
```

**Console output**
```
Using cordova-fetch for cordova-ios@^5.1.1
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.MyAppName.app
	Name: myAppName
iOS project created with cordova-ios@5.1.1
Installing "cordova-plugin-androidx" for ios
Installing "cordova-plugin-androidx-adapter" for ios
Installing "cordova-plugin-firebasex" for ios
Plugin dependency "cordova-plugin-androidx@1.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-androidx" already installed on ios.
Plugin dependency "cordova-plugin-androidx-adapter@1.1.0" already fetched, using that version.
Dependent plugin "cordova-plugin-androidx-adapter" already installed on ios.
Running command: pod install --verbose

[!] The `MyAppName [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyAppName/Pods-MyAppName.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `MyAppName [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-MyAppName/Pods-MyAppName.release.xcconfig'. This can lead to problems with the CocoaPods installation

Failed to install 'cordova-plugin-firebasex': Error: Cannot find module 'xml2js'
Require stack:
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/ios/helper.js
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /Users/user/n/lib/node_modules/cordova/src/help.js
- /Users/user/n/lib/node_modules/cordova/src/cli.js
- /Users/user/n/lib/node_modules/cordova/bin/cordova
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
Cannot find module 'xml2js'
Require stack:
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/lib/utilities.js
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/ios/helper.js
- /Users/user/projects/MyAppName/plugins/cordova-plugin-firebasex/scripts/ios/after_plugin_install.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /Users/user/n/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /Users/user/n/lib/node_modules/cordova/src/help.js
- /Users/user/n/lib/node_modules/cordova/src/cli.js
- /Users/user/n/lib/node_modules/cordova/bin/cordova

```

**Other information:**

needed to install npm i xml2js lib to success create ios platform

**Comment by pghoratiu** [comment]
I also experience this issue in a monorepo multi project ionic setup. 
It got resolved by itself after cleaning up the project and reinstalling the dependencies.

**Comment by dpa99c** [comment]
`xml2js` was replaced with `xml-js` in a [rework of the hook scripts](https://github.com/dpa99c/cordova-plugin-firebasex/commit/bda54cb59293cf0ca8f72e0b3263a4890a228f55) therefore `xml2js` is [no longer a dependency](https://github.com/dpa99c/cordova-plugin-firebasex/search?q=xml2js&unscoped_q=xml2js).

It may be that upgrading from an earlier version of the plugin causes this issue so to resolve this be sure to completely uninstall and remove the older version of the plugin from your project.

You can confirm the plugin works correctly in a clean project environment by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Comment by neuronas** [comment]
in the test projects you have "xml2js": "^0.4.19" as a devDependencies, also the got the error when run cordova prepare android, I install it as a devDependencie anyway, thanks
