### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by salehasadi** [dpa99c/cordova-plugin-firebasex#280]
# Bug report

**Current behavior:**
Hi I just added this plugin to my project step by step based on Documents but after running app showing blank screen and as I checked in adb logcat results it says : 

> 01-21 10:17:59.966 31538 31538 I chromium: [INFO:CONSOLE(57378)] "ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[HomePage -> FirebaseX]: 
01-21 10:17:59.966 31538 31538 I chromium:   StaticInjectorError(Platform: core)[HomePage -> FirebaseX]: 
01-21 10:17:59.966 31538 31538 I chromium:     NullInjectorError: No provider for FirebaseX!
01-21 10:17:59.966 31538 31538 I chromium: Error: StaticInjectorError(AppModule)[HomePage -> FirebaseX]: 
01-21 10:17:59.966 31538 31538 I chromium:   StaticInjectorError(Platform: core)[HomePage -> FirebaseX]: 
01-21 10:17:59.966 31538 31538 I chromium:     NullInjectorError: No provider for FirebaseX!

also when I remove FirebaseX from my component app run and works perfectly as before

**Expected behavior:**
run and work and also log the firebase token to console

**Steps to reproduce:**

**Screenshots**
<img src="https://user-images.githubusercontent.com/14921568/72782495-1321b500-3c39-11ea-8cca-a551fea51db8.png" width="300" height="500">

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `android 8.1.0`
  - `ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - `com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"`
-`cordova-plugin-actionsheet 2.3.3 "ActionSheet"`
-`cordova-plugin-advanced-http 2.3.1 "Advanced HTTP plugin"`
-`cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"`
-`cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"`
-`cordova-plugin-camera 4.1.0 "Camera"`
-`cordova-plugin-device 2.0.3 "Device"`
-`cordova-plugin-dialogs 2.0.2 "Notification"`
-`cordova-plugin-file 6.0.2 "File"`
-`cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"`
-`cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"`
-`cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"`
-`cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"`
-`cordova-plugin-splashscreen 5.0.3 "Splashscreen"`
-`cordova-plugin-statusbar 2.4.3 "StatusBar"`
-`cordova-plugin-whitelist 1.3.4 "Whitelist"`
-`uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"`
- Dev machine OS and version, e.g.
    - Linux
        - `Deepin`
        
</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
The adb logcat extract you provided shows the JS console output of Ionic which is mirrored to the native logcat. It gives no indication of a cause of the issue and I would speculate the problem lies within your use of the plugin within the Ionic layer.

You can validate that this plugin works correctly by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

**Comment by salehasadi** [comment]
@dpa99c I'm not saying that plugin does not work, I'm asking to know what's the problem that as I implement this plugin in project and start to use it as docs 

https://github.com/dpa99c/cordova-plugin-firebasex#ionic-4
it shows a blank screen to me, and now I'm working with this plugin but not as the doc. I'm using it like this and it works for me
![image](https://user-images.githubusercontent.com/14921568/72800016-a79d0f00-3c5b-11ea-9d1a-a246314fde39.png)

and is this a correct way of using this!?
thanks

**Comment by dpa99c** [comment]
The [FirebaseX Typescript API](https://ionicframework.com/docs/native/firebase-x) is owned and maintained by Ionic and provides a wrapper around the JS plugin API that this plugin provides.

If your implementation works but their example implementation does not, you may wish to raise an issue against Ionic Native to resolve this.

**Comment by salehasadi** [comment]
> The [FirebaseX Typescript API](https://ionicframework.com/docs/native/firebase-x) is owned and maintained by Ionic and provides a wrapper around the JS plugin API that this plugin provides.
> 
> If your implementation works but their example implementation does not, you may wish to raise an issue against Ionic Native to resolve this.

ooh, Ok thanks for that
