### ISSUE TITLE
plugin not compatible with cordova-plugin-code-push

### ISSUE THREAD

**Issue by isreehari** [dpa99c/cordova-plugin-firebasex#286]
We had the same issue in cordova-plugin-firebase with code-push 
 - https://github.com/arnesson/cordova-plugin-firebase/issues/1086
We are getting the same issue in cordova-plugin-firebasex with code-push. I am just creating an issue here so that other can solution. 

```
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1,2.3]"

but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was 2.3.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the artsitive dependencies that lead to the art ifact with the issue.

-- Project 'app' depends onto net.minidev:json-smart@2.3
-- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@5.1
```

**Comment by brassier** [comment]
Thanks for posting this.  I'm running into this too.  I've seen hints of `com.google.gms:google-services:4.3.3` resolving some of these dependency problems.  If I manually add this to my root build.gradle it also seems to work.

I don't know all of the inter-dependencies, but I'm curious if adjusting below to 4.3.3 would resolve this issue in a cleaner way?  @dpa99c - is this a possibility from your perspective?
https://github.com/dpa99c/cordova-plugin-firebasex/blob/c2222555b2cace5c53ffc3023dae277aae881fee/src/android/build.gradle#L13

**Comment by brassier** [comment]
I did just run a test locally by simply updating the line above to 4.3.3.  That did get past the build issues with the CodePush plugin.  @dpa99c - are there any negative impacts to adjusting this to 4.3.3?
