### ISSUE TITLE
ERROR: Error: Internal error encountered.

### ISSUE THREAD

**Issue by WEBGONDEL** [dpa99c/cordova-plugin-firebasex#289]
Hello dpa99c,

I have downloaded your sample firebasex-test project, but after i added the token and all instructions the only error I am getting is:

ERROR: Error: Internal error encountered.

How can I find out what exactly the problem is?

Thank you so much for you work and your help.

greetings from Germany

Edit: if i changing one letter of the token i am getting an error related to a wrong token, so this connection is alread working...

**Comment by dpa99c** [comment]
I am unable to offer support for specific usage problems with this plugin - please use issues to report suspected bugs or request new features.
You can ask for support on StackOverflow, Ionic Forums, or elsewhere.
