### ISSUE TITLE
IOS Notifications not showing if cordova-plugin-deeplinks installed (can be reproduced with cordova-plugin-firebasex-test)

### ISSUE THREAD

**Issue by Amaury-T** [dpa99c/cordova-plugin-firebasex#292]
Hello @dpa99c 

First of all, thanks for this plugin.
Anyway, I have been struggling with my IOS notifications for a few days now... And I have finally identify the issue.

**Current behavior:**

The source of the pb is the use of this plugin with the cordova-plugin-deeplinks plugin.
[https://www.npmjs.com/package/cordova-plugin-deeplinks](url)
[https://github.com/e-imaxina/cordova-plugin-deeplinks](url)

On android all is fine, deep linking and notifications are working.
On IOS deeplinking is working but not the notification. The app could still receive messages, onMessageReceived is called (even if it is in background, once in foreground we can see the log of the notification) BUT, no notifications are displayed (when app is in background), no pop up, nothing in the notification center, nothing at all...
If I remove the cordova-plugin-deeplinks plugin and delete/add platform again, notifications are woking fine.

This have been tested on a real iphone 5s with IOS 12.4.5 with the cordova-plugin-deeplinks test example.

I don't understand yet deeply how plugins works but I hope it will be easily fixable

**Expected behavior:**

Both plugins can work together.

**Steps to reproduce:**
On the cordova-plugin-firebasex-test project, add in config.xml 
`    <universal-links>
      <host name="abc scheme="https" />
    </universal-links>`
It doesn't matter if there is or not a real deeplnking configured, in both case, notification does not work, I have tested both, with a real configured deeplink, and with this one.

add plugin cordova-plugin-deeplinks
`cordova plugin add cordova-plugin-deeplinks`

deploy the app on real iphone, launch it, accept permission, retrieve fcm token, put it in background and try to send a notification (with the firebase console for example).

No notification will be shown, once the app in foreground, log of onMessage is displayed.

**Environment information**

All have been tested with your example repo cordova-plugin-firebasex-test
[https://github.com/dpa99c/cordova-plugin-firebasex-test](url)

- Cordova CLI version 
9.0.0 (cordova-lib@9.0.1)

- Cordova platform version
Installed platforms:
  ios 5.1.1
Available platforms: 
  android ^8.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-deeplinks 1.1.1 "Cordova Deeplinks Plugin"
cordova-plugin-firebasex 7.0.2 "Google Firebase Plugin"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version, e.g.
    - OSX
ProductName:	Mac OS X
ProductVersion:	10.15.2
BuildVersion:	19C57        

_Runtime issue_
- Device details
Real Iphone 5S

- OS details
IOS 12.4.5
	

Thanks again for your time.
BR

**Comment by Amaury-T** [comment]
Hello, is there a way to have both plugins cordova-plugin-deeplinks and cordova-plugin-firebasex woking together in IOS ?

**Comment by dpa99c** [comment]
One possible problem is that `cordova-plugin-deeplinks` [contains an iOS AppDelegate](https://github.com/e-imaxina/cordova-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BCULPlugin.m) which [implements the `didReceiveRemoteNotification`](https://github.com/ionic-team/ionic-plugin-deeplinks/blob/master/src/ios/AppDelegate%2BIonicDeeplink.m#L86) and this plugin [also contains its own AppDelegate](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m) to receive remote notifications. 
However iOS only allows one AppDelegate so when both of these plugins are added to a project, only one will be called.

`cordova-plugin-deeplinks` also [contains numerous hook scripts](https://github.com/e-imaxina/cordova-plugin-deeplinks/tree/master/hooks) which could cause issues with the hooks scripts this plugin uses to configure the native Xcode project for iOS.

Unfortunately I cannot provide support in diagnosing the conflicts between various plugins and this one. i.e. this plugin works fine in isolation

**Comment by lukke1603** [comment]
@Amaury-T Did you find a solution for that problem?
