### ISSUE TITLE
iOS notification don't arrive when app is in background mode

### ISSUE THREAD

**Issue by appsOne** [dpa99c/cordova-plugin-firebasex#293]
Dear @dpa99c ,

thank you for this plugin, we use it on our app and everything work almost perfect.

We have some problem with receiving notification on iOS device. When app is on in the background mode (or killed) and we send notification through Firebase Console in most terms notification doesn't arrive.
We have enable capabilities in Xcode for Push Notification and Background mode -> Remote notification. Also in Firebase we have imported APNs Authentication Key.

We use this code for obtain token (same for Android):
```
this.firebaseX.hasPermission().then((hasPermission: boolean) => {
    if(hasPermission){
        this.firebaseX.getToken().then((token: string) => {
            // SAVE TOKEN ON FIRESTORE
        })
    } else {
        this.firebaseX.grantPermission().then((hasPermission: boolean) => {
            if (hasPermission){

                this.firebaseX.getToken().then((token: string) => {
                    // SAVE TOKEN ON FIRESTORE
                })
            }
        });
    }
})
```

My question is are we using these methods the right way? Do we need to use `getAPNSToken()` for iOS?

Thanks

**Comment by dpa99c** [comment]
You can build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to verify your APNS configuration with Firebase. Misconfigured APNS in Firebase or provisioning profile without APNS permission are the most common cause of this issue.
