### ISSUE TITLE
Is it possible to let IOS itslelf handle the badge count like on Android ?

### ISSUE THREAD

**Issue by Amaury-T** [dpa99c/cordova-plugin-firebasex#294]
Hello,

I would like to understand if it is a normal behaviour that on IOS, badge count is not auto incremented like on android? (Tested with my app and the the cordova-plugin-firebasex-test app on an Iphone 5S with IOS 12.4.5)

I saw that we can update the badge count either on the notification message itself or on the app directly by calling setBadgeNumber method, but I would have liked to let the system handle the badge count, like android does. Is it possible on IOS, does it requires something to do?

**Comment by dpa99c** [comment]
Neither iOS or Firebase automatically tracks and increments the badge count on iOS so this is something you must do yourself by keeping track and incrementing the counter on either your server or from within the app - see [this SO post](https://stackoverflow.com/a/54830942/777265)

**Comment by Amaury-T** [comment]
Thanks for the response, it's what I thought I understood.
I will manage it server side. 
Thanks again!
