### ISSUE TITLE
Push icon is a filled square of accent color or a monochrome

### ISSUE THREAD

**Issue by ir2pid** [dpa99c/cordova-plugin-firebasex#296]
I can't get the push icons to show up for android devices.

icon is: 
![xxxhdpi](https://user-images.githubusercontent.com/907075/73858421-a9102f00-4838-11ea-8632-6c413263e635.png)

I apply the accent color and add it to my manifest as:
in config.xml

```
<config-file parent="/manifest/application" target="AndroidManifest.xml">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>
```
in package.json

```
      "cordova-plugin-firebasex": {
        "ANDROID_ICON_ACCENT": "#FF0076B2"
       }
```

the issue is during push for android devices, 

- either the push icon is in monochrome or

- the push icon is a filled accent rectangle

I checked the platform folder and see all the mdpi, ldpi xhdpi monochrome drawables called "notification_icon.png" there.

**Comment by dpa99c** [comment]
Android only supports monochrome icons in the statusbar - polychromatic images are not supported.
