### ISSUE TITLE
Push notification when app is open

### ISSUE THREAD

**Issue by oscarsales** [dpa99c/cordova-plugin-firebasex#302]
When the app is open (foreground), the onMessageReceived event triggers, but the notification doesn't appear in the device notification bar, only when the app is closed (background).

Maybe this is intentional, because I've seen other developers reporting or complaining about this as a bug. In my case, my client needs notifications to arrive also when the app is open. Actually, this used to work correctly in the past, but at some point we updated dependencies, made changes to the ionic project, and now notifications don't arrive. (So I can't tell him it's not possible, because he remembers it used to work).

I tried combining this plugin with the local-notifications plugin, to display a notification manually when onMessageReceived triggers, android OK, but as already reported in this page, then iOS doesn't work (both plugins conflict, and push stop working).

I've seen in some forums that it's possible to make changes to the native code directly to solve this problem, but that code wouldn't be included in the repository, which means that it wouldn't work for someone else who downloaded the project.

**Comment by dpa99c** [comment]
See [Foreground notifications](https://github.com/dpa99c/cordova-plugin-firebasex#foreground-notifications) and try it in the [example app project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Comment by oscarsales** [comment]
@dpa99c ok, but according to your link, this option "notification_foreground", must be set in the backend, which is sending the notifications, there's nothing I can do from the app in ionic?. I'm saying this because someone else is programming the backend, not me. So there's nothing I can do, I need to report it so they make the change. Correct?

**Comment by dpa99c** [comment]
Yes, this plugin expects that you are in control of the FCM message payload being sent to the app and can add the necessary keys as outlined in the documentation.
