### ISSUE TITLE
iOS wont archive

### ISSUE THREAD

**Issue by stuhowarth** [dpa99c/cordova-plugin-firebasex#303]
Ok so I 'WAS' havign quite a major issue with the app archiving in Xcode. Firebase was working on Android and also on iOS if I directly installed it to my device from Xcode but the minute I tried to archive it I was getting errors like the following:

Undefined symbol: _OBJC_CLASS_$_CLSStackFrame firebasex
Undefined symbols for architecture armv7: "_GULLogBasic", referenced from: _FIRLogBasic in FirebaseCore(FIRLogger.o)
Firebase.h file not found

I followed the countless fixes which included things like adding $(inherited) or adding the missing frameworks to the linked embedded libraries. NOTHING WORKED. However I eventually got it fixed on my own accord. Here are the steps I did just in case anybody else is having this issue.

1 - Remove the iOS platform - sudo cordova platform rm ios
2 - Remove Firebasex - sudo cordova remove plugin cordova-plugin-firebasex
3 - Check to ensure firebasex files are removed from both the plugins folder and package.json
4 - Remove any other google analytics plugin (I also had cordova-plugin-google-analytics)
5 - Add iOS platform sudo cordova platform add iOS
6 - Follow cocapods installation highlighted in the these docs:

**Comment by dpa99c** [comment]
Thanks for posting your solution however it seems specific to your project and possibly due to a conflict with another plugin (e.g. cordova-plugin-google-analytics).

If you are able to reproduce the issue in the isolation of the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) please let me know.

**Comment by stuhowarth** [comment]
Hey, I accidently submitted this too soon. This post was for others to follow who may be in the same situation as me. Yes you are correct that I think the issue was the conflict with cordova-plugin-google-analytics.
