### ISSUE TITLE
Error when adding platform

### ISSUE THREAD

**Issue by mishkeTz** [dpa99c/cordova-plugin-firebasex#308]
# Bug report

**Current behavior:**

I got an error with this plugin when adding the platform. When I downgraded version to **6.0.2** I didn't get that error anymore but I got another error on runtime saying: 'Failed to connect to direct channel, error: error domain=com.google.fcm code=501 "(null)"'

    Running command: pod install --verbose
    Searching for inspections failed: #<Pod::UserInterface::InspectorReporter:0x007f8dd474eaa0> 
    does not handle inspector_successfully_recieved_report

    Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1 Error 
    output:
    Searching for inspections failed: #<Pod::UserInterface::InspectorReporter:0x007f8dd474eaa0> 
    does not handle inspector_successfully_recieved_report
        at ChildProcess.whenDone (/Users/mac/Framework7/cordova-plugin-firebasex- 
    test/node_modules/cordova-common/src/superspawn.js:135:23)
        at ChildProcess.emit (events.js:159:13)
        at maybeClose (internal/child_process.js:943:16)
        at Socket.stream.socket.on (internal/child_process.js:363:11)
        at Socket.emit (events.js:159:13)
        at Pipe._handle.close [as _onclose] (net.js:568:12)
    Failed to restore plugin "cordova-plugin-firebasex" from config.xml. You might need to try adding 
    it again. Error: Error: pod: Command failed with exit code 1 Error output:
    Searching for inspections failed: #<Pod::UserInterface::InspectorReporter:0x007f8dd474eaa0> 
    does not handle inspector_successfully_recieved_report

**Expected behavior:**
It should install the plugin without any errors.

**Steps to reproduce:**
I installed fresh [cordova-plugin-firebasex-test](https://github.com/dpa99c/cordova-plugin-firebasex-test) project per documentation. 

**Environment information**

- Cordova CLI version 
        - 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
        - ios 5.1.1
- Dev machine OS and version, e.g.
    - OSX
        - ProductName: Mac OS X / ProductVersion:	10.15.2

_Runtime issue_
- Device details
    - iPhone 6
- OS details
    - iOS 12.4.5	
	
_iOS build issue:_
- Node JS version
    - v9.3.0
- XCode version
    - 11.3.1

**Console output**
<summary>Failed to connect to direct channel, error: error domain=com.google.fcm code=501 "(null)"</summary>
</details><br/><br/>

**Comment by dpa99c** [comment]
> Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1

Most likely your local pod repo is out-of-date so it can't find the latest Firebase SDK components referenced in the latest plugin version.

Try this:

    pod repo update
    cordova platform rm ios --nosave 
    cordova platform add ios --nosave

**Comment by mishkeTz** [comment]
@dpa99c `pod repo update` fixed the problem. Thanks a lot!

**Comment by tomavic** [comment]
This issue raised again with Macbook M1 and a fresh clone from ionic tabs template.

```
 cordova platform add ios --nosave
Using cordova-fetch for cordova-ios@^5.1.1
(node:58283) Warning: Accessing non-existent property 'ios' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Adding ios project...
iOS project created with cordova-ios@5.1.1
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-firebasex" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
pod: Command failed with exit code 1

```

**Comment by rikwijnen** [comment]
I've got the same error as @tomavic described on a MacBook Pro with M1 chip. `pod repo update` does not fix the issue on newer MacBooks.

@dpa99c, can you have a look at the issue? Please let me know if you need more information.

**Comment by slothstronaut** [comment]
Just to add a bit more details to the above answer, you need to run

```
sudo arch -x86_64 gem install ffi
```

...from any directory.

Then once done, cd into your `cordova/platform/ios` directory

and run:

```
arch -x86_64 pod install
```

Then remove and add platform again, and it should work the next time 👍 

Also happened after trying to setup a cordova project on M1 for the first time.
