### ISSUE TITLE
Error collecting project

### ISSUE THREAD

**Issue by w4ugit** [dpa99c/cordova-plugin-firebasex#310]
Updated the plugin to version 8.0.0. I get this error when trying to compile a project

The following build commands failed:
        CompileC /Users/taruk/Library/Developer/Xcode/DerivedData/Є-Експрес-dwyvlsirxfirovdjubnxnkrahpxk/Build/Intermediates.noindex/Є-Експрес.build/Debug-iphonesimulator/Є-Експрес.build/Objects-normal/x86_64/AppDelegate+FirebasePlugin.o Є-Експрес/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

Help me understand why it occurs?

**Comment by dpa99c** [comment]
This is not enough information to diagnose the cause of your issue. 
However error code 65 often refers to a code signing error. 
Also make sure you have updated your local Cocoapods repo with `pod repo update`, then remove+re-add the Cordova iOS platform and clean the build in Xcode before attempting to build again.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by alemdg** [comment]
still happening......

today with test project.
