### ISSUE TITLE
Property does not exist on type 'FirebasePlugin'

### ISSUE THREAD

**Issue by nightowlcodes** [dpa99c/cordova-plugin-firebasex#313]
# Bug report
I cannot use many of firebase auth properties for example using signInUserWithEmailAndPassword  return Property 'signInUserWithEmailAndPassword' does not exist on type 'FirebasePlugin'; 
I am using Ionic V5

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms:
  android 8.1.0
  browser 6.0.0`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 8.0.0 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"`

**Related code:**
signIn() {
window.FirebasePlugin.signInUserWithEmailAndPassword('email@email.com', '123456',
      success => {
        console.log( success); 
      }, error => { console.log(error);}
 }

</details><br/><br/>

**Comment by dpa99c** [comment]
`signInUserWithEmailAndPassword()` [does exist](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/www/firebase.js#L238) along with the other v8 auth functions - please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for usage examples.

Note that the FirebaseX Ionic Typescript wrapper has not yet been updated to add Typescript mappings for these new functions - please feel free to open an issue against Ionic Native to request that they be added.
