### ISSUE TITLE
Analytics/Crash/Performance Collection enabling is unclear

### ISSUE THREAD

**Issue by TdoubleG** [dpa99c/cordova-plugin-firebasex#315]
# Documentation issue

It's unclear if we need to call the analytics collection on every start of the app (session based) or is it enough to enable/disable the collections only once, like the plugin stores the information about the status? 

Same question for crashlytics and performance.

**Comment by dpa99c** [comment]
This is outlined in the [Firebase documentation](https://firebase.google.com/docs/analytics/configure-data-collection) - i.e. the setting persists between sessions - but I'll add a note to the documentation to make this clearer
