### ISSUE TITLE
iOS build failed issue with AppAuth Pod

### ISSUE THREAD

**Issue by Fever905** [dpa99c/cordova-plugin-firebasex#319]
Not sure what is going on, using cordova ios@5.1.1 and getting a compile error with AppAuth:

The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/Oil_Analysis-alepbbrfapgngxbrndlbvvkdcvqp/Build/Intermediates.noindex/ArchiveIntermediates/Oil\ Analysis/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/AppAuth.build/Objects-normal/arm64/OIDExternalUserAgentIOSCustomBrowser.o /Users/user/oa/platforms/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Not sure if there is an actual problem with that POD or with all of them because that is the first one.

Tried removing platforms completely, reading the ios platform then adding the plugin

Have updated the pods, the pod depencency manager, installed all the gems, done everything.

Any idea?  Is it an issue with 5.1.1 and 5.1.0  ?  It was working fine for me earlier today witgh 5.0.1 but I need 5.1.0+ to use WKWebView instead of the old one.

My build does work without this plugin, but I need this for firebase notifications.

Any ideas?

**Comment by dpa99c** [comment]
Please make sure you have set up Cocoapods and updated your local pods repo using `pod repo update`. See the documentation for details. Try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment against a known working codebase.

Closing as this issue seems specific to your build env - works fine my build envs using `cordova-ios@5,1,1`

**Comment by Fever905** [comment]
Yep, I've done that numerous times.  I'm going to start fresh again and see if I can get it working.

**Comment by Fever905** [comment]
Ah, well no the example project does not compile either, gets an error at the same spot.

** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/user/Library/Developer/Xcode/DerivedData/FirebaseTest-hkgzcyasfxzxizhgjdtaovnujyrt/Build/Intermediates.noindex/ArchiveIntermediates/FirebaseTest/IntermediateBuildFilesPath/Pods.build/Debug-iphoneos/AppAuth.build/Objects-normal/armv7/OIDExternalUserAgentIOSCustomBrowser.o /Users/user/fbx/cordova-plugin-firebasex-test/platforms/ios/Pods/AppAuth/Source/iOS/OIDExternalUserAgentIOSCustomBrowser.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
Users-iMac:cordova-plugin-firebasex-test user$

**Comment by dpa99c** [comment]
Here's my [console.log](https://github.com/dpa99c/cordova-plugin-firebasex/files/4267448/console.log) for the build

**Comment by Fever905** [comment]
Tried another fresh install using ios@5.0.0 and same result.  What could be causing this!

**Comment by Fever905** [comment]
I'm wondering if the latest cocoapods update no longer works with XCode 10.1 .. That's the only thing I can think of.   I will try again in my cloud environment using the latest XCode.  This Mac I have locally won't let me go to the latest version :(

**Comment by Fever905** [comment]
![Screen Shot 2020-02-28 at 10 31 36 AM](https://user-images.githubusercontent.com/2319655/75561988-e1f58b00-5a15-11ea-8c12-17bd3b1bbf49.png)
I'm getting a parse error on the AppAuth file, expected "," ... see screenshot.  What would be causing this!!?

**Comment by Fever905** [comment]
Seems like others have had this problem https://stackoverflow.com/questions/59023380/firebase-ios-swift-authentication-api-unavailablemaccatalyst-problem

**Comment by Fever905** [comment]
After some trial and error I found a solution. Use pod 'GoogleSignIn', '~> 4.1.1' instead of version 5.0.1 -- for anyone using XCode 10.1  .. the new GoogleSignin only works with Xcode 11+

**Comment by Fever905** [comment]
Is there any way to build it without the Google Signin?

**Comment by dpa99c** [comment]
Not without forking the plugin and removing it yourself

**Comment by Fever905** [comment]
I've put in a request to my boss to buy me a new Mac.  This is just sillly trying to work in a Legacy environment.  Thanks for your help on this.

**Comment by dpa99c** [comment]
Yeah, Apple is always going to deprecate old hardware pretty fast so they can sell you new hardware!
Look out for their new Macs due later this year which use Apple ARM architecture instead of Intel x86.
I'm pretty sure they will deprecate the Intel-based Macs soon after their ARM Macs hit the market.
So lookout for the next major version of Xcode which runs on ARM-based Macs only 😠 

Tell your boss I told him to buy you a new Mac 😁

**Comment by Fever905** [comment]
Oh no lol. Well we got the 2018 model iMac 21 inch.  Come on they can't deprecate all the intel machines can they?  Not for a long time I think.

**Comment by AbdullaevTimur** [comment]
Hi, I have issue with AppAuth too. 

If I downgrade _AppAuth_ to _1.2.0_ or try to use _GoogleSignIn 4.1.1_ then i catch a lot of errors _(14)_ linked with this items. For example with **ASAuthorizationControllerDelegate**: _Cannot find protocol declaration for 'ASAuthorizationControllerDelegate';_ And also a lot of errors in _AppDelegate(FirebasePlugin)_ in _"Apple Sign In"_ section _(l.504)_. The same with corodova-plugin-firebasex-test ENV. 

May ot be Xcode version? My Xcode version 10.1

**Comment by danigv** [comment]
Hello,

I'm having this issue with Xcode 10.1, which I assume is incompatible with the plugin recent versions.

So I guess the last version compatible with Xcode 10 is 7.0.2, right? Thank you!

**Comment by romainfd** [comment]
Hello,

Based on my test `7.0.2` was the latest version not requiring `GoogleSignIn` and downgrading to this version fixed it for me.
