### ISSUE TITLE
Uncaught TypeError: window.FirebasePlugin.onNotificationOpen is not a function

### ISSUE THREAD

**Issue by DangerD256** [dpa99c/cordova-plugin-firebasex#320]
Code worked fine before until old cordova-plugin-firebase became deprecated and i had to update everything and install cordova-plugin-firebasex since i couldn't compile app.
I'm able to get token and receive notification but only `onNotificationOpen` fails...

```
	window.FirebasePlugin.onTokenRefresh(function(token) { // This works
		saveToken(token);
	}, function(error) {
		console.error(error);
	});
	window.FirebasePlugin.onNotificationOpen(function(data) { //window.FirebasePlugin.onNotificationOpen is not a function
		alert('Notification'+JSON.stringify(data));
	});
```

Any suggestion?

**Comment by dpa99c** [comment]
`onNotificationOpen` has been replaced with `onMessageReceived`.
Please read the documentation,

**Comment by DangerD256** [comment]
Thanks, works fine now =)
