### ISSUE TITLE
xcodebuild: Command failed with exit code 65

### ISSUE THREAD

**Issue by jpduckwo** [dpa99c/cordova-plugin-firebasex#323]
# Bug report

**Current behavior:**

Building the test repo or my project results in error `xcodebuild: Command failed with exit code 65`

Error building `cordova-plugin-firebasex-test` (commit da195ce3639ab1b54ef1937cfb9464499546f02a)

```
The following build commands failed:
	CompileC /Users/xxx/Library/Developer/Xcode/DerivedData/FirebaseTest-dlrluwgizrqcdxctqasjwtfzumhl/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/CustomFCMReceiverPlugin.o /Users/xxx/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-customfcmreceiver/CustomFCMReceiverPlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
```

Error building my project

```
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/xxx/Library/Developer/Xcode/DerivedData/Crewmojo-axcclukmppzuamdsybrlucydvkpv/Build/Intermediates.noindex/Crewmojo.build/Debug-iphonesimulator/Crewmojo.build/Script-C83E948905523E6F7C12544B.sh
(1 failure)
xcodebuild: Command failed with exit code 65
```

I have tried to many pod related reinstallation steps e.g. reinstalled ruby / cocoapods / pod repo / pod install etc.

**Expected behavior:**
The test project should compile

**Steps to reproduce:**
Checked out latest test project
npm install
cordova platform add ios
cordova build ios

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms:
  android 8.1.0
  ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - `cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 8.1.0 "Google Firebase Plugin"
cordova-plugin-googleplus 8.4.0 "Google SignIn"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 2.1.4 "Cordova WKWebView File XHR Plugin"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"`
- Dev machine OS and version, e.g.
    - OSX
        - `ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76`
        
_iOS build issue:_
- Node JS version
    - `v12.3.1`
- XCode version
    - `Version 11.3.1 (11C504)`

**Comment by dpa99c** [comment]
Sorry, this was my fault. 

I updated the test project to use the new iOS custom receiver mechanism but that functionality was still on the master branch of this plugin and hadn't been published yet, so when you built the test project it pulled in v8.1.0 of this plugin from npm which doesn't contain the  iOS custom receiver code.

I've just published v8.1.1 to npm which contains the custom receiver code, so that resolves the build issue with the test project.

**Comment by stegithub** [comment]
Hi @dpa99c , i've the same problem with latest version 8.1.1

**Comment by dpa99c** [comment]
@stegithub this specific issue was caused by the example project containing code referencing a plugin class not present in v8.1.0 but this class is present in v8.1.1.

In which case you would see an error something like this:

	In file included from /Users/dave/Documents/projects/@scratch/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-customfcmreceiver/CustomFCMReceiverPlugin.m:2:
	/Users/dave/Documents/projects/@scratch/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-customfcmreceiver/CustomFCMReceiver.h:1:9: fatal error: 'FirebasePluginMessageReceiver.h' file not found
	#import "FirebasePluginMessageReceiver.h"
	    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    The following build commands failed:
	CompileC /Users/dave/Library/Developer/Xcode/DerivedData/FirebaseTest-clkbkirulkdcdkhhnvihqrtnnweg/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/CustomFCMReceiver.o /Users/dave/Documents/projects/@scratch/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-customfcmreceiver/CustomFCMReceiver.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

If not, please check your build is not actually failing due to #326.
