### ISSUE TITLE
bug: Conflict with GoogleTagManager

### ISSUE THREAD

**Issue by HansKrywaa** [dpa99c/cordova-plugin-firebasex#327]
# Bug report

**Current behavior:**

In Version `8.1.0` the GoogleTagManager was added. This seems to be a Problem with the [Google Maps Plugin](https://www.npmjs.com/package/cordova-plugin-google-analytics) i need. Error Log while building for iOS is:

> duplicate symbol '_OBJC_METACLASS_$_TAGUniversalAnalytics' in:
    /platforms/ios/Pods/GoogleTagManager/Frameworks/GoogleTagManager.framework/GoogleTagManager(TAGUniversalAnalytics_47ae6af5e05e8872f6f955d1561b62df.o)
    /Plugins/cordova-plugin-google-analytics/libGoogleAnalyticsServices.a(TAGUniversalAnalytics.o)
ld: 334 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And many other similar to this.

Downgrading FirebaseX to `8.0.1` worked, but that is of course not want i want. I'm not as much into native IOS Development so maybe you know **how to fix this**?

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms:
  android 8.1.0
  ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    <details>
    <summary>Show Installed Plugins</summary>

    ```
    call-number 0.0.2 "Cordova Call Number Plugin"
    cordova-background-geolocation 3.6.0 "BackgroundGeolocation"
    cordova-clipboard 1.3.0 "Clipboard"
    cordova-open-native-settings 1.5.2 "Native settings"
    cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
    cordova-plugin-advanced-background-mode 1.0.4 "BackgroundMode"
    cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
    cordova-plugin-advanced-nativeaudio 1.0.2 "Cordova Native Audio"
    cordova-plugin-advanced-websocket 1.1.5 "Cordova advanced websocket plugin"
    cordova-plugin-android-permissions 1.0.2 "Permissions"
    cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
    cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
    cordova-plugin-app-version 0.1.9 "AppVersion"
    cordova-plugin-appavailability 0.4.2 "AppAvailability"
    cordova-plugin-appcenter-crashes 0.5.1 "App Center Crashes for Cordova"
    cordova-plugin-appcenter-shared 0.5.1 "App Center shared code for Cordova"
    cordova-plugin-apprate 1.5.0 "AppRate"
    cordova-plugin-background-fetch 6.0.3 "CDVBackgroundFetch"
    cordova-plugin-badge 0.8.8 "Badge"
    cordova-plugin-bluetoothle 4.5.7 "Bluetooth LE"
    cordova-plugin-camera 4.1.0 "Camera"
    cordova-plugin-contacts 3.0.1 "Contacts"
    cordova-plugin-device 2.0.3 "Device"
    cordova-plugin-dfu-update 1.0.3 "DFU Update"
    cordova-plugin-dialogs 2.0.2 "Notification"
    cordova-plugin-email-composer 0.9.2 "EmailComposer"
    cordova-plugin-facebook4 6.3.0 "Facebook Connect"
    cordova-plugin-file 6.0.2 "File"
    cordova-plugin-file-opener2 3.0.0 "File Opener2"
    cordova-plugin-file-transfer 1.7.1 "File Transfer"
    cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"
    cordova-plugin-flic-lib 1.1.1 "Flic"
    cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
    cordova-plugin-googlemaps 2.7.0-20191107-1035 "cordova-plugin-googlemaps"
    cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
    cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
    cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
    cordova-plugin-ios-keychain 3.0.1 "KeyChain Plugin for Cordova iOS"
    cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
    cordova-plugin-market 1.2.0 "Market"
    cordova-plugin-nativestorage 2.3.2 "NativeStorage"
    cordova-plugin-network-information 2.0.2 "Network Information"
    cordova-plugin-play-default-sounds 1.0.0 "PlayDefaultSounds"
    cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
    cordova-plugin-secure-preferences 1.2.2 "Secure Preferences"
    cordova-plugin-sms-retriever-manager 0.0.2 "Device"
    cordova-plugin-splashscreen 5.0.3 "Splashscreen"
    cordova-plugin-statusbar 2.4.3 "StatusBar"
    cordova-plugin-timer 1.0.1 "Native timer"
    cordova-plugin-vibration 3.1.1 "Vibration"
    cordova-plugin-whitelist 1.3.4 "Whitelist"
    cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
    cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
    cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
    cordova-support-google-services 1.3.2 "cordova-support-google-services"
    cordova.plugins.diagnostic 5.0.1 "Diagnostic"
    es6-promise-plugin 4.2.2 "Promise"
    ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
    ```
    </details>

- Dev machine OS and version, e.g.
    - OSX
        - `ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76`
	
_iOS build issue:_
- Node JS version
    - `v10.16.3`
- XCode version
    -  `11.3.1`

**Comment by dpa99c** [comment]
As stated in the error message, the conflict is with `cordova-plugin-google-analytics`.
The problem is that this plugin [bundles a static version](https://github.com/danwilson/google-analytics-plugin/blob/master/ios/libGoogleAnalyticsServices.a) of the Google Analytics Services library which is old and therefore incompatible with the Google Tag Manager pod which is now bundled with this plugin.

Firstly, the method of bundling a static library is inherently incompatible with the Cordova  plugin environment where multiple plugins are likely to reference the same library.

Secondly, the Google Analytics Services library which  `cordova-plugin-google-analytics` bundles [has been sunsetted](https://support.google.com/analytics/answer/9167112?hl=en) which AFAIK means that any events it sends to the Google servers will be ignored.

For both of these reasons, there is no change that can be made in this plugin to rectify the conflict.

**Comment by HansKrywaa** [comment]
Thanks for your Explanation! 😊
