### ISSUE TITLE
InApp messaging triggered without configuration

### ISSUE THREAD

**Issue by capc0** [dpa99c/cordova-plugin-firebasex#333]
# Bug report

**Current behavior:**

I updated to the lastest version of this plugin and noticed a console log that tells me that there are requests being made for in app messaging, without me enabling it. 

**Expected behavior:**

In app messaging should not be initialized with no configuration.

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- Installed platforms:
  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-update 2.0.2 "AppUpdate"
cordova-plugin-appversion 1.0.0 "App Version"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.1 "File Opener2"
cordova-plugin-firebasex 8.1.1 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-ios-disableshaketoedit 1.0.0 "iOS Disable Shake to Edit"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 3.4.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
- Dev machine OS and version, e.g.
    - OSX
        

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

[Firebase/InAppMessaging][I-IAM130004] Failed restful api request to fetch in-app messages: seeing http status code as 403 with body as {
  "error": {
    "code": 403,
    "message": "Firebase In-App Messaging API has not been used in project xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firebaseinappmessaging.googleapis.com/overview?project=xxxxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console API activation",
            "url": "https://console.developers.google.com/apis/api/firebaseinappmessaging.googleapis.com/overview?project=xxxxx"
          }
        ]
      }
    ]
  }
}


```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
InappMessaging was added by PR #312. Its Firebase SDK component exposes no API functions so it's not possible to allow enabling/disabling of it, hence if this Firebase SDK component is pulled into the build, there is no way to stop it from making that request and subsequently failing.
However this is simply an error log message - it doesn't cause build or runtime issues so you can ignore it.

Regardless of this, the Firebase InappMessaging SDK component is going to be removed again from this plugin in v9 due to the build issues it causes for the iOS platform when building using the Cordova CLI (see #326), so this will be implicitly resolved for you when v9 is subsequently released.

**Comment by capc0** [comment]
ok thanks for the info.
rolling with v 8.0.1 until version 9 comes out. much appreciated!
