### ISSUE TITLE
[FEATURE] Transition to Firebase Crashlytics

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-plugin-firebasex#335]
Currently this plugin uses the original Crashlytics SDK which is part of the Fabric SDK.
Since Google acquired Fabric, they have merged Crashlytics into Firebase so [Fabric is now deprecated and will shut down on 31 March 2020](https://fabric.io/kits/ios/crashlytics/update), though it's my understanding that Fabric-based Crashlytics will continue to function after this date so long as the Fabric project has been transitioned to Firebase.

Therefore we should move the plugin from (the deprecated) Fabric Crashlytics to Firebase Crashlytics as [outlined in the Firebase docs](https://firebase.google.com/docs/crashlytics/upgrade-sdk).

However, the [Firebase Crashlytics API](https://firebase.google.com/docs/crashlytics/get-started-new-sdk) (currently in Beta) is not an exact mapping of the Fabric API - some API functions have changed signature or are even are not supported.

For example, currently this plugin uses the [`recordCustomExceptionName`](https://docs.fabric.io/appledocs/Crashlytics/Classes/Crashlytics.html#//api/name/recordCustomExceptionName:reason:frameArray:) API method to send a custom stacktrace to Crashlytics for non-fatal errors. This allows replacing the auto-generated native stacktrace (no use in a Cordova app) with a Javascript stacktrace generated by `stacktrace.js` (the same approach [is used](https://github.com/invertase/react-native-firebase/blob/master/packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m#L162) by [react-native-firebase](https://github.com/invertase/react-native-firebase)).

However, the new Firebase Crashlytics API [does not currently support custom stack traces](https://github.com/firebase/firebase-ios-sdk/issues/4706) so we'd be unable to bring this feature across.

**Comment by dpa99c** [comment]
PR #432 has been submitted to resolve this - I will regression test ASAP

**Comment by dpa99c** [comment]
This has been implemented on the dev branch.

I've successfully tested on iOS but currently not seeing any crash data for Android using the new Firebase Crashlytics implementation.
If someone else could also give the dev branch and test and confirm if they see crashlytics data for Android, that'd be great.

To install the plugin direct from the dev branch:

    cordova plugin add https://github.com/dpa99c/cordova-plugin-firebasex#dev

**Comment by Roshankd1** [comment]
@zmoshansky  any luck with testing crash report for Android?

**Comment by dpa99c** [comment]
I'm testing this and still unable to get crash details to show in the Firebase Console Crashlytics Dashboard for Android.
It seems that Firebase is being notified of the crash as it's causing the "crash free users" statistic to change but the crash details are not appearing in the dashboard.

![image](https://user-images.githubusercontent.com/2345062/85694052-af5f5480-b6ce-11ea-962c-4a47859bc0e0.png)

I'll also need to fix the NDK crash reporting for Android (for Cordova apps containing C/C++ libraries invoked via the NDK) since crashes originating in a compiled C library are not being recorded at all on Android (not even in "crash free users").

**Comment by dpa99c** [comment]
I finally got Android crash reporting working:

![image](https://user-images.githubusercontent.com/2345062/85697671-e6833500-b6d1-11ea-9e4a-fbb5bf76c083.png)


Thanks to [this comment on SO](https://stackoverflow.com/questions/54707667/i-cannot-view-crash-detail-of-firebase-crashlytics-for-android-and-got-stuck-on#comment104602414_58659863), I ran in `platforms/android/`:

    ./gradlew cleanBuildCache && ./gradlew --refresh-dependencies

Then forced a crash, then I saw in the logcat:

    2020-06-25 10:45:54.710 9922-11889/? I/FirebaseCrashlytics: Crashlytics Reports Endpoint upload complete: 5EEB8B0E0397-0001-5E2D-51D8468E4E93

So guess it was something cached in the Android build.

Still need to fix NDK crash reporting before merging to master & releasing...

**Comment by Roshankd1** [comment]
@dpa99c  Hi Dave, thank you for the update on Android, I was wandering if you'd know something regarding this error I am seeing in iOS after update. I have already tried importing GoogleServices-Info.plist again but no luck.

xx[4278:1163883] 6.23.0 - [Firebase/Installations][I-FIS002003] Firebase Installation registration failed for app with name: __FIRAPP_DEFAULT, error:
The server responded with an error: 
 - URL: https://firebaseinstallations.googleapis.com/v1/projects/my-app-prod/installations/ 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "Requests to this API firebaseinstallations.googleapis.com method google.firebase.installations.v1.FirebaseInstallationsService.CreateInstallation are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/xx/apiui/credential"
          }
        ]

**Comment by dpa99c** [comment]
@Roshankd1 looking at the [Firebase iOS SDK source code](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m#L261) it appears this error is related to the project configuration.
There's a similar report [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/1555#issuecomment-593489516).
I'm not seeing this error on iOS and I don't believe the Firebase Crashyltics changes are related to it.
So it is likely specific to your Firebase project configuration.

**Comment by Roshankd1** [comment]
@dpa99c  thank you I thought so as well and have been battling since yesterday trying to see what's missing or excess after the update :D I will keep trying! Good day :)

**Comment by dpa99c** [comment]
This functionality has been released in a new major version: `cordova-plugin-firebasex@10.0.0`

**Comment by Roshankd1** [comment]
@dpa99c Hey Dave, finally able to fix my firebase config errors but still seeing a problem with Android.

I've tested in both release/debug environment still getting this error:

_polyfills-es2015.js:3657 Unhandled Promise rejection: Cannot set Crashlytics user ID - Crashlytics collection is disabled ; Zone: <root> ; Task: null ; Value: Cannot set Crashlytics user ID - Crashlytics collection is disabled undefined_

**Comment by dpa99c** [comment]
@Roshankd1 looks like there's a regression on [this line](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L146) - it should not be a negative condition.

**Comment by dpa99c** [comment]
Just pushed a commit to master which should fix it.

**Comment by Roshankd1** [comment]
@dpa99c  Amazing thank you! Quick one, how are you testing crash on iOS? I'd imagine the with firebaseX wrapper right?

I am not able to see crash report pushed in Console(probably something to do with my crash test code??)

I used firebase.sendCrash();

Here is my log:
2020-06-29 18:23:10.577854+0200 XX[5088:1455022] AAA, simulate crash called
Assertion failed: (NO), function -[FirebasePlugin sendCrash:], file /Users/{}/app/platforms/iOS/XX/Plugins/cordova-plugin-firebasex/FirebasePlugin.m, line 1109.

**Comment by globules-io** [comment]
Having this issue here, seems related? Please let me know if you'd like me to open a new ticket..

**Comment by Roshankd1** [comment]
@globules-io The message seems pretty clear tbh, try to enable API as mentioned in the log message and also make sure you have updated your google-services.json file with latest API_KEY that you can retrieve from the fire base console.

To allow your API key in question to be used with the new Firebase Installations API:
• go to the Google Cloud Console
• choose the relevant project (i.e. the project you use for your application)
• open the menu and go to APIs & Services -> Credentials
• click Edit API key for the API key in question
• scroll down to API restrictions
• from the dropdown, choose Firebase Installations API
• click Save
• wait a couple of minutes for Google servers to update and retry...

**Comment by Roshankd1** [comment]
[https://stackoverflow.com/questions/58495985/firebase-403-permission-denied-firebaseerror-installations-requests-are-blo](url)

**Comment by globules-io** [comment]
@Roshankd1 they are enabled, it is a iOS issue only, fixed it was somewhat fixed by uninstalling / reinstalling and redoing pods. Not sure what happened.
Don't mind that comment anymore :)

**Comment by fcamblor** [comment]
@dpa99c First of all, thank you for handling this in the plugin.

Would it be possible to know what are the implications of not aligning our apps to `cordova-plugin-firebasex` >= `10.0` by November 15th ?

I stumbled upon this issue today, and the timing/effort to both :
- upgrade `firebasex`
- upgrade other plugins using old `firebasex` versions as transitive dependencies
- roll out new version of my app with those changes to all my users
looks very tight to me.


That's why I'd need to know what's going to happen by Nov. 15th **if I don't upgrade in time** (now that the problem is fixed, I assume you should have an idea on the impacts) :
- Will I simply not get errors in crashlytics when `firebasex` will have some failures ? (silent errors)
- Will I have some features of `firebasex` that will not work ? (if yes, which ones ?)
- Will some calls to `firebasex` plugin going to generate exceptions and break my app ?
- Will my whole app not run at all ? (because of some kind of `firebasex` bootstrapping error due to deprecated backend)

**Comment by dpa99c** [comment]
@fcamblor 

> * Will I simply not get errors in crashlytics when `firebasex` will have some failures ? (silent errors)

My understanding is that after 15 Nov, any apps which haven't been migrated will stop receiving crash reports in Firebase.
Even if you've updated the latest version of your app, users with old app versions installed will not have their crashes reported.


If you open the Crashlytics console in Firebase console for a project which has not yet been migrated you should see a warning like this:
![image](https://user-images.githubusercontent.com/2345062/97689796-049fde00-1a94-11eb-908a-5b8b85941bdf.png)
 
"Learn more" links [to here](https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=ios&authuser=1)

> * Will I have some features of `firebasex` that will not work ? (if yes, which ones ?)
> * Will some calls to `firebasex` plugin going to generate exceptions and break my app ?
> * Will my whole app not run at all ? (because of some kind of `firebasex` bootstrapping error due to deprecated backend)

The rest of the Firebase plugin functionality should work fine.
Your app will continue to run and function as it does currently, but any crash reports sent via Fabric Crashlytics will be sent to a backend endpoint which will no longer accept them.
The Crashlytics crash report upload is carried out internally by the Firebase SDK at app startup - if it fails, it won't affect your app functionality, you will probably just see an error in the Android Logcat/iOS Xcode console log output.

> * Are iOS apps concerned by the change ?
Both iOS and Android apps are affected.

**Comment by fcamblor** [comment]
@dpa99c thanks for your (very) quick feedback, as always you're providing insightful answers and I really appreciate it.

If I summarize, it looks like if I was not using Crashlytics before (it's my case) then I shouldn't be impacted.

I will cross fingers the exception raised by firebase internals when trying to reach the shutted down endpoint will not be caught by my general-purpose exception handler (my general-purpose exception handler is showing an error popup to end users) and will rather be caught and handled by firebase silently.

That's one of my fears, and I assume it will be complicated to know the answer to this question before Nov 15th :(

**Comment by tomavic** [comment]
Hello @dpa99c Is there is any setting to disable crashlytics or how to bypass it cause I am getting android build errors when I am using it with capacitor. I don't need crashlytics and I can't find a way to disable it in this plugin's methods. 

FYI the android build error is 

```
Caused by: org.gradle.api.GradleException: Applying the Firebase Crashlytics plugin to a library project is unsupported. It should only be applied to the application module of your project to enable automatic upload of obfuscation mapping files for your application.
```

I am using latest version of everything 🗡️

**Comment by fcamblor** [comment]
@tomavic not sure if this will solve your build time issue (it looks more like a runtime workaround) but you can a look at [this section of the doc](https://github.com/dpa99c/cordova-plugin-firebasex#disable-data-collection-on-startup) (it allows to disable crashlytics at startup)

**Comment by tomavic** [comment]
@fcamblor yes i can do this when I am using cordova, but i am using capacitor. And the way to use cordova with capacitor is only install plugin without specifying variables.

Do you know how to set these variables the right way?

**Comment by fcamblor** [comment]
@tomavic I'm sorry I don't have knowledge into Capacitor yet :(

**Comment by tomavic** [comment]
@fcamblor me too 😔

I don't have any experience with capacitor. I was using cordova for the past time, and turned to capacitor because of firebase plugins issues. And AGAIN I faced it too! What an epic
