### ISSUE TITLE
[Question] native crash log on android not deobfuscated

### ISSUE THREAD

**Issue by capc0** [dpa99c/cordova-plugin-firebasex#336]
I am not sure if this is the right place the ask, but we are receiving crash reports in firebase on android without any valuable information.
Users are reporting that the screen stays black on start-up and than the app crashes. 

Could it be that the firebase stuff is not initizaled yet and therefore i only see the stacktraces like below?

![image](https://user-images.githubusercontent.com/27284008/76396211-0b4cda00-6379-11ea-8c61-4f99101dc29a.png)

Is there any way i can get more info out of this?

**Comment by dpa99c** [comment]
The Crashlytics SDK automatically captures and uploads native crash data - this is a black box feature and there's nothing this plugin can do to modify what gets uploaded.

Your crash looks like it's arising in `libart.so` - the compiled C library which provides the Android runtime, so I suggest Googling the SIGTRAP code and see what it returns.

Closing this as there's nothing that can be done from the plugin perspective to improve what Crashlytics displays for your stacktrace.
