### ISSUE TITLE
TypeError: Cannot read property 'getToken' of undefined in Ionic3 project

### ISSUE THREAD

**Issue by Sagarkhenat** [dpa99c/cordova-plugin-firebasex#337]
Hi @dpa99c ,  I tried to use the latest version of cordova-plugin-firebasex for my ionic3 app. I also did refer your ionic3 example for firebasex plugin. But after adding the code, I am getting the error as 'TypeError: Cannot read property 'getToken' of undefined'. Below is the code which I have used:

In my login.ts file:
if ( this.accessToken ) {
                this.fireBaseService.getFirebaseXToken();
}

In my firebase-service.ts file===**====
export class FireBaseService {
    protected token:any;
    public firebasePlugin;

async getFirebaseXToken() {
    let token;
    this.firebasePlugin = (<any>window).FirebasePlugin;
         token = await this.firebasePlugin.getToken(token => {
            console.log('Response from getToken===>>>>',token);
          });
    }
}

These are the specs for my ionic3 project:
 "cordova": "^9.0.0",
 "cordova-android": "8.1.0",
"cordova-plugin-firebasex": "^8.1.1",
"cordova-android-play-services-gradle-release": "3.0.0",
"cordova-android-support-gradle-release": "^3.0.0",
"cordova-plugin-androidx": "^1.0.2",
"cordova-plugin-androidx-adapter": "1.1.0",

 "devDependencies": {
"@ionic/app-scripts": "^3.2.2",
"typescript": "~2.6.2"
}
 
I wanted to use this plugin as it is actively maintained and prompt replies by the maintainers. If there are any changes to be done in my code, am I missing something, any kind of help will be helpful. Thanks.

**Comment by dpa99c** [comment]
I'm unable to provide support for specific usage of the plugin - please ask for help on Ionic Forums or Stackoverflow. 
Please only open issues to report a suspected bug (which is validated against the example project or by providing exact steps to reproduce) or to request new features.

Please refer to the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working reference of the plugin functionality.

**Comment by yaro08** [comment]
@Sagarkhenat are you tried adding setTimeout function? Like this: 
setTimeout(()=> {
      (<any>window).FirebasePlugin.setCrashlyticsUserId('DEVELOP_USER')
    }, 1000);

this works for me, but I can't get a promise result. I will consider upload my project to ionic 5
