### ISSUE TITLE
Payload data object is not found while app is not in memory.

### ISSUE THREAD

**Issue by sibabratswain11** [dpa99c/cordova-plugin-firebasex#34]
Notification works perfectly. I have been facing an issue with tapping on the notification. After taping on the notification I get the payload data object in my app **onNotificationOpen** subscription only if the app is in memory.  

I don't get the payload data while the app is not in memory. In other words, it does not work accordingly if the app is not in memory. This issue has been with the older version as well. 

Is there any patch for this?

_I am using Firebase cloud messaging for this matter_

**Comment by dpa99c** [comment]
I'm currently working on a rewrite of the notifications functionality of this plugin which will address this issue in addition to fixing other existing issues and adding more features.
But I'll leave this issue open for now to capture the problem and when my new version is finished, it can be tested against this criteria.

**Comment by dpa99c** [comment]
BTW which platform are you seeing this issue on? iOS, Android or both?

**Comment by sibabratswain11** [comment]
In android. Not tested in iOS yet.

**Comment by dpa99c** [comment]
Thanks - I have observed the same issue in Android but also not tested this on iOS.

**Comment by tomavic** [comment]
```

├───build_script
│   ├───new_script
│   │   └───src
│   │       ├───log
│   │       └───vcs
│   └───resources
│       ├───com.cit.vericash.empcustomer
│       │   ├───googleServices
│       │   ├───img
│       │   │   └───mahfazti
│       │   │       └───svg
│       │   ├───res
│       │   │   ├───icon
│       │   │   │   ├───android
│       │   │   │   └───ios
│       │   │   ├───notificationSmallIcon
│       │   │   │   ├───drawable-hdpi
│       │   │   │   ├───drawable-mdpi
│       │   │   │   ├───drawable-xhdpi
│       │   │   │   ├───drawable-xxhdpi
│       │   │   │   └───drawable-xxxhdpi
│       │   │   └───screen
│       │   │       ├───android
│       │   │       └───ios
│       │   └───translations
│       │       └───app
│       ├───com.fbnquest.demo.vericash
│       │   ├───app_icons
│       │   ├───css
│       │   │   └───theme
│       │   ├───googleServices
│       │   ├───img
│       │   │   ├───menu_theme
│       │   │   ├───mutual_funds
│       │   │   └───standerd

```

**Comment by dpa99c** [comment]
FYI this should be fixed on the [dev branch](https://github.com/dpa99c/cordova-plugin-firebase/tree/dev) if you want to give that a test.

I'm currently reworking the plugin on dev  - when rework is completed, I'll merge to master and release a new major version.

**Comment by sibabratswain11** [comment]
I have tried with [dev branch](https://github.com/dpa99c/cordova-plugin-firebase/tree/dev). It does not work accordingly. App loads when the app is not in memory while opening the app. That can not find the payload data.

**Comment by dpa99c** [comment]
I've just published `cordova-plugin-firebasex@5.0.0`.
This is a major version that reworks the cloud messaging code and so will resolve this issue.
Please regression test using v5.0.0 of this plugin to confirm.

Note: v5.0.0 makes breaking changes to the plugin API - see the [CHANGELOG](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md#version-500) for details.

You may find it useful to test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which has a built-in FCM messaging client with test messages.

**Comment by dpa99c** [comment]
Fixed in v5.0.0

**Comment by sibabratswain11** [comment]
yup it is working just fine.

**Comment by sibabratswain11** [comment]
@dpa99c Please look into this. I am using firebase cloud function to trigger the notification. I am using firebase-admin. Show the payload looks something like this. 

`const payloadMobile = 
{
              notification: {
                title: title,
                body: body,
                icon: icon,
                vibrate: '1',
                color: "#f7066a",
                sound: 'my_sound',
                notification_android_sound: "my_sound",
              },
`  ` data: {
                patient_id: patient_id,
                notification_type: notification_type,
                title: title,
                body: body,
                payment_status: payment_status,
                color: "#f7066a",
                sound: 'my_sound',
                notification_android_sound: "my_sound"
              }
            }`

`const responseMobile = await admin.messaging().sendToDevice(uniqueDevicesTokenArrayMobile, payloadMobile)`.

which works fine, I can get the notifications with custom color and custom icons. I am facing issue with the custom sound. 

I also tried with the script as you have explained in the docs.
`npm run send -- --message=android_notification.json --token="chLm2WNJcDY:APA91bFQxiTOg5aq8wJtVowkHyAIQXpzLYsuZdk00sl4D-iO5kmsuP0DcocEhDJe326d2PG9a0o1_0JQw3p0V2T9Iti5zRbukHNzmGCasxfA__XQd4g9qsxSZHrOKBasJ9qX39ZiA5ZO"
 ` 

This also works fine except the sound property. Even if I remove the sound property also it gives me default sound here from script run. 

`<resource-file src="resources/android/raw/my_sound.mp3" target="app/src/main/res/raw/my_sound.mp3" />`
this is also there in config.xml and does its job without any issue.

What might be the issue for which I can not make the custom ring tone work? From both firebase function and the samle .json files?

Platform - ionic 3, firebase-x 9.0.2(@latest)

> why to open an issue rather fix here. any suggestions will help me a lot. Thanks.

**Comment by dpa99c** [comment]
Have you tried to reproduce this by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app?

**Comment by sibabratswain11** [comment]
No, I have not tested the app. As I am implementing it in ionic. So can I build and test [Example Ionic 3 project ](https://github.com/dpa99c/cordova-plugin-firebasex-ionic3-test) app?

**Comment by sibabratswain11** [comment]
I have tried and it does not work with the example project you have suggested.  
[Please Watch this](https://youtu.be/6P2G6dnhqBo)

**Comment by sibabratswain11** [comment]
@dpa99c does it work for you? It is simply not working with the test app. Could you please check? Android version - 10

**Comment by dpa99c** [comment]
For Android 8.0 and above, it's the notification channel that defines the sound, not the `sound` key in the FCM message payload (see https://stackoverflow.com/a/54308706/777265)

I've updated the [Android Notification Sound](https://github.com/dpa99c/cordova-plugin-firebasex#android-notification-sound) and [Android Notification Channels](https://github.com/dpa99c/cordova-plugin-firebasex#android-notification-channels) sections of the documentation to make this clearer.
