### ISSUE TITLE
messageType always data for iOS

### ISSUE THREAD

**Issue by martinriviere** [dpa99c/cordova-plugin-firebasex#340]
# Bug report

Hi !
I am pretty sure I am missing something, but I can't figure out what is wrong.
I am trying to send push notifications with the Firebase REST API, it works great on Android, but not on iOS...

Thanks a lot for your help !

**Current behavior:**
On Android, it works like a charm, background and foreground.
On iOS, thought I receive the notification (logged upon receipt via onMessageReceived), messageType is always "data", while it is "notification" on Android. The "notification" object is display as it if was part of the data payload.
Remote notifications is checked in Xcode's Background Modes, and I did receive notifications with the previous plugin I had on this project (cordova-plugin-fcm, I switched to firebasex to easily manage foreground notifications).
I use FCM token for both Android and iOS.

**Expected behavior:**
I should receive push notifications, and messageType should be "notification".

**Environment information**
- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- android 8.1.0
	- ios 5.1.1
- Plugins & versions installed in project (including this plugin)
	- cordova-plugin-actionsheet 2.3.3 "ActionSheet"
	- cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
	- cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
	- cordova-plugin-camera 4.1.0 "Camera"
	- cordova-plugin-datepicker 0.9.3 "DatePicker"
	- cordova-plugin-device 2.0.3 "Device"
	- cordova-plugin-downloader 0.0.4 "Downloader"
	- cordova-plugin-email-composer 0.9.2 "EmailComposer"
	- cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
	- cordova-plugin-exit 1.0.3 "Exit"
	- cordova-plugin-file 6.0.2 "File"
	- cordova-plugin-filechooser 1.2.0 "File Chooser"
	- cordova-plugin-filepath 1.5.7 "cordova-plugin-filepath"
	- cordova-plugin-filepicker 1.1.6 "File Picker"
	- cordova-plugin-firebasex 9.0.0 "Google Firebase Plugin"
	- cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
	- cordova-plugin-save-image 0.3.0 "SaveImage"
	- cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
	- cordova-plugin-splashscreen 5.0.3 "Splashscreen"
	- cordova-plugin-statusbar 2.4.3 "StatusBar"
	- cordova-plugin-whitelist 1.3.4 "Whitelist"
	- cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
	- cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
	- cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
	- es6-promise-plugin 4.2.2 "Promise
- Dev machine OS and version, e.g.
    - OSX
        - 10.15.3
        
_Runtime issue_
- Device details
    - iPhone XR
- OS details
    - iOS 13.4	
	
**Related code:**
API payload : 
`{
    "registration_ids": [
      token
    ],
    "priority": "high",
    "content_available": true,
    "notification": {
                "title": "test",
                "body": "test",
            },
            "data": {
                "title": "test",
                "body": "test",
            }
  }`

**Comment by dpa99c** [comment]
Please refer to the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a working reference and ensure you have followed all the APNS setup instructions to use Firebase on iOS for push notifications.
