### ISSUE TITLE
[FEATURE] Add plugin variables for Fabric API Key / Secret and logic to pass it down to the SDK

### ISSUE THREAD

**Issue by Edmu** [dpa99c/cordova-plugin-firebasex#341]
# Feature request

- Add plugin variables for Fabric API Key / Secret and logic to pass it down to the SDK.

We did migration from Fabric to Firebase and linked firebase project to the Fabric integration but the crash data is not arriving to Firebase Crashlytics Web Interface (only crash-free metric gets updated)

This is from https://docs.fabric.io/android/examples/firebase/faq.html

A: If you’ve completed the click-through Fabric migration flow to migrate to Firebase, you can keep using the Fabric Crashlytics SDK. In that case, you should leave your old Fabric API key in your app.

After you link your app, you can choose to upgrade to the Firebase Crashlytics SDK in beta for iOS or Android, which requires making updates to your code.

This plugin both uses Fabric & Crashlytics SDK atm but does not provide ability to set / implement  API Keys usage.

**Comment by dpa99c** [comment]
It is not necessary to include the Fabric API key with this plugin to receive Crashlytics data in the Firebase console - once you have linked your project with Firebase, the Fabric key is no longer needed to upload crash data.
I have myself moved production apps from Fabric to Firebase which use this plugin and they receive Crashlytics data in Firebase console without need for the Fabric API keys.

However, you need to unlink your Fabric app from Firebase before Crashlytics data will flow through to the Crashlytics console in Firebase as [outlined here](https://stackoverflow.com/a/49229545/777265)

**Comment by Edmu** [comment]
I already did that and thats np for me. But I don't this can be called complete migration - unlinking does delete older fabric data and firebase assumes it's new app.

**Comment by phillipmoon** [comment]
@dpa99c when we try to install version 9.0.0 or 9.0.1-cli we get an error at run time of the mobile app.  The error reads `[Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request id=, content_type=application/json; charset=utf-8}`

We don't have a Fabric account linked to our Firebase project as we're using a new Firebase project.  Do we need to link a Fabric account to our fresh Firebase project to resolve this issue?

Any help would be appreciated.

**Comment by Carlosps** [comment]
How did you manage to solve this @phillipmoon ?
