### ISSUE TITLE
TagManagerResources.bundle" not found.

### ISSUE THREAD

**Issue by Fever905** [dpa99c/cordova-plugin-firebasex#342]
Hey!  I got my new Mac and I'm trying to compile.  Seeing a new error I've never seen before.  So for this tag manager thing I setup and downloaded my GTM-XXXXXXX.json file for tag manager (config'd for iOS app).  I'm still seeing this error though.   I don't use tag manager for anything in my app, is this even required and/or could it be disabed?

Either way here is the error I'm getting.  I've run the pod install and pod repo update, and pod dependencies in my platforms/ios/ folder.   Is there anything else I need to do?

PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/michaeldemutis/Library/Developer/Xcode/DerivedData/Oil_Analysis-gnihdqyqqjgcawagwlheuxfsxppy/Build/Intermediates.noindex/ArchiveIntermediates/Oil\ Analysis/IntermediateBuildFilesPath/Oil\ Analysis.build/Debug-iphoneos/Oil\ Analysis.build/Script-84D03849F3A23BF860D16DA7.sh (in target 'Oil Analysis' from project 'Oil Analysis')
    cd /Users/michaeldemutis/oa/platforms/ios
    /bin/sh -c /Users/michaeldemutis/Library/Developer/Xcode/DerivedData/Oil_Analysis-gnihdqyqqjgcawagwlheuxfsxppy/Build/Intermediates.noindex/ArchiveIntermediates/Oil\\\ Analysis/IntermediateBuildFilesPath/Oil\\\ Analysis.build/Debug-iphoneos/Oil\\\ Analysis.build/Script-84D03849F3A23BF860D16DA7.sh
/Users/michaeldemutis/oa/platforms/ios/Pods/GoogleSignIn/Resources/GoogleSignIn.bundle
error: Resource "/Users/michaeldemutis/Library/Developer/Xcode/DerivedData/Oil_Analysis-gnihdqyqqjgcawagwlheuxfsxppy/Build/Intermediates.noindex/ArchiveIntermediates/Oil Analysis/BuildProductsPath/Debug-iphoneos/GoogleTagManager/TagManagerResources.bundle" not found. Run 'pod install' to update the copy resources script.

**Comment by dpa99c** [comment]
This is a Cordova CLI build issue - see #326 
A new plugin release is required to resolve this - in the meantime use an earlier plugin version for Cordova CLI builds e.g. v8.0.1

**Comment by Fever905** [comment]
Thank you for the fast response!!

**Comment by Fever905** [comment]
I will try to build from XCode.  Should be ok I think.

**Comment by gczudowski** [comment]
i have the same issue in 2021. any news?

**Comment by jussikinnula** [comment]
I also have the same issue in 2021.

I have tried all the workarounds, but for example cordova-plugin-firebasex version 8 doesn't work anymore (tries to use obsolete APIs).

**Comment by marioklump** [comment]
@gczudowski @jussikinnula, today I had the same issue.

Please make sure that you are using the cli version of the plugin.

I used the version constraint `^12.1.0-cli` in my `package.json` after updating my npm dependencies:

```
"cordova-plugin-firebasex": "^12.1.0-cli",
```

Internally the prepended caret caused that the version 12.1.0 (the non-cli version) was installed.

After pinning the version to `12.1.0-cli`, I was able to build my iOS project.

```
"cordova-plugin-firebasex": "^12.1.0-cli",
```

Maybe it's the same reason, why your build fails.

It is also documented in the last paragraph of https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds. I don't know why I haven't seen this part of the documentation before spending hours to find the cause of this issue...

**Comment by Fever905** [comment]
Ah I'm having same problem i had 2 years ago but with a new app!  Now I remember the cli version!  LOL this is funny but awesome its solved quickly.
