### ISSUE TITLE
[BUG] [ANDROID 10] - Sound notification

### ISSUE THREAD

**Issue by Furieux33** [dpa99c/cordova-plugin-firebasex#345]
Hello,

The sound of the notification not working on Samsung Galaxy Note 10 (Android 10)...
But you can try to fix this, with : https://github.com/FirebaseExtended/flutterfire/issues/523#issuecomment-574904729

Regards,

**Comment by dpa99c** [comment]
Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and send the [android_notification_custom_channel](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/android_notification_custom_channel.json) test message using the built-in FCM client (note that on Android 8+ it is the notification channel, not the FCM message payload, that defines which sound is played).

If this does not work as expected, please specify **exactly** what is issue is (e.g. no sound vs wrong sound).

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by renznamoc21** [comment]
This is still an issue even in example project default notification sound play instead the custom sound file
