### ISSUE TITLE
Please help - No visible @interface for 'FIRTrace' declares the selector 'incrementCounterNamed'. FirebasePlugin.m

### ISSUE THREAD

**Issue by jrluiscarvalho** [dpa99c/cordova-plugin-firebasex#346]
Hello everyone!

I have this problem reported in the title, I can't build my app on my iOS, it's the only error that happens.

Thank you all

**Comment by dpa99c** [comment]
Make sure your Cocoapods installation is up-to-date - [see here](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods).

Try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate external factors.

**Comment by jrluiscarvalho** [comment]
Hy @dpa99c , thanks for response. 


I did the process you asked for and at the terminal, I got error 65. I know it is related to a certificate.

So I solved this issue and copied my GoogleService-Info file from the existing project to the firebasex test project. The project built perfectly using xcode but not in the terminal.

In my existing project, I have firebase and firebasex. It is a legacy project and we have both facilities to service android and ios.

Do you think there may be a conflict between the two firebase?

Thanks for listening.

**Comment by dpa99c** [comment]
Including `cordova-plugin-firebase` and `cordova-plugin-firebasex` in the same project will cause conflicts and probably build failures - I do not recommend it.

Regarding the CLI build failing, please see [this documentation note](https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds)

Closing as I don't believe there is an underlying issue with the plugin itself.
