### ISSUE TITLE
Crashlytics not working on iOS

### ISSUE THREAD

**Issue by dodomui** [dpa99c/cordova-plugin-firebasex#348]
# Bug report

**Current behavior:**

By using the firebase crashlytics, Android can log the error by logError successfully, but IOS unable.
I did received some error from Xcode console while I try to produce error in the app, which you may refer to output below.

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- Installed platforms:
  android 8.1.0
  ios 5.1.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0
- Plugins & versions installed in project (including this plugin)
    - cordova-android-firebase-gradle-release 4.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 4.0.0 "cordova-android-play-services-gradle-release"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-buildinfo 4.0.0 "BuildInfo"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-customurlscheme 4.4.0 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-facebook4 6.4.0 "Facebook Connect"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 9.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googleplus 8.4.0 "Google SignIn"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.4.0 "cordova-support-google-services"
- Dev machine OS and version, e.g.
    - OSX
        - `Catalina 10.15.3`
        
- Node JS version
    - `v12.16.1`

**Related code:**
This is the service I used to handle error.
```
import { Injectable, ErrorHandler } from '@angular/core';
import { Platform } from '@ionic/angular';

import { FirebaseX } from '@ionic-native/firebase-x/ngx';

import { UserService } from './user.service';

@Injectable({
  providedIn: 'root'
})

export class ErrorService extends ErrorHandler {

  constructor(
    private platform: Platform,
    private firebaseX: FirebaseX,
    private userService: UserService
  ) {
    super();
  }

  log(error: any): void {
    super.handleError(error);

    const message = error.message ? error.message : error.toString();
    const stacked = error.stack ? error.stack : {};
    const uid = this.userService.uid ? this.userService.uid : '';

    try {
      if (this.platform.is('cordova')) {
        if (uid) {
          this.firebaseX.setCrashlyticsUserId(uid);
        }

        this.firebaseX.logError(message, stacked).then(result => {
          //console.log(result);
        }).catch(err => {
          console.log(err);
        });
      } else {

      }
    } catch (e) {
      console.error(e);
    }
  }

}
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary></summary>

```

// Paste any relevant JS/native console output here
2020-03-23 19:45:44.244615+0800 v2[1358:363903] -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x113e0b190
2020-03-23 19:45:44.245821+0800 v2[1358:363903] FirebasePlugin[native] ERROR: EXCEPTION: -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x113e0b190
2020-03-23 19:45:44.245950+0800 v2[1358:363300] [Process] kill() returned unexpected error 1
2020-03-23 19:45:44.246118+0800 v2[1358:363300] [Process] kill() returned unexpected error 1
2020-03-23 19:45:44.262117+0800 v2[1358:363300] ERROR: FirebasePlugin[native]: EXCEPTION: -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x113e0b190
2020-03-23 19:45:44.262589+0800 v2[1358:363300] -[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x113e0b190
```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
Please re-test against the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to rule out external causes (e.g. invalid user ID being passed)

**Comment by dodomui** [comment]
I tried removed stacked info from error and it's working on iOS now.
While I can passed both message and stacked error to crashlytics on android.

```
this.firebaseX.logError(message).then(result => {
        }).catch(err => {
          console.log(err);
        });
```

**Comment by dpa99c** [comment]
See the [example project usage](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L57) for a working illustration and use this as a reference.

Closing as I believe this works fine if the correct data structure is passed on iOS - I use it in several production apps.
