### ISSUE TITLE
 No visible @interface for 'FIRTrace' declares the selector 'incrementCounterNamed'. FirebasePlugin.m

### ISSUE THREAD

**Issue by jrluiscarvalho** [dpa99c/cordova-plugin-firebasex#349]
Hello @dpa99c , i remove a cordova-plugin-firebase and the error persists. Anyone Recommendation? 

I build again in other folder.

Thank you so much.

**Comment by dpa99c** [comment]
Do not open duplicate issues or you will be banned from my repos. 

Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a working reference.

I am not able to offer free support for using the plugin - please ask on Stackoverflow or elsewhere.
Issues should only be opened if a bug is suspected in which case it should be validated against the example project before reporting and should be thoroughly documented with steps to reproduce.
