### ISSUE TITLE
signOutUser

### ISSUE THREAD

**Issue by xurdep** [dpa99c/cordova-plugin-firebasex#353]
# Feature request

Is posible that method signOutUser removes all Google cache files? When you sign out and then sign in again, the account chooser doesn't show.. Next time you sign in, the login is silent with the previous account.
Account chooser only is showed at the first time you sign in. I don't know if this is a bug or is something that is not implemented yet. 
Thank you in advange!

**Comment by dpa99c** [comment]
This looks to be a bug - well, a shortcoming in Firebase's use of Google SignIn anyway...
I had assumed Firebase would take care of signing out of Google when you signed out of Firebase, but apparently not: it seems you must manually sign out of both on [Android](https://github.com/firebase/FirebaseUI-Android/issues/187#issuecomment-225625136) and [iOS](https://stackoverflow.com/a/40107017/777265).

I will test this scenario and implement a fix in the next plugin release if needed.

**Comment by xurdep** [comment]
Hi!!

Thank you very much for your response and apreciate support!

B.R

**Comment by xurdep** [comment]
How can I test this changes?? Can I overwrite the commited file srcc/android/FirebasePlugin.java and build again? Thank you

**Comment by dpa99c** [comment]
You can install directly off the master branch until this is released in the next version to npm:

    cordova plugin add https://github.com/dpa99c/cordova-plugin-firebasex

**Comment by xurdep** [comment]
> You can install directly off the master branch until this is released in the next version to npm:
> 
> ```
> cordova plugin rm cordova-plugin-firebasex --nosave && cordova plugin add https://github.com/dpa99c/cordova-plugin-firebasex --nosave
> ```

Hi!
It works like a charm! 
But I had problems uninstalling the plugin and added with the above command, I think It was for version conflict with other plugins but I'm not sure and I didn't want "another plugin war" jajaja... 

Finally I solved adding changes manually to  FirebasePlugin.java file existing in "plugins" and "node_modules" folders and rebuild until new version is released.

Thank you @dpa99c 
Regards
