### ISSUE TITLE
iOS build failed, after installed firebasex plugin

### ISSUE THREAD

**Issue by andaralex** [dpa99c/cordova-plugin-firebasex#355]
Can anyone help me to resolve this issue?
Error Message:
    cd /Users/sys-user/Documents/alex_test/firebasexTest/platforms/ios
    /bin/sh -c /Users/sys-user/Library/Developer/Xcode/DerivedData/MyApp-eutgugwgbqkjqnbrxcmouurlxiab/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-3688AD476B48CA093821D301.sh
error: Resource "/Users/sys-user/Library/Developer/Xcode/DerivedData/MyApp-eutgugwgbqkjqnbrxcmouurlxiab/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/sys-user/Library/Developer/Xcode/DerivedData/MyApp-eutgugwgbqkjqnbrxcmouurlxiab/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Script-3688AD476B48CA093821D301.sh
(1 failure)
<img width="576" alt="Screenshot 2020-03-31 at 1 16 19 PM" src="https://user-images.githubusercontent.com/922142/78000385-d1586d80-7351-11ea-8b3b-0e17081af85c.png">

**Comment by dpa99c** [comment]
Please don't open issues for support reasons - I cannot offer free technical support to plugin users.

Issues should only be opened to report a bug (which has either been reproduced in the example project and/or with a documented set of steps to reproduce) or to request a new feature.
