### ISSUE TITLE
Cannot find protocol declaration for 'ASAuthorizationControllerDelegate';

### ISSUE THREAD

**Issue by AbdullaevTimur** [dpa99c/cordova-plugin-firebasex#356]
Hello! I use "Cordova 8" and xCode 10.1 to build my app. 

I update my "FirebaseAuth" pod to 6.5.1 for solving issue with "AppAuth 1.3.0".

During build my iOs App i catch errors in "AppDelegate.h+FirebasePlugin.h" file" (l.7): 
1. Cannot find protocol declaration for 'ASAuthorizationControllerDelegate'; did you mean 'UINavigationControllerDelegate'?
2. Cannot find protocol declaration for 'ASAuthorizationControllerPresentationContextProviding' and also 18 error in other files connected with "ASAuthorizationController".

**Comment by dpa99c** [comment]
Please update to Xcode 11 - Xcode 10 is out-of-date and therefore not supported.
