### ISSUE TITLE
problem when add platform ios

### ISSUE THREAD

**Issue by marcosricardo** [dpa99c/cordova-plugin-firebasex#362]
Why does this happen when I add the ios platform?

<img width="1013" alt="Screen Shot 2020-04-08 at 09 27 06" src="https://user-images.githubusercontent.com/27781419/78784336-8bb42a00-797b-11ea-93c4-855f2287149c.png">

**Comment by dpa99c** [comment]
Run `cd platforms/ios && pod install --verbose` or `cordova platform ios --verbose` to get a detailed error as to why pod install failed.

A likely cause is out-of-date local pods repo, so be sure to run `pod repo update` as [outlined in the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#out-of-date-pods).

Also try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to rule out possible causes specific to your project such as plugin conflicts.
