### ISSUE TITLE
 'getId' does not exist on type 'FirebaseX'

### ISSUE THREAD

**Issue by nileshbandekar** [dpa99c/cordova-plugin-firebasex#366]
https://github.com/dpa99c/cordova-plugin-firebasex/blob/d6c3b247232cdcfd95828137c6a96bb393d98ebd/www/firebase.js#L32

I was planning to use this id for device identification

> export class AppComponent {
> constructor(private firebase: FirebaseX){}
> **_//ERROR :  Property 'getId' does not exist on type 'FirebaseX'_**
> this.firebase.getId( (sucess) => {
>       alert('getId sucess # ' + sucess);
>     }, (error) => {
>       alert('getId error # ' + error);
>     });
> }

**Comment by dpa99c** [comment]
This relates to the [Ionic Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts) which is owned/maintained by Ionic.

While the plugin JS API exposes the `getId()` function, the Typescript wrapper does not yet.

Please raise an issue or PR against [Ionic Native](https://github.com/ionic-team/ionic-native/) to add this.

Closing at this plugin is not responsible for maintaining the Ionic Typescript wrapper.
