### ISSUE TITLE
tagmanager and inappmessaging variables in framework tag

### ISSUE THREAD

**Issue by lparcshinoda** [dpa99c/cordova-plugin-firebasex#369]
The plugin.xml of the latest cli version (9.0.3-cli) contains these 2 tags:

<framework src="com.google.android.gms:play-services-tagmanager:$ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION" />
<framework src="com.google.firebase:firebase-inappmessaging-display:$ANDROID_FIREBASE_INAPPMESSAGING_VERSION" />

but the variables are not defined in the preferences tags (due to components being removed from the cli version) - this is making the build fail with error:

Could not get unknown property 'ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by lonwi** [comment]
I had the same issue and to solve the build issue I added missing properties to the package.json

"cordova": {
      "cordova-plugin-firebasex": {
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "true",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "true",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "true",
        "ANDROID_ICON_ACCENT": "#FF00FFFF",
        **"ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",**
        "ANDROID_PLAY_SERVICES_AUTH_VERSION": "17.0.0",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.2.1",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "20.0.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "19.0.3",
        "ANDROID_FIREBASE_PERF_VERSION": "19.0.1",
        "ANDROID_FIREBASE_AUTH_VERSION": "19.1.0",
        **"ANDROID_FIREBASE_INAPPMESSAGING_VERSION": "19.0.3",**
        "ANDROID_FIREBASE_FIRESTORE_VERSION": "21.4.0",
        "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
        "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.1",
        "ANDROID_GSON_VERSION": "2.8.6"
      }
}
removed platforms and build it again

**Comment by lparcshinoda** [comment]
Yes, but doing this way the build will fail on iOS (because of the pods
error as specified here
https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds).



Il giorno gio 16 apr 2020 alle ore 15:32 Wojciech Bubolka <
notifications@github.com> ha scritto:

**Comment by dpa99c** [comment]
Sorry, this is a regression created when resolving the merge conflict from master - will push out  a `9.0.4-cli` patch release ASAP to fix this.

**Comment by dpa99c** [comment]
The above fix is published in `cordova-plugin-firebasex@9.1.0-cli`
