### ISSUE TITLE
8.x Builds fine, 9.x still refuses to successfully build for iOS, ionic 5, @angular/fire

### ISSUE THREAD

**Issue by markamccorkle** [dpa99c/cordova-plugin-firebasex#370]
# Bug report

**Current behavior:**
Build will not successfully complete iOS build. I've tried rearranging where this plugin is read from in the package as this is what fixes 8.x but I have yet to get this 9.x working with iOS. For whatever reason it seems the pod install gets messed up and doesn't successfully finish. 
FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

Just add the plugin in an ionic 4/5 project and also add     "@angular/fire": "^6.0.0"

**Expected behavior:**

iOS should build fine without a pod install failure

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `cordova platform ls`
Installed platforms:
  android 8.1.0
  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.4.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-apprate 1.5.0 "AppRate"
cordova-plugin-ble-central 1.2.4 "BLE"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 8.1.0 "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-native-spinner 1.1.3 "Native Spinner"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-touch-id 3.3.1 "Touch ID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-support-google-services 1.3.2 "cordova-support-google-services"
cordova.plugins.diagnostic 5.0.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
v13.13.0
- XCode version
11.4.1

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/ci/Library/Developer/Xcode/DerivedData/app-hffdzcaslawaakezqlprrwinwhgy/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app.build/Script-CE511C13E15CE5FB46067619.sh (in target 'app' from project 'app')
    cd /Users/ci/app/platforms/ios
    /bin/sh -c /Users/ci/Library/Developer/Xcode/DerivedData/app-hffdzcaslawaakezqlprrwinwhgy/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app.build/Script-CE511C13E15CE5FB46067619.sh
error: Resource "/Users/ci/Library/Developer/Xcode/DerivedData/app-hffdzcaslawaakezqlprrwinwhgy/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** BUILD FAILED **
```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
Use the [CLI version](https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds) for CLI builds.
However note #369.
