### ISSUE TITLE
ReferenceError: callback is not defined

### ISSUE THREAD

**Issue by sun34133** [dpa99c/cordova-plugin-firebasex#371]
I am getting the issue 
Error in Success callbackId: FirebasePlugin75355054 : ReferenceError: callback is not defined

I am using the **cordova-ios 5.1.1**

**And following cordova plugins:**
_br.com.brunogrossi.MediaScannerPlugin 0.1.3 "Media Scanner Plugin"
com.dawsonloudon.videoplayer 1.0.0 "VideoPlayer"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calendar 5.1.4 "Calendar"
cordova-plugin-certificates 0.6.4 "Certificate Plugin"
cordova-plugin-device 2.0.3-dev "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2-dev "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 8.0.1 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.2-dev "Geolocation"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"_

Please let me know if I am doing anything wrong here.

![image](https://user-images.githubusercontent.com/2997498/79579719-942c0380-80e5-11ea-860d-5f1b3b4ddbb9.png)

**Comment by dpa99c** [comment]
From the log extract it looks like you are calling [`grantPermission()`](https://github.com/dpa99c/cordova-plugin-firebasex#grantpermission) without passing in the required callback function for the plugin to pass the result to so it is failing when attempting to parse and pass the boolean result to the callback.

Pass in the callback as required and it should fix your issue.
Please also see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working reference.

**Comment by dylanfpaul** [comment]
@dpa99c So is the callback is expected but not required to fulfill the general functionality? I'm guessing its more for logging purposes or to implement some other logic in case of a failure?

**Comment by dpa99c** [comment]
> @dpa99c So is the callback is expected but not required to fulfill the general functionality? I'm guessing its more for logging purposes or to implement some other logic in case of a failure?

yes but I'd think it unlikely you wouldn't want to define a callback in a production app, e.g. to inform the user of the consequence and/or log an event to analytics

**Comment by dylanfpaul** [comment]
@dpa99c for sure, thanks for the reply.
