### ISSUE TITLE
[FEATURE] Firebase test lab

### ISSUE THREAD

**Issue by Ross-Rawlins** [dpa99c/cordova-plugin-firebasex#375]
# Feature request
Firebase base automated test lab

I have been looking into the firebase testlab with its automated testing. Because cordova/ionic runs in the webview no events are passed to the native thread for testing. Could the plugin be extended to do this just for the testing purposes where you can pass events to the native thread.

**Comment by dpa99c** [comment]
This isn't something I'd spend time on adding but I'd be happy to accept a PR that implements it.

**Comment by ianitsky** [comment]
Unfortunately firebase test lab does not work for webview. Does not work
for cordova.

**Comment by dpa99c** [comment]
> Unfortunately firebase test lab does not work for webview. Does not work for cordova.

Yes [that was](https://stackoverflow.com/a/43257717/777265) and still is the case.
