### ISSUE TITLE
Android on notification tap callback not triggered

### ISSUE THREAD

**Issue by damirsel** [dpa99c/cordova-plugin-firebasex#376]
# Bug report

**Current behavior:**
At moment plugin activates app once you tap on notification if app isn't in foreground.

What we want actually is to execute some code once user taps on the notification. At moment not a single line inside onMessegeReceived method is executed.

**Expected behavior:**

To trigger callback once user taps on a notification
**Steps to reproduce:**

Add plugin to phonegap project compile and send cloud message from FCM that contains "notification_foreground": "true"
**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v` 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
Installed platforms:
  android 8.0.0
  browser 6.0.0
- Dev machine OS and version, e.g.
    - Windows 10
        - `winver` 1909
        
_Runtime issue_
- Device details
    - Nexus One Emulator x86
- OS details
    - Android 8.1 Oreo
	
_Android build issue:_	
- Node JS version
    - `node -v` 12.16.0
- Gradle version
	- `ls platforms/android/.gradle`  6.0.1
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml` 28
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	

**Related code:**
```
FirebasePlugin.onMessageReceived(function(message) {
		try{
			alert("onMessageReceived");
			alert(message);
			if (message.tap) {
				alert('message TAPPED');
			}

			if(message.messageType === "notification"){
				handleNotificationMessage(message);
			}else{
				handleDataMessage(message);
			}
		}catch(e){
			alert("Exception in onMessageReceived callback: "+e.message);
		}
```

</details><br/><br/>

**Comment by dpa99c** [comment]
On regression testing `cordova-plugin-firebasex@9.1.0` on Android 10 using the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test), tapping on a foreground notification correctly calls `onMessageReceived()` as can be seen in [this screencapture](http://ge.tt/47kpgj23).

Please build and run the example project and use its built-in FCM client to send a test message and confirm this.

**Comment by cyrilfr** [comment]
I've the same issue. Nothing happen when I tap on the notification on Android when it opens the app on iOS.
