### ISSUE TITLE
Forestore SetDocumentInFirestoreCollection doesn't work

### ISSUE THREAD

**Issue by re2005** [dpa99c/cordova-plugin-firebasex#377]
# Bug report

**Current behavior:**

Using this code sample:

```
var documentId = "my_doc_3";
var document = {
    "a_string": "foo",
    "a_list": [1, 2, 3],
    "an_object": {
        "an_integer": 1,            
    }
};
var collection = "my_collection";
FirebasePlugin.setDocumentInFirestoreCollection(documentId, document, collection, function(){
    console.log("Successfully set document with id="+documentId);
}, function(error){
    console.error("Error setting document: "+error);
});
```

Creates a collection "my_collection" but not with the correct data inside, instead it ignores the document data and save something else

ancestorOrigins

```
hash "#/"
host ""
hostname ""
href "file:///android_asset/www/index.html#/"
origin "file://"
pathname "/android_asset/www/index.html"
port ""
protocol "file:"
search ""
```

**Expected behavior:**

When using the method "setDocumentInFirestoreCollection" should save the correct document data.

**Steps to reproduce:**

Just trigger this code:

```
var documentId = "my_doc";
var document = {
    "a_string": "foo",
    "a_list": [1, 2, 3],
    "an_object": {
        "an_integer": 1,            
    }
};
var collection = "my_collection";
FirebasePlugin.setDocumentInFirestoreCollection(documentId, document, collection, function(){
    console.log("Successfully set document with id="+documentId);
}, function(error){
    console.error("Error setting document: "+error);
});
```

Check the result inside Firebase/database console 

**Environment information**

- Cordova CLI version 
	- `9.0.0`
- Cordova platform version
	- `android 8.1.0`
- Plugins & versions installed in project (including this plugin)

> cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
> cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
> cordova-plugin-badge 0.8.8 "Badge"
> cordova-plugin-ble 2.0.1 "Evothings BLE API"
> cordova-plugin-device 2.0.3 "Device"
> cordova-plugin-dialogs 2.0.2 "Notification"
> cordova-plugin-eddystone 1.3.0 "Eddystone"
> cordova-plugin-firebasex 9.1.0-cli "Google Firebase Plugin"
> cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
> cordova-plugin-splashscreen 5.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.4.3 "StatusBar"
> cordova-plugin-vibration 3.1.1 "Vibration"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"

- Dev machine OS and version, e.g.
    - OSX

> ProductName:	Mac OS X
> ProductVersion:	10.15.4
> BuildVersion:	19E266

Thanks for any help!

**Comment by dpa99c** [comment]
Please try building and running the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) as this [makes use of `setDocumentInFirestoreCollection()`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L847) and the data written to Firestore appears as expected:

![image](https://user-images.githubusercontent.com/2345062/80099177-f6fa2080-8565-11ea-8baa-ccd7cea0914a.png)

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by re2005** [comment]
Het @dpa99c Sorry about the delay.

After your comment here, I tried again using the example and it works fine.

Perhaps you can update the readme example with this code.

Thanks a lot!
