### ISSUE TITLE
Build failing due to resource ...InAppMessagingDisplayResources.bundle not found

### ISSUE THREAD

**Issue by benazir46** [dpa99c/cordova-plugin-firebasex#379]
# Bug report

**Current behavior:**
After adding the plugin on Ionic V3 or V4 project, build fails with the error bellow:
I tried the following commands to fix: 
- pod repo update
- sudo gem install cocoapods
- pod install
- ionic cordova build ios (with or without sudo)

There is no code signing issue as I did use this plugin before and published the app. Just to be sure, I created a fresh project using the lonic cordova project, but still it throws the same error:

> PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh (in target 'myApp' from project 'myApp')
    cd /Users/benazir/Projects/myApp/platforms/ios
    /bin/sh -c /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh
error: Resource "/Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** BUILD FAILED **

The following build commands failed:
        PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.

**Expected behavior:**
Ionic project builds successfully.

**Steps to reproduce:**

- ionic start myApp tabs --cordova
- ionic cordova platform add ios
- ionic cordova build ios (successful)
- ionic serve (successful)
- ionic cordova plugin add cordova-plugin-firebsex
- ionic cordova build ios (fails)

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`: 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `cordova platform ls`: 
Installed platforms:
  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`: Catalina 10.15.4
        
- OS details
    - _e.g. iOS 13.4.1
	
_iOS build issue:_
- Node JS version
    - `node -v`: v12.16.2
- XCode version
11.4.1

**Console output**
<details>
<summary>console output</summary>

```

GenerateDSYMFile /Users/benazir/Projects/myApp/platforms/ios/build/emulator/myApp.app.dSYM /Users/benazir/Projects/myApp/platforms/ios/build/emulator/myApp.app/myApp (in target 'myApp' from project 'myApp')
    cd /Users/benazir/Projects/myApp/platforms/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/benazir/Projects/myApp/platforms/ios/build/emulator/myApp.app/myApp -o /Users/benazir/Projects/myApp/platforms/ios/build/emulator/myApp.app.dSYM

PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh (in target 'myApp' from project 'myApp')
    cd /Users/benazir/Projects/myApp/platforms/ios
    /bin/sh -c /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh
error: Resource "/Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

** BUILD FAILED **


The following build commands failed:
        PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/benazir/Library/Developer/Xcode/DerivedData/myApp-asdgmvpfzvjlrbajiyrxqlmvsnjk/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-C425B68117DFED80D0991756.sh
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds
