### ISSUE TITLE
[BUG?] Getting Error while installing plugin

### ISSUE THREAD

**Issue by allnash** [dpa99c/cordova-plugin-firebasex#381]
# Bug report
```
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-firebasex': CordovaError: Uh oh!
File already exists at destination "/Users/{{WORKSPACE}}/app/platforms/ios/{{APP}}/Resources/GoogleService-Info.plist" for resource file specified by plugin cordova-plugin-firebasex in iOS platform
    at install (/Users/{{WORKSPACE}}//{{APP}}//app/platforms/ios/cordova/lib/plugman/pluginHandlers.js:64:23)
    at ActionStack.process (//app/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (//app/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin /app/node_modules/cordova-common/src/PluginManager.js:144:17)
    at Api.addPlugin (/app/platforms/ios/cordova/Api.js:245:10)
    at handleInstall (/.nvm/versions/node/v10.18.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:581:10)
    at 
/.nvm/versions/node/v10.18.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:349:28
    at process._tickCallback (internal/process/next_tick.js:68:7)
for resource file specified by plugin cordova-plugin-firebasex in iOS platform
```

`conifg.xml`

```
    <plugin name="cordova-plugin-firebasex" spec="^9.1.1">
        <variable name="FIREBASE_ANALYTICS_COLLECTION_ENABLED" value="false" />
        <variable name="FIREBASE_PERFORMANCE_COLLECTION_ENABLED" value="false" />
        <variable name="FIREBASE_CRASHLYTICS_COLLECTION_ENABLED" value="false" />
    </plugin>
```

**Expected behavior:**
Plugin should install

**Steps to reproduce:**
cordova plugin add <plugin_name>

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`

9.0.0 (cordova-lib@9.0.1)

- Cordova platform version

iOS

- Dev machine OS and version, e.g.
OSX(Latest)

**Comment by allnash** [comment]
I tried removing that file and re-installing, won't work.

**Comment by dpa99c** [comment]
This could be caused by a conflict with another plugin or another issue specific to your project.
Please try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to confirm the plugin builds correctly in isolation.

**Comment by allnash** [comment]
@dpa99c I don't know why it would.
Here is the list:

```
    <plugin name="cordova-plugin-whitelist" spec="~1.3.4" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="~2.1.3" />
    <plugin name="cordova-plugin-camera" spec="^4.1.0" />
    <plugin name="cordova-plugin-camera-preview" spec="~0.11.2" />
    <plugin name="cordova-plugin-keyboard" spec="~1.2.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~5.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="~2.4.3" />
    <plugin name="cordova-plugin-customurlscheme" spec="~4.4.0">
        <variable name="URL_SCHEME" value="nutri" />
    </plugin>
    <plugin name="cordova-plugin-ionic-webview" spec="~4.1.3" />
    <plugin name="cordova-plugin-device" spec="^2.0.3" />
    <plugin name="cordova-plugin-safariviewcontroller" spec="~1.6.0" />
    <plugin name="cordova-plugin-enable-multidex" spec="~0.2.0" />
    <plugin name="cordova-plugin-firebasex" spec="^9.1.1" />
```

**Comment by allnash** [comment]
that's all I am using, to be honest, there are no other plugins that conflicts with Google Firebase.

**Comment by allnash** [comment]
Ok, I did some more digging around: Use instructions here:
```
https://stackoverflow.com/questions/51131825/how-to-reinstall-plugins-already-recoded-in-config-xml-in-cordova
```

Followed these steps:
1. `Delete` folder `ios` `android` inside `platforms`.
2. Delete All plugins under `plugins` folder
2. Run `cordova prepare`

@dpa99c remove all plugins and only kept this one, still ran into the issue.

**Comment by allnash** [comment]
Ok, I did some more digging around: Use instructions here:
```
https://stackoverflow.com/questions/51131825/how-to-reinstall-plugins-already-recoded-in-config-xml-in-cordova
```

Followed these steps:
1. `Delete` folder `ios` `android` inside `platforms`.
2. Delete All plugins under `plugins` folder
2. Run `cordova prepare`

@dpa99c Still keep this issue in mind.

I will revert to `9.1.0` and try again

**Comment by allnash** [comment]
I was unable to fix it, after trying a few times. It gave me an error to run pod install.
I give up. Maybe will try the alternative that doesn't do magical configuration behind the scenes.
https://github.com/chemerisuk/cordova-plugin-firebase-messaging#readme

**Comment by theavijitsarkar** [comment]
@dpa99c This is one of the best plugins for firebase, I have been using this for a long time. Off late, installing this in ios has become a night mare. I get it going after multiple platform removes, 9.0.1-cli and what not. Can this be a little streamlined like before

**Comment by theavijitsarkar** [comment]
@dpa99c Also build time takes 3x longer with this installed.

**Comment by dpa99c** [comment]
@theavijitsarkar this is open-source software: if you are not happy with it, submit a PR to make it better

**Comment by theavijitsarkar** [comment]
@dpa99c I am extremely sorry for putting this out in a wrong way. I am a big fan of your work, and this is an awesome plugin. I wish someday I have the talent to be able to contribute. Totally respect that this is an open source software, just was pointing out to my difficulty. Thanks again for putting this out there.

**Comment by tomavic** [comment]
Need to support this update 
https://developer.android.com/distribute/play-policies 

Thanks @dpa99c

**Comment by wswoodruff** [comment]
For me this issue was resolved when I removed `<resource-file src="GoogleService-Info.plist"/>` from `config.xml`. I was working on updating from `cordova-plugin-firebase-messaging` and that was leftover from having that plugin installed.

Found this answer from this comment in another Issue: https://github.com/dpa99c/cordova-plugin-firebasex/issues/152#issuecomment-536706886
