### ISSUE TITLE
[FEATURE] Add support for Firebase Storage

### ISSUE THREAD

**Issue by PrincesseLulu** [dpa99c/cordova-plugin-firebasex#383]
https://firebase.google.com/docs/storage

**Comment by vlafranca** [comment]
Hi, why have this been abandonned ? I also need this feature.

**Comment by dntzbgh** [comment]
Hello, 
I'm also interested in the status update of this feature. Is it going to be added or there is some other limitation that makes it impossible to make? 
I see that the issue was marked as completed.
