### ISSUE TITLE
[!] Unable to find a specification for `Crashlytics (= 3.14.0)`

### ISSUE THREAD

**Issue by mzl1988** [dpa99c/cordova-plugin-firebasex#384]
![image](https://user-images.githubusercontent.com/11645762/81041390-4fbfa680-8ee0-11ea-97f0-3ab2e5375577.png)

[Crashlytics (legacy)](https://fabric.io/kits/ios/crashlytics/update?type=manual)

![image](https://user-images.githubusercontent.com/11645762/81041453-77167380-8ee0-11ea-9ebd-7205d735b3b9.png)

**Comment by dpa99c** [comment]
The solution is shown in your screenshot: `pod repo update`
https://github.com/dpa99c/cordova-plugin-firebasex#out-of-date-pods
