### ISSUE TITLE
Can we authenticate users with Facebook Account?

### ISSUE THREAD

**Issue by Livideakoto** [dpa99c/cordova-plugin-firebasex#387]
- Authenticates with Facebook Account
- Among authentication functions presented there is not a function that gives the ability to connect a user with his facebook account. Can you implement this function in the authentication API. If it already exists, the documentation should be updated with the adequate process.

Thanks for the job done ✅

**Comment by dpa99c** [comment]
No, Firebase Auth is not supported as it requires introducing a dependency on the weighty Facebook SDK. For this reason it will not be added to this plugin directly though possibly will be added as a child/sibling plugin in future if I have need for it.
