### ISSUE TITLE
IOS cordova build ios 

### ISSUE THREAD

**Issue by Nelo-cool** [dpa99c/cordova-plugin-firebasex#388]
Help my guys please:)
After build that: cordova build ios --device --buildFlag="-UseModernBuildSystem=0" or cordova build ios --device i can see: 

> n file included from <module-includes>:1:
> /Users/admin/.taco_home/remote-builds/taco-remote/builds/Thisislogic.Gtrk37/platforms/ios/Pods/Headers/Public/Firebase/Firebase.h:15:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found
> #import <FirebaseCore/FirebaseCore.h>
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> /Users/admin/.taco_home/remote-builds/taco-remote/builds/Thisislogic.Gtrk37/platforms/ios/GTRK«CyrillicName»/Plugins/cordova-plugin-firebasex/FirebasePlugin.m:4:9: fatal error: could
>       not build module 'Firebase'
> #import "Firebase.h"
>  ~~~~~~~^~~~~~~~~~~~
> 2 errors generated.

I had this error in XCode, in bash... I think that at the time of installing the plugin something went wrong. But I checked pods (1.9.1 installed by sudo), added and removed it. Not help:( But meybe you will help me?:)

**Comment by dpa99c** [comment]
This is insufficient information to diagnose the cause of the issue.
However, at a guess I see a possible cause with `GTRK«CyrillicName»` as Cyrillic characters in paths are known to cause issues with iOS builds - try removing any Cyrillic characters in the path.

Also please attempt to build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase to validate your dev environment.

If you encounter a similar problem with the example project, please complete the issue template in full including full console output by appending the `--verbose` flag to any CLI commands.
