### ISSUE TITLE
BUILD FAILED ANDROID

### ISSUE THREAD

**Issue by richardjimenezyolo** [dpa99c/cordova-plugin-firebasex#389]
Hi guys... I'm trying to get this plugin up and running in a new blank project and at the moment of building. Can anyone help me out?

This is the output:
``FAILURE: Build failed with an exception.                                                   
* What went wrong:                                                                            
Execution failed for task ':app:compileDebugJavaWithJavac'.                                   
> Compilation failed; see the compiler error output for details.                              
                                                                                              
* Try:                                                                                        
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get 
more log output. Run with --scan to get full insights.                                        
                                                                                              
* Get more help at https://help.gradle.org                                                    
                                                                                              
BUILD FAILED in 1m 16s                                                                        
this is the cordova version that I'm using:
`9.0.0 (cordova-lib@9.0.1)`

And android version:
`cordova-android@^8.0.0`

**Comment by dpa99c** [comment]
This is insufficient information to diagnose the cause of the issue.
Please attempt to build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase to validate your dev environment.

If you encounter a similar problem, please complete the issue template in full including full console output by appending the `--verbose` flag to any CLI commands.

**Comment by richardjimenezyolo** [comment]
I ended up figuring out the problem and it was just windows being windows.

I installed arch Linux and everything worked just fine. It took me a few days but I ended up with it working ;)
