### ISSUE TITLE
cordova 9.0 + cordova-ios 5.1.1 failed to install latest version firebasex

### ISSUE THREAD

**Issue by yuanzuo** [dpa99c/cordova-plugin-firebasex#393]
trying to install firebasex, got this error:

>cordova plugin add cordova-plugin-firebasex
Installing "cordova-plugin-firebasex" for ios
Installing "cordova-plugin-androidx" for ios
Installing "cordova-plugin-androidx-adapter" for ios
Failed to install 'cordova-plugin-firebasex': undefined
CordovaError: Promise rejected with non-error: '/bin/sh: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory\n'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

my environment: 
cordova:9.0
cordova-ios: 5.1.1

Please help!

**Comment by dpa99c** [comment]
The error indicates Cocoapods is not working correctly on your machine.

- Read the [documentation](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods)
- Try building [the example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your dev env
- Append `--verbose` to CLI commands to get full error details to assist in diagnosing the issue

This is not a bug with the plugin.
