### ISSUE TITLE
xcode build error with firebasex 9.1.1

### ISSUE THREAD

**Issue by yuanzuo** [dpa99c/cordova-plugin-firebasex#394]
cordova: 9.0.0
cordova ios:5.1.1
xcode: version 11.3.1
macOS: Mojave 10.14.6
firebasex: 9.1.1

cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-firebasex 9.1.1 "Google Firebase Plugin"

error:
fatal error: error in backend: Unexpected end of file
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-ios8.0-simulator
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.

**Comment by yuanzuo** [comment]
fatal error: error in backend: Unexpected end of file
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-ios8.0-simulator
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/fq/hcwnkp712rz8sfhzps5nh995ty1lkp/T/FIRMessagingSecureSocket-157d20.m
clang: note: diagnostic msg: /var/folders/fq/hcwnkp712rz8sfhzps5nh995ty1lkp/T/FIRMessagingSecureSocket-157d20.cache
clang: note: diagnostic msg: /var/folders/fq/hcwnkp712rz8sfhzps5nh995ty1lkp/T/FIRMessagingSecureSocket-157d20.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/yzuo/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

**Comment by yuanzuo** [comment]
it looks the error from compiling FIRMessagingSecureSocket.m:

CompileC /Users/yzuo/Library/Developer/Xcode/DerivedData/xxx-crcxbtvzvkaeyeedslfatiafumhx/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseMessaging.build/Objects-normal/x86_64/FIRMessagingSecureSocket.o /Users/yzuo/trucking22copy\ t0512/platforms/ios/Pods/FirebaseMessaging/Firebase/Messaging/FIRMessagingSecureSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target

**Comment by dpa99c** [comment]
> Target: x86_64-apple-ios8.0-simulator

You are trying to build for iOS 8.0 which, [as documented](https://github.com/dpa99c/cordova-plugin-firebasex#supported-mobile-platform-versions), is not supported by Firebase SDK or this plugin.

**Comment by yuanzuo** [comment]
Hi Dave, I switched to firebasex 8.1.0. but I still get error on CLI build ios:
error: Resource "/Users/yzuo/Library/Developer/Xcode/DerivedData/xxx-crcxbtvzvkaeyeedslfatiafumhx/Build/Products/Debug-iphonesimulator/FirebaseInAppMessaging/InAppMessagingDisplayResources.bundle" not found. Run 'pod install' to update the copy resources script.

Any ideas?Also, What I need for this plugin is just for monitoring event like this in my javascript code: window.FirebasePlugin.logEvent("accountInfoController", "");
Could you please recommend a minimum version of this plugin to serve my purpose?I also need to a version w/o using UIWebView. 
Thanks

    On Tuesday, May 12, 2020, 11:48:38 AM EDT, Dave Alden <notifications@github.com> wrote:  
 
 



Target: x86_64-apple-ios8.0-simulator


You are trying to build for iOS 8.0 which, as documented, is not supported by Firebase SDK or this plugin.
