### ISSUE TITLE
Doesn't compile after installation

### ISSUE THREAD

**Issue by iconio** [dpa99c/cordova-plugin-firebasex#396]
# Bug report

**Current behavior:**
After installing the plugin the project doesn't compile and it finishes with error 65.

If I remove the plugin the project compiles perfectly.

**Environment information**
```
Ionic:

   Ionic CLI                     : 6.9.0 (/Users/wd/.nvm/versions/node/v12.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 17 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.11.1 (/Users/wd/.nvm/versions/node/v12.11.1/bin/node)
   npm        : 6.14.4
   OS         : macOS Catalina
   Xcode      : Xcode 11.4.1 Build version 11E503a
```

**Console output**

```
> cordova run ios
[cordova] ** BUILD FAILED **
[cordova]
[cordova]
[cordova] The following build commands failed:
[cordova] 	PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/wd/Library/Developer/Xcode/DerivedData/myApp-gftvmmnfqwbuwvcufrjakxcubeym/Build/Intermediates.noindex/myApp.build/Debug-iphonesimulator/myApp.build/Script-0B21D8ADE62B0FDBDC4B0B25.sh
[cordova] (1 failure)
[cordova] xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.

        cordova run ios exited with exit code 65.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds

**Comment by iconio** [comment]
Hey @dpa99c I did that. I got the GoogleService file both plist and json on the root of my project and it doesn't compile at all. Same error.

**Comment by dpa99c** [comment]
The FirebaseX Typescript wrapper is part of Ionic Native - please [raise an issue there](https://github.com/ionic-team/ionic-native/issues/new)

**Comment by iconio** [comment]
Just for future reference if someone else has this issue, the problem is not with FirebaseX, it's with the cocoapods.

As of today, there is not a fix yet, BUT there is a work around:
https://github.com/CocoaPods/CocoaPods/issues/8677#issuecomment-480247466

Thanks @dpa99c

**Comment by dariobertini** [comment]
> Hey @dpa99c I did that. I got the GoogleService file both plist and json on the root of my project and it doesn't compile at all. Same error.
> 
> There is also somebody else on Ionic Forum with the same issue.
> 
> I'm following the instructions on the documentation, and on this part: https://github.com/dpa99c/cordova-plugin-firebasex#ionic-4
> When I add this to my app.module.ts I get this:
> 
> > Type FirebaseXOriginal is not assignable to type Provider.
> 
> Even thou I'm not calling this FirebaseXOriginal.
> 
> ```
> import { FirebaseX } from '@ionic-native/firebase-x/ngx';
> 
> providers: [ ... , FirebaseX ]
> ```
@iconio 
how do you solve this issue? Because seems not related to bug reported.

**Comment by iconio** [comment]
Hey @dariobertini I got the solution using this [coment](https://github.com/CocoaPods/CocoaPods/issues/8677#issuecomment-480247466): 

**Solution:**
I deleted the [CP] Copy Pods Ressources build phase manually from the the project. bundle exec pod install doesn't add the [CP] Copy Pods Ressources build phase again, so this solution is fine for us.
