### ISSUE TITLE
Why don't notifications arrive on iOS?

### ISSUE THREAD

**Issue by aapa96** [dpa99c/cordova-plugin-firebasex#397]
Why don't notifications arrive on iOS

my application compiled well I installed it but notifications do not arrive

**Comment by pravinkumarputta** [comment]
I'm facing the same problem, but only when the app is in the background. I'm receiving notification callback when the app is in the foreground in Android and iOS. In the case of background, only Android is working fine.

When I open the app manually, then sent a message that receives in the callback.
I think the system is not handling background notification.

In iOS, I'm using below message payload,
`{
  "name": "my_notification",
  "notification": {
    "body": "Notification body",
    "title": "Notification title"
  },
  "apns": {
    "payload": {
      "aps": {
        "content_available": 1,
        "badge": 1,
        "sound": "default"
      }
    }
  },
  "to": "dl_DL5xan0VVqawoD9-VED:APA91bFiu46KBEg-dGgxYIXu08UncUYDHM-B6ehyPzmLqFIGTbH3bsKkgMe1-rqnWT3WXt0owLXWEWHw7CWkZzQqKZDOCYRxCXscj_cw0iamBAzVAJ6tqxjYq1TU5et_TdHXoxE2a9QT",
  "priority": "high",
  "restricted_package_name": ""
}`

I'm trying to integrate FCM in my app from the last 3 days. I tried so many plugins. Finally, this plugin working 75%.

Can you help me...

**Comment by dpa99c** [comment]
@aapa96  Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex) as a known working codebase to validate your iOS APNS configuration and development environment, using its built-in FCM v1 client to send valid test messages.

**Comment by dpa99c** [comment]
@pravinkumarputta same as above and also see [this](https://github.com/dpa99c/cordova-plugin-firebasex/issues/364#issuecomment-613313456)

**Comment by outofsocial** [comment]
in my case, i changed app name unicode(korean) to only english it solved,
when plugin added, pod install path broken with unicode then generated pod______.framework inside platform and plugin install failed but build without error.
