### ISSUE TITLE
have a problem with Ios

### ISSUE THREAD

**Issue by aapa96** [dpa99c/cordova-plugin-firebasex#398]
notifications come to me, it is printed on the console but it is not shown on the emulator or cell phone. IOS ONLY;

**Comment by aapa96** [comment]
![Uploading Captura de Pantalla 2020-05-13 a la(s) 23.00.12.png…]()

**Comment by dpa99c** [comment]
Please follow the issue guidelines:
https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues
