### ISSUE TITLE
Notification not comes when app is in kill mode(not in recents) in android ionic 4 using firebase x plugin in ionic 4

### ISSUE THREAD

**Issue by jay9792** [dpa99c/cordova-plugin-firebasex#402]
# Bug report

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by jay9792** [comment]
please provide me solution of when app is in kill mode not in recents at that time notification does not comes using firebase x plugin in android 

ionic 4

**Comment by dpa99c** [comment]
You've not followed the [guidelines for reporting issues](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues) so this issue will now be closed.

However you may want look at #235 to see if this is the cause of your problem on Android (though you haven't completed the issue template in order to know what device you are testing on).

Please read the issue guidelines thoroughly before reporting another issue.

**Comment by jay9792** [comment]
it would be great if you please provide me solution for backgroud notification when app is killed it is not coming notification

please suggest me what is the exact solution

**Comment by jay9792** [comment]
i am checking in xiomi note 5 pro

**Comment by dpa99c** [comment]
> i am checking in xiomi note 5 pro

Then yes, this is covered by #235

**Comment by jay9792** [comment]
please provide solution m getting notification when app is killed

ionic 4
platform :android

please share the payload json what should be default

**Comment by jay9792** [comment]
please provide me the exact solution what should be done

**Comment by dpa99c** [comment]
> please provide me the exact solution what should be done

My contracting rate is $700/day. If we can agree your requirements, I will make a time estimate of how long that will take and present you with a quoted price. If you are happy with that price, and make payment upfront via bank transfer, I am happy to provide you with an exact bespoke solution.
