### ISSUE TITLE
I don't get notification with app is killed

### ISSUE THREAD

**Issue by hugobernardoni** [dpa99c/cordova-plugin-firebasex#403]
Hello good afternoon.
I am implementing the Firebase routine using the data load.
In the onMessageReceived method I receive the information both in the foreground and in the background. (from there I do my actions, including I trigger the notification using the local notification)
However, when I kill the app and trigger the push, I don't receive any data. Actually, I get paid, but when I open the app again.
Sensation that he is on hold, and only acts when the application is opened.
Can someone help me?

`this.firebase.onMessageReceived().subscribe((notification: any) => {
      console.log(new Date(Date.now()).toLocaleString());
      console.log(notification);  
      console.log("Message type: " + notification.messageType);
    });`

**Comment by dpa99c** [comment]
You did not complete the issue template so it's unclear what platform or device you are testing on, whether you have tested using the example project or exactly how to reproduce the issue.

Please read the [guidelines for reporting issues](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues) and if you still think an issue exists which is a genuine suspected bug (and not a support request) then open and new issue and complete the issue template **in full**.
