### ISSUE TITLE
Firebase deprecating direct channel API

### ISSUE THREAD

**Issue by znewsham** [dpa99c/cordova-plugin-firebasex#406]
Firebase has stated they will deprecate their direct channel API from V7 and that within the next year they will remove the backend features for this. It seems like this plugin forces direct channel to be true:
```
[FIRMessaging messaging].shouldEstablishDirectChannel = true;
```

Is this required for all apps to receive push notifications in the foreground? Can it be set to false by some configuration in the plist of the application?

**Comment by lucassouza16** [comment]
I was same issue

**Comment by dpa99c** [comment]
> Firebase has stated they will deprecate their direct channel API from V7 and that within the next year they will remove the backend features for this

Please can you provide a link to the documentation which states this.

**Comment by patrick-entinux** [comment]
@dpa99c I'm not the original poster but here's the email I received from Firebase today:

> Hi *company*
>
> We are writing to let you know that [Firebase Messaging iOS Direct Channel API support](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#/c:objc(cs)FIRMessaging(py)shouldEstablishDirectChannel) is marked for deprecation. **Firebase Messaging iOS SDK version 7.0 will be a breaking change where the SDK will no longer support iOS Direct Channel API**.
> 
> What do I need to know?
> 
> Firebase Messaging iOS Direct Channel has been used for sending data to apps when they are in the foreground and for upstream messages. The Firebase Messaging iOS SDK v7.0 (slated to be released in September 2020) will no longer support the iOS Direct Channel API**. Your app will break if you update to the Firebase Messaging iOS SDK v7.0 without migrating off the iOS Direct Channel API.**
> 
> We are removing this feature in favor of natively supported messaging features provided by Apple Push Notification Service.
> 
> To prevent disruptions to your users, we recommend that you **discontinue use of the iOS Direct Channel API as soon as possible.** Please note that for the time being, your existing users can still continue to receive messages via the iOS Direct Channel API. However, within the next year, we will follow up this announcement with plans to deprecate the backend service support which may break your app with older versions of the Messaging iOS SDK (prior to v7.0).
> 
> What do I need to do?
> 
> -   To prevent disruptions to your users, we recommend that you discontinue use of the iOS Direct Channel API and use an [alternative](https://firebase.google.com/docs/cloud-messaging/ios/receive) such as FCM’s APNs interface for downstream data message delivery.
> -   If you are not using [FCM HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1). FCM HTTP v1 API provides full APNs support. If you need to continue using FCM Legacy API, you can:
> 
> -   [Add the \`content\_available\` key to your payload](https://firebase.google.com/docs/cloud-messaging/http-server-ref) if you continue to use the legacy sender API.
> 
> -   For upstream messages, make arrangements to send messages directly from your app to your servers.
> -   For real time updates, you can use [Cloud Firestore](https://firebase.google.com/docs/database), or other services.
> 
> You are an owner of the following Firebase project(s) that uses Firebase Messaging iOS Direct Channel API:
> 
> -   ** (my projects) **
> 
> As always, if you have any questions or need any assistance, feel free to [reach out to support](https://firebase.google.com/support?utm_campaign=firebase_maps_billing_account&utm_medium=email&utm_source=email) for more assistance.

**Comment by znewsham** [comment]
Can confirm - I got the same email

**Comment by selvindenis97** [comment]
Got the same e-mail but never specified which one to use.
Is there any way to verify if the app uses APN or Direct Channel?

**Comment by znewsham** [comment]
@dpa99c Thanks for the quick turn around on this, I see that you've merged the changes to master, but I don't see a new plugin/package version - is one required?

**Comment by dpa99c** [comment]
@znewsham this will go out in the next release (hence the label "ready for release").
Until then, if you want this functionality, you can install the plugin directly off the master branch.

However given the Firebase Messaging iOS SDK v7.0 is slated to be released in September 2020 and backend support will only subsequently be disabled "within the next year", I don't see any urgent rush to integrate this immediately.

**Comment by znewsham** [comment]
Awesome, thanks for the response - I just wanted to get a rough timeline!
