### ISSUE TITLE
Connect app to Firebase Analytics

### ISSUE THREAD

**Issue by maksymov** [dpa99c/cordova-plugin-firebasex#411]
How can I see my app data in Firebase Analytics?
Where I need to paste this code from firebase console tutorial:
```
@import UIKit;
@import Firebase;

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [FIRApp configure];
  return YES;
}
```

**Comment by dpa99c** [comment]
Please read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) and [guidelines  for reporting issues](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues).
This is not the place to ask for support - ask on StackOverflow or elsewhere.

**Comment by maksymov** [comment]
so, where I can ask support? I can't fix this issue for a long time and no any documentation about this :(
