### ISSUE TITLE
 plugin has old android support dependencies instead of using the new AndroidX equivalent.

### ISSUE THREAD

**Issue by losciur** [dpa99c/cordova-plugin-firebasex#412]
Hi,
I'm trying to use this plugin with capacitor and in Android Studio I get this error 'Cannot resolve symbol ActivityCompat' at line:
import android.support.v4.app.ActivityCompat;

In the capacitor documentation says that: 
Error: "package android.support.* does not exist"
This error occurs when some Cordova or Capacitor plugin has old android support dependencies instead of using the new AndroidX equivalent. You should report the issue in the plugin repository so the maintainers can update the plugin to use AndroidX dependencies.

I don't know if it's the same error...
But the final question is:
This plugin has old android support dependencies instead of using the new AndroidX equivalent, do you think to upgrade?

Thanks!

**Comment by nereolopez** [comment]
Hi, 

I did not face that issue with this package, but with others. Try `npm install --save-dev jetifier` and then `npx jetify`. (you can add that to your `postinstall` of your `package.json` so it will do it with any new dependency you install if needed). This will run in the background for a while as it converts to AndroidX the libraries you use that are not AndroidX ready (it does not show the progress, so give it a time before npx cap syncing / copying back). 

Hope this helps!

**Comment by dpa99c** [comment]
This plugin [has dependencies](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L9) on [cordova-plugin-androidx](https://github.com/dpa99c/cordova-plugin-androidx) and [cordova-plugin-androidx-adapter](https://github.com/dpa99c/cordova-plugin-androidx-adapter) which add AndroidX support to Cordova projects and dynamically patch any source code (including this plugin) from the legacy Android Support Library to AndroidX.

This works fine in a Cordova environment (you can test this yourself with [the example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)) however it may not work in a Capacitor project. However this is a Cordova plugin and Capacitor is not officially supported.

**Comment by losciur** [comment]
@nereolopez  thank you very much, it works!
@dpa99c I know, I used this plugin since years with Cordova and in these days I'm trying to use Capacitor... Thank you for your job with Cordova!
