### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by cerealexx** [dpa99c/cordova-plugin-firebasex#420]
# Feature request
Any plans to add mlkit functionality to FirebaseX? There is no viable cordova plugin for mlkit atm so it would be a great addition.

**Comment by dpa99c** [comment]
This plugin is intended to include the most commonly used features of the Firebase SDK.
It already includes quite a lot of those features and hence causes app builds to get quite large, so I'm hesitant to add machine learning as I don't believe it's that commonly used and looks like it might add quite a lot of weight (going by the number of components in the [Android Firebase SDK](https://firebase.google.com/support/release-notes/android)).

Therefore I think this is best encapsulated in a new Firebase plugin which is explicitly for the machine learning functionality and made compatible with this plugin.
This might be something @chemerisuk would consider adding to his suite of individual Cordova Firebase plugins.
