### ISSUE TITLE
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

### ISSUE THREAD

**Issue by Kavyagupta24** [dpa99c/cordova-plugin-firebasex#424]
I'm using Cordova to build iOS apps. When I'm uploading a build to AppStoreConnect, I'm getting the well known deprecation message:

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

The POD generated files  AppAuth and GoogleSignIn, after installing this plugin have instance of UIWebview showing (Supports sign-in via "UIWebVIew") log. 
Please update the plugin removing all UIWebView usage and using WKWebView.

**Comment by dpa99c** [comment]
Duplicates #266
