### ISSUE TITLE
Not getting background notifications on iOS

### ISSUE THREAD

**Issue by iconio** [dpa99c/cordova-plugin-firebasex#425]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Once the app in in background mode this shows up on XCode's console and I can't receive notification while the app is in background. If the app is in foreground the notification shows up without a problem.
I also have a log confirming that Notifications is enabled.

> _hasPermission: YES

> FirebasePlugin[native] LOG: FCM direct channel = false

> FirebasePlugin[native]: FCM direct channel = false

**Expected behavior:**
To be able to receive push notifications when the app is on Background.

**Environment information**

```
Ionic:

   Ionic CLI                     : 6.10.0 (/Users/wd/.nvm/versions/node/v12.11.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.1.0
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 15 other plugins)

Utility:

   cordova-res (update available: 0.14.0) : 0.8.1
   native-run (update available: 1.0.0)   : 0.3.0

System:

   ios-deploy : 1.10.0
   ios-sim    : 8.0.2
   NodeJS     : v12.11.1 (/Users/wd/.nvm/versions/node/v12.11.1/bin/node)
   npm        : 6.14.5
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c
```

**Related code:**
```
// Check for Permission accordingly to documentation
if (this.platform.is('ios')) {
    token = await this.firebaseX.getToken();
    const hasPermission = await this.firebaseX.hasPermission();
    if (!hasPermission) {
        await this.firebaseX.grantPermission();
    }
}
```

**Console output**
<details>
<summary>console output</summary>

```

Ionic Native: deviceready event fired after 277 ms
2020-06-09 18:40:57.452323-0300 registerForRemoteNotifications
2020-06-09 18:40:57.452403-0300  _hasPermission: YES
2020-06-09 18:40:57.703922-0300 Metal GPU Frame Capture Enabled
2020-06-09 18:40:57.705922-0300 Metal API Validation Enabled
2020-06-09 18:41:12.096532-0300 FirebasePlugin[native] LOG: FCM direct channel = true
2020-06-09 18:41:12.105379-0300 FirebasePlugin[native]: FCM direct channel = true
```

When in background mode:
```
2020-06-09 18:54:44.351349-0300 FirebasePlugin[native] LOG: FCM direct channel = false
2020-06-09 18:54:44.622303-0300 FirebasePlugin[native]: FCM direct channel = false
```

</details><br/><br/>

**Other information:**
I want to to say thank you for this, this is amazing.

**Comment by dpa99c** [comment]
The most likely cause of this issue is your APNS configuration since background notifications on iOS working fine for myself and other users of this plugin, indicating the issue is not caused by a bug in the plugin code.

Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase to validate your APNS configuration and read the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/certs) on setting up APNS in Firebase.

With regard to this:

> FirebasePlugin[native]: FCM direct channel = false

This log message is irrelevant to background notifications as it concerns the (now deprecated) direct channel API which is only applicable while the app is in the foreground - see #406.
