### ISSUE TITLE
onMessageReceived() can't receive Notification in background when app is closed

### ISSUE THREAD

**Issue by dhruvika123** [dpa99c/cordova-plugin-firebasex#426]
Hello, 
I'm not able to receive any notification in background as system notification in Android and IOS

Here is my Environment for ionic ,cordova and angular
Ionic CLI                     : 5.4.4
Cordova CLI               : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms      : android 8.1.0
@angular/cli                : 8.1.3

Here is My package.json for Firebase X plugins:
"dependencies": {
    "@ionic-native/firebase-x": "^5.26.0",
    "cordova-plugin-firebasex": "^9.1.2-cli",
}

Here is my code I'm using FCM service for notification. 

  async listenToNotifications() {

    return this.firebaseNative.onMessageReceived().subscribe(
     async res => {
        this.translate.get("OK").subscribe(value => {
          this.ok_label = value;
        });
        this.translate.get("CANCEL").subscribe(value => {
          this.cancel_label = value;
        });
        let msg: any = res;
        if (this.platform.is("android")) {
          if (msg.type == "publish_ig") {
            msg.body = msg.postText;
            let alert = await this.alertCtrl.create({
              header: msg.title,
              message: msg.titleText,
              buttons: [
                {
                  text: this.cancel_label,
                  role: "cancel"
                },
                {
                  text: this.ok_label,
                  handler: async () => {
                    let modal =await this.modalCtrl.create({
                      component:ShareInstagramPage,
                      componentProps:	msg
                    });
                    modal.present();
                  }
                }
              ]
            });
            alert.present();
          }
        } else {

          if (
            msg["gcm.notification.type"] == "publish_ig" &&
            msg.tap
          ) {
            let data = {
              type: msg["gcm.notification.type"],
              titleText: msg["gcm.notification.titleText"],
              origin: msg["gcm.notification.origin"],
              blogId: msg["gcm.notification.blogId"],
              body: msg["gcm.notification.notificationText"],
              igPic: msg["gcm.notification.igPic"],
              screenName: msg["gcm.notification.screenName"],
              media0: msg["gcm.notification.media0"],
              media1: msg["gcm.notification.media1"],
              media2: msg["gcm.notification.media2"],
              media3: msg["gcm.notification.media3"]
            };
            
            let modal =await this.modalCtrl.create({
              component:ShareInstagramPage,
              componentProps:	msg
            });
            modal.present();
          }
        }
      })
  }

And this method listenToNotifications() is calling in app.component.ts when platform is ready.

Currently when i am sending notification via backend I'm receiving notification alert but only when app is open.

Really Appreciate For anyone's help.
Thanks

**Comment by dpa99c** [comment]
Background notifications are working fine for myself and other users of this plugin, indicating the issue is not caused by a bug in the plugin code.

Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase to validate your Firebase configuration. 

Please also search for existing closed issues which may help you eg #425
