### ISSUE TITLE
onMessageReceived does not work ios after the application has been opened using push notifications.

### ISSUE THREAD

**Issue by osben** [dpa99c/cordova-plugin-firebasex#427]
# Bug report

FirebasePlugin.onMessageReceived does not work ios after the application has been opened using push notifications.

Downloading application and memory.
Send a push.
By clicking on the received push, the application opens and processes FirebasePlugin.onMessageReceived.
Without closing the application, I send another push.
Nothing happens (

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - ipad air 2 ( 13.5.1)

	
	
_iOS build issue:_
- Node JS version
    - `node -v` - v12
- XCode version
last

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
See [Foreground notifications](https://github.com/dpa99c/cordova-plugin-firebasex#foreground-notifications) documentation.

Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase for reference.

**Comment by osben** [comment]
@dpa99c 
You are wrong, because the message is delivered without problems even without "notification_foreground": "true"
