### ISSUE TITLE
[Action Required] Update your apps to use latest Firebase Crashlytics SDKs before November 15, 2020

### ISSUE THREAD

**Issue by urlexnilz** [dpa99c/cordova-plugin-firebasex#428]
Hi @dpa99c ,

today we received the following email from Firebase:

> We are replacing Fabric Crashlytics SDKs and beta versions of the Firebase Crashlytics SDKs with the generally available Firebase Crashlytics SDKs.
> 
> To continue getting crash reports in the Firebase console, make sure to upgrade your apps to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity before November 15, 2020.
> 
> The following project(s) linked with your account include apps that have enabled Crashlytics:
> - projectname

It seems that one of our projects is affected because we are using Firebase-X. We are currently using Firebase-X 7.0.1. Do we need to update?  

Cheers

**Comment by dpa99c** [comment]
Yes, when this plugin has been updated you will need to update to the new version - see #335
