### ISSUE TITLE
iOS get payload data when app is killed/not running

### ISSUE THREAD

**Issue by yaro08** [dpa99c/cordova-plugin-firebasex#429]
Part of documentation: 
"_...**iOS background notifications**
**If the app is in the background but is still running** (i.e. has not been task-killed) and the device is not in power-saving mode, the onMessageReceived callback can be invoked when the message arrives without requiring user interaction (i.e. tapping the system notification). To do this you must specify "content-available": 1 in the apns.payload.aps section of the message payload - see the Apple documentation for more information. When the message arrives, the onMessageReceived callback will be invoked without the tap property, indicating the message was received without user interaction. If the user then taps the system notification, the app will be brought to the foreground and onMessageReceived will be invoked again, this time with tap: "background" indicating that the user tapped the system notification while the app was in the background._..."

# Feature request

I would to know how to get payload data when the app is closed/killed/not-runing.

My problem is that when app is killed and push notification is received, on press it the app is started but nothing else. I think because it's not implemented the right method, but I am not sure. I think for this purpose this method can help: `application:didFinishedLaunchingWithOptions`

but I don't know how to add it to the plugin :( 
maybe someone resolved this same issue and can help.

this is the sources where I researched:
- https://stackoverflow.com/questions/35058870/handling-push-notifications-when-app-is-terminated
- https://stackoverflow.com/questions/51302525/ios-push-notification-when-app-is-killed 
- https://stackoverflow.com/questions/22780275/how-to-handle-on-click-on-push-notifications-ios/49598192#49598192 
- https://stackoverflow.com/questions/20771312/push-notification-didfinishlaunchingwithoptions

**Comment by dpa99c** [comment]
This plugin [implements `application:didFinishedLaunchingWithOptions`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L41) as a [swizzled method](https://nshipster.com/method-swizzling/).

If a push notification message is received on iOS when the app is not running/in the background, then when the user taps on the system notification, the app will be launched/restored and the [`didReceiveNotificationResponse`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L459) method will be invoked if the APNS payload specifies `content-available: `1.

You can test this by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and using its built-in FCM v1 API client to send the [`ios_notification_default_sound_and_badge` message](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_default_sound_and_badge.json) which [contains the appropriate APNS key](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/ios_notification_default_sound_and_badge.json#L12).
