### ISSUE TITLE
Fabric Crashlytics SDK depreciated - migrate before Nov 15, 2020 #36

### ISSUE THREAD

**Issue by Roshankd1** [dpa99c/cordova-plugin-firebasex#431]
Will we received updated version of Cordova-plugin-firebasex before November 2020?

**Comment by dpa99c** [comment]
Duplicates #335.

This is open source software - I will implement it as and when I have time.
However, if you'd like to pay for this to be implemented sooner, please let me know and we can talk about cost.

**Comment by giuale88** [comment]
Hi @dpa99c  thank you so much for you contribute! We will wait to your update!!! thank you

**Comment by Roshankd1** [comment]
@dpa99c  thank you for the swift reply. I am actually a freelancer myself working for a client who is using this plugin. I shall discuss your proposal with the client.

**Comment by Roshankd1** [comment]
@dpa99c thank you Dave, we will wait for an update from your side. Really appreciate your efforts. 
Have a great day!

**Comment by dpa99c** [comment]
Guys, you may need to thank @vickydlion instead of me thanks to his PR #432 which adds the Firebase Crashlytics SDK migration.
I will give it a regression test when I get a chance (hopefully in the next couple of days) and if there are no issues, I'll push out a patch release containing it ASAP 🚀

**Comment by giuale88** [comment]
@dpa99c  and vickydlion we appreciate your works.  I
REGARDS SO SO SO  MUCH
