### ISSUE TITLE
Phone Verification: Firebase native Instance not propagated to firebase sdk

### ISSUE THREAD

**Issue by cdpndt** [dpa99c/cordova-plugin-firebasex#433]
Hello,

I am using phone verification in android and Plugin works well but when signing in using signInWithCredential(), the native firebase instance is not propagating to firebase sdk. I cannot get user instance using sdk

Thanks

**Comment by dpa99c** [comment]
Sorry this does not make sense to me. 
Please complete the issue template in full, giving code examples and if possible illustrate the problem using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)
