### ISSUE TITLE
[FEATURE] Support Firebase Crashlytics custom keys & logs

### ISSUE THREAD

**Issue by zmoshansky** [dpa99c/cordova-plugin-firebasex#434]
Crashlytics supports custom keys & logs to provide dynamic data with crash reports.

Per the API Docs, exceptions should be static, with dynamic data appended via custom keys
![image](https://user-images.githubusercontent.com/3180807/84949010-65a8b580-b0a1-11ea-9b92-2a259dfdb061.png)

API Docs:
https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#log-excepts
https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=android#add-logs

Would you be open to a PR to support this feature once #335 is closed and this plugin migrates to the Crashlytics sdk instead of using the fabric sdk?

**Comment by dpa99c** [comment]
The migration to Firebase Crashlytics is now implemented on the dev branch ([see here](https://github.com/dpa99c/cordova-plugin-firebasex/pull/432#issuecomment-646136059)).
Please feel free to open a new PR against that code on dev.

**Comment by Roshankd1** [comment]
@dpa99c Hi Dave, just a quick one. How are you testing crash on iOS? Ionic native wrapper function sendCrash works perfect for Android but in iOS, it doesn't seem to push crash to the console. Any thoughts? Thank you :)

**Comment by dpa99c** [comment]
@Roshankd1  I do all regression testing using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) which is a known codebase designed as a test harness for validation of this plugin's functionality.

I can confirm that using it, I was able to see both iOS & Android crash data appear in the Crashlytics dashboard of the Firebase console using the new Firebase Crashlytics implementation in `cordova-plugin-firebasex@10`.

**Comment by Roshankd1** [comment]
@dpa99c  Thanks so much, will give it a try..Have a good day!

**Comment by Roshankd1** [comment]
@dpa99c Hi Dave, Sorry I keep coming :D.. My GoogleService-Info.plist is being overridden by preset config values of firebase:

They get added once the iOS build is completed. Is this normal?

  <key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key>
    <string>true</string>
    <key>FIREBASE_PERFORMANCE_COLLECTION_ENABLED</key>
    <string>true</string>
    <key>FirebaseCrashlyticsCollectionEnabled</key>
    <string>true</string>

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#disable-data-collection-on-startup
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/ios/helper.js#L198
