### ISSUE TITLE
getToken() returns null

### ISSUE THREAD

**Issue by Hanzofm** [dpa99c/cordova-plugin-firebasex#437]
**Current behavior:**

Call to getToken() returns null on async response.

**First, steps already checked:**

-Firebase project created.
-google-services.json is downloaded and present into root path and into platforms/android/app
-clean installation removing platform and plugins folder
-the bundle id is configured in config.xml and into firebase project
-I have tried with --livereload parameter and without it  runs

**Installed versions:**

cordova-plugin-firebasex : 9.1.2
cordova-plugin-androidx: 2.0.0
cordova-plugin-androidx-adapter: 1.1.1
@ionic-native/firebase-x: 5.26.0

**Environment versions:**

Cordova-CLI:9.0.0
@ionic/angular 5.1.0
cordova-android: 8.1.0
node: 10.16.1

Samsung with Android 9 version

**Cordova plugin list:**

cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 9.1.2 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2-dev "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"

When try to execute this:

`(<any>window).FirebasePlugin.getToken(token => console.log(`token: ${token}`));`

or

```
this.firebasex.getToken().then(firebaseToken => {
                console.warn('token',firebaseToken);
```

or

```
  this.platform.ready().then(() => {
this.firebasex.getToken().then(firebaseToken => {
                console.warn('token',firebaseToken);
});
```

It returns null in each console print.

**Expected behavior:**
it should return the device token

Thanks a lot for your time.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-firebasex#gettoken):

> Null if the token has not been allocated yet by the Firebase SDK.

The Firebase SDK allocates the token asynchronously as it requires comms with the Firebase servers.
e.g. if the device is not connected to the internet, it will not obtain a token.

This plugin/function is widely in use and can be validated by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Comment by Hanzofm** [comment]
If this helps to someone:

My problem was in google cloud console / api & services/ credentials.

When i was created the firebase project I modified the default api key and restrict to google maps. This causes an 403 error when firebase tries to communicate with servers. Create a new credential without restrictions or restrict to"Firebase Installations API" solves the problem.

**Comment by imranAliOfficial** [comment]
> If this helps to someone:
> 
> My problem was in google cloud console / api & services/ credentials.
> 
> When i was created the firebase project I modified the default api key and restrict to google maps. This causes an 403 error when firebase tries to communicate with servers. Create a new credential without restrictions or restrict to"Firebase Installations API" solves the problem.

Thanks @Hanzofm you are a life saver. I was getting the null token and was unable to figure this out since las 3 day. I have tried every possible solution but your proposed solution worked. Hurraaaahhhhhh!!!
