### ISSUE TITLE
Android crash report not logging in firebase console after latest plugin update - issue 432

### ISSUE THREAD

**Issue by Roshankd1** [dpa99c/cordova-plugin-firebasex#438]
For the latest integration of Firebase plugin update [https://github.com/dpa99c/cordova-plugin-firebasex/pull/432]

@dpa99c As you pointed out in the comment during merge, I gave it a try with Android and unfortunately, not able to see crash reports in Firebase console.

**Comment by dpa99c** [comment]
Thanks for reporting - I will look into why Android is not report Crashlytics data using Firebase Crashlytics when I have time.

Since this is an unreleased feature on the dev branch, let's keep the discussion regarding it under #335 rather than opening new issues.

**Comment by Roshankd1** [comment]
@dpa99c  Thanks Dave, appreciate that.
