### ISSUE TITLE
Cannot fit requested classes in a single dex file

### ISSUE THREAD

**Issue by samall76** [dpa99c/cordova-plugin-firebasex#439]
This plugin used to work fine, but now I receive an error while building the Android app. No problems on iOS. Can someone help me with this?

Cannot fit requested classes in a single dex file (# methods: 120876 > 65536)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  The number of method references in a .dex file cannot exceed 64K.
  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by samall76** [comment]
cordova plugin add cordova-plugin-enable-multidex

**Comment by Roshankd1** [comment]
A simple work around would be to add few lines in build.grade file app level.
Here is a link with further details:
[https://developer.android.com/studio/build/multidex]
