### ISSUE TITLE
Read payloads without tapping the notification while app in background

### ISSUE THREAD

**Issue by ariffaisal7** [dpa99c/cordova-plugin-firebasex#444]
Hello, thank you for all your efforts in this plugin.
I have something to ask about how to read the payload when the application is in the background and the operating system receives notifications in the tray without having to click (tap). is there an alternative way to do this?

I have read the documentation which contains by default there is no callback for that :
[#background-notifications](https://github.com/dpa99c/cordova-plugin-firebasex#background-notifications)

Thanks a lot

**Comment by dpa99c** [comment]
You cannot read the message payload while the app is in the background/not running.
The system notification is part of the core OS - no app code is invoked by the OS until the user taps the system notification.
