### ISSUE TITLE
Notification not showing on some devices, but onMessageReceive is called

### ISSUE THREAD

**Issue by lucassouza16** [dpa99c/cordova-plugin-firebasex#445]
Notification not showing, but onMessageReceive It is called when notification is received

**Comment by dpa99c** [comment]
This is not sufficient information to open an issue.
Please read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#cloud-messaging), test using [the example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and if you're still able to reproduce the issue, provide full details by completing the issue template.
