### ISSUE TITLE
Build error !! - Add FIRApp configure.

### ISSUE THREAD

**Issue by bigleesan** [dpa99c/cordova-plugin-firebasex#446]
Hello.
Spent a lot of time to build my project for IOS.
and I saved GoogleService-Info.plist in folder ( Project -> Resources )
I cannot find any reason why this would happen. Here is the code:

2020-07-09 09:53:20.006416+1200 pushtest[11839:871372] 6.27.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure]; (FirebaseApp.configure() in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

//=======================================================
// ios environment
//=======================================================
cordova-lib@9.0.1 with:
  cordova-common@3.2.1
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v12.16.1
  npm: 6.13.4

iOS platform:
  Xcode 11.5

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-firebasex#firebase-config-setup):

> Download your Firebase configuration files, `GoogleService-Info.plist` for iOS and `google-services.json` for android, and place them in the root folder of your cordova project.

i.e. place in the same directory as your `config.xml` and run `cordova prepare ios` so the plugin picks up `GoogleService-Info.plist` and deploys it to the Xcode project.

**Comment by bigleesan** [comment]
Hi, 
Thanks, But I have a same error. 
Please check below image file. It is your test sample. 

Thanks
 
![img1](https://user-images.githubusercontent.com/51064966/87007133-dc0a8480-c215-11ea-9668-3d226f97e1c0.GIF)
