### ISSUE TITLE
Could not build module 'Firebase'

### ISSUE THREAD

**Issue by 15638228357** [dpa99c/cordova-plugin-firebasex#454]
ios 32/Pods/Headers/Public/Firebase/Firebase.h:15:9: 'FirebaseCore/FirebaseCore.h' file not found
'AppDelegate.h' file not found
Could not build module 'Firebase'

ionic3 remove firebase   then  add firebasex

**Comment by dpa99c** [comment]
This is insufficient information to open an issue but the most likely cause is a problem with your cocoapods installation - please see [the documenation](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods).

Please build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working codebase to validate your dev environment.

If you do need to open an issue, please complete the issue template in full.
