### ISSUE TITLE
Error building xample project in xcode 10.1 

### ISSUE THREAD

**Issue by renznamoc21** [dpa99c/cordova-plugin-firebasex#455]
# Bug report

**CHECKLIST**
- [ ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Showing Build FirebaseTest Failed Expected ',' IODExternalUserAgentIOSCustomBrowser.h
 -->

**Expected behavior:**
Success Build

**Steps to reproduce:**
Build Project using xcode 10.1

**Screenshots**
![image](https://user-images.githubusercontent.com/33001159/87520630-d13c6d80-c6b5-11ea-936f-3e00f602c4f4.png)

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-custom-config 5.1.0 "cordova-custom-config"
      cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
 cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
 cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
 cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.0.0 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version, e.g.
    - OSX
        -  ProductName:	Mac OS X
           ProductVersion:	10.13.6
           BuildVersion:	17G13035
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - Not yet run in device
- OS details
    - 
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - v8.11.1
- XCode version
  Version 10.1 (10B61)

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
> Build Project using xcode 10.1

Xcode 10 contains the iOS 12 SDK which is not a supported by the latest Firebase SDK.
Please update to the latest Xcode release (11.5) and build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to verify your build environment.
