### ISSUE TITLE
10th version of plugin broke getToken method on iOS

### ISSUE THREAD

**Issue by SaintNK** [dpa99c/cordova-plugin-firebasex#456]
Hello! On 10 version of plugin for iOS - `FirebasePlugin.getToken(token => console.log(token),error =>console.error(error))` always returns undefined, because logic of method was broken: 
now getToken in Objective-C source not use callback from javascript FirebasePlugin.getToken call, it use sendToken method https://github.com/dpa99c/cordova-plugin-firebasex/blob/82d1ddbfac9e9de23f3d3439d94dff00281b2c6d/src/ios/FirebasePlugin.m#L151-L156
which always checks tokenRefreshCallbackId (which sets only by onTokenRefresh method)
https://github.com/dpa99c/cordova-plugin-firebasex/blob/82d1ddbfac9e9de23f3d3439d94dff00281b2c6d/src/ios/FirebasePlugin.m#L369-L371
and send token only to this callback 
https://github.com/dpa99c/cordova-plugin-firebasex/blob/82d1ddbfac9e9de23f3d3439d94dff00281b2c6d/src/ios/FirebasePlugin.m#L430-L434
and this is totally wrong and breaks specification.

**So if you didn't call onTokenRefresh and call FirebasePlugin.getToken(token => console.log(token),error =>console.error(error)) plugin not send token at all.**

<img width="1311" alt="Снимок экрана 2020-07-15 в 16 14 40" src="https://user-images.githubusercontent.com/17924803/87529173-cb945700-c6b8-11ea-8ecd-055a42f056d1.png">
<img width="864" alt="Снимок экрана 2020-07-15 в 16 15 49" src="https://user-images.githubusercontent.com/17924803/87529225-dea72700-c6b8-11ea-8ce5-d0df6e1908ba.png">

**Comment by dpa99c** [comment]
This has been fixed in `cordova-plugin-firebasex@10.1.1`
