### ISSUE TITLE
Remote Config `getValue` returning undefined/null on first app startup.

### ISSUE THREAD

**Issue by rbrand21** [dpa99c/cordova-plugin-firebasex#459]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
6.10.1
- Cordova platform version
	- `cordova platform ls` 
android 8.1.0
  browser 6.0.0
  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cc.fovea.cordova.purchase 8.1.1 "Purchase"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 9.0.1 "Google Firebase Plugin"
cordova-plugin-googleplus 8.5.0 "Google SignIn"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-sign-in-with-apple 0.0.1 "cordova-plugin-sign-in-with-apple"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-youtube-video-player 2.4.0 "CordovaYoutubeVideoPlayer"
cordova-sqlite-storage 4.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
cordova-support-android-plugin 1.0.2 "cordova-support-android-plugin"
cordova-support-google-services 1.4.1 "cordova-support-google-services"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
ProductName:    Mac OS X
ProductVersion: 10.15.4

    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
iPhone X
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	iOS 13.5.1
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
Both functions below are in a `remote-config-service.ts`
```
    /**
     * Setup the remote config by fetching param values and activating them.
     * Assign fetchActivation to promise to wait on before calling getConfigValue
     */
    async setupConfig() {
        try {
            if (this.platform.is('cordova')) {
                await this.af.fetch(600);
                this.setupDone = this.af.activateFetched();
            }
        } catch (e) {
            console.error('Config setup falied: \n' + e.stack);
        }
    }

    /**
     * Call the remote config API to receive the corresponding config val.
     * @param configValName - the config val name matching that on the firebase console.
     */
    async getConfigValue(configValName: RemoteConfigValues): Promise<string> {
        await this.setupDone;
        if (this.platform.is('cordova')) {
            let value;
            try {
                let tryCounter = 0;
                while (!value) {
                    value = await this.af.getValue(configValName);
                    tryCounter++;
                    if (tryCounter > 100) {
                        await this.af.logError('Exiting getValue loop due to counter limit exceeded')
                        break;
                    }
                }
            } catch (e) {
                await this.af.logError('Unable to get the config value for: ' + RemoteConfigValues.TUTORIAL_MONETARY + '\n' + e.stack);
            }
            console.log('Config Service: returning: ' + value);
            return value;
        } else {
            return this.configDefaults[configValName];
        }
    }
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**
The problem is that `getValue()` is not returning a value on initial app install.

I call `setupConfig()` from app.component.ts.
I call `getConfigValue()` from the initially loaded page in the app on `ngOnInit()`
I'm having to call `getValue()` in a loop because it's returning undefined and I don't see any flag to wait on to indicate that remote config is "ready". This problem only exists on the initial install. On subsequent app launches, the config value returns on the first call.

**Comment by dpa99c** [comment]
I'm not able to reproduce this issue on either iOS or Android - in both cases the value is always available immediately once remote config has been fetched and activated.

Please download and try [this test case Cordova project](https://github.com/dpa99c/cordova-plugin-firebasex/files/4954738/test.zip) and confirm you get the same results:

![android](https://user-images.githubusercontent.com/2345062/88078402-57542a80-cb74-11ea-8c7a-976b5addeaf6.jpg)
![ios](https://user-images.githubusercontent.com/2345062/88078409-59b68480-cb74-11ea-82f1-19c05b29af4a.png)

**Comment by rbrand21** [comment]
Thanks, will download this and see.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by kprigel** [comment]
I can verify that this is an issue.  I get the same stack trace on both the test app and our app.  

2020-08-06 16:07:53.934 9898-9949/uk.co.workingedge.firebase.test D/FirebaseRemoteConfig: Persisted config file was not found.
    java.io.FileNotFoundException: /data/user/0/uk.co.workingedge.firebase.test/files/persisted_config (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at android.app.ContextImpl.openFileInput(ContextImpl.java:560)
        at android.content.ContextWrapper.openFileInput(ContextWrapper.java:202)
        at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.readPersistedConfig(com.google.firebase:firebase-config@@19.1.4:339)
        at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.getConvertedLegacyConfigs(com.google.firebase:firebase-config@@19.1.4:196)
        at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.saveLegacyConfigsIfNecessary(com.google.firebase:firebase-config@@19.1.4:151)
        at com.google.firebase.remoteconfig.RemoteConfigComponent$$Lambda$4.call(Unknown Source:2)
        at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by a5601564** [comment]
> I can verify that this is an issue. I get the same stack trace on both the test app and our app.
> 
> 2020-08-06 16:07:53.934 9898-9949/uk.co.workingedge.firebase.test D/FirebaseRemoteConfig: Persisted config file was not found.
> java.io.FileNotFoundException: /data/user/0/uk.co.workingedge.firebase.test/files/persisted_config (No such file or directory)
> at java.io.FileInputStream.open0(Native Method)
> at java.io.FileInputStream.open(FileInputStream.java:231)
> at java.io.FileInputStream.(FileInputStream.java:165)
> at android.app.ContextImpl.openFileInput(ContextImpl.java:560)
> at android.content.ContextWrapper.openFileInput(ContextWrapper.java:202)
> at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.readPersistedConfig(com.google.firebase:firebase-config@@19.1.4:339)
> at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.getConvertedLegacyConfigs(com.google.firebase:firebase-config@@19.1.4:196)
> at com.google.firebase.remoteconfig.internal.LegacyConfigsHandler.saveLegacyConfigsIfNecessary(com.google.firebase:firebase-config@@19.1.4:151)
> at com.google.firebase.remoteconfig.RemoteConfigComponent$$Lambda$4.call(Unknown Source:2)
> at com.google.android.gms.tasks.zzz.run(com.google.android.gms:play-services-tasks@@17.0.2:2)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> at java.lang.Thread.run(Thread.java:764)

i am the same ，so what is the solution？
