### ISSUE TITLE
Subscribe not working

### ISSUE THREAD

**Issue by svenboogaart** [dpa99c/cordova-plugin-firebasex#463]
**Current behavior:**

I updated my ap from 8.* to the latest version and my subscribe was not working anymore.

I checked out the latest example project and tried to subscribe. 
In file/line https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L329
I replaced my_topic with a value that looks like a mac adres without ':'.
The output is failed to subscribe to topic: Task failed for unknown reason.

After this I reverted back to my_topic and I still get the same error.

I tried running it in an android virtual device and on a real device (motorola moto c plus) I get the same error on both tests.

**Environment information**
- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `  android 8.1.0`
- Plugins & versions installed in project (including this plugin)
    - cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.0.0 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version
    - Ubuntu 18.04

I created a completely new android project following the [manual](https://firebase.google.com/docs/cloud-messaging/android/client#set-up-firebase-and-the-fcm-sdk) with the same google-service.json file and it works fine there.

**Comment by a2kan** [comment]
Same here in Android, 
Cordova: v 9.0.1
Cordova Android: v 8.1

I also upgraded from 9 to 10.1.1 and following methods are failing
1, signOutUser
2. subscribe
3. unsubscribe
4. updateUserProfile

All failed with this error "Task failed for unknown reason". This error does not help to investigate the problem..

**Comment by a2kan** [comment]
I checked the version of FirebasePlugin.java file
After I changed back the last commit on signOutUser (about handleTaskOutcome) it works,
example

public void signOutUser(final CallbackContext callbackContext, final JSONArray args){
        cordova.getThreadPool().execute(new Runnable() {
            public void run() {
                try {
                    FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
                    if(user == null){
                        callbackContext.error("No user is currently signed");
                        return;
                    }
                    // Sign out of Firebase
                    FirebaseAuth.getInstance().signOut();

                    // Try to sign out of Google
                    try{
                        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN).build();
                        GoogleSignInClient mGoogleSignInClient = GoogleSignIn.getClient(cordovaActivity, gso);
                        **//handleTaskOutcome(mGoogleSignInClient.signOut(), callbackContext);
                        mGoogleSignInClient.signOut()
                                .addOnCompleteListener(cordovaActivity, new OnCompleteListener<Void>() {
                                    @Override
                                    public void onComplete(@NonNull Task<Void> task) {
                                        callbackContext.sendPluginResult(new PluginResult(PluginResult.Status.OK));
                                    }
                                });**
                    }catch(Exception googleSignOutException){
                        callbackContext.success();
                    }

                } catch (Exception e) {
                    handleExceptionWithContext(e, callbackContext);
                }
            }
        });
    }

I hope this will help to solve the issue faster and proper way..

**Comment by svenboogaart** [comment]
I updated to the latest version but im still getting the same error.

**Comment by dpa99c** [comment]
@svenboogaart the fix is on the master branch but has not been released (hence the `ready for release` tag).
If you require it in the meantime, please install the plugin directly off the master branch.

**Comment by svenboogaart** [comment]
@dpa99c How often is there a release? e.g. is it once a month? Im in doubt if i should download the master or wait for the release.
