### ISSUE TITLE
Targeting standard build vs cli build?

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#464]
Is there a way to always target the latest cli build vs the standard build?
IE: `ionic cordova plugin add cordova-plugin-firebasex`  (installs @10.1.2)

But how to install firebasex@10.1.2-cli without having to state the specific build?
IE: `ionic cordova plugin add cordova-plugin-firebasex@10.1.2-cli`  (installs @10.1.2-cli)

Something like:
IE: `ionic cordova plugin add cordova-plugin-firebasex@cli`  (would install @10.1.2-cli)

I have a bunch of scripts that deploy various plugins and I don't like pinning specific plugin versions in those scripts unless its absolutely necessary.

**Comment by MLuan** [comment]
Hi :)

You can use `cordova plugin add cordova-plugin-firebasex@latest-cli`

**Comment by dpa99c** [comment]
As @MLuan said

**Comment by rolinger** [comment]
@MLuan @dpa99c - thanks guys.  I searched for that and found it in the docs, glazed right by it a few times I guess.
