### ISSUE TITLE
[FEATURE] Actionnable button in Push notification

### ISSUE THREAD

**Issue by fpoirier1** [dpa99c/cordova-plugin-firebasex#471]
Hello,

I would like to know if it is possible to have actionnable buttons for push notification with this plugin ? 

Does it support the `click_action` and `apn.payload.aps.category` attributes ? From what I understand, in iOS, we need to declare the categories at app startup.

More details here : https://firebase.google.com/docs/cloud-messaging/concept-options#example-notification-message-with-platform-specific-delivery-options

Thank you in advance

**Comment by dpa99c** [comment]
The plugin doesn't currently support this feature.
Looking at the [Apple documentation](https://developer.apple.com/documentation/usernotifications/declaring_your_actionable_notification_types) it would be possible to extend the plugin to implement it but it would be considerable work to create a generic mechanism to register and respond to arbitrary categories. 
I would think the plugin would need to allow these categories to be defined in the `config.xml` and then inject them into the app's Info.plist so they can be registered at app startup and handled on incoming notifications at runtime.
I'm happy to accept a PR which implements such a feature.

**Comment by fpoirier1** [comment]
I think we could inspire ourselves on what was done on the [katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications) side. Here is their implementation of the feature : 

https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/ios/APPNotificationCategory.m

**Comment by roman-rr** [comment]
Created pull #482

**Comment by dpa99c** [comment]
The code from PR #482 is now on master
