### ISSUE TITLE
The notification cannot display in device when the application is in foreground, after turn on notification settings (iOS only)

### ISSUE THREAD

**Issue by pptrexvn** [dpa99c/cordova-plugin-firebasex#472]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

The notification cannot display in device when the application is in foreground, after turn on (allow) notification settings (iOS only)

**Expected behavior:**
The notification should be displayed in foreground after allow notification 

**Steps to reproduce:**
Step to reproduce:

1 - Send a notification to iOS device with this structure
```
{
    "data":{
      "notification_foreground": "true",
      "notification_title": "Notification title",
      "notification_body": "Notification body",
    },
    "notification": {
      "title": "Notification title",
      "body": "Notification body"
    },
    "apns": {
      "payload": {
        "aps": {
          "badge": 1,
        }
      }
    },
    name: 'test'
};
```

The notification is displayed when the App is in foreground and is in background. (ok)

2 - Put the App to background, go to system settings and **turn off** notification (only for my App) and resume App to foreground again.

After that, I push above notification to device. No notification is displayed in device (still ok).

3 - Put the App to background again, go to system settings and **turn on** notification and resume the App to foreground again.

Now device cannot display any notification (still working when put App to Background). After close App then open again, everything work fine

**Environment information**
- Cordova 9.0
- "cordova-custom-config": "5.1.0",
- "cordova-ios": "5.1.1",
- "cordova-open-native-settings": "1.5.2",
- "cordova-plugin-androidx": "1.0.2",
- "cordova-plugin-androidx-adapter": "1.1.0",
- "cordova-plugin-badge": "0.8.8",
- "cordova-plugin-cocoapod-support": "1.6.2",
- "cordova-plugin-cookie-polyfill": "1.3.1",
- "cordova-plugin-customurlscheme": "4.4.0",
- "cordova-plugin-device": "2.0.2",
- "cordova-plugin-dialogs": "2.0.1",
- "cordova-plugin-file": "6.0.2",
- "cordova-plugin-file-opener2": "3.0.0",
- "cordova-plugin-firebasex": "10.1.0", 
- "cordova-plugin-splashscreen": "5.0.2",
- "cordova-plugin-statusbar": "2.4.3",
- "cordova-plugin-whitelist": "1.3.3",
- "cordova-plugin-wkwebview-engine": "1.2.1",
- "cordova-plugin-keyboard": "1.2.0",
- "cordova-plugin-screen-orientation": "3.0.2",
- "cordova-plugin-wkkeyboardfix": "1.0.1",

**Device details**
    - iPhone 7s
**OS details**
    - iOS 13.5

**Comment by dpa99c** [comment]
I can't repro this issue - see [this screen capture](http://ge.tt/5uKQUA63).

Tested on iPhone 7 running iOS 13.6 and it works as expected: after re-enabling notifications in Settings, foreground notifications are displayed.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by avinashkgit** [comment]
I am also not getting notification when in fore ground.
<img width="471" alt="Screenshot 2020-11-04 at 12 40 57 PM" src="https://user-images.githubusercontent.com/22341729/98069908-f8a08b80-1e9a-11eb-8851-b0e5dfcf140c.png">

**Comment by pkr06** [comment]
I am also experiencing a similar problem when notification is not displayed in the foreground. I could confirm that the event is captured and message details are the same, just that the message is not displayed when the application is in foreground. If the application is killed and restarted, then the messages are shown and everything is back to normal. I debugged the app (developed by some other team in offshore) for possible bug but there is nothing so far. The fact that application restarts solves the problem without any change in configuration or settings is puzzling.

Any help will be appreciated.
