### ISSUE TITLE
(Un-)Subscribe a topic will always return an error

### ISSUE THREAD

**Issue by commanderk33n** [dpa99c/cordova-plugin-firebasex#473]
# Bug report

**CHECKLIST**
- [x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x ] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

if i use 
```
   FirebasePlugin.subscribe("latest_news", function(){
        console.log("Subscribed to topic");
    }, function(error){
        console.error("Error subscribing to topic: " + error);
    });
```
get always error callback, even if the (un-) subscription was successful

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

(Un-)Subscribe a topic will always return an error

Empty cordova project with the plugin

**Expected behavior:**

no error, successful return

**Steps to reproduce:**

use
```
   FirebasePlugin.subscribe("latest_news", function(){
        console.log("Subscribed to topic");
    }, function(error){
        console.error("Error subscribing to topic: " + error);
    });
```

**Workarround for me**

change FirbasePlugin.java #2300

```
private void handleTaskOutcome(@NonNull Task<Void> task, CallbackContext callbackContext) {
        try {
            if (task.isSuccessful()) {
                callbackContext.success();
            }else if(task.getException() != null){
                callbackContext.error(task.getException().getMessage());
            }else{
                callbackContext.error("Task failed for unknown reason");
            }
        } catch (Exception e) {
            handleExceptionWithContext(e, callbackContext);
        }
    }
```

to

```
private void handleTaskOutcome(@NonNull Task<Void> task, CallbackContext callbackContext) {
        try {
            if (task.isSuccessful() **|| task.getException() == null**) {
                callbackContext.success();
            }else if(task.getException() != null){
                callbackContext.error(task.getException().getMessage());
            }else{
                callbackContext.error("Task failed for unknown reason");
            }
        } catch (Exception e) {
            handleExceptionWithContext(e, callbackContext);
        }
    }
```

i have no idea why isSuccessful() is false and task.getException() is null, but it works

**Comment by ratikanta131** [comment]
I am facing the same error.
