### ISSUE TITLE
[Android] Background notifications do not vibrate on custom channels

### ISSUE THREAD

**Issue by cels** [dpa99c/cordova-plugin-firebasex#474]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Notifications sent to a custom channel do not vibrate although app is properly subscribed and vibration pattern is defined (as in the example project)

The system notifications on custom channels do not vibrate. Custom channels are working as a different ringtone is used in contrast to default channel notifications.

Also not working in the example project.

**Expected behavior:**

Notifications should vibrate.

**Steps to reproduce:**

Build example project and send a notification with following content:
```
{
  "registration_ids": [ "abc...." ],
  "notification": {
    "title": "Test title",
    "body": "Test body",
    "icon": "thumbs_up",
    "android_channel_id": "my_channel_id"
  }
}
```
The notification is successfully received on the custom channel (proven by custom ring tone) but it does not vibrate.

**Screenshots**

**Environment information**

- Cordova CLI version 
9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
Installed platforms:
  android 8.1.0
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0
- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.0.0 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova-plugin-whitelist 1.3.4 "Whitelist"
- Dev machine OS and version, e.g.
Arch Linux 5.7.10-arch1-1 x86_64 GNU/Linux
        
_Runtime issue_
- Device details
    - Motorola Moto Z 2 Flash (XT1789-06)
    - Motorola One Vision (XT1970-3)
    - and other Androids in the wild
- OS details
    - Android 9, PPX29.159-24, patch level 1 July 2019
    - Android 10, QSAS30.62-33-2, patch level 1 July 2020
	
_Android build issue:_	
- Node JS version
v14.6.0
- Gradle version
4.10.3  6.5.1  vcs-1
- Target Android SDK version
28 and 29
- Android SDK details
  Path                                               | Version | Description                             | Location                                           
  -------                                            | ------- | -------                                 | -------                                            
  build-tools;28.0.3                                 | 28.0.3  | Android SDK Build-Tools 28.0.3          | build-tools/28.0.3/                                
  build-tools;29.0.3                                 | 29.0.3  | Android SDK Build-Tools 29.0.3          | build-tools/29.0.3/                                
  emulator                                           | 30.0.12 | Android Emulator                        | emulator/                                          
  patcher;v4                                         | 1       | SDK Patch Applier v4                    | patcher/v4/                                        
  platform-tools                                     | 30.0.1  | Android SDK Platform-Tools              | platform-tools/                                    
  platforms;android-26                               | 2       | Android SDK Platform 26                 | platforms/android-26/                              
  platforms;android-28                               | 6       | Android SDK Platform 28                 | platforms/android-28/                              
  platforms;android-29                               | 4       | Android SDK Platform 29                 | platforms/android-29/                              
  sources;android-29                                 | 1       | Sources for Android 29                  | sources/android-29/                                
  system-images;android-29;google_apis_playstore;x86 | 8       | Google Play Intel x86 Atom System Image | system-images/android-29/google_apis_playstore/x86/
  tools                                              | 26.1.1  | Android SDK Tools 26.1.1                | tools/  

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

Thanks for your work and in advance for your support! :-)

**Comment by dpa99c** [comment]
I've tested this using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

When the app is in the background/not running, I sent the [`android_notification_custom_channel` message](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/android_notification_custom_channel.json) which corresponds to the [custom channel](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L144) defined in the example app which specifies a [vibration pattern](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L162).

I tested on a Google Pixel 2 running Android 10. 
When the app was running in the foreground, running in the background, and not running (task killed), the device vibrated when the above message was received.

However only the first vibration in the pattern was executed. i.e. it vibrated once for 300ms, not twice.
The pattern `[300, 200, 300]` means is should vibrate for 300ms, pause for 200ms, vibrate for 300ms.

When the app is in the background or not running, the Android OS displays a system notification.
At this point, no app or plugin code is executed until such time as the user taps the notification which triggers a launch intent for the app.
Therefore I don't think there's anything that can be done to change the behaviour by changing the plugin code.

It may be that different Android OEMs respond differently so it's possible that some devices won't vibrate when a custom channel is used but others do.
If possible try testing the above on a Google Pixel device running Android 10 so we have a common device environment for comparison.

**Comment by cels** [comment]
Thanks for your reply.

We'll try to get our hands on a Pixel device or at least test on other devices, but I already assumed it is system dependent...

**Comment by dpa99c** [comment]
OK I'll close this on the basis that it's working on a Google Pixel but other Android OEMs may not support custom notification sounds and there's nothing this plugin can do from a code perspective to resolve that.

**Comment by rekire** [comment]
Sorry, but "When the app is in the background or not running, the Android OS displays a system notification." is a lie of the documentation, not sure if that was true in the past. Today this is handled by your own app or in detail in `FirebaseMessagingService`, however you cannot customize or react on the push when you are not in the foreground without hacks. So in the end your point is still valid that this is not possible by default.
