### ISSUE TITLE
Remove unused bluetooth permission from plist

### ISSUE THREAD

**Issue by Saddi993** [dpa99c/cordova-plugin-firebasex#475]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
This plugin is asking for bluetooth permission `NSBluetoothPeripheralUsageDescription` to be added in plist. But we are not using this service, so our app doesn't need this permission.

**Steps to reproduce:**
Test flight rejecting IOS build.

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- `Installed platforms:
  ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - branch-cordova-sdk 3.4.0 "branch-cordova-sdk"
    - cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
    - cordova-clipboard 1.3.0 "Clipboard"
    - cordova-custom-config 5.1.0 "cordova-custom-config"
    - cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
    - cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
    - cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
    - cordova-plugin-app-version 0.1.9 "AppVersion"
    - cordova-plugin-badge 0.8.8 "Badge"
    - cordova-plugin-camera 4.1.0 "Camera"
    - cordova-plugin-contacts 3.0.1 "Contacts"
    - cordova-plugin-device 2.0.3 "Device"
    - cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
    - cordova-plugin-file 6.0.2 "File"
    - cordova-plugin-file-transfer 1.7.1 "File Transfer"
    - cordova-plugin-filechooser 1.2.0 "File Chooser"
    - cordova-plugin-filepath 1.5.8 "cordova-plugin-filepath"
    - cordova-plugin-filepicker 1.1.6 "File Picker"
    - cordova-plugin-firebasex 9.0.1-cli "Google Firebase Plugin"
    - cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
    - cordova-plugin-ionic 4.2.0 "IonicCordova"
    - cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
    - cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
    - cordova-plugin-media 5.0.3 "Media"
    - cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
    - cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
    - cordova-plugin-splashscreen 5.0.4 "Splashscreen"
    - cordova-plugin-statusbar 2.4.3 "StatusBar"
    - cordova-plugin-streaming-media 2.3.0 "StreamingMedia"
    - cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
    - cordova-plugin-vibration 3.1.1 "Vibration"
    - cordova-plugin-whitelist 1.3.4 "Whitelist"
    - cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
    - cordova.plugins.diagnostic 4.0.12 "Diagnostic"
    - es6-promise-plugin 4.2.2 "Promise"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        

</details><br/><br/>

**Other information:**
- If we remove it from plist, apple rejects the build.
- If we add them in plist, apple still rejects saying you can't ask for permissions you're not using.

**Comment by dpa99c** [comment]
This plugin doesn't add a bluetooth permission to the plist. 
You can search the source code or build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to satisfy yourself of this.
