### ISSUE TITLE
InApp Messaging not working in Android

### ISSUE THREAD

**Issue by kapilsriram** [dpa99c/cordova-plugin-firebasex#478]
I couldnt get InApp messaging working in my Android App. I have tried doing almost everything including sending the message to all live users. Except this, i have everything else working fine. Is there something I missed? the documentation says there is nothing we need to do, the plugin already includes the modules.

**Comment by dpa99c** [comment]
This looks like a regression bug as I can't get it to work now either although it definitely worked previously so may be due to updating the InApp Messaging SDK component in a recent release.

I'll look into this.

**Comment by dpa99c** [comment]
The inappmessaging component was erroneously removed from `plugin.xml` - I've re-added it in the above commit.
This fix will go out in the next patch release.
