### ISSUE TITLE
On-demand plugin size

### ISSUE THREAD

**Issue by Javinator9889** [dpa99c/cordova-plugin-firebasex#481]
# Feature request

By default, `firebasex` plugin includes the entire Firebase suite, increasing the application size a lot while maybe only some features are being used actually.

I propose developing an on-demand handler that registers the function calls while running, as the only possible entry point is `FirebasePlugin` and the class has only an instance. With this in mind, while generating both iOS and Android projects only are included the dependencies for the in-use Firebase suite items.

As this may be difficult, another possibility would be to allow the user to define which libraries he wants to be included during project generation. This way, by default all options are included (as this is easier) and the user can choose which ones to exclude (or which ones to include), so then the final product will have only the required dependencies and the app size will be hugely reduced, as most of the users use only Analytics or Crashlytics.

I hope this is taken into account and I would be glad to help if necessary.

**Comment by ianitsky** [comment]
Great propose @Javinator9889 .
I think this is a great feature. But how you propose to do this?

I only imagine do something like this splitting the repo to others, each with your lib and necessary code. 

Have you some another idea?

**Comment by dpa99c** [comment]
This is covered by #291
