### ISSUE TITLE
Custom notification sound is not working in iOS 13.6

### ISSUE THREAD

**Issue by SibabratSwain** [dpa99c/cordova-plugin-firebasex#484]
I have followed the documentation and the custom notification was working just fine. But in the updated iOS version(13.6) in iPhone SE(old) I am unable to get the custom notification sound. It. might be a bug fir the updated iOS version. 

Could you please check this!

I have added the plugin in my ionic 3 apps. Let me show you a few things and codes for better understandings. 

I have added this to config.xml under ios platform. 
  
`<resource-file src="resources/ios/sound/notification_sound.caf" />`

![Screen Shot 1942-05-26 at 2 59 40 PM](https://user-images.githubusercontent.com/38970037/90380921-4d054d80-e09a-11ea-9c82-fd14047b0292.png)
in the above screenshot, you can clearly see the file under Resources. 

_it is a .caf file and less than 30 seconds hence follow apple rules for ringtone which I got after converting like in docs_

The push notification works through firebase cloud functions like this. 
![Screen Shot 1942-05-26 at 3 02 01 PM](https://user-images.githubusercontent.com/38970037/90381186-a1a8c880-e09a-11ea-8ffd-f03c9e4335db.png)

This was working fine but now not. Awaiting your response to this.

**Comment by spacesuitdiver** [comment]
Ours is working fine with simply `sound: 'mysound.caf'` as part of the notification payload.

**Comment by SibabratSwain** [comment]
@spacesuitdiver Yes, buddy. It worked. Just removed notification sound from data Object
