### ISSUE TITLE
Automatically enable Sign in with Apple Entitlement (its possible, in fact, easy!)

### ISSUE THREAD

**Issue by slothstronaut** [dpa99c/cordova-plugin-firebasex#485]
This issue is half documentation issue, half feature request. The documentation states: "Note: AFAIK there is currently no way to automate the addition of this capability" with regards to enabling Sign In with Apple entitlement: https://github.com/dpa99c/cordova-plugin-firebasex#ios-3

Maybe at the time of writing it was not possible, but it is now trivial to enable this entitlement automatically. I've created a plugin to do so: https://github.com/findmate/cordova-plugin-enable-applesignin ... It's just a few lines added in plugin.xml

I've been testing with this, and when you remove/add platform, it will correctly set the capability, one less manual thing to worry about!

It would be great to include this capability automatically, or at least mention the plugin in the docs so people don't have to remember to manually enable this capability.

**Comment by dpa99c** [comment]
Maybe this entitlement was always there since Sign In with Apple was released and I just missed it but could've sworn I looked for it when implementing this...
Anyway thanks for pointing it out - will add it to the `config.xml`
