### ISSUE TITLE
Reauthenticate with email and password

### ISSUE THREAD

**Issue by bergergit** [dpa99c/cordova-plugin-firebasex#486]
# Feature request

Hello there!

When executing sensitive changes like updating an email or password, we need to [reauthenticate users](https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user)

Looking at the documentation, for **Apple** or **Google** sign in, we can get a credential using [authenticateUserWithApple / authenticateUserWithGoogle](https://github.com/dpa99c/cordova-plugin-firebasex#signinwithcredential) and then use it to [reauthenticate with credential](https://firebase.google.com/docs/auth/android/manage-users#re-authenticate_a_user)

```
FirebasePlugin.authenticateUserWithApple(function(credential) {
    FirebasePlugin.reauthenticateWithCredential(credential, function() {
         console.log("Successfully reauthenticated");
    }, function(error) {
        console.error("Failed to reauthenticate", error);
    });
}, function(error) {
    console.error("Failed to sign in", error);
});
```

To reauthenticate users with email and password, we would need to create a credential by creating an EmailAuthProvider (Android and iOS) with Email and Password, and then pass it to the signInWithCredential above. But apparently, we can't create an EmailAuthProvider with the current plugin implementation.

_Android example_
```
AuthCredential credential = EmailAuthProvider
        .getCredential("user@example.com", "password1234");

// Prompt the user to re-provide their sign-in credentials
user.reauthenticate(credential)
```

From the documentation, I don't see a way to do this. 
Is this feature really missing?

Thank you for your support!

**Comment by ianitsky** [comment]
Hi @bergergit I heaved this problem too.

The better solution is create a function that changes the user email and return a authentication token to you re-authenticate the user.
