### ISSUE TITLE
It doesn't seem clear if it's possible to remove event listeners such as `onTokenRefresh`.

### ISSUE THREAD

**Issue by spacesuitdiver** [dpa99c/cordova-plugin-firebasex#488]
Thanks for the awesome plugin, I have a quick stupid question that I can't seem to determine if possible (or necessary). I would like to unregister listening to `onMessageReceived` and `onTokenRefresh` if the user is logged out and thought I more cleared way about this would be to unregister these listeners vs. just writing guards within them.

Is it possible to unregister event listeners?

**Comment by dpa99c** [comment]
Just pass an empty function:

	FirebasePlugin.onTokenRefresh(function(){});
