### ISSUE TITLE
Android version 6 has different custom sound payload than documented.

### ISSUE THREAD

**Issue by spacesuitdiver** [dpa99c/cordova-plugin-firebasex#489]
I am a bit confused by the documentation listed here https://github.com/dpa99c/cordova-plugin-firebasex#on-android-7-and-below

I fumbled upon getting my Android 6 device working by accidently sending it my iOS payload as shown below but the documentation doesn't seem to be accurate or I am doing something wrong.

The following is what I end up doing that works (one can also omit the .caf ext, my file format is actually .wav oddly so there's some massaging going on it seems).
```
{
  "to": "xxx",
  "notification": {
    "title": "Test Title",
    "body": "Test Body",
    "sound": "mycustomsound.caf"
  },
  "data": {
    "href": "..."
  }
}
```

I'm happy to make a PR but not sure what should change.

**Comment by dpa99c** [comment]
I have regression tested this on a Samsung Galaxy S4 running Android 6.0.1 and from my testing, the plugin behaves correctly as documented.
I ran the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app and used its FCM client to send the [`android_notification`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/android_notification.json#L16) test message which specifies [`blackberry.mp3`](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/res/android/raw/blackberry.mp3).
The custom sound played correctly when the message was sent to the device's FCM token.

The FCM v1 API documentation accordingly states that the `sound` key must be specified in the [`android.notification`](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification) message section, not the [root `notification`](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#notification) section.
