### ISSUE TITLE
Build failed:  add a super class to fix this problem @interface FirebasePluginMessageReceiverManager

### ISSUE THREAD

**Issue by lucaele** [dpa99c/cordova-plugin-firebasex#493]
Hi all,
i have an error on build ios.
______
class 'FirebasePluginMessageReceiverManager' defined without specifying a base class [-Wobjc-root-class]
@interface FirebasePluginMessageReceiverManager
           ^
.../cordova-plugin-firebasex/FirebasePluginMessageReceiverManager.h:3:48: note: 
      add a super class to fix this problem
@interface FirebasePluginMessageReceiverManager
                                               ^
                                                : NSObject 
1 warning generated.

** BUILD FAILED **
________

cordova version: 9.0.0
platform ios: 5.1.1

**Pod dependecies:**
        pod 'Google-Mobile-Ads-SDK', '~> 7.64.0'
	pod 'Firebase/Core', '6.31.0'
	pod 'Firebase/Messaging', '6.31.0'
	pod 'Firebase/Performance', '6.31.0'
	pod 'Firebase/RemoteConfig', '6.31.0'
	pod 'Firebase/Crashlytics', '6.31.0'
	pod 'GoogleSignIn', '5.0.2'
	pod 'GoogleTagManager', '7.1.2'

Any idea to fix it? or how add a super class on project... 
Thanks

**Comment by makeiteazy** [comment]
Hi, I have the same issue. Built with Xcode 12 beta 6.

**Comment by stefanhk31** [comment]
@makeiteazy 's workaround gets the project running, but this file gets overwritten every time I run my project via capacitor. It looks like the interface still doesn't have the base class in the plugin, as it stands. Is there word of if/when this will be implemented into a new version?

I am encountering the issue on v11.0.3

**Comment by FlawaCLV** [comment]
I still have this error
