### ISSUE TITLE
This is conflicting with Admob-Free plugin

### ISSUE THREAD

**Issue by hypesol** [dpa99c/cordova-plugin-firebasex#495]
cordova-plugin-firebasex having issue with admob-free plugin. I am using admob-free my app but when installed cordova-plugin-firebasex in my app that was not compiling. both plugin are not running at the same time.

**Comment by dpa99c** [comment]
[cordova-plugin-admob-free](https://github.com/ratson/cordova-plugin-admob-free) has [a dependency](https://github.com/ratson/cordova-plugin-admob-free/blob/master/plugin.xml#L29) on [cordova-admob-sdk](https://github.com/ratson/cordova-admob-sdk) which [references](https://github.com/ratson/cordova-admob-sdk/blob/master-github/plugin.xml#L18) the `play-services-base` and `play-services-ads` components of the Play Services library and [defaults to v11.0.4](https://github.com/ratson/cordova-admob-sdk/blob/master-github/plugin.xml#L16) of the Play Services library.

This plugin [depends on](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L77) the `play-services-tagmanager` and `play-services-auth` components of the Play Services library and currently defaults to [v17.0.0](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L64) and [v18.0.0](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L65) respectfully.

Therefore there is a version clash between the Play Services libray version that `cordova-plugin-admob-free` is including vs this plugin.
You'll need to use the `PLAY_SERVICES_VERSION` plugin variable provided by `cordova-admob-sdk` to align the versions requested by that plugin with those requested by this one.

For example:

	cordova plugin rm cordova-admob-sdk --force && cordova plugin add cordova-admob-sdk --variable PLAY_SERVICES_VERSION=17.0.0


Note that the [latest version of `play-services-ads`](https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads?repo=google) is `19.4.0` whereas [the latest of `play-services-base`](https://mvnrepository.com/artifact/com.google.android.gms/play-services-base?repo=google) is `17.4.0` however `cordova-admob-sdk` does not enable you to specify these independently.

Closing as this is not an issue caused directly by this plugin and requires configuration of `cordova-admob-sdk` to resolve it.

**Comment by danielosky** [comment]
I am using the "admob-plus-cordova" plugin and it conflicts with "cordova-plugin-firebasex"

The current versions are:

"admob-plus-cordova": {
 "APP_ID_ANDROID": "ca-app-pub-XXXXXX",
 "APP-ID-IOS": "ca-app-pub-XXXXX"
 }

"cordova-admob-sdk": {
 "PLAY_SERVICES_VERSION": "20.4.0"
 }

"cordova-plugin-firebasex": {
"ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "18.0.4",
 "ANDROID_PLAY_SERVICES_AUTH_VERSION": "20.7.0"
 }


It doesn't want to compile... I would be very grateful for your help!
