### ISSUE TITLE
fetchFirestoreCollection casting filter types to string

### ISSUE THREAD

**Issue by bayssmekanique** [dpa99c/cordova-plugin-firebasex#496]
# Bug report

**CHECKLIST**
- [ x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ x ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ x ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ x ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When creating a filter for a `fetchFirestoreCollection` request (on Android) and filtering using a number type (primitive number, not string encoded number), the query will always return `0` results because the code in `FirebasePlugin.java`  which converts the filter array into an actual query object casts the `value` entry as a `string` primitive automatically.

https://github.com/dpa99c/cordova-plugin-firebasex/blob/753e529574054f2c3b31ea82d810dd13dc69bb9d/src/android/FirebasePlugin.java#L2162-L2179

I have not tested this functionality on iOS yet, nor am I well versed enough in Obj-C to tell if this issue will exist on iOS based solely on the code.

**Expected behavior:**

The query should maintain the primitive number type for the query.

**Steps to reproduce:**

```ts
const collection = 'posts'
const filter = [
  [ 'postAt', '<=', Date.now() ]
]
firebase.fetchFirestoreCollection(collection, filter, (documents: any) => resolve(documents), (error: string) => reject(new Error(error))
```

**Environment information**

- Cordova CLI version: `9.0.0`

**Other information:**
I'm not entirely certain how to resolve this issue cleanly. It doesn't appear that the `JSONArray` has a way to determine the primitive type (though the JSON syntax does denote this by omitting the quotes around primitive numbers).

Reference: https://processing.org/reference/JSONArray.html

The only way I can see around this would involve additions to the filter object to specify type, which could be a breaking change if not handled correctly.

**Comment by dpa99c** [comment]
Value typing isn't something that was handled in the [PR](https://github.com/dpa99c/cordova-plugin-firebasex/pull/367) which added support for Firestore filters but I've added support for this in the above commit (currently on the dev branch).
It enables an optional `valueType` element to be specified in the relevant filter arrays which forces the native type to that which is specified. 
Since the additional parameter is optional, this does not introduce a breaking change to the plugin API.
