### ISSUE TITLE
[ios] Actionable notifications do not fully execute code in onMessageReceived()

### ISSUE THREAD

**Issue by cels** [dpa99c/cordova-plugin-firebasex#497]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Making backend calls in the `onMessageReceived()` results in pending HTTP requests that only get executed once the app is back in foreground.
Sometimes it works for the first time but all subsequent requests stall.

See screenshots below.

Note: We are not 100% sure if this is caused by the firebasex plugin, Cordova, or even iOS itself.

**Expected behavior:**

Simply fully execute the backend calls.

**Steps to reproduce:**

Just add a `$.ajax()` HTTP request (or something similar) at the end of `handleNotificationMessage()` in `www/js/index.js` of the test project.
Bring app to background and send an actionable notification and tap it so the code gets executed.
The logs are printed as expected but the HTTP request don't get executed until the app is opened again. (Safari debugger shows the pending requests)

**Screenshots**

After two notifications in foreground and then tapping two actionable notifications while in background (two calls per notification):
![background](https://user-images.githubusercontent.com/2692037/91830856-9a112400-ec43-11ea-8072-bff9f8b2a405.png)

Back in foreground with timed out request and two successful:
![foreground](https://user-images.githubusercontent.com/2692037/91830942-b8771f80-ec43-11ea-8891-803749b83ceb.png)

**Environment information**

- Cordova CLI version 
10.0.0

- Cordova platform version
Installed platforms:
  ios 6.1.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0

- Plugins & versions installed in project (including this plugin)
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.1.2 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova-plugin-whitelist 1.3.4 "Whitelist"

- Dev machine OS and version, e.g.
    - OSX
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
        
_Runtime issue_
- Device details
iPhone 6
- OS details
ios 12.4.8

_iOS build issue:_
- Node JS version
v12.16.1
- XCode version
11.6

Thanks for your effort!

**Comment by dpa99c** [comment]
I believe this is a limitation of actionable notifications on iOS: 
Since tapping an action button causes app code to be invoked without displaying the app to the user, presumably it's Apple's intention to stop this being abused so they limit what processing can be done while the actionable notification thread is being executed. I guess from your issue, that includes remote HTTP requests being limited.

I don't believe there is any code change that can be made in the plugin to work around this.
I can only suggest a workaround approach such as setting a flag in local storage in the app which is checked when the app is next resumed from the background and then using this to subsequently make the HTTP requests while the app is in the foreground.

I'll flag this as a caveat of usage but closing as there's no further action that can be taken from a plugin perspective.

**Comment by cels** [comment]
Okay, that's what we also feared :-(
A flag would not work for us as this wouldn't be "real time".
Anyway, would have been a nice feature :man_shrugging: 
Thanks!

**Comment by dpa99c** [comment]
> A flag would not work for us as this wouldn't be "real time".

Could you record the timestamp of when the actionable notification is interacted in local storage?
At least that way you'd have the "real time" of the interaction recorded when it was sent to your server on app resume?

The Firebase Analytics SDK works that way - it batches up analytics messages and sends them at intervals but the actual timestamp when the analytics event was logged is recorded as part of the event metadata.

**Comment by cels** [comment]
Would be a nice idea, but we want to change the state of an asset which has to be synced back to the server and all other devices of the user as soon as it happens.
Nevermind! This only would have been a nice additional convenience feature.
