### ISSUE TITLE
IONIC 3 - FIREBASE - onNotificationOpen()

### ISSUE THREAD

**Issue by apsantos-dev** [dpa99c/cordova-plugin-firebasex#50]
IONIC 3 - Push Notifications Firebase

Hello,

A week ago I was able to push, click on the message and get the data correctly. A few days ago, trying to run the project on another machine showed error that the repository could not be found. It was like this:

https://stackoverflow.com/questions/56014935/problem-with-play-services-measurement-base-on-ionic

In the item,

2 - Install: ionic cordova plugin add https://github.com/dpa99c/cordova-plugin-firebase#GH-1057-April-05-android-build-issue

I noticed you are now using the "cordova-plugin-firebasex". So far so good, I installed and the push came correctly.

But now I can not make any dealings when I click on the notification. I used it like this:

app.component.ts

```
this.platform.ready().then(() => {
      statusBar.backgroundColorByHexString("#00516d");
      splashScreen.hide();

      this.fcm
        .listenToNotifications()
        .pipe(
          tap(msg => {
            console.log(msg);
          })
        )
        .subscribe();
});
```

fcm.ts

```
import {Firebase} from "@ionic-native/firebase";

constructor (public firebase: Firebase) {}

listenToNotifications() {
    return this.firebase.onNotificationOpen();
}
```

---

From what I've noticed, the new plugin can not execute the onNotificationOpen()

Can you tell me where I'm going wrong?

Sorry for English errors!
My sincerest regards.

**Comment by dpa99c** [comment]
As you'll see from [the CHANGELOG](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md), this fork has deviated from `cordova-plugin-firebase` such that `cordova-plugin-firebasex` is no longer the same plugin as `cordova-plugin-firebase` - it has a different API and behaviour, e.g. `onNotificationOpen()` renamed to `onMessageReceived()`

The `@ionic-native/firebase` wrapper points at `cordova-plugin-firebase` so if you want to use this fork, you'll need to use it directly via the JS API rather than via the Ionic Native Typescript wrapper for `cordova-plugin-firebase`.

**Comment by Abdulrahmanh95** [comment]
@dpa99c Does downgrading `cordova-plugin-firebasex` to version 4.0.0 resolve `onNotificationOpen`?

**Comment by dpa99c** [comment]
@Abdulrahmanh95 v4.0.0 is out-of-date with respect to the version which contains numerous bug fixes and additional features. I would not recommend using 4.0.0 for this reason.

**Comment by Abdulrahmanh95** [comment]
@dpa99c Thanks a lot.
I've just fix it with version 6 is working properly with my ionic 3 application.

**Comment by benskarunya** [comment]
@Abdulrahmanh95,
I am using ionic 3 and added this plugin as well. And i am struck without import firebase how to use the methods? can i get some sample script. Thanks Benny

**Comment by hiepxanh** [comment]
before: 
`this.firebase.onNotificationOpen();`
after:
`(this.firebase as any).onMessageReceived();`

**Comment by Abdulrahmanh95** [comment]
@benskarunya 
You just have to use without firebase service (using plain JavaScript):
```
(<any>window).FirebasePlugin.onNotificationOpen(function (response) {
    if (response.tap) { console.log('push to some page'); }
 })
```

and you can receive the token the same way:
```
(<any>window).FirebasePlugin.getToken(function (token) { console.log('token', token); })
```

**Comment by hiepxanh** [comment]
I feel you, we can have this transform as onNotificationOpen:
```.ts
onNotificationOpen() {
      return new Observable(observer => {
            (window as any).FirebasePlugin.onMessageReceived((response) => {
                observer.next(response);
            });
       });
}
```

**Comment by sahyun1** [comment]
I'm getting Cannot read property 'setScreenName' of undefined

if I do `ionic cordova run android `
and set a breakpoint, FirebasePlugin is undefined..
`(window as any).FirebasePlugin`

anyone have any idea..?

**Comment by sahyun1** [comment]
my bad make sure you use cordova android >8
