### ISSUE TITLE
'cocoapods version is out-of-date' problem in appflow on iOs, on ionicframework.com

### ISSUE THREAD

**Issue by PegasusAwesome** [dpa99c/cordova-plugin-firebasex#504]
Hiya,

# Bug report
- [V ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)
- [V ] I confirm this is a suspected bug or issue that will affect other users
- [V ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.
- [V ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.
- [V ] I have checked that no similar issues (open or closed) already exist.

Describe how the bug manifests.
- Tried to build the example project in the appflow on ionicframework.com (iOS-Xcode11).
- This results in:
`Failed to install 'cordova-plugin-firebasex': Error: cocoapods version is out-of-date - please update to cocoapods@^1.9.0 - current version: 1.7.5`

Explain how you're sure there is an issue with this plugin rather than your own code: 
- I'm using the example project, not my own code.

Describe what the behavior should be without the bug.
- The build process should not give the failure message.

If you are able to illustrate the bug with an example, please provide steps to reproduce.
- Get example project.
- Build it in the appflow on ionicframework.com.

**Screenshots**

None necessary. The failure message is clear.

Node.js version     | v12.17.0     
Cordova CLI version | 9.0.3 (cordova-lib@9.0.2)
npm version         | 6.14.4     
macOS version       | 10.14.6
Xcode version       | Xcode 11.5

Hope you can help. I tried changing the version to 6.0.2, since I read in other similar bug reports that that might help. But it didn't. Also tried version 9.1.1, 10.2.0 and 10.2.0-cli. None of these resolved the problem though.

Also tried building other apps in the same environment: the issue does not appear. This issue only appears the moment I try to do anything with the firebasex plugin.

Best,
Marcel

**Comment by dpa99c** [comment]
Your problem is clear from the error message: `cocoapods version is out-of-date - please update to cocoapods@^1.9.0 - current version: 1.7.5`

You need to update the installed version of cocoapods on your Mac. The plugin requires v1.9.0+.

**Comment by PegasusAwesome** [comment]
Hi dpa99c,

Thanks for your reply.
We're building on appflow, not mac. 
I'll contact the appflow people and ask them if they are responsible for the 1.7.5 version or if firebasex is pulling it from somewhere.

**Comment by PegasusAwesome** [comment]
One last question: if appflow is hard wired to use cocaopods 1.7.5, is there a version of firebasex that works with 1.7.5 ?

**Comment by dpa99c** [comment]
> I'll contact the appflow people and ask them if they are responsible for the 1.7.5 version or if firebasex is pulling it from somewhere.

Cocoapods is a system-wide global installation - it is a peer dependency for using this plugin which cannot require it as a downstream dependency. On a Mac you would download and install the latest version. In a cloud build environment like AppFlow, I have no idea.

> One last question: if appflow is hard wired to use cocaopods 1.7.5, is there a version of firebasex that works with 1.7.5 ?

Maybe - you can dig back through the old versions but I wouldn't recommend it as the latest versions contain many bug fixes for issues present in previous versions.

**Comment by PegasusAwesome** [comment]
>Maybe - you can dig back through the old versions 
>but I wouldn't recommend it as the latest versions contain many bug fixes for issues present in previous versions.
Was afraid of that, ;-)
Keep up the good work, thanks a thousand times for answering me, and thanks a million for making this project!
