### ISSUE TITLE
Get Data on onMessageReceived from Notification

### ISSUE THREAD

**Issue by simonreger** [dpa99c/cordova-plugin-firebasex#506]
when a user clicks on the notification I want to transfer information to the app. So that the app knows what kind of message it is and then forward it to certain pages. E.g. "You have a new friend request" -> forwarding to "Friends". Etc.

This is my message array in PHP:
`    $fields = array (
            //'to' => $id,
            'registration_ids' => array (
                    $id
            ),      
            'notification' => array (
                    "title" => "New Friend request",
                    "body" => "you got a new Friend"
            ),                    
            'data' => array (
                    "typ" => "1"
            )
    );  `

And this is the function in Cordova App:
`      window.FirebasePlugin.onMessageReceived(function(message) {
          data = message.getData();
          typ = data.get("typ");
          alert (typ);
      }, function(error) {
          console.error(error);
      }); `

But this doesn't Work. How can i fetch the data?

**Comment by dpa99c** [comment]
Please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and its [associated test messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages) for a working example of how to send FCM notification messages with custom data payloads.

**Comment by simonreger** [comment]
I tried:
alert (message.notification.title);

like example project index.js line 287.
But doesn't work.
