### ISSUE TITLE
Document breaking API changes from cordova-plugin-firebase

### ISSUE THREAD

**Issue by dpa99c** [dpa99c/cordova-plugin-firebasex#51]
# Documentation issue

Add a sub-section under "Migrating from cordova-plugin-firebase" in the README which explicitly states the breaking API changes. 

It should also make it clear that `ionic-native/@firebase` will not work with this plugin due to the breaking API changes and so how Ionic users can directly use the JS API of the plugin in Typescript (with examples).

**Comment by GuiF007** [comment]
Any replacement of `ionic-native/@firebase` planned ?

**Comment by dpa99c** [comment]
@GuiF007 https://github.com/ionic-team/ionic-native/pull/3106

**Comment by GuiF007** [comment]
Seems only Ionic v4 ? :(

**Comment by GuiF007** [comment]
At least, with ionic v3, the old plugin still works, but I use almost nothing (just automatic events)
