### ISSUE TITLE
Automatically enabled Sign in with Apple Entitlement causes xCode Error

### ISSUE THREAD

**Issue by EinfachHans** [dpa99c/cordova-plugin-firebasex#511]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Since your Change with #485 Sign in with Apple Entitlement is automatically added to the Project. For us not using SwA we get the Error: **Provisioning profile "..." doesn't support the Sign in with Apple capability.**

**Expected behavior:**

Maybe it is possible (with a script?) to only add this Entitlement if a specific Preference is set? (Or the other way, but like it's now, i think its kinda "breaking change" for everybody not using it.

**Comment by dpa99c** [comment]
Darn. OK, I think the best approach is to use a plugin variable to optionally set the Sign In with Apple capability in the Xcode entitlements. I'll see if I have time to push out a patch release later today with this functionality.

**Comment by Davedave2004** [comment]
I was also experiencing this, for now I just set it back to use the previous version. Good thing to know that somebody already opened an issue for this. 👍

**Comment by EinfachHans** [comment]
@Davedave2004 If you want to use the other Features from Version **11.0.0**, it's currently just one click to remove the Entitlement from xcode again 😊

**Comment by EinfachHans** [comment]
@dpa99c I can create a PR to help you. What do you think about a logic similar to the one you use in the Diagnostics Plugin for enabling Modules? But here for kinda "Sections"? So we will only have this one for now, but maybe some others in the future? If we do so, do you prefer one Preference for all sections (like Diagnostic), or one preference for each section?

**Comment by dpa99c** [comment]
@EinfachHans this plugin is already [writing to various plists based on plugin variable values](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/ios/helper.js#L192) so I was just going to remove [the `<config-file>` blocks](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L113) from `plugin.xml` and write the values directly into the entitlement plists in JS using `applyPluginVarsToPlists()`

**Comment by dpa99c** [comment]
OK I've published a fix for this in `cordova-plugin-firebasex@11.0.1`.

This adds the plugin variable `IOS_ENABLE_APPLE_SIGNIN` (which defaults to `false`) but if it's set to `true` at plugin install time it will enable the Sign In with Apple capability in Xcode:

    cordova plugin add cordova-plugin-firebasex --variable IOS_ENABLE_APPLE_SIGNIN=true

**Comment by EinfachHans** [comment]
@dpa99c Thank you for your fast work 🎉
