### ISSUE TITLE
Where are isAnalyticsCollectionEnabled(), isCrashlyticsCollectionEnabled(), isPerformanceCollectionEnabled() methods ?

### ISSUE THREAD

**Issue by ludochane** [dpa99c/cordova-plugin-firebasex#516]
Hi,
on the readme of the project those methods are presented :

- isAnalyticsCollectionEnabled()
- isCrashlyticsCollectionEnabled()
- isPerformanceCollectionEnabled()

But I can't find them on FirebasePlugin. Is it a bug or is there an other way to call them ?

Regards,

**Comment by dpa99c** [comment]
Please check you are using the most recent version of the plugin.

These are defined in the JS plugin API (for example [isAnalyticsCollectionEnabled()](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/www/firebase.js#L115)) and are each demonstrated in the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) (for example [isAnalyticsCollectionEnabled()](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js#L460)).

**Comment by Crylion** [comment]
Well it is defined in the Javascript but not in the Typescript Typings 😅
Which might be the reason the @ionic/native Wrapper also does not provide these Methods.
