### ISSUE TITLE
scripts/lib/utilities.js - package.json unable to parse - doesn't exists

### ISSUE THREAD

**Issue by Wade-BuildOtto** [dpa99c/cordova-plugin-firebasex#517]
in the scripts/lib/utilities.js doesn't allow for the file to not exists, it just needs some extra handling.

thx

https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/lib/utilities.js#L29

**Comment by dpa99c** [comment]
`packsge.json` is a required component of a Cordova project and should never not exist

**Comment by manusis** [comment]
The cordova build fails when only this plugin is enabled. There should be a fallback to package-lock.json as that file exists.
