### ISSUE TITLE
APNS legacy binary protocol

### ISSUE THREAD

**Issue by JohEngstrom** [dpa99c/cordova-plugin-firebasex#519]
Hi!

I'm just in the process of implementing this great plugin in our app. I only have one question.

Will this plugin still work for iOS after November 2020 when they turn off APNS legacy binary protocol and switch to HTTP/2?
https://developer.apple.com/news/?id=11042019a

Thanks!

**Comment by dpa99c** [comment]
This plugin does not directly integrate with APNS but relies on Firebase's integration [which has been migrated](https://groups.google.com/g/firebase-talk/c/O14qffe-GyI?pli=1).
