### ISSUE TITLE
[ANDROID] Firebase Performance - Network section no data captured

### ISSUE THREAD

**Issue by klliew-hks** [dpa99c/cordova-plugin-firebasex#520]
Current behavior:
No data captured in Firebase Performance network section for Android.

Expected behavior:
Network section for Android Firebase Performance should able to capture network data.

Environment information:
Cordova CLI version
- 9.0.0 (cordova-lib@9.0.1)

Installed platforms:
  android 9.0.0
  ios 5.1.1
Available platforms: 
  browser ^6.0.0
  electron ^1.0.0
  osx ^5.0.0
  windows ^7.0.0

Plugins & versions installed in project
cordova-clipboard 1.3.0 "Clipboard"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 2.5.1 "Advanced HTTP plugin"
cordova-plugin-android-imei 1.0.0 "Android IMEI"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-call-number 1.0.1 "Cordova Call Number Plugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-exit 1.0.3 "Exit"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-fingerprint-aio 3.0.1 "FingerprintAllInOne"
cordova-plugin-firebasex 10.2.0 "Google Firebase Plugin"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-iroot 0.8.1 "iRoot"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-networkinterface 2.0.0 "NetworkInterface"
cordova-plugin-privacyscreen-storyboard 0.3.1 "PrivacyScreenPlugin-Storyboard"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-secure-storage-echo 5.1.1 "SecureStorage"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-tapjackingprotection 0.1.1 "TapjackingProtectionPlugin"
cordova-plugin-timer 1.0.1 "Native timer"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"
cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
cordova-save-image-gallery 0.0.26 "saveImageGallery"
cordova.plugins.diagnostic 5.0.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"

Dev machine: macOS 10.14.6
Device details: Happened to all Android devices (Android 8, Android 9, Android 10)
Android Studio 4.0.0

<img width="1148" alt="Screenshot 2020-09-23 at 2 45 34 PM" src="https://user-images.githubusercontent.com/65693574/93977849-b4a36c80-fdad-11ea-99f0-2c00e1c1511d.png">

thank you for help

**Comment by dpa99c** [comment]
It looks like this is [a bug](https://github.com/arnesson/cordova-plugin-firebase/issues/697) in the integration of the Firebase Performance SDK inherited from [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase).

According the to [Firebase documentation](https://firebase.google.com/docs/perf-mon/get-started-android?authuser=0#add-perfmon-plugin), the Firebase Performance Monitoring Gradle plugin must be added for Android in order to monitor network requests.
However this plugin's [current Gradle configuration](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/build.gradle) does not include the Performance Monitoring Gradle plugin

**Comment by trajano** [comment]
Not sure if it is because of this change, but Android builds with JDK8 are failing because of incompatible class levels.

**Comment by dpa99c** [comment]
@trajano see [my comment here](https://github.com/dpa99c/cordova-plugin-firebasex/issues/535#issuecomment-706533158)
