### ISSUE TITLE
build prod release for IOS in macox never finishes

### ISSUE THREAD

**Issue by alemdg** [dpa99c/cordova-plugin-firebasex#521]
**Current behavior:**

ionic cordova build ios --prod --release NEVER finish compiling.....

- Cordova CLI version 
	- `cordova -v`
9.0.0 (cordova-lib@9.0.1)

- Cordova platform version
	- `cordova platform ls`
Installed platforms:
  ios 5.1.1

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-clipboard 1.3.0 "Clipboard"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-firebasex 11.0.1-cli "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser 3.1.1-dev "InAppBrowser"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 3.0.0-dev "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.1 "Cordova WKWebView Engine"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`

ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266

_iOS build issue:_
- Node JS version
    - `node -v`
v6.11.2

- XCode version
11.5

**Comment by dpa99c** [comment]
Please try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment. 
Also I notice you are using an outdated iOS platform version - `cordova-ios@5.1.1` - you should try updating to the latest `@6.1.1`.

**Comment by dpa99c** [comment]
Closed due to no response
