### ISSUE TITLE
Request to add the following parameters 

### ISSUE THREAD

**Issue by tatiyaki12** [dpa99c/cordova-plugin-firebasex#522]
# Feature request
This parameters doesn`t track from the firebaseX analytics

purchase Recommended Event (Retail/Ecommerce)
add_payment_info Recommended Event (Retail/Ecommerce)
add_to_cart Recommended Event (Retail/Ecommerce)
add_to_wishlist Recommended Event (Retail/Ecommerce)
begin_checkout Recommended Event (Retail/Ecommerce)
generate_lead Recommended Event (Retail/Ecommerce)
refund Recommended Event (Retail/Ecommerce)
view_item Recommended Event (Retail/Ecommerce)
view_item_list Recommended Event (Retail/Ecommerce)
view_search_results Recommended Event (Retail/Ecommerce)
add_shipping_info Recommended Event (Retail/Ecommerce)
remove_from_cart Recommended Event (Retail/Ecommerce)
select_item Recommended Event (Retail/Ecommerce)
select_promotion Recommended Event (Retail/Ecommerce)
view_promotion Recommended Event (Retail/Ecommerce)
view_cart Recommended Event (Retail/Ecommerce)
sign_up Recommended Event (General)
login Recommended Event (General)
share Recommended Event (General)
tutorial_begin Recommended Event (General)
tutorial_complete Recommended Event (General)
join_group Recommended Event (General)
search Recommended Event (General)
select_content Recommended Event (General)
spend_virtual_currency Recommended Event (General)

**Comment by dpa99c** [comment]
It is your responsibility to track these events using [`logEvent()`](https://github.com/dpa99c/cordova-plugin-firebasex#logevent).
If you want to track these events, you need to log them in the appropriate place in your application.
