### ISSUE TITLE
Request to add signInWithFacebook(accessToken) 

### ISSUE THREAD

**Issue by coddicat** [dpa99c/cordova-plugin-firebasex#523]
From previous requests, I realized that there are no plans to add the Sign in with Facebook function since the SDK is very heavy, but is it possible to add the signInWithFacebook (accessToken) function, where the accessToken has already been received from the outside (another plugin, for example, cordova-plugin-facebook4)?

**Comment by dpa99c** [comment]
The [`signInUserWithCustomToken()`](https://github.com/dpa99c/cordova-plugin-firebasex#signinuserwithcustomtoken) plugin API method enables you to provide a custom token to sign in to Firebase Auth. 
Beyond this I have no plans to provide a specific token authentication mechanism for Facebook.
If/when I have the time/need to add Facebook integration to this plugin, it will probably be as a separate micro-plugin which extends this plugin to pull in the Facebook SDK and provide tight native integration between Firebase Auth and Facebook.
