### ISSUE TITLE
iOS pipeline build failed with Xcode task

### ISSUE THREAD

**Issue by rahulkmurali** [dpa99c/cordova-plugin-firebasex#525]
error: FirebaseCrashlytics does not support provisioning profiles. FirebaseCrashlytics does not support provisioning profiles, but provisioning profile ABC has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'FirebaseCrashlytics' from project 'Pods')

I have set it to automatic but again error shows teamID missing even I added the team ID in the Xcode task.

Tried the below option also in Xcode task. But not worked.

args: 'CODE_SIGNING_ALLOWED=No'

Packages:

macOS-latest
cordova-plugin-firebasex: "10.2.0-cli"
@ionic-native/core: "^5.0.7"

npm - 6.14.6
@ionic/cli - 6.11.8
cordova@10.0.0
cordova-ios@^6.1.0

Pod updated to latest version using "sudo gem install cocoapods" in the server.

**Comment by dpa99c** [comment]
Are you using a remote build environment (such as Azure or Ionic AppFlow) or are you building locally?

**Comment by rahulkmurali** [comment]
@dpa99c Azure pipeline

**Comment by dpa99c** [comment]
Please [see this SO post](https://stackoverflow.com/questions/62677014/ionic-cordova-ios-xxx-does-not-support-provisioning-profiles-azure-pipelines). Your issue is not caused by this plugin directly but by Azure Pipelines not working with Cocoapods dependencies.
