### ISSUE TITLE
Request to implement getAndSaveFacebookCredentialByToken method  

### ISSUE THREAD

**Issue by coddicat** [dpa99c/cordova-plugin-firebasex#526]
Can you please implement a new method to get & save a credential from Facebook's token and return its id to able to use signInWithCredential where the credential is from Facebook?

something like:
import com.google.firebase.auth.FacebookAuthProvider;
....
public void getAndSaveFacebookCredentialByToken(final CallbackContext callbackContext, final JSONArray args){
        cordova.getThreadPool().execute(new Runnable() {
            public void run() {
                try {
		    String token = args.getString(0);
                    AuthCredential credential = FacebookAuthProvider.getCredential(token);
                    String id = FirebasePlugin.instance.saveAuthCredential(credential);
                    callbackContext.success(id);
                } catch (Exception e) {
                    handleExceptionWithContext(e, callbackContext);
                }
            }
        });
    }

**Comment by dpa99c** [comment]
Reopening as  stalebot incorrectly closed it
