### ISSUE TITLE
Branch `GH-1057-April-05-android-build-issue` deleted

### ISSUE THREAD

**Issue by jeescu** [dpa99c/cordova-plugin-firebasex#53]
Good day!

Please help! Branch `GH-1057-April-05-android-build-issue` is deleted already. The path with this branch is the only firebase version that works on our project. Can you help us w/c alternative version that will still work for us? 

### Tools versions:
- ionic 3.19.0
- cordova 8.1.2 (cordova-lib@8.1.1)
- node 8.9.x

Thanks in advance!

**Comment by dpa99c** [comment]
Please use the latest release of this plugin fork which is currently `cordova-plugin-firebasex@6.0.1`

**Comment by iouhammi** [comment]
@dpa99c, is this version compatible with cordova 8, because the plugin requires cordova >= 9.
If not, how can I use this plugin with cordova 8, since I have other plugins that are not yet compatible with cordova 9?

**Comment by jeescu** [comment]
@iouhammi exactly. This alternative works for me https://github.com/wizpanda/cordova-plugin-firebase-lib/releases/tag/v4.1.0
