### ISSUE TITLE
Raise iOS library versions to 6.33.0

### ISSUE THREAD

**Issue by sebastian-zarzycki-es** [dpa99c/cordova-plugin-firebasex#530]
Firebase recently released 6.33.0, where they've fixed the minimum deployment target issues (8.0, where 9.0+ is allowed now).

https://firebase.google.com/support/release-notes/ios
https://github.com/firebase/firebase-ios-sdk/issues/6449

For now, I can override manually in plugin.xml, but hopefully this can be updated with new release of `cordova-plugin-firebasex`.

**Comment by sebastian-zarzycki-es** [comment]
Thank you!

**Comment by burtsevyg** [comment]
Firebase released 6.34.0, 6.33.0 does not fix minimum deployment target issue.
