### ISSUE TITLE
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources failed in iOS azure pipeline

### ISSUE THREAD

**Issue by rahulkmurali** [dpa99c/cordova-plugin-firebasex#533]
The following build commands failed:
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/runner/Library/Developer/Xcode/DerivedData/mobileapp-bvebnuhsxlrtuwhhfpsypdxwodlz/Build/Intermediates.noindex/mobileapp.build/Release-iphonesimulator/mobileapp.build/Script-EC176571895897421C9020E4.sh

"cordova-plugin-firebasex": "^10.2.0-cli",
"cordova-ios": "6.1.1",
POD version 1.9.3

**Comment by dpa99c** [comment]
Support cannot be offered when using this plugin in remote build environments such as Azure Pipeline, Ionic Appflow, etc. because the development environment is not under your direct control.
See also #525.
