### ISSUE TITLE
Inconsistent delivery of messages to iOS (14)

### ISSUE THREAD

**Issue by pliablepixels** [dpa99c/cordova-plugin-firebasex#539]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [?] I confirm this is a suspected bug or issue that will affect other users

- [NA] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Description:**

I recently migrated from `phonegap-plugin-push` to `corodova-plugin-firebasex`. What I've observed is that messages often don't arrive on my iPhone (iOS 14) even though the FCM send status is successful. There are times when it shows on the lock screen and times when it doesn't. 

Prior to migration to your plugin, I was using the legacy protocol of FCM and `phonegap-plugin-push`

The payload my FCM cloud function is sending is this: (I send to both android and iOS. The issue is only with iOS)

```
{"android": {"notification": {"channel_id": "zmninja", "icon": "ic_stat_notification", "image": "some_url", "notification_priority": "PRIORITY_HIGH"}}, "apns": {"headers": {"apns-priority": "10", "apns-push-type":"alert"}, "payload": {"aps": {"badge": 2, "content-available": 1, "mutable-content": 1, "sound": "default"}}}, "data": {"eid": "153477", "image_url_jpg": "something", "mid": "2", "notification_foreground": "true"}, "notification": {"body": "[a] detected:person:99% front at 09:19 AM, 11-Oct", "title": "DoorBell Alarm (153477)"}, "token": "<tokenid>"}

```
I don't see any conflicts with the formats in the sample test repository you have (I do provide additional fields). 

On the device side, this is the log I see:

```
[xpcservice<com.pliablepixels.zmninja-pro.zmNinjaNotification([daemon<com.apple.SpringBoard>:63])>:33227] Error 45 setting darwin role to UserInteractiveNonFocal: Operation not supported, falling back to setting priority
[xpcservice<com.pliablepixels.zmninja-pro.zmNinjaNotification([daemon<com.apple.SpringBoard>:63])>:33227] Set darwin priority to: PRIO_DEFAULT
```

I'm not sure if its an issue with the V1 protocol or something in my payload that is causing this plugin to not display all messages. On my phone, I have notification settings for my app set to display in lock screen.

Thanks for any advice.

**Comment by dpa99c** [comment]
> There are times when it shows on the lock screen and times when it doesn't.

No plugin code is invoked if a message arrives in the background or is not running unless the user taps the notification to launch the app. 
All processing is done by iOS via APNS therefore there's nothing the plugin can do to affect this behaviour.
Any inconsistency lies with the Firebase integration with APNS.

**Comment by pliablepixels** [comment]
Thanks and you were right.

For posterity, the problem was `content-available:1`, which shouldn't be supplied unless the intent is to wake up the app for available content. Why that resulted in sporadic notification banners, I don't know. But removing it seems to have fixed the issue.
