### ISSUE TITLE
plugin is not working on ios cordova 9.0.0

### ISSUE THREAD

**Issue by NourShHasan** [dpa99c/cordova-plugin-firebasex#54]
Plugin is not working on ios 5.0.1 but working fine on android
ios build is successful but i can't receive notifications from firebase, but on android it's working fine

**Comment by dpa99c** [comment]
This is not sufficient information to open an issue.

The plugin has been tested with `cordova-ios@5.0.1` using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test). Please use this to validate your own implementation.
