### ISSUE TITLE
Bug in build.

### ISSUE THREAD

**Issue by eeerrrttty** [dpa99c/cordova-plugin-firebasex#540]
BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
[cordova-plugin-background-fetch] libDir: /home/romario/divas-app/src-cordova/platforms/android/app/libs

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script '/home/romario/divas-app/src-cordova/platforms/android/CordovaLib/cordova.gradle' line: 64

* What went wrong:
A problem occurred evaluating project ':app'.
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 555ms
Command failed with exit code 1: /home/romario/divas-app/src-cordova/platforms/android/gradlew cdvBuildRelease -b /home/romario/divas-app/src-cordova/platforms/android/build.gradle

 App · Command "cordova" failed with exit code: 1
 App · ⚠️  [FAIL] Cordova CLI has failed

my config.xml:

`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.divas.app" version="1.1.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Divas</name>
    <description>divas-app</description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <allow-navigation href="https://viacep.com.br/ws/*" />
    <allow-navigation href="https://api.nfse.io/validate/NaturalPeople/taxNumber/*" />
    <allow-intent href="https://viacep.com.br/ws/*" />
    <allow-intent href="https://api.nfse.io/validate/NaturalPeople/taxNumber/*" />
    <platform name="android">
        <preference name="AndroidXEnabled" value="true" />
        <icon density="mdpi" src="res/android/mdpi.png" />
        <icon density="hdpi" src="res/android/hdpi.png" />
        <icon density="xhdpi" src="res/android/xhdpi.png" />
        <icon density="xxhdpi" src="res/android/xxhdpi.png" />
        <icon density="xxxhdpi" src="res/android/xxxhdpi.png" />
        <access origin="*" />
        <allow-intent href="*" />
        <allow-navigation href="*" />
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <preference name="KeepRunning" value="true" />
    <preference name="android-targetSdkVersion" value="29" />
    <allow-navigation href="about:*" />
</widget>
`

my package.json:

`{
  "name": "com.divas.app",
  "displayName": "divas-app",
  "version": "1.1.0",
  "description": "A sample Apache Cordova application that responds to the deviceready event.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ecosystem:cordova"
  ],
  "author": "Apache Cordova Team",
  "license": "Apache-2.0",
  "dependencies": {
    "cordova-android": "^9.0.0",
    "cordova-bring-to-front": "git+https://github.com/markeeftb/cordova-bring-to-front.git",
    "cordova-plugin-androidx": "^3.0.0",
    "cordova-plugin-androidx-adapter": "^1.1.1",
    "cordova-plugin-background-fetch": "^6.1.1",
    "cordova-plugin-background-mode": "^0.7.3",
    "cordova-plugin-bring-to-front": "0.0.3",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-firebasex": "^11.0.3",
    "cordova-plugin-vibration": "^3.1.1"
  },
  "devDependencies": {
    "cordova-plugin-whitelist": "^1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-camera": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-vibration": {},
      "cordova-plugin-bring-to-front": {},
      "cordova-plugin-background-mode": {},
      "cordova-plugin-background-fetch": {},
      "cordova-plugin-firebasex": {
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "true",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "true",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "true",
        "ANDROID_ICON_ACCENT": "#FF00FFFF",
        "ANDROID_FIREBASE_PERFORMANCE_MONITORING": "false",
        "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
        "ANDROID_PLAY_SERVICES_AUTH_VERSION": "18.1.0",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.5.0",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "20.3.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "19.2.0",
        "ANDROID_FIREBASE_PERF_VERSION": "19.0.9",
        "ANDROID_FIREBASE_AUTH_VERSION": "19.4.0",
        "ANDROID_FIREBASE_INAPPMESSAGING_VERSION": "19.1.1",
        "ANDROID_FIREBASE_FIRESTORE_VERSION": "21.7.0",
        "ANDROID_FIREBASE_CRASHLYTICS_VERSION": "17.2.2",
        "ANDROID_FIREBASE_CRASHLYTICS_NDK_VERSION": "17.2.2",
        "ANDROID_GSON_VERSION": "2.8.6",
        "ANDROID_FIREBASE_PERF_GRADLE_PLUGIN_VERSION": "1.3.1"
      },
      "cordova-plugin-androidx": {},
      "cordova-plugin-androidx-adapter": {}
    },
    "platforms": [
      "android"
    ]
  }
}`

what is happening ?

**Comment by dpa99c** [comment]
> No installed build tools found. Install the Android build tools version 19.1.0 or higher.

This is a problem with your build environment not this plugin.
Please try building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working reference to resolve any issues with the build environment on your development machine.

**Comment by eeerrrttty** [comment]
sorry for issue, really it was a bug with my environment.
