### ISSUE TITLE
[Improvement] Add this line to code for fix actionable notifications

### ISSUE THREAD

**Issue by roman-rr** [dpa99c/cordova-plugin-firebasex#542]
Hey @dpa99c 
I don't wanna create new pull request (it will override some my custom local changes). 
But please, just add this line into `AppDelegate+FirebasePlugin.m` line number **76**

```Objective-C
// Delegate notification center here (prevent missing notifications)
[UNUserNotificationCenter currentNotificationCenter].delegate = self;
```

It is required by [apple docs](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate?language=objc) 
> Important
> You must assign your delegate object to the UNUserNotificationCenter object before your app finishes launching. For example, in an iOS app, you must assign it in the application:willFinishLaunchingWithOptions: or application:didFinishLaunchingWithOptions: method of your app delegate. Assigning a delegate after these methods are called might cause you to miss incoming notifications.

In my case it solve problem when app was terminated by user, and then first actionable notification doesn't trigger function in background. Only first, because it is call `application:didFinishLaunchingWithOptions:`, and notifications there was not ready.

**Comment by spennyf** [comment]
Hey, thanks for the great work on this plugin, any chance this will be merged in soon?
