### ISSUE TITLE
Xcode Compilation Issue: Fabric Error

### ISSUE THREAD

**Issue by Akz47** [dpa99c/cordova-plugin-firebasex#543]
We have just upgraded to Firebasex 11.0.3, and followed the documentation to update Cocoapod dependencies as well.

We have cleaned the project folder before rebuilding it. When compiling in Xcode, the following error is produced:

```
PhaseScriptExecution Crashlytics /Users/Admin/Library/Developer/Xcode/DerivedData/SampleApp-cxgejywwolwuycfrzpbfxpjsfiwt/Build/Intermediates.noindex/SampleApp.build/Debug-iphoneos/SampleApp.build/Script-20FFD7893513469F97C6862D.sh (in target 'SampleApp' from project 'SampleApp')
    cd /Users/Admin/Development/Projects/SampleApp/platforms/ios
    /bin/sh -c /Users/Admin/Library/Developer/Xcode/DerivedData/SampleApp-cxgejywwolwuycfrzpbfxpjsfiwt/Build/Intermediates.noindex/SampleApp.build/Debug-iphoneos/SampleApp.build/Script-20FFD7893513469F97C6862D.sh

/Users/Admin/Library/Developer/Xcode/DerivedData/SampleApp-cxgejywwolwuycfrzpbfxpjsfiwt/Build/Intermediates.noindex/SampleApp.build/Debug-iphoneos/SampleApp.build/Script-20FFD7893513469F97C6862D.sh: line 2: /Users/Admin/Development/Projects/SampleApp/platforms/ios/Pods/Fabric/run: No such file or directory

Command PhaseScriptExecution failed with a nonzero exit code
```

The app previously compiled fine before the upgrade.

Software versions:
- Cordova 9.0.0
- Cordova iOS: 5.0.1
- Xcode 11

Do we need to install the Fabric module, or remove its references from somewhere? At Project Settings > Build Phases, the Crashlytics executes the shell command ""${PODS_ROOT}/Fabric/run"".

However, the iOS platform Podfile does not include Fabric in its dependencies:
```
source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'
use_frameworks!
target 'SampleApp' do
        project 'SampleApp.xcodeproj'
        pod 'FBSDKCoreKit', '5.15.0'
        pod 'FBSDKLoginKit', '5.15.0'
        pod 'FBSDKShareKit', '5.15.0'
        pod 'Firebase/Core', '6.33.0'
        pod 'Firebase/Auth', '6.33.0'
        pod 'Firebase/Messaging', '6.33.0'
        pod 'Firebase/Performance', '6.33.0'
        pod 'Firebase/RemoteConfig', '6.33.0'
        pod 'Firebase/InAppMessaging', '6.33.0'
        pod 'FirebaseFirestore', :tag => '6.33.0', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git'
        pod 'Firebase/Crashlytics', '6.33.0'
        pod 'GoogleSignIn', '5.0.2'
        pod 'GoogleTagManager', '7.1.4'
end
```

Please advise, thank you.

**Comment by dpa99c** [comment]
This plugin historically used the Fabric SDK for Crashlytics functionality, however due to Google's deprecation of Fabric, this was removed in [v10.0.0](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/CHANGELOG.md#version-1000) and replaced with the Firebase Crashlytics SDK.
It looks as though your platform project still contains references to the Fabric SDK so re-add the iOS platform project to remove them:

    cordova platform rm ios && cordova platform add ios@latest

If you still have issues, built the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment.

**Comment by Akz47** [comment]
Thank you for your tips.

There were various compilation issues after recreating the iOS platform, so we resorted to just editing the original Xcode Project Settings > Build Phases and removing the "Crashlytics" section, and it works fine now.
