### ISSUE TITLE
message_id for data payload

### ISSUE THREAD

**Issue by tuta67** [dpa99c/cordova-plugin-firebasex#544]
message_id (or google.message_id when app in the background) matches actual message_id returned by https://fcm.googleapis.com/fcm/send when notification is sent. However, it is only 1 or 2 digits long when data payload is sent. Can anything be done?

**Comment by dpa99c** [comment]
The `message_id` is generated by the Firebase SDK, not by this plugin which simply returns the value passed to it by the SDK.
So therefore this plugin has no influence of the actual value passed.
