### ISSUE TITLE
Ionic emulate problem

### ISSUE THREAD

**Issue by boblepepeur** [dpa99c/cordova-plugin-firebasex#545]
Hey hey, on ionic, when i try to emulate with -> ionic cordova emulate ios -l --external --consolelogs

When recompiling & launching, always a new browser page is opened with that url -> https://xxx.firebaseapp.com/__/auth/iframe?apiKey=xxxx

**Comment by dpa99c** [comment]
This plugin wraps the native iOS and Android SDKs. 
Browser emulation is not supported.

**Comment by boblepepeur** [comment]
Agree, but i speak about device emulation on my mac

**Comment by dpa99c** [comment]
Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a working reference to diagnose issues with your project.
i.e. Build and run the example project app and compare to your own.

**Comment by boblepepeur** [comment]
that was the problem
