### ISSUE TITLE
VerifyPhoneNumber

### ISSUE THREAD

**Issue by soledigit** [dpa99c/cordova-plugin-firebasex#546]
Dears,

Am using @ionic-native/Firebase-x v10.2 and Cordova plugin v5.28

Building it for Android 9.

below is the function i am using:

    this.firebase.verifyPhoneNumber(phone, 60).then((credential) => {
      console.log("otp_send_success", credential);
      this.verfificationId = credential.verificationId;
      this.translate.get('sending_otp_success').subscribe(value => {
        this.showToast(value);
      });
      this.otpNotSent = false;
      this.dismissLoading();
      this.createInterval();
    }).catch((error) => {
      console.log("otp_send_fail", error);
      this.otpNotSent = true;
      this.resendCode = true;
      this.dismissLoading();
      this.translate.get('sending_otp_fail').subscribe(value => {
        this.showToast(value);
      }); 
    });

am getting below error when runing on emulator

vendor.js:1823 **ERROR TypeError: Object(...) is not a function
    at FirebaseX.verifyPhoneNumber (vendor.js:98221)**
    at OtpPage.webpackJsonp.156.OtpPage.sendOtpPhone (main.js:191)
    at OtpPage.webpackJsonp.156.OtpPage.sendOTP (main.js:150)
    at OtpPage.webpackJsonp.156.OtpPage.ionViewDidEnter (main.js:100)
    at ViewController._lifecycle (vendor.js:23121)
    at ViewController._didEnter (vendor.js:23030)
    at NavControllerBase._didEnter (vendor.js:58564)
    at NavControllerBase._transitionFinish (vendor.js:58374)
    at vendor.js:58360
    at t.invoke (polyfills.js:3)

What am i doing wrong?

**Comment by dpa99c** [comment]
This relates to the [Ionic Typescript wrapper for this plugin](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/firebase-x/index.ts) which is owned/maintained by Ionic.

You can use the JS plugin API defined by this plugin directly via the `FirebasePlugin` global namespace.

To resolve your Typescript issue, please raise an issue or PR against [Ionic Native](https://github.com/ionic-team/ionic-native/).

Closing as this plugin is not responsible for maintaining the Ionic Typescript wrapper.
