### ISSUE TITLE
Not working on Cordova 10 and Cordova-iOS 6.1.1

### ISSUE THREAD

**Issue by Allwithyou999** [dpa99c/cordova-plugin-firebasex#547]
This works for Android but doesn't work for iOS.

"cordova": 10.0.0
"cordova-ios": "^6.1.1",
"cordova-plugin-firebasex": 11.0.3,
"cordova-plugin-firebasex": {
                "ANDROID_ICON_ACCENT": "#FF11FF11",
                "IOS_STRIP_DEBUG": "true",
                "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "false",
                "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "false",
                "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "false",
                "SETUP_RECAPTCHA_VERIFICATION": "false",
                "ANDROID_FIREBASE_CONFIG_FILEPATH": "res/fb/android/google-services.json",
                "IOS_FIREBASE_CONFIG_FILEPATH": "res/fb/ios/GoogleService-Info.plist"
}

For iOS, I can't even see the registration alert of push notification.
Is there something I missed?

**Comment by dpa99c** [comment]
It works fine with `cordova-ios@6.1.1` - please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app as a known working reference.  If you have problems with that, then refer to the documentation for help with fixing your development environment.

**Comment by linhtranvu** [comment]
I can confirm I have the same issue. Dont know why
