### ISSUE TITLE
Incompatible with Cordova 10

### ISSUE THREAD

**Issue by jernejbeg** [dpa99c/cordova-plugin-firebasex#549]
Tried to use the plugin in one of my recent project where I needed to use Cordova 10., but this plugin cannot be installed (not supported). 

Can we expect an update regarding that? 

Thanks in advance.

**Comment by dpa99c** [comment]
This plugin is [fully compatible](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L10) with `cordova@10` CLI as well as the latest platform versions: `cordova-android@9.0.0` and `cordova-ios@6.1.1`. 
Please build and run the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) to confirm this for yourself.
