### ISSUE TITLE
Option to provide identity token instead of credential in authenticateUserWithApple

### ISSUE THREAD

**Issue by sfeast** [dpa99c/cordova-plugin-firebasex#551]
Some of us (I think more than myself) are using this plugin in addition to the Firebase JS SDK, just to provide functionality not available in that SDK (such as A/B testing).

So I need to authenticate users on the JS side, but the current [authenticateUserWithApple](https://github.com/dpa99c/cordova-plugin-firebasex#authenticateuserwithapple) implementation doesn't allow for that as it returns a credential to use with the signInWithCredential API of this plugin.

Ideally we could get the identityToken returned by Apple, similar to [this plugin](https://github.com/twogate/cordova-plugin-sign-in-with-apple), which can then be used to create a credential on the JS side, e.g. something like:

```
const credential = new firebase.auth.OAuthProvider('apple.com').credential({
    idToken: identityToken
});
```

for authenticating the user.

& at least I don't think there's a way to authenticate the user on the web/JS side with the current implementation but please do correct me if I'm wrong.

**Comment by sfeast** [comment]
Just leaving a comment in an attempt to keep this open

**Comment by Birowsky** [comment]
Based on an Apple sign in success, is there currently a way to obtain idToken and refreshToken from Firebase at all?

**Comment by TheNotorius0** [comment]
I agree, it would be nice. When you use **authenticateUserWithGoogle** the credential returned has an **idToken** so we can then use **signInWithCredential**, but I can't get it to work with [authenticateUserWithApple](https://github.com/dpa99c/cordova-plugin-firebasex#authenticateuserwithapple)

**Comment by dpa99c** [comment]
Superseded by #857 857
