### ISSUE TITLE
Cannot read property 'name' of undefined while preparing firebase for ios in ionic4 app

### ISSUE THREAD

**Issue by bhargavas12** [dpa99c/cordova-plugin-firebasex#552]
Getting the below error while building the app:

ios settings bundle was successfully generated
cordova-plugin-firebasex: Preparing Firebase on iOS
Cannot read property 'name' of undefined
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.

##[error]Bash exited with code '1'.
Finishing: Build iOS

Xcode versin used: 11.7
Node version: 10.14.x
firebaseX version: 7.0.1

Thanks,
Bhargav.

**Comment by dpa99c** [comment]
Build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment.

If the example project doesn't build successfully, search previously closed existing issues for a solution and if you don't find one, create a new issue and complete the issue template in full including providing verbose log output containing any error messages.

If it does build successfully, then do as instructed above in your own project: run `cordova build ios --verbose` to output full details of the error and use it to diagnose the issue in your project. 
Given the error is `Cannot read property 'name' of undefined`, I would start by checking the `config.xml` is valid and contains a valid `<name>` element.
