### ISSUE TITLE
App crashes if logError called on iOS with no error message

### ISSUE THREAD

**Issue by N0ps32** [dpa99c/cordova-plugin-firebasex#555]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

If the logError function is accidentally called with no error message the App crashes. This should result in a javascript error instead.

**Expected behavior:**

The App should not crash

**Steps to reproduce:**

Call the logError function with no error message.

**Environment information**

- Cordova CLI version 
	- 10.0.0
- Cordova platform version
	- ios 6.1.1
- Plugins & versions installed in project (including this plugin)
    - cannot disclose
- Dev machine OS and version, e.g.
    - OSX
        
_Runtime issue_
- Device details
    - every iOS device

**Console output**
<details>
<summary>console output</summary>

```
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x???????? __exceptionPreprocess
1  libobjc.A.dylib                0x???????? objc_exception_throw
2  CoreFoundation                 0x???????? -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x???????? ___forwarding___
4  CoreFoundation                 0x???????? _CF_forwarding_prep_0
5  app                       0x???????? __FIRCLSUserLoggingRecordError_block_invoke + 305 (FIRCLSUserLogging.m:305)
6  app                       0x???????? __FIRCLSUserLoggingWriteAndCheckABFiles_block_invoke + 463 (FIRCLSUserLogging.m:463)
7  libdispatch.dylib              0x???????? _dispatch_client_callout
8  libdispatch.dylib              0x???????? _dispatch_lane_barrier_sync_invoke_and_complete
9  app                       0x???????? FIRCLSUserLoggingWriteAndCheckABFiles + 476 (FIRCLSUserLogging.m:476)
10 app                       0x???????? FIRCLSUserLoggingRecordError + 345 (FIRCLSUserLogging.m:345)
11 app                      0x???????? __27-[FirebasePlugin logError:]_block_invoke + 1170 (FirebasePlugin.m:1170)
```

</details><br/><br/>

**Other information:**

This should be an easy fix in the logError method.

The line that causes the crash is:
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L1170

**Comment by cerealexx** [comment]
Same here...
