### ISSUE TITLE
No matching client found for package name when building for multiple chains

### ISSUE THREAD

**Issue by NirGrocerKey** [dpa99c/cordova-plugin-firebasex#558]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

we are using Fastlane to build our android and iOS apps, the config.xml hold reference to the right google-services.json file,
when building every app alone it works flawlessly.
when we try to build multiple apps it crashes with:
Execution failed for task ':app:processDebugGoogleServices'.
No matching client found for package name XXXXX-XXXX

between every build we remove the platform, change the config.xml and re adding the platform.

when i check the build folder i see that the config.xml is changed correctly but the google-services.json file that being copied t the android/app folder is the old one, can we clear the plugin cache some how?

**Expected behavior:**

we need the correct google-servces.json to be copied to the android/app folder and not the cached one

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
10.0.0
- Cordova platform version
	- `cordova platform ls`
9
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
ubuntu
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
The plugin [checks if `google-services.json` already exists](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/after_prepare.js#L72) in `platforms/android/app/` so if you want to copy a new version just remove the existing `platforms/android/google-services.json` as part of your cleardown or remove and re-add `platforms/android/` entirely (which is probably safer if you are changing the app package name between builds).

**Comment by NirGrocerKey** [comment]
hey
as part of the building process we removed the platform, changed the config.xml to the new settings and build it again. still got the cached json.
the only thing that worked is to remove the plugin after each build and re adding it in a new build
