### ISSUE TITLE
ios app fails to receive notification after first one is received

### ISSUE THREAD

**Issue by NourShHasan** [dpa99c/cordova-plugin-firebasex#56]
Dear friend,
nice job for this plugin, 

I'm developing my new app using cordova 9.0.0, the plugin is working fine on android, but I have issue on ios, what happed ? I've added the firebase config files to my project and  build the project on xcode with no issues or errors  then i sent notification from FCM, I received the notification on android only, I tried to trace the issue but i found nothing wrong, then i removed the plugin and installed it again and tried over and over then i found the application receives the notification one time only and if i tried to send it again it doesn't !!!

I'm using: 
cordova 9.0.1
iOS 5.0.1
android 8.0.0

Please any help you can give me

**Comment by dpa99c** [comment]
Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a working reference. Follow the instructions in the example repo to setup and send messages to the example app project.

Use this to validate your own implementation.

**Comment by NourShHasan** [comment]
Dear my friend,

I've downloaded the example project and added .plist file to the project then changed the project id and build the ios platform then I sent a push notification from FCM but i did.t receive the notification

**Comment by dpa99c** [comment]
Check your iOS APNS configuration (provisioning profile used for app build, app capabilities in Xcode, APNS cert/auth key in Firebase project). 
It works fine for me with the original app package name.

**Comment by NourShHasan** [comment]
what is APNS cert/auth key in Firebase project ?
 
Please give me some details about it

**Comment by dpa99c** [comment]
https://firebase.google.com/docs/cloud-messaging/ios/certs

**Comment by NourShHasan** [comment]
Thank you friend the was very good, the plugin is working fine now on ios and android.
