### ISSUE TITLE
[iOS] Update to support Firebase SDK v7

### ISSUE THREAD

**Issue by khlau10** [dpa99c/cordova-plugin-firebasex#561]
I have tried to use this plugin together with  [admob-plus](https://github.com/admob-plus/admob-plus) and encountered the following error when `pod install --verbose`

```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":
  In snapshot (Podfile.lock):
    GoogleUtilities/Environment (= 7.1.1)

  In Podfile:
    Firebase/Auth (= 6.33.0) was resolved to 6.33.0, which depends on
      FirebaseAuth (~> 6.9.2) was resolved to 6.9.2, which depends on
        GoogleUtilities/Environment (~> 6.7)

    Google-Mobile-Ads-SDK (~> 7.68) was resolved to 7.68.0, which depends on
      GoogleAppMeasurement (~> 7.0) was resolved to 7.1.0, which depends on
        GoogleUtilities/AppDelegateSwizzler (~> 7.0) was resolved to 7.1.1, which depends on
          GoogleUtilities/Environment (= 7.1.1)
```

I believe this is similar to this [issue](https://github.com/dpa99c/cordova-plugin-firebasex/issues/9) but this time around it is to up it to version 7.
Any plan for upgrading this and what's your suggestion for the workaround for now ?

**Comment by faytekin** [comment]
+1

**Comment by FatManiac** [comment]
@dpa99c Hi, the firebase plugin will be updated someday or be updatable for ios ?

**Comment by kosbar** [comment]
+1

**Comment by dpa99c** [comment]
Resolved in the major version release `cordova-plugin-firebasex@12.0.0` which updates to Firebase iOS SDK v7
