### ISSUE TITLE
No working in IOS (APNs token is null) until FirebasePlugin.grantPermission called

### ISSUE THREAD

**Issue by linhtranvu** [dpa99c/cordova-plugin-firebasex#565]
# Bug report

**Current behavior:** No working in IOS (null APNs Token) until `FirebasePlugin.grantPermission` called

**Expected behavior:** App permission should be asked as default behavior, or describe on document as a MUST function to be called firstly

**Steps to reproduce:** Install plugin, call `FirebasePlugin.getAPNSToken` return null, that mean we cannot send push message to app

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v` 9
- Cordova platform version 
	- `cordova platform ls` IOS 6.1.1 
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`

      "cordova-custom-config": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-enable-multidex": {},
      "cordova-plugin-androidx-adapter": {},
      "cordova-plugin-hello-c": {}

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers` Catalina
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details: IP 7 Plus
- OS details: IOS 13.5.1
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
I think it's fairly self-explanatory that you can't send push notifications or interact with the push notifications API until the user has granted push notification permission.
The plugin does not do this automatically as it's up to the app developer when they want to request this permission from their users.
