### ISSUE TITLE
Native build errors: must extend [Instantiatable]

### ISSUE THREAD

**Issue by dcxn** [dpa99c/cordova-plugin-firebasex#567]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] **I tried but could not reproduce** the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
When building on CI docker image, the output of `npx ionic cordova build android --prod --release` lists several new errors, some of them seem to be related with this plugin. See errors below:

```
> Task :CordovaLib:prepareLintJarForPublish
> Task :app:lintVitalRelease
platforms/android/app/src/main/AndroidManifest.xml:6: Error: MainActivity must extend android.app.Activity [Instantiatable]
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">

platforms/android/app/src/main/AndroidManifest.xml:37: Error: AppMeasurementService must extend android.app.Service [Instantiatable]
        <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />

platforms/android/app/src/main/AndroidManifest.xml:38: Error: FirebasePluginMessagingService must extend android.app.Service [Instantiatable]
        <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">

platforms/android/app/src/main/AndroidManifest.xml:43: Error: OnNotificationOpenReceiver must extend android.content.BroadcastReceiver [Instantiatable]
        <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver" />

Explanation for issues of type "Instantiatable":
   Activities, services, broadcast receivers etc. registered in the manifest
   file (or for custom views, in a layout file) must be "instantiatable" by
   the system, which means that the class must be public, it must have an
   empty public constructor, and if it's an inner class, it must be a static
   inner class.
7 errors, 0 warnings
```

At least 1 other cordova plugin has a similar error thrown.

**Expected behavior:**
No such errors while building the app for android. 

**Steps to reproduce:**
At the moment, I can only reproduce on docker CI image that installs the tool versions mentioned in the environment info and android build issue sections.

**Environment information**

- Cordova CLI version: `v10.0.0` (latest)
- Cordova platform version: `cordova-android@9.0.0` (latest)
- Plugins & versions installed in project: `"cordova-plugin-firebasex": "^11.0.3-cli",`
- CI machine is Debian stretch with Java 8

_Android build issue:_	
- Node JS version: `14.15.1`
- Gradle version: folders for `6.5` & `6.7.1`, cordova build forces run with 6.5
- Target Android SDK version: `29`
- Android SDK details: `sdkmanager --list | sed -e '/Available Packages/q'` - command does not produce output in the docker image but i am installing the following:
```
echo y | sdkmanager "build-tools;29.0.3"
echo y | sdkmanager "platform-tools" "platforms;android-29"
```

**Comment by dcxn** [comment]
Closing since I might have found the fix to the issues, seems like a docker image configuration problem. Will reopen in case this is not the case and I have new information.

**Comment by jnsc** [comment]
Hi @dcxn can you please give a bit more infos how you solved your issue. I'm in a quite similar situation like you (same error, also seems docker related as building works locally). If found this issue trough a google search, I would be really thankfully (and maybe also other people in the future) for any kind of hint. Thanks a lot.

**Comment by dcxn** [comment]
hey @jnsc, I had an old setup and configuration of the android sdk in my docker image. The main thing i did was carefully reconfiguring and running it specifically as [mentioned in the updated android dev docs](https://developer.android.com/studio/command-line#tools-sdk), so unzipping it to `android_sdk/build-tools/version/` and then exporting the bin path `android_sdk/build-tools/version/bin` in the docker image environment (and all other paths you main need). Hope it helps.

**Comment by jnsc** [comment]
Hi @dcxn, thanks, it helped a lot, I fixed my issue.
