### ISSUE TITLE
[FEATURE] stacktrace.js with logError

### ISSUE THREAD

**Issue by charpour** [dpa99c/cordova-plugin-firebasex#57]
Hi,

Would it be possible to add something like this: https://github.com/wizpanda/cordova-plugin-firebase-lib/blob/master/src/android/FirebasePlugin.java#L552

It makes javascript error reporting so much easier, and it looks good on firebase crashlytics as well.

Thanks

**Comment by charpour** [comment]
and here's the discussion around it: https://github.com/wizpanda/cordova-plugin-firebase-lib/pull/8

**Comment by dpa99c** [comment]
@sagrawal31 is this something you could look at bringing across from your repo?

**Comment by sagrawal31** [comment]
Sure, I'll do this.

**Comment by charpour** [comment]
Many thanks @sagrawal31 , appreciate it

**Comment by dpa99c** [comment]
This has been released in v6.0.3
