### ISSUE TITLE
Implement authorization request for critical alerts on ios

### ISSUE THREAD

**Issue by cels** [dpa99c/cordova-plugin-firebasex#572]
# Feature request

Hi,
we would like to use critical alerts in iOS but the plugin does not provide any way to request the permission to do that.
Another problem might be to include the entitlements in the build process but I'm sure that's not a problem of this plugin.

I played around with the existing code and got it working by adding `UNAuthorizationOptionCriticalAlert` in https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L294

Unfortunately I'm not a Objective-C/iOS developer, so I lack the knowledge to implement the feature properly (with checks for iOS >12.0, make it optional in the `grantPermission()` method, etc.) and directly provide a PR :disappointed: 

With this implemented it would be possible to send critical alerts to the app which would notify the user even in silent mode.

Here is a short overview on how to use it: https://medium.com/@shashidharyamsani/implementing-ios-critical-alerts-7d82b4bb5026

Tanks a lot in advance! :-)

**Comment by maximilianloy** [comment]
We would like to get this feature implemented soon and would finance the development!

**Comment by cels** [comment]
Anything new on this topic?

**Comment by ArnoutCreemers** [comment]
I have opened PR [#693](https://github.com/dpa99c/cordova-plugin-firebasex/pull/693) which adds support to request critical alert permissions on iOS.

**Comment by cels** [comment]
Looks like this is done.
Thank you very much @ArnoutCreemers and @dpa99c! :partying_face:
