### ISSUE TITLE
cordova-firebasex-cli version plugin

### ISSUE THREAD

**Issue by ManivannanVC** [dpa99c/cordova-plugin-firebasex#575]
Hi,

I used below plugins for ios platform. I am not getting notification for the subscribed topics,
I placed google service info.plist in root directory.

cordova-admobsdk 7.49.0 "Google Mobile Ads SDK for Cordova"
cordova-plugin-admobpro 2.49.0 "AdMob Plugin Pro"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-firebasex 10.0.0-cli "Google Firebase Plugin"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-market 1.2.0 "Market"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-sqlite-2 1.0.6 "SQLitePlugin"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 6.0.2 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"

Notfication is not received. Is there any thing required to install? What was the mistake?

**Comment by trung-pham** [comment]
I have same problem, it works fine with v11.0.3 but not with v11.0.3-cli
