### ISSUE TITLE
Error after updating Cordova 10

### ISSUE THREAD

**Issue by mehmetkaynak** [dpa99c/cordova-plugin-firebasex#578]
Hi @dpa99c , after i update cordova cli 10 i getting this error : 
`failed with exit code 1 Error output:

platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:860: error: cannot find symbol
                    handleBooleanTaskOutcome(FirebaseRemoteConfig.getInstance().activate(), callbackContext);
                                                                               ^
  symbol:   method activate()
  location: class FirebaseRemoteConfig
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:872: error: cannot find symbol
                    handleBooleanTaskOutcome(FirebaseRemoteConfig.getInstance().fetchAndActivate(), callbackContext);
                                                                               ^
  symbol:   method fetchAndActivate()
  location: class FirebaseRemoteConfig
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:884: error: cannot find symbol
                    handleTaskOutcome(FirebaseRemoteConfig.getInstance().reset(), callbackContext);
                                                                        ^
  symbol:   method reset()
  location: class FirebaseRemoteConfig
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:931: error: cannot find symbol
                    Map<String, FirebaseRemoteConfigValue> nativeValues = FirebaseRemoteConfig.getInstance().getAll();
                                                                                                            ^
  symbol:   method getAll()
  location: class FirebaseRemoteConfig
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:954: error: cannot find symbol
                        settings.setFetchTimeoutInSeconds(args.getLong(0));
                                ^
  symbol:   method setFetchTimeoutInSeconds(long)
  location: variable settings of type Builder
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:958: error: cannot find symbol
                        settings.setMinimumFetchIntervalInSeconds(args.getLong(1));
                                ^
  symbol:   method setMinimumFetchIntervalInSeconds(long)
  location: variable settings of type Builder
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:961: error: cannot find symbol
                    handleTaskOutcome(FirebaseRemoteConfig.getInstance().setConfigSettingsAsync(settings.build()), callbackContext);
                                                                        ^
  symbol:   method setConfigSettingsAsync(FirebaseRemoteConfigSettings)
  location: class FirebaseRemoteConfig
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java:973: error: cannot find symbol
                    handleTaskOutcome(FirebaseRemoteConfig.getInstance().setDefaultsAsync(defaultsToMap(defaults)), callbackContext);
                                                                        ^
  symbol:   method setDefaultsAsync(Map<String,Object>)
  location: class FirebaseRemoteConfig
Note:platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
`

**Comment by ianitsky** [comment]
I'm using cordova 10 and It's ok
