### ISSUE TITLE
Do you plan to migrate Google Play Developer API to 3 version?

### ISSUE THREAD

**Issue by yoldar** [dpa99c/cordova-plugin-firebasex#58]
I have just deployed app to Play Store and got warning that Google Play Developer v1 and v2 will be deprecated at 1st December 2019. 

https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by dpa99c** [comment]
This plugin does not interact with the Google Play Developer API (which is used to automated in-app billing and app distribution).
