### ISSUE TITLE
CI caching strategy for pods

### ISSUE THREAD

**Issue by jpike88** [dpa99c/cordova-plugin-firebasex#585]
Anyone tried to build in CI, and want to eliminate the long download of all the pods?

It's a Cordova project though, so the iOS folder isn't present until a certain point...

Trying to do this with GitHub Actions. anyone have any ideas?

**Comment by dpa99c** [comment]
This is beyond the scope of this plugin and better raised against the [cordova-ios](https://github.com/apache/cordova-ios) platform

**Comment by jpike88** [comment]
Can you pls raise it in a way that's accurate? Or can you pinpoint exactly what mechanism is causing this so I can follow it up? It blows up build logs and takes ages but you know more than I do, I just want to phrase the problem in the best way possible.

**Comment by jpike88** [comment]
Hi @dpa99c sorry to poke, but do you know the exact nature of the issue? Can you help me write an issue to the Cordova-ios guys or point me in the right direction?
