### ISSUE TITLE
Build failed in ios while adding google plus

### ISSUE THREAD

**Issue by kalaiprakash93** [dpa99c/cordova-plugin-firebasex#588]
Hi,
I am using both Google plus and firebasex plugin in my project.
Two days before it was worked well.
But now it makes build issue in iOS.
There is no build error is not coming. Just saying failed to install cordova-plugin-firebasex like that.
please provide any suggestion regarding this.

**Issue:**

Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1 Error output:
Cloning into '/var/folders/zw/0z5j9jrd0ps23m6bn9f93mbm0000gn/T/d20210213-1843-h7guz8'...
     Note: switching to '8c5af96d5acebebdabd1752aae5baac52e948c1c'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false

**Comment by cemelmaci** [comment]
downgrading cordova-plugin-googleplus to 8.5.0 works (Using GoogleUtilities (6.7.2)). Version 8.5.1 uses incompatible version of GoogleUtilities (7.2.2).
best regards

**Comment by dpa99c** [comment]
The Firebase v6 SDK for iOS implicitly uses GoogleUtilities v6.
This issue will be resolved by v12 of this plugin which will migrate to Firebase v7 SDK for iOS which uses GoogleUtilities v7.
