### ISSUE TITLE
I AM UNABLE OT IMPLEMENT THIS ON CORDOVA 10 . IS IT NOT SUPPORTED PLEASE LET ME KNOW

### ISSUE THREAD

**Issue by praveenpl03** [dpa99c/cordova-plugin-firebasex#589]
THE DOCUMENT SHOWING IT WORKS ON CORDOVA 10 ALSO BUT I AM FEELING NOT LUCKY PLEASE SHARE ME SOME INSTALATION OR IMPLEMENTATION MANUAL 

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by kalaiprakash93** [comment]
@praveenpl03 , could you please mention which hybrid technology using ?
If it is ionic means, 
please find the following documention
[https://ionicframework.com/docs/native/firebase-x]
don't forget to add it in app module

**Comment by praveenpl03** [comment]
I am using cordova cli only . no ionic

**Comment by kalaiselvi1505** [comment]
use the below comment for installation,
cordova plugin add cordova-plugin-firebasex
https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds

**Comment by burtsevyg** [comment]
I get import error:
```
In file included from .../platforms/ios/Runner/Plugins/cordova-plugin-firebasex/FirebasePlugin.m:1:
.../platforms/ios/Runner/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
```
I found in:
https://raw.githubusercontent.com/dpa99c/cordova-plugin-firebasex/master/plugin.xml
this line:
```
...
<pod name="FirebaseFirestore" git="https://github.com/invertase/firestore-ios-sdk-frameworks.git" tag="6.33.0"/>
...
```
but there are 7.X versions in:
https://github.com/invertase/firestore-ios-sdk-frameworks/tags

I think we need to update versions in plugin.xml

**Comment by praveenpl03** [comment]
![Screenshot 2021-02-15 at 9 22 57 PM](https://user-images.githubusercontent.com/67776553/107968352-45384e80-6fd4-11eb-9e64-bb3f8e3d13ee.png)
![Screenshot 2021-02-15 at 9 24 41 PM](https://user-images.githubusercontent.com/67776553/107968362-4a959900-6fd4-11eb-8965-10f694a68eb6.png)
![Screenshot 2021-02-15 at 9 24 15 PM](https://user-images.githubusercontent.com/67776553/107968374-4ff2e380-6fd4-11eb-88db-e0acd55e0e33.png)
I am unable to go ahead

**Comment by burtsevyg** [comment]
@praveenpl03 
Do you try test project? 
https://github.com/dpa99c/cordova-plugin-firebasex-test

**Comment by burtsevyg** [comment]
hm seems like you install npm wrong way. Try this instructions:
https://treehouse.github.io/installation-guides/mac/node-mac.html

**Comment by praveenpl03** [comment]
I am able to use all plugins other than firebasex 
Anybody tried it on cordova 10

**Comment by praveenpl03** [comment]
cordova plugin add cordova-plugin-androidx-adapter i find the issue frds 
its working now after adding this
