### ISSUE TITLE
iOS build issue Xcode 10

### ISSUE THREAD

**Issue by davide75** [dpa99c/cordova-plugin-firebasex#59]
I cloned the cordova-plugin-firebasex-test repository, tried to build it in my environment (Mac OS 10, Xcode 10.3) but iGet the same error as in issue #32 

I tried all the steps: edited build settings and build phases, tried pod install, pod repo update, but I'm still stuck on this error message

<img width="277" alt="Schermata 2019-07-26 alle 13 24 50" src="https://user-images.githubusercontent.com/48058181/61948667-c79f8e80-afa8-11e9-941b-7bb90b9c168a.png">
 
Any suggestions? Thanks

**Comment by dpa99c** [comment]
It definitely looks like a problem with Cocoapods.

did you open the `.xcworkspace` rather that `.xcodeproj`?

**Comment by davide75** [comment]
I opened the .xcworkspace

**Comment by dpa99c** [comment]
The setup of Cocoapods in your environment is the issue.
Try cloning the [Cocoapods example](https://github.com/CocoaPods/CocoaPodsExampleLibrary) and building its [example Xcode project](https://github.com/CocoaPods/CocoaPodsExampleLibrary/tree/master/Example) to validate/diagnose your Cocoapods setup.

**Comment by davide75** [comment]
At last I fixed my issue by adding $(inherited) to Header Search Paths and removin Lipods*.a  in link binary with library. I was missing the correct settings in Xcode. Now I am able to build... Should I add initialization code in main AppDelegate class as suggested in Firebase docs?

I'm a newbie, thank you if you can help me :-)

**Comment by dpa99c** [comment]
> Should I add initialization code in main AppDelegate class as suggested in Firebase docs?

This plugin handles the AppDelegate methods for you.
The best place to start is to build and run the [test project](https://github.com/dpa99c/cordova-plugin-firebasex) as a working reference. Once you've got push notifications working correctly with that, you can use it as a reference for your own apps.

**Comment by dpa99c** [comment]
(Closing as original issue is resolved)
