### ISSUE TITLE
open app automatically when killed/closed with notification-data fcm

### ISSUE THREAD

**Issue by shomid** [dpa99c/cordova-plugin-firebasex#591]
I want to open app(ionic5) is killed/closed with notification-data.<br>
json for api fcm-google is below:<br>

    {
    "to": "ca2KNRcxSz2waPUzY1SogM:APA91bH1hopX7x55urxeubs4Y0UQvYAoQtMaciLymjSxN0ht9AshWwXo4fkXpKmASHjyCG2Q8B8pw0X_0PtgfKByWVRPV2ARVQ85OWK8q06XZkYxAeLhIZvpISab9CemfU47CW5IagVE",
    "data": {
        "force-start": "1",
        "forceStart":"1",
        "no-cache": "1",
        "body": "Test",
        "title": "Test",
        "sound": "default",
        "icon": "default",
        "badge": 56
    },
    "priority": "high"
    }

I use `forceStart` in json but not work.<br>
where is the problem from ?

**Comment by shomid** [comment]
No one to guide?

**Comment by dpa99c** [comment]
There is not sufficient information in your issue to diagnose any specific problem - you didn't even say which platform this relates to (iOS or Android).
However, based on your reference to `force-start` I presume you are referring to what is not a standard Firebase feature but is specific to [phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push) which uses it to [trigger an intent](https://github.com/phonegap/phonegap-plugin-push/blob/50010275041e2726fd6788a7b7928baf47ead3e9/src/android/com/adobe/phonegap/push/FCMService.java#L353) if the app is not already running on Android.

This plugin does not yet contain such equivalent functionality, however this is an open issue (#235) to integrate the AutoStarter library for Android to resolve this.
