### ISSUE TITLE
[Help] FirebasePlugin.verifyPhoneNumber with manual user input code

### ISSUE THREAD

**Issue by aldoexpert** [dpa99c/cordova-plugin-firebasex#596]
Hello

Please help, how to use this FirebasePlugin.verifyPhoneNumber if number and phone in difference device so user will input code with manually

How to verifi code is valid ?
Thanks

**Comment by dpa99c** [comment]
Using a different device for the app and the phone containing the SIM card is not currently a supported scenario - `verifyPhoneNumber` requires the app to be running on the device containing the SIM card for the relevant phone number.
