### ISSUE TITLE
Android can not get fcm token, Now FirebaseInstanceId.getInstance().getToken() is deprecated. 

### ISSUE THREAD

**Issue by Crazyang** [dpa99c/cordova-plugin-firebasex#597]
# Bug report

**CHECKLIST**
- [] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `11.2.22`
        
_Runtime issue_
- Device details
    - Samsung Galaxy S8,
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `12.18.3`
- Gradle version
	- `6.1`
- Target Android SDK version
	- default
- Android SDK details
	- default
	
Envirement
"cordova-android": "^9.0.0",
"cordova-browser": "~6.0.0",
"cordova-custom-config": "^5.1.0",
"cordova-ios": "^6.2.0",
"cordova-plugin-androidx": "^3.0.0",
"cordova-plugin-androidx-adapter": "^1.1.3",
"cordova-plugin-console": "^1.1.0",
"cordova-plugin-enable-multidex": "^0.2.0",
"cordova-plugin-firebasex": "^11.0.3",
"cordova-plugin-whitelist": "~1.3.4",
"cordova-plugin-wkwebview-file-xhr": "^3.0.0"

Now i used android to get token is null , i check the plugin code , find an function getToken() is deprecated.
So i check it on firebase on https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.

And it suggestion we maybe need to change it into FirebaseInstallations to get token

Or there are another reason for causing app can not get token

**Comment by aldoexpert** [comment]
Hi @Crazyang 
I still use [https://github.com/dpa99c/cordova-plugin-firebasex#gettoken](https://github.com/dpa99c/cordova-plugin-firebasex#gettoken) and still work for now

**Comment by dpa99c** [comment]
As documented in [getToken()](https://github.com/dpa99c/cordova-plugin-firebasex#gettoken) the token will initially be `null` until allocated by the Firebase SDK. You can use [onTokenRefresh()](https://github.com/dpa99c/cordova-plugin-firebasex#ontokenrefresh) to listen for the allocation of a new token.

This is unrelated to the deprecation of FirebaseInstanceId which continues to work fine in the current release version of this plugin. A future version of this plugin will migrate from FirebaseInstanceId to Firebase Installations SDK.
