### ISSUE TITLE
fatal error: module 'FirebaseFirestore' not found

### ISSUE THREAD

**Issue by juanmanueldeveloper** [dpa99c/cordova-plugin-firebasex#599]
Command: **ionic cordova build ios --release**

**Error:**
```
Documents/Proyectos/colmena/frontend/app-isapre-colmena/platforms/ios/Colmena/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: 
      module 'FirebaseFirestore' not found
@import FirebaseFirestore;
 ~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.
** BUILD FAILED **

The following build commands failed:
        CompileC /Users/jm_devlife/Library/Developer/Xcode/DerivedData/Colmena-gjwlwyylbvaqdceakpapmuilvdyw/Build/Intermediates.noindex/Colmena.build/Release-iphonesimulator/Colmena.build/Objects-normal/x86_64/FirebasePlugin.o /Users/jm_devlife/Documents/Proyectos/colmena/frontend/app-isapre-colmena/platforms/ios/Colmena/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by danielraban** [comment]
@juanmanueldeveloper these are all warnings, there is probably an error higher up in the log.

**Comment by juanmanueldeveloper** [comment]
> Comando: **ionic cordova build ios --release**
> 
> **Error:**
> 
> ```
> Documents/Proyectos/colmena/frontend/app-isapre-colmena/platforms/ios/Colmena/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: 
>       module 'FirebaseFirestore' not found
> @import FirebaseFirestore;
>  ~~~~~~~^~~~~~~~~~~~~~~~~
> 1 error generated.
> ** BUILD FAILED **
> 
> The following build commands failed:
>         CompileC /Users/jm_devlife/Library/Developer/Xcode/DerivedData/Colmena-gjwlwyylbvaqdceakpapmuilvdyw/Build/Intermediates.noindex/Colmena.build/Release-iphonesimulator/Colmena.build/Objects-normal/x86_64/FirebasePlugin.o /Users/jm_devlife/Documents/Proyectos/colmena/frontend/app-isapre-colmena/platforms/ios/Colmena/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> xcodebuild: Command failed with exit code 65
> [ERROR] An error occurred while running subprocess cordova.
> ```

@dpa99c Me puedes ayudar con este issue?

**Comment by dpa99c** [comment]
There is sufficient detail in the error log to diagnose the problem.
Please see the [Reporting a bug or problem](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-a-bug-or-problem) section, specifically with regard to using the `--verbose` CLI build flag to generate a full build log containing details of the error then open a new issue containing the verbose log if necessary.
Please also see the various [iOS-specific](https://github.com/dpa99c/cordova-plugin-firebasex#ios-specific) notes as they contain solutions for the most common causes of build failures.

**Comment by vvarda** [comment]
Yep, it's everything about updating **name** tag in **config.xml** -- Latin only. For another cases use [localisation plugin](https://www.npmjs.com/package/cordova-plugin-localization-strings).

**Comment by bhargavas12** [comment]
/Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:4:9: fatal error: module 'FirebaseFirestore' not found
@import FirebaseFirestore;
 ~~~~~~~^~~~~~~~~~~~~~~~~
1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/FirebasePlugin.o /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --release exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.

Facing the same error
Need help, Thanks.

**Comment by bhargavas12** [comment]
> Yep, it's everything about updating **name** tag in **config.xml** -- Latin only. For another cases use [localisation plugin](https://www.npmjs.com/package/cordova-plugin-localization-strings).

How to update this?
