### ISSUE TITLE
Does it works for iOS nowadays? Thank you

### ISSUE THREAD

**Issue by manel00** [dpa99c/cordova-plugin-firebasex#605]
Hello,

I am facing the issue of FCM.onNotification() and it doesnt work, would like to try this framework but need to know in advances if it will have some problem on iOS,

Thank you

Kind Regards

**Comment by dpa99c** [comment]
This plugin is maintained and working on the latest version of iOS.
You can try it yourself using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).
