### ISSUE TITLE
Can we open app route when notification is tapped

### ISSUE THREAD

**Issue by StefanZivkovic** [dpa99c/cordova-plugin-firebasex#607]
Hi,

It's question more than it is a issue.
Currently, without problems I manage to send & receive push notification on `Android`. 

This is how message looks for firebase push notification which is sent from our backend (node.js):
```
const messageObject = {
      token: getValidFcmToken.token,
      notification: {
        title,
        body,
      },
      android: {
        notification: {
          // clickAction: 'something', // having this prevents me from opening the app when notification is clicked 
          (when app is in background). Also (window as any).FirebasePlugin.onMessageReceived is not triggered
        },
      },
      apns: {},
      data: {
        notification_foreground: 'true',
      },
};
```

On frontend (React) I use `(window as any).FirebasePlugin.onMessageReceived` to inspect what is happening. 

`config.xml` file:
```
<platform name="android">
       <!-- this edit-config block is used only in debug & development, and generally is removed -->
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:usesCleartextTraffic="true" /> 
        </edit-config>
        
        <preference name="APP_SECRET" value="<%= appSecret[brandLowercase].android %>" />
        <% if (codePush && codePush.android) { %>
        <preference name="CodePushDeploymentKey" value="<%= codePush.android %>" />
        <% } %>
        <preference name="Orientation" value="portrait" />
        <preference name="AndroidLaunchMode" value="singleInstance" />
        <allow-intent href="market:*" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-36x36.png" density="ldpi" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-48x48.png" density="mdpi" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-72x72.png" density="hdpi" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-96x96.png" density="xhdpi" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-144x144.png" density="xxhdpi" />
        <icon src="www/assets/<%= tenantId %>/favicon/android-icon-192x192.png" density="xxxhdpi" />
</platform>
```

In the generated `AndroidManifest.xml`  file I have something like:
```
<activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" 
android:label="@string/activity_name" android:launchMode="singleInstance" android:name="MainActivity" 
android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" 
android:windowSoftInputMode="adjustResize">
      <intent-filter android:label="@string/launcher_name">
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter android:autoVerify="true">
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:host="was-eur-ww-dev-app20.azurewebsites.net" android:scheme="https"/>
      </intent-filter>
</activity>
    ...
<service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
  <intent-filter>
    <action android:name="com.google.firebase.MESSAGING_EVENT"/>
  </intent-filter>
</service>
```

Question: with this plugin `cordova-plugin-firebasex`, can we define route to which we want our app to open in moment when the notification is tapped by user? If yes, how?

**Comment by dpa99c** [comment]
If you want your app to carry out some specific behaviour on receiving a push notification message, I'd suggest defining a key in the data payload of the message which is passed to the app in `onMessageReceived` when the user taps the system notification, for example:

```
{
      token: getValidFcmToken.token,
      notification: {
        title,
        body
      },
      data: {
        notification_foreground: 'true',
        my_action: "do_something"
      }
}
```

Then when the user taps the system notification, the payload is delivered to `onMessageReceived` where you can act on it:

```
FirebasePlugin.onMessageReceived(function(message) {
    if(message.my_action === "do_something"){
        doSomethingWithMyAction();
    }
}, function(error) {
    console.error(error);
});
```

**Comment by StefanZivkovic** [comment]
Thanks for reply.
Well, have to check on that. I was more curios about statements provided by firebase docs, related to `android->notification->clickAction`, and `apns->payload->aps->category`:
1. https://firebase.google.com/docs/cloud-messaging/concept-options#example-notification-message-with-platform-specific-delivery-options
2. https://firebase.google.com/docs/cloud-messaging/send-message#example-notification-click-action
3. https://firebase.google.com/docs/dynamic-links/rest

**Comment by dpa99c** [comment]
The Firebase SDK documentation is written as if you are integrating a native Android or iOS app with the Firebase SDK and therefore are writing your app business logic in the native code layer.
For example, in a native Android app, you can launch a different activity or intent based upon the `click_action` in the notification message.
And in a native iOS app, you can show a different view controller based upon a selected category.

However since your app is a Cordova hybrid app, all your business logic resides in the Javascript layer so this plugin is providing the native bridge between your app logic and the Firebase SDK. Therefore the native plugin implementation has to be more generic than that which you would implement in a native app.

As it happens, thanks to [PR #482](https://github.com/dpa99c/cordova-plugin-firebasex/pull/482), iOS categories are now supported and do deliver the `click_action` outcome to the `onMessageReceived` callback.

However for Android, there is currently no support for the `click_action` since the Firebase SDK intends this to be used with a native (multi-activity/intent) Android app whereas Cordova apps are inherently single activity/single intent.
