### ISSUE TITLE
Conflict with Google plus plugin

### ISSUE THREAD

**Issue by digaantarora** [dpa99c/cordova-plugin-firebasex#614]
Unable to install the plugin, as I get the below error
cordova-plugin-firebasex depends on GoogleSignIn, which may conflict with another plugin. GoogleSignIn@~> 5.0.2 is already installed and was not overwritten.
Running command: pod install --verbose
     Cloning into '/var/folders/bd/szzyq3bx17gfm7j8t5y8v7pr0000gn/T/d20210406-59485-1cvvulb'...

     Note: switching to '8c5af96d5acebebdabd1752aae5baac52e948c1c'.
     

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch

**Comment by digaantarora** [comment]
v12 solved this

**Comment by gaetanlgce** [comment]
Hi,

The version 12 work's fine but I have the same problem with the new version 13. Is there a regression or just a mistake in my project ?

**Comment by franalt** [comment]
I have the same problem on v13

**Comment by afelipelli** [comment]
> 

Any solution or workaround?

**Comment by afelipelli** [comment]
In case someone else finds this issue in the future, I solved it by changing the GoogleUtilities podfile used within Google Plus plugin:

Changed to:
<pod name="GoogleUtilities" spec="~> 7.7.0"/>

Inside the plugin.xml

**Comment by dlandtaa** [comment]
@afelipelli After you changed the `plugin.xml` file, how did you get those changes to take affect?

**Comment by afelipelli** [comment]
After you change the plugin.xml you should be able to remove the ios
platform and add it again to test.

If it works, you probably want to fork the plugin, change it and have your
package.json point to the changed version, so you don't have to do the
manual step to build.

You could use our fork if you wish:

https://github.com/veggly/cordova-plugin-googleplus


Regards,
Alex

Em qui., 1 de set. de 2022 às 2:04 AM, dlandtaa ***@***.***>
escreveu:
