### ISSUE TITLE
iOS app crashing on calling startTrace method part 2 (Issue #602 only partially solved)

### ISSUE THREAD

**Issue by jhpetersen** [dpa99c/cordova-plugin-firebasex#616]
Hi there,

3 weeks ago i filed a bug report https://github.com/dpa99c/cordova-plugin-firebasex/issues/602 regarding hard app crashes on iOS during the startTrace methos, which was thought to be fixed by commit https://github.com/dpa99c/cordova-plugin-firebasex/commit/e9c23fbf614889a5a6401c824a8d8d068b24488f which was merged into release 12.0.0.

As [already mentioned](https://github.com/dpa99c/cordova-plugin-firebasex/issues/602#issuecomment-805071582) in the bug report comments, i observed another related iOS crash within the same method.
(as these seem to be tightly coupled issues, i don't fill all of the bug report template sections again..)

Now another hard crash (EXC_BAD_ACCESS KERN_INVALID_ADDRESS) within startTrace happened again with cordova-plugin-firebasex version 12.0.0.
See the following stacktrace:
```
0   libobjc.A.dylib          objc_msgSend + 8
1   CoreFoundation           -[__NSDictionaryM objectForKey:] + 184
2   myApp                    FirebasePlugin.m - Zeile 1452
                                __29-[FirebasePlugin startTrace:]_block_invoke + 1452
3   libdispatch.dylib        _dispatch_call_block_and_release + 32
4   libdispatch.dylib        _dispatch_client_callout + 20
5   libdispatch.dylib        _dispatch_queue_override_invoke + 692
6   libdispatch.dylib        _dispatch_root_queue_drain + 356
7   libdispatch.dylib        _dispatch_worker_thread2 + 116
8   libsystem_pthread.dylib  _pthread_wqthread + 216
9   libsystem_pthread.dylib   start_wqthread + 8
```

Googling for NSMutableDictionary objectForKey and EXC_BAD_ACCESS suggests some threading issues, as NSMutableDictionary  is not thread safe.
I once again looked over the corresponding iOS code in FirebasePlugin.m.
The only two things i noticed compared to other dictionaries were:
- all methods using property traces (startTrace, stopTrace and incrementCounter) are calling the dictionary directly, whereas f.e. methods calling firestoreListeners dictionary are wrapped within `@synchronized` scope
- other NSMutableDictionary variables (like firestoreListeners and authCredentials) were defined as static and initialized by alloc init opposed to `@synthesized` property and initialization with new for traces dictionary.

I don't know, if any of these causes the crash, but it looks to me like if this is something to have a closer look on.

regards and thanks in advance

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Comment by jhpetersen** [comment]
Definitely not fixed and should not be closed, but high priority.
I had to disable metrics capturing (= not use startTrace and stopTrace) on iOS completely to prevent the App from crashing 😞 

Firebase tools should be meant to improve app quality, not to make it worse 😉 
So can some experienced iOS dev check this specific bug?

**Comment by dpa99c** [comment]
I see no reason not to make the traces dictionary static and synchronised which should hopefully resolve this issue.

Note that this plugin is a fork of [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) and therefore this code is not mine but has been [directly inherited](https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/ios/FirebasePlugin.h#L40) along with its bugs.
Therefore it looks like this has always been an issue in the plugin code.

**Comment by dpa99c** [comment]
This change has just been released in major version `cordova-plugin-firebasex@13.0.0`.
Please confirm if the crashes are still encountered with this new version or if they are resolved by it.

**Comment by jhpetersen** [comment]
Thank you for the fix.
I will need some time to test the update on a smaller user basis and see if it fixes this issue..

**Comment by jhpetersen** [comment]
Sorry that it took me so long to verify the proposed fix.
Sadly the error still occures, see the following log:

**com.apple.root.default-qos SIGABRT ABORT 0x00000001c7df3334**
```
Crashed: com.apple.root.default-qos
0  libsystem_kernel.dylib         0x1c7df3334 __pthread_kill + 8
1  libsystem_pthread.dylib        0x1e5879a9c pthread_kill + 272
2  libsystem_c.dylib              0x1a2eb5b84 abort + 124
3  libsystem_malloc.dylib         0x1a915e4c8 _malloc_put + 558
4  libsystem_malloc.dylib         0x1a915e6a8 malloc_report + 64
5  libsystem_malloc.dylib         0x1a9153410 free + 516
6  CoreFoundation                 0x199b53f28 mdict_rehashd + 288
7  CoreFoundation                 0x1999cb22c -[__NSDictionaryM setObject:forKey:] + 724
8  myApp                          0x1009172a4 __29-[FirebasePlugin startTrace:]_block_invoke + 1476 (FirebasePlugin.m:1476)
9  libdispatch.dylib              0x1996d9a84 _dispatch_call_block_and_release + 32
10 libdispatch.dylib              0x1996db81c _dispatch_client_callout + 20
11 libdispatch.dylib              0x1996de968 _dispatch_queue_override_invoke + 756
12 libdispatch.dylib              0x1996ecfe0 _dispatch_root_queue_drain + 388
13 libdispatch.dylib              0x1996ed7d8 _dispatch_worker_thread2 + 112
14 libsystem_pthread.dylib        0x1e587a768 _pthread_wqthread + 216
15 libsystem_pthread.dylib        0x1e588174c start_wqthread + 8
```

Can you reopen this issue?
And why the legacy tag was applied to this?

I am quite helpless right now - this issue did not happen to me during development (in Emulator and on iPad device) but happened within days on alpha release with only a few users.

Are there any people out there actually using this plugin's startTrace functionality on iOS without having this problem?
Someone having an idea, what could cause this crash and how to fix it?

a sigh and a thanks :/
