### ISSUE TITLE
Pipeline build failed for ios in Ionic 5 app 

### ISSUE THREAD

**Issue by bhargavas12** [dpa99c/cordova-plugin-firebasex#620]
Locally I am able to build the project successfully and able to run the app in simulator.
But when I try to build the same in azure pipeline  I am getting the below error. 
I am struck at this point. :( 
Need help on how we can proceed on this.

************** ERROR *************************

CompileC /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/IONAssetHandler.o /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-ionic-webview/IONAssetHandler.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'project' from project 'project')
    cd /Users/runner/work/1/s/platforms/ios
    export LANG\=en_US.US-ASCII
    /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios12.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DCOCOAPODS\=1 -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS\=1 -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DPB_FIELD_32BIT\=1 -DPB_NO_PACKED_STRUCTS\=1 -DPB_ENABLE_MALLOC\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility\=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version\=2 -fobjc-legacy-dispatch -iquote /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-generated-files.hmap -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-own-target-headers.hmap -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-all-target-headers.hmap -iquote /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-project-headers.hmap -I/Users/runner/work/1/s/platforms/ios/build/emulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseABTesting/FirebaseABTesting.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseAuth/FirebaseAuth.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCore/FirebaseCore.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseInstanceID/FirebaseInstanceID.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseMessaging/FirebaseMessaging.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig/FirebaseRemoteConfig.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleToolboxForMac/GoogleToolboxForMac.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/PromisesObjC/FBLPromises.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/Protobuf/Protobuf.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/nanopb/nanopb.framework/Headers -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/Firebase -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseAnalyticsInterop -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseAuthInterop -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop -I/Users/runner/work/1/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator -I/Users/runner/work/1/s/platforms/ios/Pods/Firebase/CoreOnly/Sources -I/Sources/FBLPromises/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources-normal/x86_64 -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources/x86_64 -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources -F/Users/runner/work/1/s/platforms/ios/build/emulator -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseABTesting -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseAuth -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCore -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseInstanceID -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseMessaging -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GTMSessionFetcher -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransport -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleToolboxForMac -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleUtilities -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/PromisesObjC -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/Protobuf -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/nanopb -F/Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/Fabric/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/FirebasePerformance/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/GoogleAppMeasurement/Frameworks -include /Users/runner/work/1/s/platforms/ios/build/sharedpch/SharedPrecompiledHeaders/6040259970454557214/project-Prefix.pch -MMD -MT dependencies -MF /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/IONAssetHandler.d --serialize-diagnostics /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/IONAssetHandler.dia -c /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-ionic-webview/IONAssetHandler.m -o /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/IONAssetHandler.o

CompileC /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/FirebasePlugin.o /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'project' from project 'project')
    cd /Users/runner/work/1/s/platforms/ios
    export LANG\=en_US.US-ASCII
    /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios12.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/runner/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DCOCOAPODS\=1 -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS\=1 -DWK_WEB_VIEW_ONLY\=1 -DWK_WEB_VIEW_ONLY\=1 -DPB_FIELD_32BIT\=1 -DPB_NO_PACKED_STRUCTS\=1 -DPB_ENABLE_MALLOC\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility\=hidden -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version\=2 -fobjc-legacy-dispatch -iquote /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-generated-files.hmap -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-own-target-headers.hmap -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-all-target-headers.hmap -iquote /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/project-project-headers.hmap -I/Users/runner/work/1/s/platforms/ios/build/emulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseABTesting/FirebaseABTesting.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseAuth/FirebaseAuth.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCore/FirebaseCore.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics/FirebaseCoreDiagnostics.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseInstanceID/FirebaseInstanceID.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseMessaging/FirebaseMessaging.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig/FirebaseRemoteConfig.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GTMSessionFetcher/GTMSessionFetcher.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransport/GoogleDataTransport.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleToolboxForMac/GoogleToolboxForMac.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleUtilities/GoogleUtilities.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/PromisesObjC/FBLPromises.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/Protobuf/Protobuf.framework/Headers -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/nanopb/nanopb.framework/Headers -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/Firebase -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseAnalyticsInterop -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseAuthInterop -I/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/FirebaseCoreDiagnosticsInterop -I/Users/runner/work/1/s/platforms/ios/build/emulator/usr/local/lib/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/runner/work/1/s/platforms/ios/build/emulator -I/Users/runner/work/1/s/platforms/ios/Pods/Firebase/CoreOnly/Sources -I/Sources/FBLPromises/include -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources-normal/x86_64 -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources/x86_64 -I/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/DerivedSources -F/Users/runner/work/1/s/platforms/ios/build/emulator -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseABTesting -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseAuth -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCore -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseInstanceID -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseMessaging -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GTMSessionFetcher -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransport -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleToolboxForMac -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/GoogleUtilities -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/PromisesObjC -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/Protobuf -F/Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Products/Release-iphonesimulator/nanopb -F/Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/Fabric/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/FirebasePerformance/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/GoogleAppMeasurement/Frameworks -include /Users/runner/work/1/s/platforms/ios/build/sharedpch/SharedPrecompiledHeaders/6040259970454557214/project-Prefix.pch -MMD -MT dependencies -MF /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/FirebasePlugin.d --serialize-diagnostics /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/FirebasePlugin.dia -c /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.m -o /Users/runner/Library/Developer/Xcode/DerivedData/project-fxugayqvszschvbnblxkoqzrvhcu/Build/Intermediates.noindex/project.build/Release-iphonesimulator/project.build/Objects-normal/x86_64/FirebasePlugin.o
While building module 'Firebase' imported from /Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.m:4:
In file included from <module-includes>:1:
/Users/runner/work/1/s/platforms/ios/Pods/Headers/Public/Firebase/Firebase.h:15:9: fatal error: 'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
/Users/runner/work/1/s/platforms/ios/project/Plugins/cordova-plugin-firebasex/FirebasePlugin.m:4:9: fatal error: could not build module 'Firebase'
#import "Firebase.h"
 ~~~~~~~^~~~~~~~~~~~
2 errors generated.


we are using below configuration:
Xcode - 12.4
MAC - 10.15
Ios Deployment target - 14.4
FirebaseX - 7.0.1
cordova-ios 5.1.1

Thanks,
Bhargav.

**Comment by battika** [comment]
Have you tried using the cli version of this plugin?

**Comment by dpa99c** [comment]
Azure pipeline is the issue and is not supported but this plugin.
See #525 and #533
