### ISSUE TITLE
error not send notification iOS on status App Active : FirebasePlugin[native] ERROR: EXCEPTION: -[NSTaggedPointerString isEqualToNumber:]: unrecognized selector sent to instance 0x8c2cd9ffe0baaec5

### ISSUE THREAD

**Issue by Danhlocnd** [dpa99c/cordova-plugin-firebasex#624]
# Bug report

**CHECKLIST**
- [ ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `cordova -v`
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
- XCode version

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by CheBo75** [comment]
adding single quotes around content-available in AppDelegate+FirebasePlugin.m line 190

`isContentAvailable = [[aps objectForKey:@"'content-available'"] isEqualToNumber:[NSNumber numberWithInt:1]];`

fixed this issue

**Comment by orenkatz** [comment]
Have the same issue and @CheBo75 solution worked for me (adding single quotes on every content-available.
Thanks!
