### ISSUE TITLE
Finding a solution for displaying a badge on android devices

### ISSUE THREAD

**Issue by MykytaPereverziev** [dpa99c/cordova-plugin-firebasex#627]
Using this plugin in the project, I encountered the problem of displaying the counter of unread notifications on the application icon on android devices. It will be cool if you share the solution to the problem here.

**Comment by dpa99c** [comment]
[As stated here](https://github.com/dpa99c/cordova-plugin-firebasex/issues/124#issuecomment-527649908), there's no way to programmatically set the badge number on Android 8+ without sending/displaying a notification.
