### ISSUE TITLE
Issue: ** ARCHIVE FAILED **  xcodebuild: Command failed with exit code 65

### ISSUE THREAD

**Issue by MESHach12345** [dpa99c/cordova-plugin-firebasex#628]
<img width="610" alt="Screen Shot 2021-06-02 at 11 02 30" src="https://user-images.githubusercontent.com/83641520/120422231-087d4100-c392-11eb-8cc9-9d4acd980ec7.png">

**Comment by MESHach12345** [comment]
> npm run ionic:build:before

> moodlemobile@3.9.4 ionic:build:before
> npx gulp

[10:57:31] Using gulpfile ~/Desktop/Work/PCMan/BUMAMobile/moodleapp/gulpfile.js
[10:57:31] Starting 'default'...
[10:57:31] Starting 'lang'...
[10:57:31] Starting 'config'...
[10:57:32] Finished 'config' after 1.26 s
[10:57:32] Finished 'lang' after 1.39 s
[10:57:32] Finished 'default' after 1.42 s
> npm run ionic:build -- --target cordova --platform ios

> moodlemobile@3.9.4 preionic:build
> npx gulp

[10:57:35] Using gulpfile ~/Desktop/Work/PCMan/BUMAMobile/moodleapp/gulpfile.js
[10:57:35] Starting 'default'...
[10:57:35] Starting 'lang'...
[10:57:35] Starting 'config'...
[10:57:35] Finished 'config' after 425 ms
[10:57:35] Finished 'lang' after 488 ms
[10:57:35] Finished 'default' after 490 ms

> moodlemobile@3.9.4 ionic:build
> node --max-old-space-size=16384 ./node_modules/@ionic/app-scripts/bin/ionic-app-scripts.js build "--target" "cordova" "--platform" "ios"

[10:57:38]  ionic-app-scripts 3.2.3 
[10:57:38]  build dev started ... 
[10:57:38]  clean started ... 
[10:57:38]  clean finished in 75 ms 
[10:57:38]  copy started ... 
[10:57:40]  deeplinks started ... 
[10:57:44]  deeplinks finished in 3.86 s 
[10:57:44]  transpile started ... 
[10:58:23]  transpile finished in 38.81 s 
[10:58:23]  preprocess started ... 
[10:58:23]  preprocess finished in 1 ms 
[10:58:23]  webpack started ... 
[10:58:23]  copy finished in 44.87 s 
[10:59:06]  webpack finished in 43.42 s 
[10:59:06]  sass started ... 
[10:59:16]  sass finished in 10.22 s 
[10:59:16]  postprocess started ... 
[10:59:17]  postprocess finished in 115 ms 
[10:59:17]  lint started ... 
[10:59:17]  build dev finished in 98.85 s 
[10:59:48]  lint finished in 30.91 s 

> moodlemobile@3.9.4 postionic:build
> npx gulp copy-component-templates

[10:59:51] Using gulpfile ~/Desktop/Work/PCMan/BUMAMobile/moodleapp/gulpfile.js
[10:59:51] Starting 'copy-component-templates'...
[10:59:52] Finished 'copy-component-templates' after 1.29 s
> npm run ionic:build:after

> moodlemobile@3.9.4 ionic:build:after
> npx gulp copy-component-templates

[10:59:55] Using gulpfile ~/Desktop/Work/PCMan/BUMAMobile/moodleapp/gulpfile.js
[10:59:55] Starting 'copy-component-templates'...
[10:59:56] Finished 'copy-component-templates' after 1.29 s
> cordova build ios --device
Overwriting existing resource file at platforms/ios/BUMA LMS/Resources/GoogleService-Info.plist
Conflict found, edit-config changes from config.xml will overwrite plugin.xml changes
Building project: /Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/BUMA LMS.xcworkspace
	Configuration: Debug
	Platform: device
	Target: 
Running command: xcodebuild -workspace BUMA LMS.xcworkspace -scheme BUMA LMS -configuration Debug -destination generic/platform=iOS -archivePath BUMA LMS.xcarchive archive CONFIGURATION_BUILD_DIR=/Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/device SHARED_PRECOMPS_DIR=/Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/sharedpch
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace "BUMA LMS.xcworkspace" -scheme "BUMA LMS" -configuration Debug -destination generic/platform=iOS -archivePath "BUMA LMS.xcarchive" archive CONFIGURATION_BUILD_DIR=/Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/device SHARED_PRECOMPS_DIR=/Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/sharedpch

User defaults from command line:
    IDEArchivePathOverride = /Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/BUMA LMS.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/device
    SHARED_PRECOMPS_DIR = /Users/meshachsamuel/desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/build/sharedpch

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
/Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'FirebaseAnalytics' from project 'Pods')
/Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'FirebaseInstanceID' from project 'Pods')
/Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'FirebaseCore' from project 'Pods')
/Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'nanopb' from project 'Pods')
/Users/meshachsamuel/Desktop/Work/PCMan/BUMAMobile/moodleapp/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'FirebaseMessaging' from project 'Pods')
error: Signing for "BUMA LMS" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'BUMA LMS' from project 'BUMA LMS')

** ARCHIVE FAILED **

xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
        
        cordova build ios --device exited with exit code 65.
        
        Re-running this command with the --verbose flag may provide more information.
meshachsamuel@Meshachs-MacBook-Pro moodleapp %

**Comment by lincolnminto-cronapp** [comment]
I'm facing a similar error trying to build a project with the following error output:

`/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'GoogleUtilitiesLegacy' from project 'Pods')
/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'GoogleSymbolUtilities' from project 'Pods')
/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'GoogleAnalytics' from project 'Pods')
/platforms/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'GoogleSignIn' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/myuser/Library/Developer/Xcode/DerivedData/myproject/Build/Intermediates.noindex/ArchiveIntermediates/myproject/IntermediateBuildFilesPath/myproject.build/Release-iphoneos/myproject.build/Script-4794735395C457C453A66901.sh
(1 failure)
`

**Comment by dpa99c** [comment]
@MESHach12345 the cause of the error is shown in your console output:

> error: Signing for "BUMA LMS" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'BUMA LMS' from project 'BUMA LMS')

The build failed because Xcode could not find a valid provisioning profile with which to sign your app.

To validate your build environment against a known working codebase, please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

@lincolnminto-cronapp your error is due to the deployment target in your project's Xcode platform project being set to lower than is supported by the Firebase SDK components. As above, please use the example project to verify your build environment.
