### ISSUE TITLE
clang: error: linker command failed with exit code 1 - for architecture arm64

### ISSUE THREAD

**Issue by asanka-indrajith** [dpa99c/cordova-plugin-firebasex#630]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
Thanks so much for this awesome plugin. We were using for 2 years. we have used this plugin almost 2 years and no problem at all. We are using CI Pipeline (Azure Devop Pipelines) to build Project. Due to Apple minsdk requirement we had to update iOS sdk to iphoneos14.4  and Xcode to ^12 in Build pieline. 
Once upgraded we start to encounter this build issue.
```
ld: in /Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(CLSInternalReport.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Since we are using CLI to build, I've tried -cli branch version as well. But same error happens.

**Expected behavior:**
App should be build without error and push notifications should work

**Steps to reproduce:**

**Screenshots**

**Environment information**

Cordova CLI version

10.0.0

Cordova platform version

cordova-android 10.0.0
cordova-ios 5.1.1
Plugins & versions installed in project (including this plugin)

call-number 0.0.2 "Cordova Call Number Plugin"
com-badrit-base64 0.2.0 "Base64"
com.unarin.cordova.beacon 3.8.1 "Proximity Beacon Plugin"
cordova-blur-app-privacy-screen 0.0.1 "BlurAppPrivacyScreen"
cordova-clipboard 1.3.0 "Clipboard"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-advanced-http 3.1.0 "Advanced HTTP plugin"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-autostart 2.3.0 "Autostart"
cordova-plugin-background-mode-bluetooth-central 1.0.0 "Bluetooth Central Background Mode"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-bluetoothle 4.5.6 "Bluetooth LE"
cordova-plugin-camera 5.0.2 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-firebasex 12.0.0-cli "Google Firebase Plugin"
cordova-plugin-inappbrowser 3.2.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-iroot 2.1.0 "iRoot"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-privacyscreen 0.3.1 "PrivacyScreenPlugin"
cordova-plugin-qrscanner 3.0.1 "QRScanner"
cordova-plugin-secure-storage-echo 5.1.1 "SecureStorage"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-inject-cookie 1.0.2 "WKWebViewInjectCookie"
cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"

- Dev machine OS and version, e.g.
    - OSX
        - macOS-10.15
        	
_iOS build issue:_
- Node JS version
    - 12.22.1 x64
- XCode version
 Xcode 12

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

Ld /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/Binary/HotDesk normal arm64 (in target 'HotDesk' from project 'HotDesk')
    cd /Users/runner/work/1/s/platforms/ios
    /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0-simulator -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk -L/Users/runner/work/1/s/platforms/ios/build/emulator -F/Users/runner/work/1/s/platforms/ios/build/emulator -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/AppAuth -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/BoringSSL-GRPC -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseABTesting -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseAuth -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseCore -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseFirestore -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseInstallations -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseInstanceID -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseMessaging -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GTMAppAuth -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GTMSessionFetcher -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleDataTransport -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleToolboxForMac -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleUtilities -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/PromisesObjC -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/Protobuf -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/abseil -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/gRPC-C++ -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/gRPC-Core -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/leveldb-library -F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/nanopb -F/Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/Fabric/iOS -F/Users/runner/work/1/s/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/FirebasePerformance/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/GoogleAppMeasurement/Frameworks -F/Users/runner/work/1/s/platforms/ios/Pods/GoogleSignIn/Frameworks -filelist /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/HotDesk.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/HotDesk_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/HotDesk.swiftmodule -ObjC -ObjC -lc++ -lsqlite3 -lz -framework AppAuth -framework CoreGraphics -framework CoreTelephony -framework CoreText -framework Crashlytics -framework FBLPromises -framework FIRAnalyticsConnector -framework Fabric -framework FirebaseABTesting -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseCoreDiagnostics -framework FirebaseFirestore -framework FirebaseInstallations -framework FirebaseInstanceID -framework FirebaseMessaging -framework FirebasePerformance -framework FirebaseRemoteConfig -framework Foundation -framework GTMAppAuth -framework GTMSessionFetcher -framework GoogleAppMeasurement -framework GoogleDataTransport -framework GoogleDataTransportCCTSupport -framework GoogleSignIn -framework GoogleToolboxForMac -framework GoogleUtilities -framework LocalAuthentication -framework MobileCoreServices -framework Protobuf -framework QuartzCore -framework SafariServices -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework absl -framework grpc -framework grpcpp -framework leveldb -framework nanopb -framework openssl_grpc -weak_framework AuthenticationServices -weak_framework UserNotifications -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/HotDesk.app-Simulated.xcent /Users/runner/work/1/s/platforms/ios/build/emulator/libCordova.a -framework UserNotifications -framework CoreLocation -framework QuartzCore -framework AVFoundation -framework CoreBluetooth -weak_framework WebKit -framework Security -framework SystemConfiguration -weak_framework ImageIO -framework AuthenticationServices -framework Pods_HotDesk -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/HotDesk_dependency_info.dat -o /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/Binary/HotDesk
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/AppAuth'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/BoringSSL-GRPC'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseABTesting'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseAuth'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseCore'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseCoreDiagnostics'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseFirestore'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseInstallations'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseInstanceID'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseMessaging'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/FirebaseRemoteConfig'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GTMAppAuth'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GTMSessionFetcher'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleDataTransport'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleDataTransportCCTSupport'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleToolboxForMac'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/GoogleUtilities'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/PromisesObjC'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/Protobuf'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/abseil'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/gRPC-C++'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/gRPC-Core'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/leveldb-library'
ld: warning: directory not found for option '-F/Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Products/Release-iphonesimulator/nanopb'
0

ld: in /Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics(CLSInternalReport.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/runner/work/1/s/platforms/ios/Pods/Crashlytics/iOS/Crashlytics.framework/Crashlytics' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Crashlytics' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseAuthInterop' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseAnalyticsInterop' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Fabric' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'GoogleSignIn' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseAnalytics' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'Firebase' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebasePerformance' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'GoogleAppMeasurement' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseCoreDiagnosticsInterop' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseAuth' from project 'Pods')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'FirebaseInstanceID' from project 'Pods')
** BUILD FAILED **


The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/HotDesk-desddkynnzbklkeresbctsoywpsn/Build/Intermediates.noindex/HotDesk.build/Release-iphonesimulator/HotDesk.build/Objects-normal/arm64/Binary/HotDesk normal arm64
(1 failure)
Command finished with error code 65: xcodebuild -workspace,HotDesk.xcworkspace,-scheme,HotDesk,-configuration,Release,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone 12 Pro Max,build,CONFIGURATION_BUILD_DIR=/Users/runner/work/1/s/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/runner/work/1/s/platforms/ios/build/sharedpch,\"-UseModernBuildSystem=0\"
xcodebuild: Command failed with exit code 65
Error: xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
    at ChildProcess.whenDone (/Users/runner/work/1/s/node_modules/cordova-common/src/superspawn.js:135:23)
        
    at ChildProcess.emit (events.js:314:20)

```

</details><br/><br/>

**Other information:**

**Comment by joshdegouveia** [comment]
We are also seeing the same issue in our CI pipeline.

```
ld: in /Users/distiller/project/platforms/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/distiller/project/platforms/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Environment information**

Cordova CLI version

9.0.0

Cordova platform version

cordova-android 9.0.0
cordova-ios 6.2.0
Plugins & versions installed in project (including this plugin)

"dependencies": {
    "@angular-builders/custom-webpack": "^8.4.1",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@briebug/ngrx-auto-entity": "~0.5.0",
    "@fortawesome/angular-fontawesome": "0.5.0",
    "@fortawesome/fontawesome-svg-core": "~1.2.28",
    "@fortawesome/free-brands-svg-icons": "5.13.0",
    "@fortawesome/free-regular-svg-icons": "5.13.0",
    "@fortawesome/free-solid-svg-icons": "5.13.0",
    "@ionic-native/android-permissions": "^5.26.0",
    "@ionic-native/app-launcher": "^5.29.0",
    "@ionic-native/app-version": "^5.23.0",
    "@ionic-native/badge": "^5.27.0",
    "@ionic-native/barcode-scanner": "^5.18.0",
    "@ionic-native/camera": "^5.24.0",
    "@ionic-native/cloud-settings": "^5.15.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/device": "^5.15.1",
    "@ionic-native/file": "^5.24.0",
    "@ionic-native/firebase-x": "5.19.1",
    "@ionic-native/geolocation": "^5.21.5",
    "@ionic-native/in-app-browser": "^5.29.0",
    "@ionic-native/launch-navigator": "^5.21.5",
    "@ionic-native/local-notifications": "^5.24.0",
    "@ionic-native/network": "^5.15.1",
    "@ionic-native/screenshot": "^5.15.1",
    "@ionic-native/social-sharing": "^5.15.1",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/sqlite": "5.20.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic-native/themeable-browser": "^5.16.0",
    "@ionic-native/unique-device-id": "^5.16.0",
    "@ionic/angular": "^4.11.10",
    "@ionic/storage": "^2.2.0",
    "@ngneat/transloco": "^2.20.1",
    "@ngneat/transloco-locale": "^1.4.0",
    "@ngneat/transloco-messageformat": "^1.3.0",
    "@ngrx/effects": "^8.3.0",
    "@ngrx/store": "^8.3.0",
    "@ngrx/store-devtools": "^8.3.0",
    "@ngui/map": "^0.30.3",
    "briebug-cordova-plugin-local-notification": "^0.9.0-beta.4",
    "briebug-cordova-plugin-themeablebrowser": "^0.5.2-alpha.1",
    "briebug-cordova-screenshot": "^0.1.7",
    "clone-deep": "^4.0.1",
    "cordova-android": "^9.0.0",
    "cordova-custom-config": "^5.1.0",
    "cordova-ios": "^6.2.0",
    "cordova-plugin-actionsheet": "^2.3.3",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-androidx-adapter": "^1.1.3",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-badge": "^0.8.8",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-firebasex": "12.1.0-cli",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-webview": "^5.0.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-splashscreen": "^6.0.0",
    "cordova-plugin-unique-device-id2": "^2.0.0",
    "cordova-plugin-x-socialsharing": "^5.6.2",
    "cordova-sqlite-storage": "^5.1.0",
    "core-js": "^2.5.4",
    "date-fns": "^2.9.0",
    "deepmerge": "^4.2.2",
    "dexie": "^3.0.3",
    "es6-promise-plugin": "^4.2.2",
    "fuzzy": "^0.1.3",
    "geolib": "^2.0.24",
    "left-pad": "^1.3.0",
    "memoizee": "^0.4.14",
    "merge-anything": "^2.4.1",
    "messageformat": "^2.3.0",
    "moize": "^5.4.5",
    "ng-inline-svg": "^9.1.0",
    "ngrx-store-ionic-storage": "^5.0.0",
    "ngrx-store-localstorage": "^8.0.0",
    "ngx-markdown": "^8.2.1",
    "pattern-match": "^0.3.0",
    "phonegap-plugin-barcodescanner": "^8.1.0",
    "pluralize": "^8.0.0",
    "pouchdb-adapter-cordova-sqlite": "^2.0.7",
    "pouchdb-adapter-idb": "^7.1.1",
    "rxdb": "^8.7.4",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.0",
    "uk.co.workingedge.phonegap.plugin.launchnavigator": "^5.0.4",
    "useragent-parser-js": "^1.0.3",
    "uuid": "^3.3.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@briebug/jest-schematic": "^2.1.0",
    "@cypress/code-coverage": "^3.8.2",
    "@ionic/angular-toolkit": "^2.3.3",
    "@types/googlemaps": "3.30.0",
    "@types/jest": "^26.0.16",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-app-launcher": "^0.4.0",
    "cordova-plugin-camera": "^5.0.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-inappbrowser": "^4.0.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cypress": "^5.6.0",
    "cypress-pipe": "^2.0.0",
    "cypress-wait-until": "^1.7.1",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine-marbles": "^0.6.0",
    "jest": "^26.6.3",
    "jest-junit": "^8.0.0",
    "jest-preset-angular": "8.1.3",
    "jsonlint": "^1.6.3",
    "mockdate": "^2.0.5",
    "ngx-build-plus": "^10.1.1",
    "serve": "^11.3.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },

Dev machine OS and version, e.g.
11.2.3 (20D91)
iOS build issue:

Node JS version
12.13.1 x64
XCode version
Xcode 12.5

**Comment by wknd** [comment]
This is happening for the same reasons as https://github.com/dpa99c/cordova-plugin-firebasex/issues/628 .
Not much can be done until its properly fixed upstream. Unfortunately the workaround with podfiles mentioned there don't work because cordova generates all that for us.

My workaround to avoid building manually will probably be helpful for others until its properly fixed:
Add a cordova after_prepare [hook](https://cordova.apache.org/docs/en/10.x/guide/appdev/hooks/) in confix.xml which calls the following ruby script:
```
#!/usr/bin/env ruby
require 'xcodeproj'
project = Xcodeproj::Project.open("platforms/ios/My Project Name.xcodeproj")

=begin
This sets arm64 to the excluded arch for iphonesimulator for all build configurations
This is to work around some libraries not having arm64 simulator support yet (apple M1)
=end

project.build_configurations.each do |builds|
  builds.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] ||= 'arm64'
end
project.save()
```
The ruby script will make the required xcodeproj setting changes for you so your pipeline doesn't freak out.

**Comment by asanka-indrajith** [comment]
@wknd Thanks a lot for the work around. 
I had to do other things to work out this.

1) Add file read permission for hook file.
`chmod 755 hooks/ios-arch-issue.rb`

2) Use the cli version of this plugin
https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds
