### ISSUE TITLE
Absurd Load Times 

### ISSUE THREAD

**Issue by Sehlor** [dpa99c/cordova-plugin-firebasex#632]
Hello guys, appriciate the plugin.

When i installed this plugin to my Ionic 5 Project My app which usually took 3-5 seconds to load started loading like 20-25 seconds now.

On android, there is no problems but as soon as i build for ios, load times going crazy.

using ios@6.1.0 with cordova 9.0

**Comment by Re4ctor** [comment]
I think you mean compiling right?
Well, there are a lot of dependency so its normal that build time is long on iOS

**Comment by dpa99c** [comment]
The additional build time is due to satisfying the heavy dependency tree of the Firebase SDK and is a caveat of using this plugin.

**Comment by grumpygary** [comment]
He said LOAD TIME.  I like the plugin, but had to move away from it for the same reason.  If there were a way to only load what I will use, then I'm sure the load time would come way down.  If I have to load everything to just get push notification support, it's not worth it.

**Comment by peitschie** [comment]
I'm using the current version of the plugin in an app, and not seeing load times anywhere near the 20-25s reported here by the way.

We're only using this for the Firebase notification integration feature, but our app startup times are largely unaffected.

I'm running on native cordova, so perhaps it's an issue with ionic not running plugin installation hooks: https://capacitorjs.com/docs/plugins/cordova#variables-and-hooks

I notice there is some heavy lifting going on in https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/scripts/ios/helper.js#L212 for example... is it possible when running with cordova we get a leaner set of included packages or something?
