### ISSUE TITLE
main/java/org/apache/cordova/firebase/FirebasePlugin.java:873: error: cannot find symbol

### ISSUE THREAD

**Issue by arteugen** [dpa99c/cordova-plugin-firebasex#636]
- Cordova CLI version 
	- 10.0.0
- Cordova platform version
	- android 9.0.0
        -  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
-  com.ozexpert.devicemeta 0.0.2 "DeviceMeta"
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-android-notch 1.0.0 "AndroidNotch"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-app-name 1.0.7 "App Namer"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 13.0.0 "Google Firebase Plugin"
cordova-plugin-inappbrowser-wkwebview 1.0.7 "InAppBrowser (WKWebView)"
cordova-plugin-iroot 3.1.0 "iRoot"
cordova-plugin-secure-storage-echo 5.1.1 "SecureStorage"
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-wkwebview-engine 1.2.2 "Cordova WKWebView Engine"
cordova-plugin-wkwebview-file-xhr 3.0.0 "Cordova WKWebView File XHR Plugin"

Error Message while Build on Android Studio:

....../platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePlugin.java:873: error: cannot find symbol
                    bundle.putString(FirebaseAnalytics.Param.SCREEN_NAME, name);
                                                            ^
  symbol:   variable SCREEN_NAME
  location: class Param

**Comment by ishaiavrahami** [comment]
getting the same

**Comment by ishaiavrahami** [comment]
did you find a solution?

**Comment by arteugen** [comment]
Hi @ishaiavrahami,
i use now still the previous version of the plugin, because it works properly.  It is possible to do in config.xml

`<plugin name="cordova-plugin-firebasex" spec="12.1.0">
.
.
.
.
</plugin>`

**Comment by dpa99c** [comment]
This error can occur when you have an old version of the Firebase SDK Analytics component pinned in your `package.json` / `plugins/fetch.json`.
Remove `ANDROID_FIREBASE_ANALYTICS_VERSION` so it defaults to the plugin default or update the pinned version.

You can validate that this plugin builds correctly in your dev environment by building the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).
If you encounter this same error building the example project, please let me know (post full details) and I will investigate further.

**Comment by arteugen** [comment]
The answer from @dpa99c is correct and it helped me to solve the situation. The issue could be closed.

Thank you very much !
