### ISSUE TITLE
iOS - Inconsistency in FCM token

### ISSUE THREAD

**Issue by fgarcia5** [dpa99c/cordova-plugin-firebasex#637]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)
- [x] I confirm this is a suspected bug or issue that will affect other users
- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.
- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.
- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

The plugin works correctly but there is an inconsistency when generating the FCM token.

If I try to send a notification to the token generated by "window.FirebasePlugin.onTokenRefresh" the notification never arrives. 

If I send a notification to all iOS devices (from Firebase) these doesn't arrive.

Instead, if I take from the XCode console the token generated by
"didReceiveRegistrationToken" and I send the notification it arrives correctly. Also, the token generated by "window.FirebasePlugin.getToken" works.

Before updated the plugin to the v13.0.0, it was working correctly.

**Environment information**

- Cordova CLI version 
	- `cordova -v` 10.0.0
- Cordova platform version
	- `cordova platform ls`
Installed platforms:
  ios 6.2.0
Available platforms: 
  android ^9.0.0
  browser ^6.0.0
  electron ^1.0.0
  osx ^6.0.0
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-app-version 0.1.12 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-calendar 5.1.5 "Calendar"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-firebasex 13.0.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 6.0.3 "SocialSharing"
cordova.plugins.diagnostic 6.0.3 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
        
_Runtime issue_
- Device details
 - iPhone 5S (iOS 12.5.3)
  - iPhone 7 Plus (iOS 14.6)
	
_iOS build issue:_
- Node JS version
    - `node -v` v12.18.3
- XCode version: 12.4 (12D4e)

</details><br/><br/>

How can we fix that? 

Thank you for your great work!

**Comment by fgarcia5** [comment]
"onTokenRefresh" works well on v12.1.0

**Comment by mctdev-marius** [comment]
Same Here, on IOS the onTokenRefresh a strange formatted token.
If i send massive Cloud message for all i do get the notification but if i try and use the token got from onTokenRefresh it dose not work, if on the other hand i try the getToken token then all worked.

It all works grate on Android Device.

Plugin version 13.0.0

**Comment by cellicom** [comment]
Same Here.
Resolved using getToken instead onTokenRefresh, only for iOS.

**Comment by mctdev-marius** [comment]
this is not a solution. The IOS has to get the update Android did and use the new firebase apis. This way unregister token will work as well.
