### ISSUE TITLE
Android Build is Failing in Ionic

### ISSUE THREAD

**Issue by kartiksolanki** [dpa99c/cordova-plugin-firebasex#639]
I am trying to build an android build with analytics. I am using "cordova-plugin-firebasex": "^8.0.1" version and this is what I have in my package.json file:
"cordova-plugin-firebasex": {
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "false",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "false",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "false",
        "ANDROID_ICON_ACCENT": "#FF00FFFF",
        "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
        "ANDROID_PLAY_SERVICES_AUTH_VERSION": "17.0.0",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "17.2.1",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "20.0.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "19.0.3",
        "ANDROID_FIREBASE_PERF_VERSION": "19.0.1",
        "ANDROID_FIREBASE_AUTH_VERSION": "19.1.0",
        "ANDROID_CRASHLYTICS_VERSION": "2.10.1",
        "ANDROID_CRASHLYTICS_NDK_VERSION": "2.1.1"
      },

I was able to make a build until last month, but right now, when I am trying to make an Android build, it gives me error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-analytics-impl:[17.0.0].
     Required by:
         project :app > com.google.android.gms:play-services-tagmanager:17.0.0
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-tagmanager-api:[17.0.0].
     Required by:
         project :app > com.google.android.gms:play-services-tagmanager:17.0.0
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.firebase:firebase-iid:[20.0.0].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.0.0
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-base:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-sdk:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-impl:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-sdk:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
/Users/wearesas/Desktop/dragon-ridge-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preReleaseBuild'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-analytics-impl:[17.0.0].
     Required by:
         project :app > com.google.android.gms:play-services-tagmanager:17.0.0
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-analytics-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-tagmanager-api:[17.0.0].
     Required by:
         project :app > com.google.android.gms:play-services-tagmanager:17.0.0
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-tagmanager-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.firebase:firebase-iid:[20.0.0].
     Required by:
         project :app > com.google.firebase:firebase-messaging:20.0.0
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.firebase:firebase-iid.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-base:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-sdk:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-base.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-impl:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-sdk:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-impl.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
   > Could not resolve com.google.android.gms:play-services-measurement-sdk-api:[17.2.1].
     Required by:
         project :app > com.google.firebase:firebase-analytics:17.2.1 > com.google.android.gms:play-services-measurement-api:17.2.1
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext
      > Failed to list versions for com.google.android.gms:play-services-measurement-sdk-api.
         > java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext

Can you please help me understand what is going wrong? I was able to build iOS but not Android. Please help.

**Comment by dpa99c** [comment]
>  I am using "cordova-plugin-firebasex": "^8.0.1" version

This version is very old which is probably why it won't build. Update to the latest version and try again.

You can verify the plugin builds within a known working codebase using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex).

**Comment by kartiksolanki** [comment]
okay. Let me try updating the plugin to latest version and check back again.

**Comment by kartiksolanki** [comment]
I am trying to install @latest plugin and it gives me error:
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 1 Error output:
Cloning into '/var/folders/00/gbhvk_952c52kwltvjmmc5c40000gn/T/d20210712-10499-11z7yq4'...
     Note: switching to 'de3fab277733c301dc04bf22183800bff5941ff1'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
     Updating files: 100% (2600/2600), done.
    at ChildProcess.whenDone (/Users/wearesas/Desktop/dragon-ridge-app/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
pod: Command failed with exit code 1 Error output:
Cloning into '/var/folders/00/gbhvk_952c52kwltvjmmc5c40000gn/T/d20210712-10499-11z7yq4'...
     Note: switching to 'de3fab277733c301dc04bf22183800bff5941ff1'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false

**Comment by kartiksolanki** [comment]
It is also giving me this error :  java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$TLSContext

Any idea what causes this? I also updated the java as well
