### ISSUE TITLE
Notifications not displayed in foreground; ios 14.6; macOS 11.5; log displays successful message

### ISSUE THREAD

**Issue by plvaldes** [dpa99c/cordova-plugin-firebasex#641]
Hi, I'd really appreciate some ideas on how to tackle this issue. Not sure it is a bug from the plugin but I have no further ideas on how to get it working. Thank you very much in advance

# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)
- [X] I confirm this is a suspected bug or issue that will affect other users
- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.
- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.
- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
I am facing this issue after the plugin was upgraded from an old version where this was working.

The notifications are not displayed when the app is in the foreground (they do work in background). However if I debug I can see that the showForegroundNotification variable is correctly set to true. Also, the logs have the following lines:

`2021-07-20 10:24:53.774504+0200 AppName[8998:2047412] FirebasePlugin[native] LOG: Local Notification succeeded
2021-07-20 10:24:53.797278+0200 AppName[8998:2046633] FirebasePlugin[native]: Local Notification succeeded`

This log is the most surprising for me because apparently everything worked fine. There is no issue with the debugging of the plugin code (method `processMessageForForegroundNotification`) or any other error displayed in the logs.

I've checked that all the versions of the plugins are the same than in the test project. The only difference is that I am using version 13.0.0-cli because I run the build with `ionic cordova` command.

**Expected behavior:**
Notifications should work both in foreground and background

**Steps to reproduce:**
Nothing specific, just running the `ionic cordova build ios` and then running the app in a real device (iPad with ios 14.6) with xcode (12.5) 

**Environment information**
- Cordova CLI version 
	- `cordova -v` 10.0.0
- Cordova platform version
	- `cordova platform ls` ios 6.2.0
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
    - cordova-custom-config 5.1.0 "cordova-custom-config"
    - cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
    - cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
    - cordova-plugin-app-version 0.1.12 "AppVersion"
    - cordova-plugin-device 2.0.3 "Device"
    - cordova-plugin-dialogs 2.0.2 "Notification"
    - cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
    - cordova-plugin-firebasex 13.0.0-cli "Google Firebase Plugin"
    - cordova-plugin-hello-c 1.1.1 "Hello"
    - cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
    - cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
    - cordova-plugin-network-information 2.0.2 "Network Information"
    - cordova-plugin-safariviewcontroller 2.0.0 "SafariViewController"
    - cordova-plugin-splashscreen 5.0.4 "Splashscreen"
    - cordova-plugin-statusbar 2.4.3 "StatusBar"
    - cordova-plugin-whitelist 1.3.4 "Whitelist"
    - cordova-sqlite-storage 3.4.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
    - cordova.plugins.diagnostic 5.0.2 "Diagnostic"
    - ionic-plugin-deeplinks 1.0.22 "Ionic Deeplink Plugin"

- Dev machine OS and version
    - macOs 11.4
        
_Runtime issue_
- Device details
    - iPad
- OS details
    - iOS 14.6	
	
_iOS build issue:_
- Node JS version
    - `node -v`12.16.1
- XCode version 12.5.1

**Console output**
<details>
<summary>console output</summary>

```
2021-07-20 11:19:31.575088+0200 collaPP Pro[8998:2046633] FirebasePlugin[native]: didReceiveRemoteNotification: {    aps =     {        alert =         {            body = "xxxxx";            title = "xxxxxx";        };        sound = default;    };    "gcm.message_id" = 111111111111;    "google.c.a.e" = 1;    "google.c.sender.id" = 111111111111;    messageType = notification;    "notification_foreground" = true;    }
2021-07-20 11:19:31.622566+0200 collaPP Pro[8998:2056872] FirebasePlugin[native] LOG: Local Notification succeeded
2021-07-20 11:19:31.626354+0200 collaPP Pro[8998:2046633] FirebasePlugin[native]: Local Notification succeeded

```

(111111111111 is not the real value)
</details><br/><br/>

**Comment by spoxies** [comment]
Not sure if this is the solution for you, but I looked at my own code and a younger version of me commented to pass "true" as a `string` and not a `boolean`. 

```
notification_foreground: "true", // (not bool) also show when in foreground
```

**Comment by plvaldes** [comment]
@spoxies yes, I'm passing the "true" as a string from my backend according to the plugin documentation (I forgot to say that the **foreground notifications do work on Android**). I looked at the code of the plugin and I think that there is some cast to boolean, but don't know much about the native ios code

**Comment by dpa99c** [comment]
@plvaldes I've regression tested `cordova-plugin-firebasex@13.0.0` on iOS 14.7 using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and foreground notifications are displayed correctly. 

Please confirm that if you build and run the example project and send one of the test messages using the [built-in messaging client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) whether the foreground notification appears as expected; for example:

    npm run-script send -- --token="<your_device_token>" --message=notification.json

**Comment by plvaldes** [comment]
Hi @dpa99c thanks for your support. I'd already tested the test project (with my own backend and my app's bundle id, as the device token is the same, I sent to the test app the same notification that I send to my app and it was correctly displayed).

What's most surprising to me is that I debugged and went through the success case of this plugin code:

`UNNotificationRequest *request = [UNNotificationRequest requestWithIdentifier:@"local_notification" content:objNotificationContent trigger:trigger];
                [[UNUserNotificationCenter currentNotificationCenter] addNotificationRequest:request withCompletionHandler:^(NSError * _Nullable error) {
                    if (!error) {
                        [FirebasePlugin.firebasePlugin _logMessage:@"Local Notification succeeded"];
                    } else {
                        [FirebasePlugin.firebasePlugin _logError:[NSString stringWithFormat:@"Local Notification failed: %@", error.description]];
                    }
                }];`

Could it be caused by the -cli version? I don't see any other difference between the test app and mine, unless there's some other plugin of my plugin list causing some incompatibility.

**Comment by plvaldes** [comment]
Hey @dpa99c  mystery solved and found out "accidentally". Mi iPad was plugged to the laptop during the tests so I could debug and see the logs. Once it was unplugged the notifications started to be displayed even when the app was in the foreground. I don't know if this was expected behavior of the debugger, I have no idea, but it is working now. Thanks for the support
