### ISSUE TITLE
getToken not work

### ISSUE THREAD

**Issue by iPwa97** [dpa99c/cordova-plugin-firebasex#647]
Hello,

i use this plugin on ionic3 with cordova 10.0(API 29) with the JS API.
since i updated the plugin to the latest version the plugin dont work well. 

i try to get a token: 

`(<any>window).FirebasePlugin.getToken(token => {
            console.log(token);
          }).catch(err => {
            console.log(err);
          });`

when i run this snippen i receive this error:

`cordova.js:314 Uncaught TypeError: Cannot read property 'catch' of undefined
    at main.js:1474
    at firebase.js:6
    at Object.callbackFromNative (cordova.js:295)
    at <anonymous>:1:9`

**Comment by dpa99c** [comment]
You are directly invoking the plugin Javascript API (`(<any>window).FirebasePlugin`) and expecting it to return a Promise which it does not. 
Either use the [Ionic Typescript wrapper](https://ionicframework.com/docs/native/firebase-x) for this plugin or update your call to use the correct Javascript function signature:

	(<any>window).FirebasePlugin.getToken(token => { console.log(token); }, err => { console.log(err); });
