### ISSUE TITLE
Submit to ionic to link

### ISSUE THREAD

**Issue by matejkramny** [dpa99c/cordova-plugin-firebasex#65]
Hi Dave, it seems this repo is more up to date than any other firebase plugins..

It might be good if you contact the ionic team since they link to a very outdated repository.

https://ionicframework.com/docs/native/firebase/

Cheers!

**Comment by dpa99c** [comment]
This is already a [PR](https://github.com/ionic-team/ionic-native/pull/3106) to add support for this plugin to Ionic Native
