### ISSUE TITLE
Update Query Operators for Firebase

### ISSUE THREAD

**Issue by codexsysin** [dpa99c/cordova-plugin-firebasex#651]
# Feature request

According to the firebase documentation, the query operators available are
< less than
<= less than or equal to
== equal to
> greater than
>= greater than or equal to
!= not equal to
array-contains
array-contains-any
in
not-in

Kindly add these operators to the upcoming version of the cordova plugin to extend the firebase query operation.

https://firebase.google.com/docs/firestore/query-data/queries

**Comment by dpa99c** [comment]
Most of these operators are already supported - see [`fetchFirestoreCollection()`](https://github.com/dpa99c/cordova-plugin-firebasex#fetchfirestorecollection)

**Comment by codexsysin** [comment]
If you could add support for 

!= not equal to
array-contains
array-contains-any
in
not-in

it might solve complex problems.

**Comment by codexsysin** [comment]
And also is there any way to use listenToFirestoreCollection in ionic 5? Current ngx library doesn't include this class

**Comment by dpa99c** [comment]
> And also is there any way to use listenToFirestoreCollection in ionic 5? Current ngx library doesn't include this class

You can invoke the plugin's JS API directly, e.g.:

```javascript
const collection = "my_collection";
const filters = [
    ['where', 'field', '==', 'value'],
    ['orderBy', 'field', 'desc']
];
const includeMetadata = true;

(<any>window).FirebasePlugin.listenToFirestoreCollection(event => {
    switch(event.eventType){
        case "id":
            console.log("Successfully added collection listener with id="+event.id);
            break;
        case "change":
            console.log("Detected collection change");
            if(event.documents){
                for(var documentId in event.documents){
                    console.log("Document ID: " + documentId);

                    const docChange = event.documents[documentId];
                    console.log("Source of change: " + docChange.source);
                    console.log("Change type: " + docChange.type);
                    console.log("Read from local cache: " + docChange.fromCache);
                    if(docChange.snapshot){
                        console.log("Document snapshot: " + JSON.stringify(docChange.snapshot));
                    }
                }
            }
            break;
    }
}, error => {
    console.error("Error adding listener: "+error);
}, collection, filters, includeMetadata);
```

**Comment by codexsysin** [comment]
Thank you for the immediate response :) Any other ways to tweak the node package?

**Comment by dpa99c** [comment]
The [FirebaseX](https://ionicframework.com/docs/native/firebase-x) Typescript wrapper for this plugin is owned/maintained by Ionic as part of [Ionic Native](https://github.com/ionic-team/ionic-native/). If their Typescript API is missing some of the JS plugin API methods provided by this plugin, I suggest opening an issue against Ionic Native requesting they be added.

**Comment by codexsysin** [comment]
Thank you so much :)
