### ISSUE TITLE
Cordova 8 support

### ISSUE THREAD

**Issue by iouhammi** [dpa99c/cordova-plugin-firebasex#66]
Hello there,

Does this plugin support cordova version 8? especially for previous versions of this plugin (<=5).

The latest version of this plugin mentions that supported version of cordova is >= 9. 
But when I switch tags to previous versions it says cordova >= 8.

Since I am using cordova 8.1.2 (cordova-lib 8.1.1), I tried installing previous version of this plugin

`ionic cordova plugin add cordova-plugin-firebasex@5.0.0`

But it says:

> Installing "cordova-plugin-firebasex" for android
> 
> Plugin doesn't support this project's cordova version. cordova: 8.1.1, failed version requirement: >=9
> 
> Skipping 'cordova-plugin-firebasex' for android
> 
> Adding cordova-plugin-firebasex to package.json
> 
> Saved plugin info for "cordova-plugin-firebasex" to config.xml
> 

Please how Can I integrate this plugin with cordova 8?

**Comment by dpa99c** [comment]
This plugin requires `cordova>=9` and `cordova-ios>=5` for implicit support for Cocoapods to satisfy the Firebase SDK dependencies for iOS. So there is no intention to support `cordova@8` / `cordova-ios@4`. If you wish to use this plugin you'll need to update to the latest versions.

Alternatively you can use another plugin such as [cordova-plugin-firebase-lib@4](https://github.com/wizpanda/cordova-plugin-firebase-lib/tree/v4.1.0) which supports `cordova@8`

**Comment by Roman8817** [comment]
Hello.
