### ISSUE TITLE
How to use FirebasePlugin.verifyPhoneNumber without reCAPTCHA verification 

### ISSUE THREAD

**Issue by hathemi** [dpa99c/cordova-plugin-firebasex#661]
i’am using ionic V3. i have installed / cordova-plugin-firebase to send verificationPhone number.
here’s the code

```
window.FirebasePlugin.verifyPhoneNumber(number, timeOutDuration, function(credential) {
console.log(credential);

// ask user to input verificationCode:
var code = inputField.value.toString();

var verificationId = credential.verificationId;

var signInCredential = firebase.auth.PhoneAuthProvider.credential(verificationId, code);
firebase.auth().signInWithCredential(signInCredential);
}, function(error) {
console.error(error);
});

```
when i call FirebasePlugin.verifyPhoneNumbe, Firebase Authentication uses a reCAPTCHA verification to complete the phone sign-in flow.
is there a way to avoid reCAPTCHA verification in Firebase authentication ?
here’s my gradle.properties

Project target.

> target=android-29
> 
> android.library.reference.1=CordovaLib
> 
> android.library.reference.2=app
> 
> cordova.gradle.include.1=cordova-plugin-android-native-pdfviewer/essyndic-AndroidNativePDFViewer.gradle
> 
> cordova.gradle.include.2=cordova-plugin-badge/essyndic-badge.gradle
> 
> cordova.system.library.1=androidx.legacy:legacy-support-v4:1.0.0
> 
> cordova.system.library.2=androidx.legacy:legacy-support-v4:1.0.0
> 
> cordova.system.library.3=androidx.legacy:legacy-support-v4:1.0.0
> 
> cordova.gradle.include.3=cordova-plugin-firebase/ess-build.gradle
> 
> cordova.system.library.4=com.google.gms:google-services:+
> 
> cordova.system.library.5=com.google.firebase:firebase-core:16.0.8
> 
> cordova.system.library.7=com.google.firebase:firebase-crash:16.+
> 
> cordova.system.library.8=com.google.firebase:firebase-config:16.4.1
> 
> cordova.system.library.9=com.google.firebase:firebase-analytics:19.0.+
> 
> cordova.system.library.10=com.google.firebase:firebase-auth:21.0.+
> 
> cordova.system.library.11=com.google.firebase:firebase-messaging:21.1.0
> 
> cordova.system.library.12=androidx.core:core:1.6.+
> 
> cordova.system.library.13=me.leolin:ShortcutBadger:1.1.22@aar
> 
> cordova.system.library.14=androidx.annotation:annotation:1.1.0
> 
> cordova.system.library.15=androidx.legacy:legacy-support-v4:1.0.0
> 
> cordova.gradle.include.6=phonegap-plugin-multidex/ess-multidex.gradle
> 
> cordova.system.library.16=com.squareup.okhttp3:okhttp:3.12.0

any suggestion please ?

**Comment by bipoza** [comment]
@hathemi
Have you fixed it?
If so, could you tell us what options you have tried? I'm having the same problem.

Thanks!

**Comment by hathemi** [comment]
frist you need to enable safetyNet in firebase 
Go to **Firebase console** -->to your project-->project overview settings-->project settings --> App check -->overview (Register your app for SafetyNet).
![image](https://user-images.githubusercontent.com/23275040/161849914-c0103872-343d-4f16-809f-f106f01c4719.png)

-- add SHA-256 and  SHA-1 fingerprint certificate to your project in firebase 
-- enable "Android ddevice verificationb" to your project 

Then you must update your google-services.json file in your project
this definetly solve it
hope it help!

**Comment by bipoza** [comment]
Wow! This option is new in Firebase.
Thank you very much for your answer. This has saved me ;)
