### ISSUE TITLE
Android: getCurrentUser() sometimes return java.lang.IllegalStateException: Task is not yet complete

### ISSUE THREAD

**Issue by yoldar** [dpa99c/cordova-plugin-firebasex#662]
I'm using Firebase v13.0.1. Crashlytics shows that this issue "java.lang.IllegalStateException: Task is not yet complete" has 3007 non-fatal events affecting 1696 users for last 24 hours. 

<img width="1209" alt="Screen Shot 2021-09-11 at 20 49 06" src="https://user-images.githubusercontent.com/1597578/132951776-77d0be97-d465-44f7-b044-5a06963b22a3.png">

If we look at the code at org.apache.cordova.firebase.FirebasePlugin.extractAndReturnUserInfo(FirebasePlugin.java:1193) we can see that providerId is taken from getIdToken() method without addOnSuccessListener

<img width="915" alt="Screen Shot 2021-09-11 at 20 46 09" src="https://user-images.githubusercontent.com/1597578/132951699-3bf9263b-acb7-47db-a16d-29c9aeb0814e.png">

I modified code to get providerId in addOnSuccessListener

<img width="826" alt="Screen Shot 2021-09-11 at 20 51 30" src="https://user-images.githubusercontent.com/1597578/132951854-ad9c33e7-c307-4c3c-80ca-6c8038f9eb86.png">

Now I'm waiting if this modification will give any positive result. My question is why calling user.getIdToken(false).getResult().getSignInProvider() throughs java.lang.IllegalStateException: Task is not yet complete?

**Comment by mamillastre** [comment]
Same issue for me (v12.1.0).
It seems that the error occur when Firebase is refreshing an expired token. Because I have this exception each time I launch my app after a few hours and it works fine for the next getCurrentUser() calls.
I will try your fix.
Thank you.

**Comment by yoldar** [comment]
Fixed

**Comment by heihitesh** [comment]
Hei, Wht is the fix ? 
Thank You
