### ISSUE TITLE
Android: Support html attributes in body notifications

### ISSUE THREAD

**Issue by ollm** [dpa99c/cordova-plugin-firebasex#666]
# Feature request

I'm migrating from `phonegap-plugin-push` and something I miss in this plugin is being able to put certain words in bold format in notifications body.

https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/FCMService.java
https://stackoverflow.com/questions/45593710/how-to-bold-text-in-a-notification

**Example:**

``` json
{
  "name": "my_notification",
  "notification": {
    "body": "Tomorrow it will be <b>28º</b>",
    "title": "Weather in Barcelona"
  },
  "data": {
    "notification_body": "Tomorrow it will be <b>28º</b>",
    "notification_title": "Weather in Barcelona"
  }
}
```
![Screenshot_1633344648](https://user-images.githubusercontent.com/18549191/135839147-8dd79cfa-1bcd-4573-bc59-f28498ebe3a3.png)

**Comment by dpa99c** [comment]
Resolved by https://github.com/dpa99c/cordova-plugin-firebasex/pull/668 which will be included in next release.
