### ISSUE TITLE
Android: Multiple notifications dismissed when clicking on one when application is closed

### ISSUE THREAD

**Issue by adammaus** [dpa99c/cordova-plugin-firebasex#674]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)
- [x] I confirm this is a suspected bug or issue that will affect other users
- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.
- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.
- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

We ran into an issue with multiple notifications being dismissed if you click on one on Android after 8.0. This particular issue happens when you receive two or more notifications when the app is completely closed. This seems to happen whether you provide a channel or not.

**Expected behavior:**

We would expect each notification to remain in the system tray until it is clicked on or dismissed.

**Steps to reproduce:**

1. Send yourself two Firebase notifications while the app is completely closed.
2. Click on one of the notifications. The other notification will disappear.

**Environment information**

- Cordova CLI version 
	- 10.0.0
- Cordova platform version
	- android 10.1.1
- Plugins & versions installed in project (including this plugin)
    - com-badrit-base64 0.2.0 "Base64"
com.lampa.startapp 6.1.6 "startApp"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-open-native-settings 1.5.5 "Native settings"
cordova-plugin-advanced-http 2.5.1 "Advanced HTTP plugin"
cordova-plugin-android-permissions 1.1.2 "Permissions"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.12 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-calllog 1.2.2 "CALLLOG"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-chooser 1.3.1 "Chooser"
cordova-plugin-customurlscheme 5.0.2 "Custom URL scheme"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file-opener2 3.0.5 "File Opener2"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 7.0.2 "Google Firebase Plugin" This is an older version of the plugin but the current code looks affected.
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.3 "LocalNotification"
cordova-plugin-media-capture 3.0.3 "Capture"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-streaming-media 2.3.0 "StreamingMedia"
cordova-plugin-whitelist 1.3.5 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-sqlite-storage 6.0.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 6.1.0 "Diagnostic"

- Dev machine OS and version, e.g.
    - OSX
        - ProductName:	macOS
        - ProductVersion:	11.6
        - BuildVersion:	20G165
                
_Runtime issue_
- Device details
    - Samsung Galaxy S10e
- OS details
    - Android 11.0

**Related code:**
In the [code](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L1931-L1933), it seems to involve FirebasePlugin.java->createChannel(final JSONObject options) where deleteChannel is called. It seems to work correctly when we comment out the deleteChannel line.

Perhaps when the existing channel is deleted it removes any previous notifications that were in that channel. Is it possible to check that a channel doesn't have any notifications before deleting / recreating the channel?

Could also possibly be related to this [comment](https://github.com/dpa99c/cordova-plugin-firebasex/issues/272#issuecomment-862832998).

**Thank you for the help and providing this plugin!**

**Comment by renemadsen** [comment]
Any news on this one getting fixed?
It's still the same issue and it's pissing users off that it does not work.

**Comment by dpa99c** [comment]
> when the app is completely closed.

when the app is completely closed, no app or plugin code is executed - the behaviour is entirely part of the Android operating system and neither this plugin or the app containing it can influence that behaviour.

**Comment by renemadsen** [comment]
> > when the app is completely closed.
> 
> when the app is completely closed, no app or plugin code is executed - the behaviour is entirely part of the Android operating system and neither this plugin or the app containing it can influence that behaviour.

What is meant by completely closed app for my situation is:
The app is closed and upon opening all notifications are cleared. And the hack is to change the java code to not create a default channel upon opening the app. 

So for me the code is still broken and issue is still open.

**Comment by adammaus** [comment]
Thank you for looking at this issue @dpa99c! 

I agree with @renemadsen that there still appears to be a problem. Most of the Android apps that I have used, they allow you to click on each one individually without losing all of the other notifications. For example when you receive text messages from multiple people.

This [pull request on a fork](https://github.com/adammaus/cordova-plugin-firebasex/pull/1/files) is an example of how the code could change. It seems to work but could benefit from others looking it over. I appreciate your help!

**Comment by Dudix** [comment]
Disappearing notifications when you launch an app or one of the notifications is a serious problem and requires fixing. The solution seems to be simple: 
https://github.com/dpa99c/cordova-plugin-firebasex/compare/master...Dudix:cordova-plugin-firebasex:patch-1
