### ISSUE TITLE
Update cordova-android@10.1.0

### ISSUE THREAD

**Issue by EMI-INDO** [dpa99c/cordova-plugin-firebasex#675]
Please update cordova-android@10.1.0

### error

Error: Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=~~/androidSDK (recommended setting)
ANDROID_HOME=~~/androidSDK (DEPRECATED)
Using Android SDK: ~~/androidSDK
The project name 'c3 analyic' contains at least one of the following characters: [ , /, \, :, <, >, ", ?, *, |]. This has been deprecated and is scheduled to be removed in Gradle 5.0. Set the 'rootProject.name' or adjust the 'include' statement (see https:/~~/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[]) for more details).
at cdv_gradle_name_1e2qmhbaxkp9i5v247lwsd3uk.run(~~/cdv-gradle-name.gradle:2)
(Run with --stacktrace to get the full stack trace of this deprecation warning.)
:wrapper

BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
Adding classpath: com.google.gms:google-services:4.3.8

> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:javaPreCompileDebug
> Task :app:generateDebugResValues
> Task :app:generateDebugResources
> Task :app:processDebugGoogleServices
> Task :CordovaLib:writeDebugAarMetadata
> Task :CordovaLib:compileDebugRenderscript
> Task :CordovaLib:generateDebugResValues
> Task :CordovaLib:generateDebugResources
> Task :app:checkDebugAarMetadata
> Task :CordovaLib:packageDebugResources
> Task :app:injectCrashlyticsMappingFileIdDebug FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https:/~~/command_line_interface.html#sec:command_line_warnings
10 actionable tasks: 10 executed

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:injectCrashlyticsMappingFileIdDebug' (type 'InjectMappingFileIdTask').
- In plugin 'com.google.firebase.crashlytics.buildtools.gradle.CrashlyticsPlugin' type 'com.google.firebase.crashlytics.buildtools.gradle.tasks.InjectMappingFileIdTask' field 'resourceFile' without corresponding getter has been annotated with @OutputFile.

Reason: Annotations on fields are only used if there's a corresponding getter for the field.

Possible solutions:
1. Add a getter for field 'resourceFile'.
2. Remove the annotations on 'resourceFile'.

Please refer to https:/~~/validation_problems.html#ignored_annotations_on_field for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https:/~~/help.gradle.org

BUILD FAILED in 2s
Command failed with exit code 1: ~~/gradlew cdvBuildDebug -b ~~/build.gradle

**Comment by nbadiganti** [comment]
I faced the same issue. In case if you're using cordova-plugin-androidx plugin, please remove it and try to build again. It worked for me. 
https://www.npmjs.com/package/cordova-plugin-androidx

**Comment by nbadiganti** [comment]
I was able to build android@10.1.0 with firebasex plugin installed. 
I have removed **cordova-android-support-gradle-release** and **cordova-plugin-androidx** to make it work. 
https://www.npmjs.com/package/cordova-android-support-gradle-release 

These info might help you, 
Ionic:

   Ionic CLI                     : 6.17.1 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.6.9
   @angular-devkit/build-angular : 0.1102.14
   @angular-devkit/schematics    : 11.2.14
   @angular/cli                  : 11.2.14
   @ionic/angular-toolkit        : 3.1.1

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : android 10.1.0, ios 6.2.0

**Comment by Tarekajaj** [comment]
in my case, I faced the same error after upgrading and old project to cordova-android@10.1.2 from 8.1.0
Updating the plugin did not solve the issue, what did was removing the plugin  **cordova-support-google-services** which was previously installed.
Hope it helps someone.
