### ISSUE TITLE
Build error with MacOS Monterey: building for iOS Simulator, but linking in object file built for iOS 

### ISSUE THREAD

**Issue by jpduckwo** [dpa99c/cordova-plugin-firebasex#678]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

I have a new laptop which came with macOS Monterey, when I checkout the cordova-plugin-firebasex-test project and try and run ios it fails to build with the follow message. I have tried with system Ruby an cocoapods and also brew based Ruby and cocoapods all result in the same issue. I suspect something is changed with the latest xcode simulator that stops it from working.

We get the same issue for our own project.

```
ld: in /Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn(GIDEMMErrorHandler_3a47e13d8ca81b41e9cdb7ef5468004a.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/Pods/GoogleSignIn/Frameworks/GoogleSignIn.framework/GoogleSignIn' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

[buildlog.txt](https://github.com/dpa99c/cordova-plugin-firebasex/files/7438141/buildlog.txt)

**Expected behavior:**
It compiles

**Steps to reproduce:**
From macOS Monterey with Xcode Version 13.1 (13A1030d) follow the instructions from the test project

**Screenshots**
NA

**Environment information**

- Cordova CLI version 
	- `10.0.0 (cordova-lib@10.1.0)`
- Cordova platform version
	- `Installed platforms:
```
  ios 6.2.0
Available platforms:
  android ^9.1.0
  browser ^6.0.0
  electron ^1.1.1
  osx ^6.0.0`
```
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
```
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 1.3.2-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 13.0.1 "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
```
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
```
ProductName:	macOS
ProductVersion:	12.0.1
BuildVersion:	21A559
```

_iOS build issue:_
- Node JS version
    - `v14.18.1`
- XCode version
`Xcode Version 13.1 (13A1030d)`

**Related code:**
NA

**Console output**
<details>
<summary>console output</summary>

```
See attached buildoutput.txt
```

</details><br/><br/>

**Other information:**
NA

**Comment by Husnain-Asharf** [comment]
Hi,
can you check this link if it fix your issue.
https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-an-object-file-built-for-io

**Comment by jpduckwo** [comment]
Hi, I tried adding as follows:

![image](https://user-images.githubusercontent.com/13150911/139561525-fb8cdb0f-cf90-4d6d-9c6e-95ff95cd2ef5.png)


I then get this error - I also tried removing and adding the plugin again

```
While building module 'Firebase' imported from /Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:3:
In file included from <module-includes>:1:
/Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/Pods/Headers/Public/Firebase/Firebase.h:15:9: fatal error:
      'FirebaseCore/FirebaseCore.h' file not found
#import <FirebaseCore/FirebaseCore.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from /Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m:2:
/Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-firebasex/FirebasePlugin.h:3:9: fatal error:
      could not build module 'Firebase'
#import "Firebase.h"
 ~~~~~~~^~~~~~~~~~~~
2 errors generated.

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/joel/Library/Developer/Xcode/DerivedData/FirebaseTest-esmrizpgqdrwkzdlcrdvatmslkcd/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/FirebasePlugin.o /Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseTest' from project 'FirebaseTest')
	CompileC /Users/joel/Library/Developer/Xcode/DerivedData/FirebaseTest-esmrizpgqdrwkzdlcrdvatmslkcd/Build/Intermediates.noindex/FirebaseTest.build/Debug-iphonesimulator/FirebaseTest.build/Objects-normal/x86_64/AppDelegate+FirebasePlugin.o /Users/joel/dev/cordova-plugin-firebasex-test/platforms/ios/FirebaseTest/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'FirebaseTest' from project 'FirebaseTest')
(2 failures)
xcodebuild: Command failed with exit code 65

```

**Comment by Husnain-Asharf** [comment]
Please try following steps:
- Try remove the Podfile.lock file and Pods folder.
- Run pod install.
- Try to build  for a real device

**Comment by jpduckwo** [comment]
Hey Husnain, I can successfully run the Archive for 'Any iOS Device' even without excluding the architectures. So I guess the problem is only with simulators. As soon as I switch back to a simulator I get the Firebase header compile issue.

**Comment by Husnain-Asharf** [comment]
You tried following steps ?
- Quit Xcode.
- Delete project's temp files located at ~/Library/Developer/Xcode/DerivedData
- Delete ProjectName.xcworkspace
- Delete Podfile.lock file and Pods folder
- Run pod repo update
- Run pod install.
- Open the newly created ProjectName.xcworkspace file and build.

**Comment by jpduckwo** [comment]
Hey, I have tried all those step and I still get the header compile issue when trying to run on the simulator. Thanks for suggesting though. As a work around I'm testing directly to my phone rather than the simulator.

**Comment by darshitmaniar** [comment]
> Hey Husnain, I can successfully run the Archive for 'Any iOS Device' even without excluding the architectures. So I guess the problem is only with simulators. As soon as I switch back to a simulator I get the Firebase header compile issue.

Yes, I am facing the same issue with simulators.

**Comment by fabltd** [comment]
Also facing the issue.

Its seems the issue is with Google Sign in. Verison 5.0.2 is being bundled and that doesn't support M1. Google have updated to 'GoogleSignIn', '6.0.2' this does support M1.  Investigating if this fixes the simulator issue.

**Comment by mafeifan** [comment]
same issue +1

**Comment by mafeifan** [comment]
@fabltd  the latest version of GoogleSignIn is 6.1.0  have you testing it?
https://cocoapods.org/pods/GoogleSignIn#changelog

**Comment by moJiXiang** [comment]
@fabltd Same issue, did you fix it?

**Comment by jpike88** [comment]
GoogleSignIn 6.x is able to be built for simulator + m1 chip. However, a bit of code in this lib will need to be updated to use it. If nobody else will, I'll submit a PR within the next week. @dpa99c are you able to review/merge it?
![Screen Shot 2022-01-19 at 20 04 25](https://user-images.githubusercontent.com/9585787/150136207-0aa5a31a-1f9c-4e46-8b56-b57847591c5c.png)

**Comment by studioromeo** [comment]
Hey folks. I saw this was included in 14.x.x of the plugin but still having this issue. 

`Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o), building for iOS Simulator, but linking in object file built for iOS`

Did anyone else have this and get around it?

**Comment by JustDoItSascha** [comment]
I have the same error with 14.0.0

**Comment by rkssaravanan12** [comment]
I have the same error with 14.0.0

**Comment by jpduckwo** [comment]
Hi @dpa99c is it possible to please re-open?

Same issue on 14.0.0 for me, unless there is a change I need to make for the pinned versions?

```
in xxx/cmj.pm.cordova-testupgrade/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o), building for iOS Simulator, but linking in object file built for iOS, file 'xxx/cmj.pm.cordova-testupgrade/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' for architecture arm64`
```

```
      "cordova-plugin-firebasex": {
        "IOS_STRIP_DEBUG": "true",
        "FIREBASE_ANALYTICS_COLLECTION_ENABLED": "false",
        "FIREBASE_PERFORMANCE_COLLECTION_ENABLED": "false",
        "FIREBASE_CRASHLYTICS_COLLECTION_ENABLED": "false",
        "ANDROID_ICON_ACCENT": "#FF00FFFF",
        "ANDROID_FIREBASE_PERFORMANCE_MONITORING": "false",
        "ANDROID_PLAY_SERVICES_TAGMANAGER_VERSION": "17.0.0",
        "ANDROID_PLAY_SERVICES_AUTH_VERSION": "19.0.0",
        "ANDROID_FIREBASE_ANALYTICS_VERSION": "19.0.0",
        "ANDROID_FIREBASE_MESSAGING_VERSION": "22.0.0",
        "ANDROID_FIREBASE_CONFIG_VERSION": "21.0.0",
        "ANDROID_FIREBASE_PERF_VERSION": "20.0.2",
        "ANDROID_FIREBASE_AUTH_VERSION": "21.0.1",
        "ANDROID_FIREBASE_INAPPMESSAGING_VERSION": "20.0.0",
        "ANDROID_FIREBASE_FIRESTORE_VERSION": "23.0.2",
        "ANDROID_FIREBASE_FUNCTIONS_VERSION": "20.0.0",
        "ANDROID_FIREBASE_IID_VERSION": "21.1.0",
        "ANDROID_FIREBASE_INSTALLATIONS_VERSION": "17.0.0",
        "ANDROID_FIREBASE_CRASHLYTICS_VERSION": "18.1.0",
        "ANDROID_FIREBASE_CRASHLYTICS_NDK_VERSION": "18.1.0",
        "ANDROID_GSON_VERSION": "2.8.7",
        "ANDROID_FIREBASE_PERF_GRADLE_PLUGIN_VERSION": "1.4.0",
        "ANDROID_GRPC_OKHTTP": "1.32.2"
      },
```

**Comment by jpike88** [comment]
I didn't have this issue on updating, works fine here. for those still with it pls ensure you flush caches, and re-initialise/rebuild your Cordova project

**Comment by mleech** [comment]
I'm also getting this issue. I'm on version '14.0.0-cli' running on an M1 Mac with Big Sur.

in xxx/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o), building for iOS Simulator, but linking in object file built for iOS, file 'xxx/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' for architecture arm64

I followed your advice @jpike88 and cleared the pod cache, deleted `node_modules/`, `plugins/`, and `platforms/` and re-ran `npm install` and re-added the platforms, but am still getting the same issue.

**Comment by jpike88** [comment]
Ok just realised the fix was for googlesignin, not googlesymbolutilities. Are you using another plugin that may be pulling that in?

**Comment by mleech** [comment]
I'm assuming it's FirebaseX that's pulling it in - I see a couple of people commenting above that also have the same error relating to GoogleSymbolUtilities

**Comment by jpduckwo** [comment]
My plugins are 
```
      "cordova-plugin-statusbar": {},
      "cordova-universal-links-plugin": {},
      "cordova-plugin-device": {},
      "cordova-plugin-nativestorage": {},
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-firebasex": {
...
      },
      "cordova-plugin-whitelist": {}
```

**Comment by studioromeo** [comment]
Not sure if this helps but I created a blank example repo of the issue https://github.com/studioromeo/cordova-firebase-example. It's a fresh cordova ios project with the firebase plugin installed.

Would be interested to hear if you folks find this works / does not work for you

**Comment by jpduckwo** [comment]
Hi @studioromeo, I gave the blank repo a try and got the following error on build:

> ld: in .../cordova-firebase-example/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o), building for iOS Simulator, but linking in object file built for iOS, file '.../cordova-firebase-example/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by villeraikko** [comment]
I'm also still experiencing this problem with version 14.0.0 with M1 processor when building for iOS simulator.

> ld: in /Users/***/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities(overload.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/***/platforms/ios/Pods/GoogleSymbolUtilities/Frameworks/frameworks/GoogleSymbolUtilities.framework/GoogleSymbolUtilities' for architecture arm64

**Comment by stanislavworkacc** [comment]
You can launch XCODE with Rosseta2. It works for me!!
