### ISSUE TITLE
Firebase Analytics receive the events only after app is uninstalled from the device.

### ISSUE THREAD

**Issue by alexbleggi** [dpa99c/cordova-plugin-firebasex#68]
Hi guys ...

After installing the plugin and configuring it successfully in an ionic 4 project, I'm able to successfully register standard events to the firebase panel but when using the logEvent() method the events are only captured after the application is uninstalled from the device. Any one with the same issue?

Thanks!

**Comment by dpa99c** [comment]
Processing of Firebase events is handled by the Firebase SDK (this plugin merely wraps and calls the Firebase SDK so it has no influence over this) and so the delay in events appearing in the Firebase Console is down to the behaviour of Firebase not this plugin.

**Comment by ndinhphi** [comment]
I have same issue

**Comment by Mariussu** [comment]
+1
