### ISSUE TITLE
Android firebasex logevent not logging

### ISSUE THREAD

**Issue by yuanzuo** [dpa99c/cordova-plugin-firebasex#71]
This happens in Android. I tested with the following code. Nothing show up in Firebase console. 

window.FirebasePlugin.logEvent("this is a test event", ""); 

>cordova plugin ls
com.cmackay.plugins.googleanalytics 0.1.22 "GoogleAnalytics"
com.phonegap.plugins.fileopener 1.0.0 "File Opener"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-contacts 2.0.1 "Contacts"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-dialogs 1.2.0 "Notification"
cordova-plugin-firebasex 6.0.2 "Google Firebase Plugin"
cordova-plugin-geolocation 2.4.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-splashscreen 3.1.0 "Splashscreen"
cordova-plugin-statusbar 2.1.2 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
org.apache.cordova.file 1.3.3 "File"
org.apache.cordova.file-transfer 0.5.0 "File Transfer"

**Comment by yuanzuo** [comment]
This issue can be closed. It looks logging event shows up on firebase console  AFTER application is uninstalled from the device.

**Comment by benskarunya** [comment]
Hi, i am facing the same issue. Event log working good in iOS but in Android it is not logging in the console. FYI, Android screenview working good.

**Comment by austinhutchison** [comment]
FYI I got this error in the Xcode console
`Event name must contain only letters, numbers, or underscores`

Doesn't explain why it was working for you in iOS - but I had this issue and wanted to share it. I'm not sure where the docs say `(must be serializable)` is explicit enough
