### ISSUE TITLE
TypeScript reports FirebasePlugin object isn't defined

### ISSUE THREAD

**Issue by peitschie** [dpa99c/cordova-plugin-firebasex#715]
Moving conversation from https://github.com/dpa99c/cordova-plugin-firebasex/issues/529#issuecomment-1056000434 into it's own bug.

Type regression introduced by the tweak in https://github.com/dpa99c/cordova-plugin-firebasex/commit/5e349afa1a073cd787cd862e8b53e063954b13e6.

Putting the export on the interfaces makes TypeScript decide this is a Module now rather than a Namespace: https://www.typescriptlang.org/docs/handbook/modules.html

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level import or export is considered a module. Conversely, a file without any top-level import or export declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).

**Comment by adipascu** [comment]
I'm adding this to get typescript running in my project:
```ts
import { FirebasePlugin } from "cordova-plugin-firebasex";

declare global {
  interface Window {
    FirebasePlugin: FirebasePlugin;
  }
}
```
