### ISSUE TITLE
Module 'FirebaseAnalytics' not found - Xcode iOS Build

### ISSUE THREAD

**Issue by codexsysin** [dpa99c/cordova-plugin-firebasex#717]
# Bug report

**CHECKLIST**
- [ yes] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ yes] I confirm this is a suspected bug or issue that will affect other users

- [ yes] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [yes ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ yes] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Error is generated in FirebasePlugin.m @import FirebaseAnalytics line.

**Expected behavior:**

Successful Build

**Steps to reproduce:**
ionic cordova build ios

**Screenshots**
<img width="1181" alt="Screenshot 2022-03-02 at 8 53 04 PM" src="https://user-images.githubusercontent.com/12164671/156410885-1b301df5-53f7-4290-9b4d-8b210f8fcaa4.png">

**Environment information**

- Cordova CLI version 
	- 11.0.0
- Cordova platform version
	- Installed platforms:
  android 10.1.1
  ios 6.2.0
Available platforms: 
  browser ^6.0.0
  electron ^3.0.0
  osx ^6.0.0
- Plugins & versions installed in project (including this plugin)
    - com.razorpay.cordova 0.16.1 "RazorpayCheckout"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-cocoapod-support 1.6.2 "Cordova CocoaPods Dependency Support"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-email-composer 0.9.2 "EmailComposer"
cordova-plugin-firebasex 13.0.0-cli "Google Firebase Plugin"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-network-information 3.0.1-dev "Network Information"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.5 "Whitelist"
cordova-plugin-x-socialsharing 6.0.3 "SocialSharing"
cordova-sqlite-storage 6.0.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
- Dev machine OS and version, e.g.
    - OSX
        - ProductName:    macOS
ProductVersion: 12.0.1
BuildVersion:   21A559

   
_iOS build issue:_
- Node JS version
    - v14.17.5
- XCode version

**Comment by gallyamow** [comment]
I have the same trouble and @codexsysin fix does not work for me

**Comment by codexsysin** [comment]
Try removing pods_framework from dependencies in xcode @gallyamow

**Comment by gallyamow** [comment]
> Try removing pods_framework from dependencies in xcode @gallyamow

thank you for answer. I'll try it on next build.
