### ISSUE TITLE
Property 'grantCriticalPermission' does not exist on type 'FirebaseX'

### ISSUE THREAD

**Issue by aaadipop** [dpa99c/cordova-plugin-firebasex#720]
hey,

i'm trying to enable critical notifs and following the [docs](https://github.com/dpa99c/cordova-plugin-firebasex#grantcriticalpermission) i need to call 
```
this.firebase.grantCriticalPermission().then(perms => {
          localStorage.setItem('pushNotifsPermission', perms)
          console.log('permissios: ', JSON.stringify(perms));
        }, error => console.log('permissios err: '));
```

but i got this err: Property 'grantCriticalPermission' does not exist on type 'FirebaseX'

"@ionic-native/firebase-x": "^5.36.0"
"cordova-plugin-firebasex": "^14.0.0-cli"

**Comment by aaadipop** [comment]
@ArnoutCreemers any hints?

I see the code is in place but when I log the firebase object there is no `grantCriticalPermission()` function

I tried to install also the latest commit and the pkg.json contains 

```
"cordova-plugin-firebasex": {
        "IOS_ENABLE_CRITICAL_ALERTS_ENABLED": "true"
      }
```

also I have the special entitlement for critical notifications

**Comment by dpa99c** [comment]
`FirebaseX` typescript defs are not part of this plugin: "@ionic-native/firebase-x": "^5.36.0"
There are now located here: https://github.com/danielsogl/awesome-cordova-plugins
