### ISSUE TITLE
bug: Android 12 support with cli version installed

### ISSUE THREAD

**Issue by EinfachHans** [dpa99c/cordova-plugin-firebasex#727]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

I installed plugin version `14.0.0-cli` and in this version `android:exported="false"` is missing on the `FirebasePluginMessagingService` Service element. In the `14.0.0` it exists.

**Expected behavior:**

`android:exported="false"` should be available in cli version to support android 12

**Comment by RobYed** [comment]
Just ran into the same issue. Would be great to see it fixed :)

**Comment by peitschie** [comment]
As an interim fix, the following snippet can be added in `config.xml`

```
<widget>
  ...
  <platform name="android">
     ...
    <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application/service[@android:name='org.apache.cordova.firebase.FirebasePluginMessagingService']">
      <!-- https://github.com/dpa99c/cordova-plugin-firebasex/issues/727 -->
      <service android:exported="false" />
    </edit-config>
    ...
  </platform>
</widget>
```

**Comment by peitschie** [comment]
This appears to be fixed in `14.1.0-cli`

Fix was landed in https://github.com/dpa99c/cordova-plugin-firebasex/commit/a2c898369771b6580d0d7831909a37c3d944b279

**Comment by RobYed** [comment]
I am using `14.2.1-cli` and it doesn't seem to be fixed.

**Comment by dpa99c** [comment]
This [is fixed](https://github.com/dpa99c/cordova-plugin-firebasex/blob/15.0.0-cli/plugin.xml#L40) in `15.0.0-cli`
