### ISSUE TITLE
ld: framework not found Pods_____

### ISSUE THREAD

**Issue by auron105** [dpa99c/cordova-plugin-firebasex#73]
# Bug report

**Current behavior:**
i follow 
   cordova plugin add https://github.com/dpa99c/cordova-plugin-firebase.git
   ionic cordova platform add ios
   ionic cordova prepare ios
   ionic cordova build ios 
get error:
ld: framework not found Pods_____
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any idea?

**Environment information**

Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.7.0
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 13 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 8.0.1
   NodeJS     : v10.16.1 (/usr/local/bin/node)
   npm        : 6.10.2
   OS         : macOS Mojave
   Xcode      : Xcode 10.3 Build version 10G8

**Comment by dpa99c** [comment]
Have you installed and updated Cocoapods [as documented](https://github.com/dpa99c/cordova-plugin-firebasex#cocoapods)?

Please also try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working reference.

**Comment by auron105** [comment]
i try example and create ionic blank project is work fine.
also i'm follow documented in my project but still have error.....
i keep try~  thx

**Comment by dpa99c** [comment]
OK, thanks for the update. I'll close as you've confirmed this is specific to your project so won't necessarily affect others.

**Comment by auron105** [comment]
I know the problem.~
Because the <name> of config.xml does not support Chinese.
i change english name it work~!

**Comment by kyoz** [comment]
Hi @auron105. I'v the same problem like you. But i dont' have any chinese work in my config.xml. Just have vietnamese as the name of the app. And it work fine.

Before using this plugin, i'v using phonegap-push and it build perfectly.

Any idea on this problem.. Thanks :((

**Comment by kyoz** [comment]
I think this problem cause by the search paths overrides. My app name is 'Sinh Cơ' which is in vietnamese. Before integrate firebasex. The app build well on both android and ios. But after integrate this plugin, everytime i build app with xcode it raised an erro like @auron105  have I have to change the app name to English and remove all space and it build well. But i have to change app name every time i open xcode. I't kind of annoying. Do you have any ideas on this @dpa99c .

Thank you very much

**Comment by sboudouk** [comment]
I also wanted to report that the app name does not support accents like "é" and "è", used in french for example.
