### ISSUE TITLE
Some weird error on Capacitor: groovy.lang.MissingMethodException:

### ISSUE THREAD

**Issue by SheppardX** [dpa99c/cordova-plugin-firebasex#742]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

if i want to run it in Capacitor i get this error 

FAILURE: Build failed with an exception.

```
* Where:
Script '.../node_modules/cordova-plugin-firebasex/src/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating script.
> No signature of method: build_ak6ui7jj1gqcn8e9jnboemdff.android() is applicable for argument types: (build_ak6ui7jj1gqcn8e9jnboemdff$_run_closure2) values: [build_ak6ui7jj1gqcn8e9jnboemdff$_run_closure2@2c3a1342]
```

there is an NPM package of your package that fix this issue 
https://www.npmjs.com/package/cordova-plugin-firebasex-fix
could u check that ?

**Comment by SheppardX** [comment]
if i remove the whole android block 

```
android {
    buildTypes {
        debug {
            firebaseCrashlytics {
                mappingFileUploadEnabled false
            }
        }
        release {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
                unstrippedNativeLibsDir "obj/local"
                strippedNativeLibsDir "build/intermediates/jniLibs/release"
            }
        }
    }
}
```

then it works and it will build

**Comment by Captainfl4me** [comment]
Same problem here. I comment whole Android block like you suggest, the error disapper but now I'm getting this error with no infos (before using firebase-x my app was compiling) : 

Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

**Comment by SheppardX** [comment]
> Same problem here. I comment whole Android block like you suggest, the error disapper but now I'm getting this error with no infos (before using firebase-x my app was compiling) :
> 
> * Where:
>   Script 'D:\Web\studnchill\node_modules\cordova-plugin-firebasex\src\android\build.gradle'
> * What went wrong:
>   Could not compile script 'D:\Web\studnchill\node_modules\cordova-plugin-firebasex\src\android\build.gradle'.
> 
> EDIT: I was just using wrong java SDK oups.. (so now it works !)

What SDK you are using now ?

**Comment by Captainfl4me** [comment]
> > Same problem here. I comment whole Android block like you suggest, the error disapper but now I'm getting this error with no infos (before using firebase-x my app was compiling) :
> > 
> > * Where:
> >   Script 'D:\Web\studnchill\node_modules\cordova-plugin-firebasex\src\android\build.gradle'
> > * What went wrong:
> >   Could not compile script 'D:\Web\studnchill\node_modules\cordova-plugin-firebasex\src\android\build.gradle'.
> > 
> > EDIT: I was just using wrong java SDK oups.. (so now it works !)
> 
> What SDK you are using now ?

I’m using default Android Studio that match Gradle version, java 11 if I remember well. And when I got this error I was on Java 18 because I was thinking that this could fix the problem but after that I forgot I changed version and got the error x)

**Comment by SheppardX** [comment]
What is default Android Studio ? 
Can u tell me pls all your versions
Android Studio:
Gradle:
Android SDK:
Java: 11 (okay)

**Comment by ratkovicnikola** [comment]
The problem could be if you used Capacitor migration tool from v3 to v4. In my case, migrator added some new versions inside **variables.gradle** file without using quotes. For example, I had **10.1.1** instead of **'10.1.1'** in my **variables.gradle** file. Once I added single quotes to all x.x.x versions (where it's missing), build succeeded.

**Comment by rvcroffi** [comment]
> The problem could be if you used Capacitor migration tool from v3 to v4. In my case, migrator added some new versions inside **variables.gradle** file without using quotes. For example, I had **10.1.1** instead of **'10.1.1'** in my **variables.gradle** file. Once I added single quotes to all x.x.x versions (where it's missing), build succeeded.

Thank you! I used capacitor migration tool today and got that error.
My *variables.gradle* file had 5 variables with no single quotes and your solution solved the problem.
Just the 3 first variables must be number (minSdkVersion, compileSdkVersion and targetSdkVersion).

**Comment by trplx** [comment]
Any updates on this error? I still have this problem with 
Android Studio: Chipmunk 2021.2.1
Gradle: 7.3.3
Android gradle plugin: 7.2.1
Java: 11

"Caused by: groovy.lang.MissingMethodException: No signature of method: build_27xng531zq6fwka43ki22hsqe.android() is applicable for argument types: (build_27xng531zq6fwka43ki22hsqe$_run_closure2) values: [build_27xng531zq6fwka43ki22hsqe$_run_closure2@6683daeb]"

**Comment by sasos90** [comment]
@trplx same on my end. Using Gradle 7.5.1 on my machine, but 7.4.2 in the Android project obviously (created by capacitor i guess?)

**Comment by dpa99c** [comment]
https://github.com/dpa99c/cordova-plugin-firebasex#capacitor-support
