### ISSUE TITLE
Can you received notifications when app is killed 

### ISSUE THREAD

**Issue by Ghayyas** [dpa99c/cordova-plugin-firebasex#75]
Hello, Im using this plugin. I received the message in background and foreground. But when App is killed I didn't received any notification. Please help?

**Comment by dpa99c** [comment]
Please try building and running the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a known working reference and using its built-in FCM API client to send a pre-defined notification message to validate your development setup.

You haven't specified which platform you are testing on but a common cause of failure to receive background notifications on iOS is incomplete/incorrect setup of APNS for Firebase - please see the [Firebase documentation](https://firebase.google.com/docs/cloud-messaging/ios/certs) for further information.

**Comment by Ghayyas** [comment]
Thank for the message @dpa99c, Im using Device Android and Ionic Framework.

**Comment by Ghayyas** [comment]
Issue Resolved:
What I do is.. in firebase console I add the key.
`force-start: 1`
And now I received the notification even when app is killed,,

**Comment by fdmartins** [comment]
> Issue Resolved:
> What I do is.. in firebase console I add the key.
> `force-start: 1`
> And now I received the notification even when app is killed,,

Hello @Ghayyas  where you set this key force-start?

**Comment by chungminhtu** [comment]
> Issue Resolved:
> What I do is.. in firebase console I add the key.
> `force-start: 1`
> And now I received the notification even when app is killed,,

I have the same issue. Pls share your solution on this. Thanks!
