### ISSUE TITLE
What is signInWithCredential() for?

### ISSUE THREAD

**Issue by dlandtaa** [dpa99c/cordova-plugin-firebasex#758]
# Documentation issue

I want to use this plugin for allowing google sign in with my app. The example given in the documentation is this:

```
FirebasePlugin.authenticateUserWithGoogle(clientId, function(credential) {
    FirebasePlugin.signInWithCredential(credential, function() {
            console.log("Successfully signed in");
        }, function(error) {
            console.error("Failed to sign in", error);
        });
}, function(error) {
    console.error("Failed to authenticate with Google: " + error);
});
```

which works but I don't understand what `signInWithCredential()` is for. The docs say

> Signs the user into Firebase with credentials obtained via an authentication method such as verifyPhoneNumber() or authenticateUserWithGoogle()

but I don't know what that means. What does it mean to sign a user into fireabase? Do I need to do this if I just want google sign in for my app?

**Comment by TiBz0u** [comment]
Hi @dlandtaa ,

You can check the step of this function directly into the code source of the plugin entry. See [here](https://github.com/dpa99c/cordova-plugin-firebasex/blob/d6b7d469eb2c8e97c6b1d901876893df27cf3da3/src/android/FirebasePlugin.java#L1411-L1443).

I think the purpose is to obtain a specific token (credential) that is understood by Firebase. 
See [official android documentation](https://firebase.google.com/docs/auth/android/google-signin#authenticate_with_firebase) for implementing Google SignIn.

Kr,

TiBz0u

**Comment by dlandtaa** [comment]
So here's the deal. We have been using the [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) for allowing users of our app to sign in with their google account. Unfortunately that plugin is just not compatible with this one. They rely on different versions of various google services and it's too hard to resolve all the conflicts. So I'd like to use this plugin for allowing users to sign in our app using their google account and just get rid of cordova-plugin-googleplus.

However, I'm not 100% sure how that is achieved with this plugin. With the other plugin, after the user signs in you get a google user id along with an id token. We pass these to our back end server where we use those values with another google server api to verify the id token is valid.

Is that necessary with this plugin? Does `signInWithCredential()` take care of that step or should we still do that ourselves as well? If so how would that look? This seems to do it but I'm not sure if this is the correct way to go about it:

````
window.FirebasePlugin.authenticateUserWithGoogle(clientId, function(credential) {
    window.FirebasePlugin.signInWithCredential(credential, function() {
        FirebasePlugin.getCurrentUser(function(user) {
            // verify user with our server here??
        });
    });
});
````
