### ISSUE TITLE
[Android] Remote config dependency version

### ISSUE THREAD

**Issue by TiBz0u** [dpa99c/cordova-plugin-firebasex#773]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

When we upload an application with the last version of the plugin, we have an error on the Google Console.
This is described here : https://firebase.google.com/support/release-notes/android#remote-config_v21-1-0
Update to 21.1.1+
_Maybe the 21.1.2 which brings a updated play-services-basement
https://firebase.google.com/support/release-notes/android#remote-config_v21-1-2_

**Expected behavior:**
No warning after upload.

**Steps to reproduce:**
Upload an application on Google Console.

**Screenshots**
![Uploading Screenshot 2022-10-18 at 10.37.08.png…]()

**Comment by dpa99c** [comment]
The pinned versions of Firebase SDK library components can be [overridden during plugin installation](https://github.com/dpa99c/cordova-plugin-firebasex#specifying-android-library-versions) for example:

	cordova plugin add cordova-plugin-firebasex --variable ANDROID_FIREBASE_CONFIG_VERSION=21.1.2

The pinned versions will be updated to the latest versions in an upcoming plugin release once they have been regression tested within the context of the plugin.

**Comment by TiBz0u** [comment]
Hello @dpa99c , thanks for your answer. That's what we already did :)

I logged this because it's a warning that can scary some users.
Moreover, do you plan to go with firebase-bom in next release?
It can be nice to easily upgrade all sdk. However, if someone need to update only a particular version, can be problematic.
