### ISSUE TITLE
Error Cordova version in 5.0.0 and lower

### ISSUE THREAD

**Issue by Supriyuadi** [dpa99c/cordova-plugin-firebasex#78]
# Documentation issue

Hi, i want to use this plugin with version 5.0.0
the documentation says 
cordova: >= 8
cordova-android: >= 8
cordova-ios: >= 4

but in your package.json 
  "dependencies": {
    "xcode": "^2.0.0",
    "cordova-lib":"^9.0.0"
  }

because of that, i can't use this plugin in my project.
this is my **Ionic Info**
Ionic:

   Ionic CLI          : 5.2.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 38 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8 

System:

   NodeJS : v9.5.0 (/usr/local/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.3 Build version 10G8

**Comment by dpa99c** [comment]
I presume it's the dependency on `cordova-lib@^9.0.0` that's causing the problem because you have `cordova@8.1.2/cordova-lib@8.1.1` ?

**Comment by Supriyuadi** [comment]
Yes i have cordova@8.1.2, but if i install this plugin, error says mininum cordova is 9.0.0.

**Comment by dpa99c** [comment]
Yes, as [stated in the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#supported-cordova-versions) the min supported version is `cordova@9`.  Please update to `cordova@9` if you want to use this plugin.
