### ISSUE TITLE
IOS build has failed after installing firebasex plugin

### ISSUE THREAD

**Issue by imadkhatib2017** [dpa99c/cordova-plugin-firebasex#781]
Hi all,
I"m trying to build my app in ios using this command:
ionic cordova build ios

My ionic info is:

Ionic:

   Ionic CLI                     : 6.20.3 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.3.4
   @angular-devkit/build-angular : 14.2.8
   @angular-devkit/schematics    : 14.2.8
   @angular/cli                  : 14.2.8
   @ionic/angular-toolkit        : 6.1.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0, ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 12 other plugins)

Utility:

   cordova-res (update available: 0.15.4) : 0.15.3
   native-run (update available: 1.7.1)   : 0.2.9

System:

   ios-sim : 8.0.2
   NodeJS  : v16.15.0 (/usr/local/bin/node)
   npm     : 8.5.5
   OS      : macOS Big Sur
   Xcode   : Xcode 12.5 Build version 12E262

Errors:
1.
/platforms/ios/Pods/GoogleSignIn/GoogleSignIn/Sources/GIDEMMErrorHandler.m:155:41: error: property 'keyWindow' not found on
      object of type 'UIWindowScene *'
        return ((UIWindowScene *)scene).keyWindow;

2.
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'AppAuth' from project 'Pods')
** BUILD FAILED **

I installed the plugin using these commands:
$ ionic cordova plugin add cordova-plugin-firebasex 
$ npm install @awesome-cordova-plugins/firebase-x 

Note: the same code works in android code.
Please advise...

**Comment by dpa99c** [comment]
`ios-sim : 8.0.2`

You are trying to run on Simulator with iOS 8.0 but the minimum supported iOS version by the latest Firebase iOS SDK v10 is iOS 11.0 - [see here](https://firebase.google.com/support/release-notes/ios#version_1000_-_october_10_2022).

`Xcode : Xcode 12.5 Build version 12E262`
You are using an outdated version of Xcode - please update to the latest version or you may have build issues.

Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment before opening issues as [outlined in the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-a-bug-or-problem)

**Comment by imadkhatib2017** [comment]
Thanks @dpa99c :) 
You saved my time.
