### ISSUE TITLE
the documentation does not specify on how to run this in debug mode

### ISSUE THREAD

**Issue by wwannous** [dpa99c/cordova-plugin-firebasex#785]
I am not sure if the option or running this in firebase debug mode is available.
is there a way to run this on ionic appflow with "-FIRDebugEnabled" argument or is their any fork of this plugin with debug enabled?

# Documentation issue

**Comment by tomivm** [comment]
With @RodriSanchez1 we find a way to enable the debug_mode to a Android USB-connected device with the objective of using Analytics debug view. 
1) Connect your developer Android device via USB.
2) Allow the connection on the device.
3) Open your terminal and run `adb devices -l`
if appears run `adb shell setprop debug.firebase.analytics.app PACKAGE.NAME` 
Now your device is in debug Mode.
I have not already tested on IOS but you can find information [here](https://firebase.google.com/docs/analytics/debugview?hl=es-419#android)

**Comment by dpa99c** [comment]
Refer to the [Firebase documentation](https://firebase.google.com/docs/analytics/debugview) for how to enable debug mode for the Firebase SDK on a test device.
The plugin is unable to help with this on either the iOS or Android platforms therefore it lies out of scope.
