### ISSUE TITLE
add plugin and run pod install

### ISSUE THREAD

**Issue by Ufloreseducapp** [dpa99c/cordova-plugin-firebasex#786]
# Bug report

**CHECKLIST**
- [ ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ +] I confirm this is a suspected bug or issue that will affect other users

- [ ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

Hi,I am new to creating an app in ios, I have an error when adding the firebasex plugin in cordova because when I add it and create the ios platform in cordova, when the firebasex plugin is installed, pod install is executed and it enters as in a cycle since it repeats the same action and at the end it does not add anything

**Expected behavior:**

**Steps to reproduce:**

first add the cordova platform add ios command.
When it's adding the plugins to the platform, when it installs firebasex, it runs pod install, and then it's in a loop

**Screenshots**

ordova platform add  ios
Using cordova-fetch for cordova-ios@^6.2.0
Adding ios project...
Creating Cordova project for the iOS platform:
        Path: platforms/ios
        Package: com.myproject.emovil
        Name: myproject
iOS project created with cordova-ios@6.2.0
Installing "cordova-plugin-add-swift-support" for ios
Installing "cordova-plugin-android-permissions" for ios
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-crop" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-dialogs" for ios
Installing "cordova-plugin-file" for ios
Installing "cordova-plugin-file-transfer" for ios
Plugin dependency "cordova-plugin-file@7.0.0" already fetched, using that version.
Dependent plugin "cordova-plugin-file" already installed on ios.
Installing "cordova-plugin-firebasex" for ios
Running command: pod install --verbose
     Cloning into '/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju'...

     Note: switching to '591d56e1300b6d11948e1b821efac785a295989c'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     

     Updating files:  28% (2695/9462)
     Updating files:  29% (2744/9462)
     Updating files:  30% (2839/9462)
     Updating files:  31% (2934/9462)
     Updating files:  32% (3028/9462)
     Updating files:  33% (3123/9462)
     Updating files:  34% (3218/9462)
     Updating files:  35% (3312/9462)
     Updating files:  36% (3407/9462)
     Updating files:  37% (3501/9462)
     Updating files:  38% (3596/9462)
     Updating files:  39% (3691/9462)
     Updating files:  40% (3785/9462)
     Updating files:  41% (3880/9462)
     Updating files:  42% (3975/9462)
     Updating files:  43% (4069/9462)
     Updating files:  44% (4164/9462)
     Updating files:  45% (4258/9462)
     Updating files:  46% (4353/9462)
     Updating files:  47% (4448/9462)
     Updating files:  48% (4542/9462)
     Updating files:  49% (4637/9462)
     Updating files:  50% (4731/9462)
     Updating files:  51% (4826/9462)
     Updating files:  52% (4921/9462)
     Updating files:  53% (5015/9462)
     Updating files:  54% (5110/9462)
     Updating files:  55% (5205/9462)
     Updating files:  56% (5299/9462)
     Updating files:  56% (5327/9462)
     Updating files:  57% (5394/9462)
     Updating files:  58% (5488/9462)
     Updating files:  59% (5583/9462)
     Updating files:  60% (5678/9462)
     Updating files:  61% (5772/9462)
     Updating files:  62% (5867/9462)
     Updating files:  63% (5962/9462)
     Updating files:  64% (6056/9462)
     Updating files:  65% (6151/9462)
     Updating files:  66% (6245/9462)
     Updating files:  67% (6340/9462)
     Updating files:  68% (6435/9462)
     Updating files:  69% (6529/9462)
     Updating files:  70% (6624/9462)
     Updating files:  71% (6719/9462)
     Updating files:  72% (6813/9462)
     Updating files:  73% (6908/9462)
     Updating files:  74% (7002/9462)
     Updating files:  75% (7097/9462)
     Updating files:  76% (7192/9462)
     Updating files:  77% (7286/9462)
     Updating files:  78% (7381/9462)
     Updating files:  79% (7475/9462)
     Updating files:  80% (7570/9462)
     Updating files:  81% (7665/9462)
     Updating files:  82% (7759/9462)
     Updating files:  83% (7854/9462)
     Updating files:  84% (7949/9462)
     Updating files:  85% (8043/9462)
     Updating files:  86% (8138/9462)
     Updating files:  86% (8213/9462)
     Updating files:  87% (8232/9462)
     Updating files:  88% (8327/9462)
     Updating files:  89% (8422/9462)
     Updating files:  90% (8516/9462)
     Updating files:  91% (8611/9462)
     Updating files:  92% (8706/9462)
     Updating files:  93% (8800/9462)
     Updating files:  94% (8895/9462)
     Updating files:  95% (8989/9462)
     Updating files:  96% (9084/9462)
     Updating files:  97% (9179/9462)
     Updating files:  98% (9273/9462)
     Updating files:  99% (9368/9462)
     Updating files: 100% (9462/9462), done.

     Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'

     Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'

     Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'

     Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'

     Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'

     Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'

     Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'

     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'

     Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'

     Submodule 'third_party/opencensus-proto' (https://github.com/census-instrumentation/opencensus-proto.git) registered for path 'third_party/opencensus-proto'

     Submodule 'third_party/opentelemetry' (https://github.com/open-telemetry/opentelemetry-proto.git) registered for path 'third_party/opentelemetry'

     Submodule 'third_party/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path 'third_party/protobuf'

     Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'

     Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'

     Submodule 'third_party/xds' (https://github.com/cncf/xds.git) registered for path 'third_party/xds'

     Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'

     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/abseil-cpp'...

pod: Command failed with exit code 1 Error output:
Cloning into '/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju'...
     Note: switching to '591d56e1300b6d11948e1b821efac785a295989c'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by switching back to a branch.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -c with the switch command. Example:
     
       git switch -c <new-branch-name>
     
     Or undo this operation with:
     
       git switch -
     
     Turn off this advice by setting config variable advice.detachedHead to false
     
     Updating files: 100% (9462/9462), done.
     Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/abseil-cpp'
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark) registered for path 'third_party/benchmark'
     Submodule 'third_party/bloaty' (https://github.com/google/bloaty.git) registered for path 'third_party/bloaty'
     Submodule 'third_party/boringssl-with-bazel' (https://github.com/google/boringssl.git) registered for path 'third_party/boringssl-with-bazel'
     Submodule 'third_party/cares/cares' (https://github.com/c-ares/c-ares.git) registered for path 'third_party/cares/cares'
     Submodule 'third_party/envoy-api' (https://github.com/envoyproxy/data-plane-api.git) registered for path 'third_party/envoy-api'
     Submodule 'third_party/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'third_party/googleapis'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
     Submodule 'third_party/libuv' (https://github.com/libuv/libuv.git) registered for path 'third_party/libuv'
     Submodule 'third_party/opencensus-proto' (https://github.com/census-instrumentation/opencensus-proto.git) registered for path 'third_party/opencensus-proto'
     Submodule 'third_party/opentelemetry' (https://github.com/open-telemetry/opentelemetry-proto.git) registered for path 'third_party/opentelemetry'
     Submodule 'third_party/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path 'third_party/protobuf'
     Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
     Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'
     Submodule 'third_party/xds' (https://github.com/cncf/xds.git) registered for path 'third_party/xds'
     Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/abseil-cpp'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/benchmark'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/boringssl-with-bazel'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/cares/cares'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/envoy-api'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/googleapis'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/googletest'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/libuv'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/opencensus-proto'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/opentelemetry'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protoc-gen-validate'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/re2'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/xds'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/zlib'...
     Submodule 'third_party/abseil-cpp' (https://github.com/abseil/abseil-cpp.git) registered for path 'third_party/bloaty/third_party/abseil-cpp'
     Submodule 'third_party/capstone' (https://github.com/aquynh/capstone.git) registered for path 'third_party/bloaty/third_party/capstone'
     Submodule 'third_party/demumble' (https://github.com/nico/demumble.git) registered for path 'third_party/bloaty/third_party/demumble'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/googletest'
     Submodule 'third_party/protobuf' (https://github.com/protocolbuffers/protobuf.git) registered for path 'third_party/bloaty/third_party/protobuf'
     Submodule 'third_party/re2' (https://github.com/google/re2) registered for path 'third_party/bloaty/third_party/re2'
     Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/bloaty/third_party/zlib'
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/abseil-cpp'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/capstone'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/demumble'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/googletest'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/protobuf'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/re2'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/zlib'...
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/bloaty/third_party/protobuf/third_party/benchmark'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/bloaty/third_party/protobuf/third_party/googletest'
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/protobuf/third_party/benchmark'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/bloaty/third_party/protobuf/third_party/googletest'...
     Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/protobuf/third_party/benchmark'
     Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/protobuf/third_party/googletest'
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf/third_party/benchmark'...
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf/third_party/googletest'...
     fatal: write error: No space left on device
     fatal: fetch-pack: invalid index-pack output
     fatal: clone of 'https://github.com/google/googletest.git' into submodule path '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf/third_party/googletest' failed
     Failed to clone 'third_party/googletest'. Retry scheduled
     Cloning into '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf/third_party/googletest'...
     fatal: write error: No space left on device
     fatal: fetch-pack: invalid index-pack output
     fatal: clone of 'https://github.com/google/googletest.git' into submodule path '/private/var/folders/pv/zlwrqvnj295fbx4hvdmy5mj80000gn/T/d20221210-8933-u1zqju/third_party/protobuf/third_party/googletest' failed
     Failed to clone 'third_party/googletest' a second time, aborting
     fatal: Failed to recurse into submodule path 'third_party/protobuf'
**Environment information**

- Cordova CLI version 
	- `cordova 11.0.0`
- Cordova platform version
	- `Installed platforms:
  ios 6.2.0
Available platforms: 
  android ^10.1.1
  browser ^6.0.0
  electron ^3.0.0
  osx ^6.0.0`
- Plugins & versions installed in project (including this plugin)
    - ` "cordova-android": "^11.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^6.2.0",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-android-permissions": "^1.1.5",
    "cordova-plugin-camera": "6.0.0",
    "cordova-plugin-crop": "^0.4.0",
    "cordova-plugin-device": "^2.1.0",
    "cordova-plugin-file": "^7.0.0",
    "cordova-plugin-file-transfer": "1.7.1",
    "cordova-plugin-firebasex": "^16.0.0",
    "cordova-plugin-ios-camera-permissions": "1.2.0",
    "cordova-plugin-media": "^6.1.0",
    "cordova-plugin-media-capture": "4.0.0",
    "cordova-plugin-network-information": "3.0.0",
    "cordova-plugin-qrscanner": "^3.0.1",
    "cordova-plugin-splashscreen": "^1.0.0",
    "cordova-sqlite-storage": "6.0.0",
    "polarcape-cordova-plugin-document-handler": "1.1.1"`
- Dev machine OS and version, e.g.
    - OSX
        - `monterey 12.5.1`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `v18.4.0`
- XCode version
   -13.3.1 (13E500a)

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by bsprengelmeijer** [comment]
Did you fix this? I'm having the same issue

**Comment by KhAliMoh** [comment]
Any updates ?

**Comment by dpa99c** [comment]
- Ensure you have the latest version of Cocopods installed, e.g. `brew upgrade cocoapods`
- Ensure your local repo is up-to-date: `pod repo update`
- Build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a know working codebase 
for reference.

If you are able to reproduce the issue in the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test), please open a new issue and fill out the issue template in full, including steps to reproduce in the example project and details of test devices used to reproduce the issue.
