### ISSUE TITLE
foreground notifications not to display on first run on iOS (Same issue as Bug report #109[fixed&closed])

### ISSUE THREAD

**Issue by yuancure** [dpa99c/cordova-plugin-firebasex#788]
# Bug report

**CHECKLIST**

- [*] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [*] I confirm this is a suspected bug or issue that will affect other users

- [*] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [*] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [*] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**
After you accept the permission prompt on iOS and send push notifications while the app is in the foreground, the app receives the data but doesn't display a native notification. If you then force quit the app and relaunch it and while the app is in the foreground send push notifications again they do come display as native notifications.
Similar issue to Bug report #109 and #744.

**Expected behavior:**
After you accept the permission prompt on iOS and send push notifications while the app is in the foreground, you should see a native notification.

**Steps to reproduce:**
1. Create a minimum app.
2. Accept the push notification prompt.
3. Keep the app in the foreground.
4. Using the device token send a push notification.

```
{
  "message": {
    "token": "eGW_...",
    "notification": {"body": "FCM Message"},
    "data": {"notification_foreground": "true" }
  }
}
```

**Environment information**
- Cordova CLI version 
	11.0.0
- Cordova platform version
	cordova-ios@6.2.0
- Plugins & versions installed in project (including this plugin)
    cordova-plugin-firebasex Version 14.2.1 or Version 16.0.0
- Device details
    iPhone 7
- OS details
    iOS 14.4 and 13.3
- Node JS version
    16.14.0
- XCode version
     13

**Comment by Vignesh9291** [comment]
Hi @yuancure @dpa99c , I am also facing the same issue. 


**Steps to reproduce:**

Create an app.
- Accept the push notification prompt.
- Keep the app in the foreground.
- Using the device token send a push notification with a simple payload.

```
{
 "to" : "eaphJPGP9kMpp5Nyhd_GM6:APA91bFp_7o_1FgcwmvfItumpboSG7DaPSrVK6n8XDj3JepxmhbJ41HTeiLTv6y90x1Ag6LI1DKIgG5Og74VT1pfZiJHKjpuer5rluwIQ9H4NxJklL_aOwDKhOrTfZuW4seKHL_6lah_",
 "notification" :{
     "body" : "your message body",
     "title": "your title for notification"
 },
  "data":{
       "notification_foreground": "true"
  }
 }

```

Environment information

Cordova CLI version
11.1.0

Cordova platform version
cordova-ios@6.3.0

Plugins & versions installed in the project (including this plugin)
cordova-plugin-firebasex Version 14.2.1 or Version 16.0.0

Device details
iPad 

OS details
iOS 14.4

Node JS version
14.21.3

XCode version
14

Please help to get over this issue. Your help is much appreciated.

**Comment by iamvignesht** [comment]
The below PR actually fixed the foreground issue. 

https://github.com/dpa99c/cordova-plugin-firebasex/pull/800

Thanks @vneenz and thanks for merging the PR @dpa99c
