### ISSUE TITLE
cordova compile android fail because cannot find symbol Build.VERSION_CODES.S

### ISSUE THREAD

**Issue by patrizi** [dpa99c/cordova-plugin-firebasex#789]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

cordova prepare android --verbose  (no problem)

cordova compile android --verbose 

No scripts found for hook "before_compile".
Loaded API for android project platforms\android\cordova\Api.js
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=D:\Apps\Android\SDK (recommended setting)
ANDROID_HOME=D:\Apps\Android\SDK (DEPRECATED)
Using Android SDK: D:\Apps\Android\SDK

BUILD SUCCESSFUL in 906ms
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Gradle Distribution URL: https://services.gradle.org/distributions/gradle-6.5-all.zip

> Configure project :app
strippedNativeLibsDir is deprecated and no longer used. Please remove it from your build configuration.

> Configure project :CordovaLib
[Cordova] cdvMinSdkVersion is overridden, try it at your own risk.
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/03 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :app:compileDebugJavaWithJavac
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:261: error: cannot find symbol
            if(getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.S && Build.VERSION.SDK_INT >=  ) {
                                                                           ^
  symbol:   variable S
  location: class VERSION_CODES
platforms\android\app\src\main\java\org\apache\cordova\firebase\FirebasePluginMessagingService.java:261: error: cannot find symbol
            if(getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.S && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                                                                                                                             ^
  symbol:   variable S
  location: class VERSION_CODES
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
27 actionable tasks: 27 executed
Command failed with exit code 1: platforms\android\gradlew cdvBuildDebug -b platforms\android\build.gradle
Error: Command failed with exit code 1: platforms\android\gradlew cdvBuildDebug -b platforms\android\build.gradle
    at makeError (node_modules\execa\lib\error.js:59:11)
    at handlePromise (node_modules\execa\index.js:114:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Expected behavior:**

**Steps to reproduce:**

**Screenshots**

**Environment information**

winver 
Windows 10 PRO 22H2 Version (build SO 19045.2364)

node -v
v16.14.1

npm -v
9.2.0

cordova -v
11.0.0

gradle -v
Gradle 6.5
Build time:   2020-06-02 20:46:21 UTC
Revision:     a27f41e4ae5e8a41ab9b19f8dd6d86d7b384dad4
Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.17 (Oracle Corporation 11.0.17+10-LTS-269)
OS:           Windows 10 10.0 amd64

cordova platform add android 
	Path: platforms\android
	Activity: MainActivity
	Android target: android-29
	Subproject Path: CordovaLib
	Subproject Path: app
	Android project created with cordova-android@9.1.0

cordova platforms

Installed platforms:
  android 9.1.0
Available platforms:
  browser ^6.0.0
  electron ^3.0.0
  windows ^7.0.0

cordova plugins

cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-device 2.1.0 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-firebasex 16.0.0 "Google Firebase Plugin"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-inappbrowser 5.0.0 "InAppBrowser"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 6.0.2 "Splashscreen"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-plugin-transport-security 0.1.2 "App Transport Security"
cordova-plugin-whitelist 1.3.5 "Whitelist"
cordova-sqlite-storage 6.1.0 "Cordova SQLite storage plugin - cordova-sqlite-storage plugin version"
cordova.plugins.diagnostic 7.1.1 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.6 "Launch Navigator"

cordova requirements android
	Requirements check results for android:
	Java JDK: installed 1.8.0
	Android SDK: installed true
	Android target: installed android-32,android-31,android-30,android-29,android-28,android-27,android-26,android-25,android-22,android-19
	Gradle: installed D:\Apps\Apache\Gradle\bin\gradle.BAT

**Comment by leevelop-up** [comment]
I solved the Android target version and Android platform with the latest version.

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html?hl=ko#ApiLevels

**Comment by patrizi** [comment]
thanks @leevelop-up  
But, I've tried to compile with android-targetSdkVersion=33 or 32 in config.xml coupled with Build Tools SDKs 31 or 32 or 33, without success.

Although I have tried uninstalling and then reinstalling (at each test) the SDK Build Tools, there are always other errors (for each version above), in particular:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Installed Build Tools revision 32.0.0 is corrupted. Remove and install again using the SDK Manager.

Only the SDK Build Tools 30 allow me to compile but then the error I indicated occurs.

**Comment by dpa99c** [comment]
```
Installed platforms:
android 9.1.0
```

[Supported Cordova Versions](https://github.com/dpa99c/cordova-plugin-firebasex#supported-cordova-versions)
> cordova-android: `>= 10`

Update to `cordova-android@10`

**Comment by patrizi** [comment]
thanks a lot @dpa99c 

I followed your suggestion with no success, but after more tests I finally solved it.
The only stable environment that had works to me, have this configuration:
- Java JDK 11 (but also 16)
- Android SDK Tools 32.0.0  
- cordova-android 11.0.0
