### ISSUE TITLE
Can't install FirebaseX for iOS

### ISSUE THREAD

**Issue by El-Tommy** [dpa99c/cordova-plugin-firebasex#790]
I'm trying to install the plugin for the ios platform, but every time I try I get the error below:

```
myuser@imac-name my-project-dir % cordova plugin add cordova-plugin-firebasex

Installing "cordova-plugin-firebasex" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-firebasex" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/myuser/Mobile/my-project-dir/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
pod: Command failed with exit code 31
```

I already deleted the folders npm_modules, plugins and platforms. I installed all the plugins (except firebasex) and the platform, and then firebasex, but I can't proceed with the installation.

My config.xml file is configured for the minimum iOS platform to be 11 `<preference name="deployment-target" value="11.0" />`, and these are my general settings:

cordova: 11.0.0
node: v18.12.1
npm: 8.19.2
cordova-android: ^10.1.2
cordova-ios: ^6.2.0"
cocoapods: 1.11.3
macOS: 13.1

I even tested it by creating a new project, without any other plugin or other platform, and the error remains.

I tried installing it this way `cordova plugin add cordova-plugin-firebasex --variable IOS_FIREBASE_SDK_VERSION=9.1.0` and it didn't work, same error.

One message I noticed when I remove the plugin after the failed install is the warning below:

```
Uninstalling cordova-plugin-firebasex from ios
Running command: pod install --verbose

[!] The Podfile does not contain any dependencies.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.

```

**Comment by Wallethub** [comment]
> I'm trying to install the plugin for the ios platform, but every time I try I get the error below:
> 
> ```
> myuser@imac-name my-project-dir % cordova plugin add cordova-plugin-firebasex
> 
> Installing "cordova-plugin-firebasex" for android
> Subproject Path: CordovaLib
> Subproject Path: app
> Installing "cordova-plugin-firebasex" for ios
> Running command: pod install --verbose
> Failed to install 'cordova-plugin-firebasex': Error: pod: Command failed with exit code 31
>     at ChildProcess.whenDone (/Users/myuser/Mobile/my-project-dir/node_modules/cordova-common/src/superspawn.js:136:25)
>     at ChildProcess.emit (node:events:513:28)
>     at maybeClose (node:internal/child_process:1091:16)
>     at Socket.<anonymous> (node:internal/child_process:449:11)
>     at Socket.emit (node:events:513:28)
>     at Pipe.<anonymous> (node:net:313:12)
> pod: Command failed with exit code 31
> ```
> 
> I already deleted the folders npm_modules, plugins and platforms. I installed all the plugins (except firebasex) and the platform, and then firebasex, but I can't proceed with the installation.
> 
> My config.xml file is configured for the minimum iOS platform to be 11 `<preference name="deployment-target" value="11.0" />`, and these are my general settings:
> 
> cordova: 11.0.0 node: v18.12.1 npm: 8.19.2 cordova-android: ^10.1.2 cordova-ios: ^6.2.0" cocoapods: 1.11.3 macOS: 13.1
> 
> I even tested it by creating a new project, without any other plugin or other platform, and the error remains.
> 
> I tried installing it this way `cordova plugin add cordova-plugin-firebasex --variable IOS_FIREBASE_SDK_VERSION=9.1.0` and it didn't work, same error.
> 
> One message I noticed when I remove the plugin after the failed install is the warning below:
> 
> ```
> Uninstalling cordova-plugin-firebasex from ios
> Running command: pod install --verbose
> 
> [!] The Podfile does not contain any dependencies.
> 
> [!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
> ```

Do pod repo update in platforms/ios and try re-install. Worked for us.

**Comment by El-Tommy** [comment]
Thank you for your help.
Worked perfectly.

However, at the end of the installation I received the warnings below, should I be concerned?

```
[!] The `My App [Debug]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-My App/Pods-My App.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `My App [Release]` target overrides the `LD_RUNPATH_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-My App/Pods-My App.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
```

**Comment by mehmetkaynak** [comment]
any updates?
