### ISSUE TITLE
Redirect to specific page when clicking on the push notification on background 

### ISSUE THREAD

**Issue by imadkhatib** [dpa99c/cordova-plugin-firebasex#796]
Hey,
I receive push notifications in foreground and background.
But when the app is in the background and a push is received, I want to open the application to a specific page, where can I do that?
in meantime nothing happens when I click on the push in background (but it works in foreground).
Is there a way to know if the push was clicked or not in background?
I"m using this version: "cordova-plugin-firebasex": "^16.0.0",
And this is my full project details:

Ionic:

   Ionic CLI                     : 6.20.3 (C:\Users\Imad\AppData\Roaming\nvm\v19.0.1\node_modules\@ionic\cli)        
   Ionic Framework               : @ionic/angular 6.2.5
   @angular-devkit/build-angular : 14.2.1
   @angular-devkit/schematics    : 14.2.1
   @angular/cli                  : 14.2.1
   @ionic/angular-toolkit        : 7.0.0

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : android 11.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 5 other plugins)

Utility:

   cordova-res : not installed globally
   native-run  : not installed globally

System:

   NodeJS : v19.0.1 (C:\Program Files\nodejs\node.exe)
   npm    : 8.19.2
   OS     : Windows 10

**Comment by fasthostinc** [comment]
Did you find a solution to this question because I have been trying alot and not getting it to work, anyone with the correct code to do this? Thanks

**Comment by imadkhatib** [comment]
Hi @fasthostinc No, unfortunately I still have this issue.

**Comment by dpa99c** [comment]
You can use [onMessageReceived](https://github.com/dpa99c/cordova-plugin-firebasex#onmessagereceived) which is called when the user taps on a background (system) or a foreground (app) notification, e.g.:

```
FirebasePlugin.onMessageReceived(function(message) {    
    if(message.messageType === "notification" && message.tap === "background"){
        // Code to navigate to specific page of your app
    }
});
```

If this isn't working, then use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your implementation.
Build and run it and use its built-in FCM messaging client to validate that the plugin is correctly handling actions for tapping system notifications.

**Comment by gouteru** [comment]
I have recently migrated fcm plugin from [andrehtissot/cordova-plugin-fcm-with-dependecy-updated](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) to this plugin.
I got same behavior when tapped my app's notification on notification bar of Android, then nothing happened and the notification disappeared.
I removed "click_action: 'FCM_PLUGIN_ACTIVITY'" from my payload of notification which has been specified in my notification payload because it was stated in the previous plugin notes. Then onMessageReceived triggered as expected when I tapped my app's notification.
I guess the previous plugin set something callback to handle the tapped notification data but firebasex plugin is not needed.

**Comment by dpa99c** [comment]
See the [sample messages](https://github.com/dpa99c/cordova-plugin-firebasex-test/tree/master/messages) in the example project as reference to the structure of FCM messages that this plugin expects

**Comment by jzonehu** [comment]
when tapped my app's notification on notification bar of Android  , FirebasePlugin.onMessageReceived
message get  "{"google.delivered_priority":"high","google.sent_time":1688976815139,"google.ttl":2419200,"google.original_priority":"high","messageType":"notification","tap":"background","from":"360483412254","google.message_id":"0:1688976815151701%ba6bfc5fba6bfc5f","gcm.n.analytics_data":"Bundle[mParcelledData.dataSize=348]","collapse_key":"com.XXX.XXXX"}"

but when app Foreground I can get like {"messageType":"notification","id":"0:1688978043974402%ba6bfc5fba6bfc5f","ttl":"2419200","body":"test00004","from":"360483412254","title":"ff","sent_time":"1688978043953","collapse_key":"com.xxxx.xxx","show_notification":"false"}

so how to fix to get  notification's  body

**Comment by prakashbarik90** [comment]
> I have recently migrated fcm plugin from [andrehtissot/cordova-plugin-fcm-with-dependecy-updated](https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated) to this plugin. I got same behavior when tapped my app's notification on notification bar of Android, then nothing happened and the notification disappeared. I removed "click_action: 'FCM_PLUGIN_ACTIVITY'" from my payload of notification which has been specified in my notification payload because it was stated in the previous plugin notes. Then onMessageReceived triggered as expected when I tapped my app's notification. I guess the previous plugin set something callback to handle the tapped notification data but firebasex plugin is not needed.

@jzonehu Thanks a lot boss! Really you saved my time...
Removing "click_action: 'FCM_PLUGIN_ACTIVITY'" from my payload of notification will do the rest of job.

**Comment by imadkhatib** [comment]
@gouteru Thanks a lot. you saved my time.
