### ISSUE TITLE
iOS verifyPhoneNumber triggers a config error

### ISSUE THREAD

**Issue by cerealexx** [dpa99c/cordova-plugin-firebasex#80]
# Bug report

**Current behavior:**
When calling verifyPhoneNumber in iOS this error gets logged:
[console.error]: "FirebasePlugin[native]: EXCEPTION: The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call [FIRApp configure]; (FirebaseApp.configure() in Swift) in the App Delegate's application:didFinishLaunchingWithOptions: (application(_:didFinishLaunchingWithOptions:) in Swift)."

**Expected behavior:**
No config error should be returned since GoogleService-Info.plist is in iside the correct Resources folder.

**Steps to reproduce:**
Call verifyPhoneNumber

**Environment information**

- Cordova CLI version 
	-  9.0.0
- Cordova platform version
	- iOS 5.0.1
- Plugins & versions installed in project (including this plugin)
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 6.0.3 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
- Dev machine OS and version, e.g.
    - OSX 10.14.6
        
_Runtime issue_
- Device details
    - iPhone 6
- OS details
    - iOS 12.4
	
_iOS build issue:_
- Node JS version
    -  10.16.0
- XCode version
 - 10.3

**Related code:**
```
this.fb.verifyPhoneNumber(phoneNum, 30)
      .then(credential => {
        console.log(credential);
      });
```

**Console output**
<details>
<summary>console output</summary>

```

"FirebasePlugin[native]: EXCEPTION: The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift)."

```

</details><br/><br/>

**Comment by dpa99c** [comment]
This might be a side effect of #77. Check if the `GoogleService-Info.plist` is referenced in `Resources` if you open the project in Xcode.

**Comment by cerealexx** [comment]
Yeah, sorry, I saw that but my file was correctly rendered inside resources dir and the error was different so I thought it wasn't related. It is though, so better close this one and follow #77
