### ISSUE TITLE
The right way to implement google login

### ISSUE THREAD

**Issue by dlandtaa** [dpa99c/cordova-plugin-firebasex#802]
# Documentation issue

I am attempting to implement google login for my app. It's not clear to me based on the documentation for this plugin exactly how that works. I have been able to put some code together that seems to work based on guesses and experimentation but I'm not sure if it's really the right way to do it. If somebody can verify the validity of this approach, I'd be glad to update the docs with an example.

```
// cordova app code

window.FirebasePlugin.authenticateUserWithGoogle(clientId, credential => {
    window.FirebasePlugin.signInWithCredential(credential, () => {
        FirebasePlugin.getCurrentUser(user => {
            // verify user with our server and store basic user data here
            const googleProvider = user.providers.find((p: any) => p.providerId === 'google.com');
            const googleAccountId = googleProvider.uid;
            const idToken = credential.idToken;
            myService.validateGoogleAuth(googleAccountId, idToken);
        });
    });
});


// web service code

const { OAuth2Client } = require('google-auth-library');

async verifyGoogleAuth(accountId: string, idToken: string): Promise<boolean> {
    const googleAuthClient = new OAuth2Client(MY_GOOGLE_OAUTH_WEB_CLIENT_ID);

    const ticket = await this.googleAuthClient.verifyIdToken({
        idToken,
        audience: MY_GOOGLE_OAUTH_WEB_CLIENT_ID
    });

    const payload = ticket.getPayload();
    const googleUserId = payload.sub;
    return clientUserId === googleUserId;
}
```

In the past I've used the [cordova-plugin-googleplus](https://github.com/EddyVerbruggen/cordova-plugin-googleplus) plugin to achieve this functionality but it's difficult to get that plugin to play nicely with this one so I'm trying to use this one for google auth.

In particular, with the other plugin, after the user signs in you get their google user id along with an id token. We pass these to our back end server where we use those values with another google server api to verify the id token is valid. Is that necessary with this plugin? Does `signInWithCredential()` take care of that step or should we still do that ourselves as well?

We generally also store information about their google account include the ID, name, email, etc. in our back end.

**Comment by dpa99c** [comment]
This plugin just wraps the native Firebase SDK components so doesn't perform any additional validation on top of what the Firebase SDK itself performs. If you want to store/validate Google account info on your back end then your above code seems appropriate

**Comment by dlandtaa** [comment]
Great, thank you for verifying that. As promised, [here is a PR](https://github.com/dpa99c/cordova-plugin-firebasex/pull/805) to update the documentation related to this subject.
