### ISSUE TITLE
adding this plugin increase the apk/aab file in more then 10MB

### ISSUE THREAD

**Issue by EYALIN** [dpa99c/cordova-plugin-firebasex#804]
adding this plugin increases the apk/aab file by more than 10MB, why is that?
can I reduce it by using only analytics?

cordova 11.0.0
Ionic 6 - Angular
Andorid

**Comment by dpa99c** [comment]
This plugin includes multiple components of the Firebase SDK hence the increase in size.
If you don't need/wish to use the majority of these components in your app, and only require analytics, consider using [cordova-plugin-firebase-analytics](https://github.com/chemerisuk/cordova-plugin-firebase-analytics) instead

**Comment by EYALIN** [comment]
@dpa99c thank you very much. you are right
