### ISSUE TITLE
ionic 5 (cordova-android 12,targetSdkVersion-33,compileSdkVersion-24) some android devices not token generate

### ISSUE THREAD

**Issue by krishnawaghmode01** [dpa99c/cordova-plugin-firebasex#813]
![Screenshot from 2023-05-29 09-20-04](https://github.com/dpa99c/cordova-plugin-firebasex/assets/106731437/c3fdc611-8022-4596-a364-38c2a46e8ce1)

**Comment by rafaelwake** [comment]
I have the same issue.

**Comment by dpa99c** [comment]
Look like you are invoking the plugin before the `deviceready` event has fired.

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) as a know working codebase for reference.

If you are able to reproduce the issue in the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test), please open a new issue and fill out the issue template in full.
