### ISSUE TITLE
The fuction onMessageReceived not working in foreground

### ISSUE THREAD

**Issue by leferami** [dpa99c/cordova-plugin-firebasex#815]
The fuction onMessageReceived not working in foreground for ios in ionic 6, but in Android is all good,  

I don't know what might be happening in android it works wonderfully but in ios it doesn't invoke the function. When it's in the background the notification does arrive

**Comment by dpa99c** [comment]
Tested using [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) on iPhone X running iOS 16.5 and it works fine:

<img width="300" src="https://github.com/dpa99c/cordova-plugin-firebasex/assets/2345062/fdb62c09-0aa2-453c-87e4-4adb49028b30"/>

Please build and run the example project as a working reference using its [built-in messaging client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to validate the functionality.
Note that the JSON structure of the FCM messages is essential for the plugin to work correctly. You can refer to the example messages in the example project for reference.
