### ISSUE TITLE
How to calling function in ionic3?

### ISSUE THREAD

**Issue by JeffreyTan1001** [dpa99c/cordova-plugin-firebasex#82]
Hi, how to calling function like this.firebase.hasPermission().then(xxx)? I'm not able to use this within ionic 3 project.

I'm getting error when calling any function
Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function

**Comment by dpa99c** [comment]
You need to call the plugin directly via its Javascript API as discussed in #50 
Since this appears to be confusing people, I'll add a section to the documentation about using this plugin fork with Ionic.

**Comment by JeffreyTan1001** [comment]
Isn't no need to import @ionic-native/firebase anymore? 
Can provide some simple example? 

Haha, I'm bit confused on this

**Comment by dpa99c** [comment]
I've added a new section to the documentation: 
https://github.com/dpa99c/cordova-plugin-firebasex#ionic-3

**Comment by JeffreyTan1001** [comment]
Thanks for answer, you’re really great and awesome.

so isn’t means can remove completely for @ionic-native/firebase with this implementation? and with this implementation no need to declare the library as ionic-native, just (<any>window).FirebasePlugin will do?

Besides, with this implementation can testing within ionic-serve right?

**Comment by dpa99c** [comment]
Yes you can remove the ionic native wrapper and just use the JS API
