### ISSUE TITLE
cordova prepare ios fails if deployment-target is set to a 3 number version, like 12.3.0

### ISSUE THREAD

**Issue by ndrake** [dpa99c/cordova-plugin-firebasex#822]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

With version 16.1.0-cli of this plugin, if you have a deployment-target specified in your app with 3 numbers, like 12.3.0:
`<preference name="deployment-target" value="12.3.0" />`

when you run `cordova prepare ios` it will fail with:

`Cannot read properties of null (reading '1')` 

This is happening in scripts/ios/helper.js on line 190:

`IPHONEOS_DEPLOYMENT_TARGET = podFile.match(iosDeploymentTargetPodRegEx)[1];`

due to a regex issue not matching 12.3.0

This regex could be a potential fix: `/platform :ios, '(\d+\.\d+\.?\d?)'/`, as it matches both 12.0 and 12.3.0, but I haven't done more testing.

**Expected behavior:**

Using plugin version 14.2.1-cli a deployment-target of 12.3.0 worked fine

**Steps to reproduce:**

See this fork of the firebaseex test repo: https://github.com/ndrake/cordova-plugin-firebasex-test/tree/bug/deployment-target-issue

Basically:

* Set deployment-target to `12.3.0`
* Update package.json to use version `16.1.0-cli` of this plugin
* Update package.json to use cordova-ios `7.0.0`
* `cordova platform add ios`
* `cordova prepare ios`

**Screenshots**

**Environment information**

- Cordova CLI version 
	- 12.0.0 (cordova-lib@12.0.1)
- Cordova platform version
	- `cordova platform ls`
```
Installed platforms:
  ios 7.0.0
Available platforms:
  android
  browser
  electron
```
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
```
cordova-custom-config 5.1.1 "cordova-custom-config"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-customfcmreceiver 1.0.0 "Custom FCM Receiver"
cordova-plugin-dialogs 3.0.0-dev "Notification"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-facebook-connect 3.2.0 "Facebook Connect"
cordova-plugin-firebasex 16.1.0-cli "Google Firebase Plugin"
cordova-plugin-hello-c 1.1.1 "Hello"
cordova.plugins.diagnostic 7.1.1 "Diagnostic"
```

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`

```
ProductName:		macOS
ProductVersion:		13.5
BuildVersion:		22G74
```
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - `node -v`
```
v16.15.0
```
- XCode version
```
14.3.1
```

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```

**Console output**
<details>
<summary>console output</summary>

```

cordova-custom-config: Skipping auto-restore of config file backup(s)
Overwriting existing resource file at platforms/ios/FirebaseTest/Resources/res/ios/sound/blackberry.caf
Overwriting existing resource file at platforms/ios/FirebaseTest/Resources/res/ios/sound/crystal.caf
Overwriting existing resource file at platforms/ios/FirebaseTest/Resources/res/ios/sound/msn.caf
Overwriting existing resource file at platforms/ios/FirebaseTest/Resources/res/ios/pn-actions.json
cordova-plugin-firebasex: Preparing Firebase on iOS
Cannot read properties of null (reading '1')

```

</details><br/><br/>

**Other information:**

**Comment by Rafayon** [comment]
Hey, have you found a solution to this? It happens to me with:
Deployment Target: 13.0.0
Firebasex: 16.1.0
ios: 6.1.1

**Comment by Rafayon** [comment]
Thanks! I changed mine to 13.0 and it worked. However in the future it might pose an issue if we need a minor version (13.0.1 etc).

**Comment by mreis1** [comment]
same problem here: 
in config.xml updated: 
<preference name="deployment-target" value="13" />
to: 
<preference name="deployment-target" value="13.0" />
and it worked as @Rafayon suggested
