### ISSUE TITLE
Android Notification Icons - Won't Build

### ISSUE THREAD

**Issue by bcolflesh** [dpa99c/cordova-plugin-firebasex#825]
Using the example from "Android Notification Icons":

`<platform name="android">
    <resource-file src="res/android/drawable-mdpi/notification_icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
    <resource-file src="res/android/drawable-hdpi/notification_icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
    <resource-file src="res/android/drawable-xhdpi/notification_icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
    <resource-file src="res/android/drawable-xxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
    <resource-file src="res/android/drawable-xxxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
</platform>
`

No longer builds in the latest Cordova, I think because all the icon paths have changed since the introduction of adaptive icons. I've tried specifying the new paths with the icon file in there, etc - but no build, no bueno,

Does someone have a working example with the current Cordova or workaround for this they can post?

**Comment by bcolflesh** [comment]
Ok, it's choking on this from the docs:

<platform name="android">
    <config-file target="AndroidManifest.xml" parent="/manifest/application">
        <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
    </config-file>
</platform>

Execution failed for task ':app:mergeReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
   > Resource compilation failed (Failed to compile resource file: C:\Users\myapp_path\platforms\android\app\src\main\res\xml\config.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[35,140]
     Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?meta-data&android:name&android). Check logs for more details.

So this must not be the correct XML anymore - does anyone have a working replacement?

**Comment by kalwinskidawid** [comment]
Bump

Did u resolve problem?

**Comment by bcolflesh** [comment]
No, but I haven't come back to this plugin while I worked on other stuff - it seems like it has numerous issues since the new Firebase SDK came out, hopefully those get ironed out.

If someone has a working icon notifications setup, I'd sure appreciate an example.

**Comment by dpa99c** [comment]
Fixed by https://github.com/dpa99c/cordova-plugin-firebasex/pull/836

Please see the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) for a working illustration of Android notification icons

**Comment by olehhrytsyshyn** [comment]
> Ok, it's choking on this from the docs:
> 
> `<platform name="android"> <config-file target="AndroidManifest.xml" parent="/manifest/application"> <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" /> </config-file> </platform>`
> 
> Execution failed for task ':app:mergeReleaseResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable
> > Resource compilation failed (Failed to compile resource file: C:\Users\myapp_path\platforms\android\app\src\main\res\xml\config.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[35,140]
> > Message: http://www.w3.org/TR/1999/REC-xml-names-19990114#AttributePrefixUnbound?meta-data&android:name&android). Check logs for more details.
> 
> So this must not be the correct XML anymore - does anyone have a working replacement?

You should add `xmlns:android="http://schemas.android.com/apk/res/android"` to `config-file` tag:

```<config-file parent="/manifest/application" target="AndroidManifest.xml" xmlns:android="http://schemas.android.com/apk/res/android">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>```
