### ISSUE TITLE
Firebase version compatible issue with admob_plus

### ISSUE THREAD

**Issue by adigujjar** [dpa99c/cordova-plugin-firebasex#829]
[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In Podfile:
    Firebase/Core (= 10.10.0) was resolved to 10.10.0, which depends on
      FirebaseAnalytics (~> 10.10.0)

    GoogleTagManager (= 7.4.3) was resolved to 7.4.3, which depends on
      FirebaseAnalytics (< 11.0, >= 9.0)

CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (< 11.0, = 10.14.0, >= 7.0)

  In Podfile:
    Firebase/Core (= 10.10.0) was resolved to 10.10.0, which depends on
      FirebaseAnalytics (~> 10.10.0) was resolved to 10.10.0, which depends on
        FirebaseAnalytics/AdIdSupport (= 10.10.0) was resolved to 10.10.0, which depends on
          GoogleAppMeasurement (= 10.10.0)

    Google-Mobile-Ads-SDK (~> 10.6.0) was resolved to 10.6.0, which depends on
      GoogleAppMeasurement (< 11.0, >= 7.0)

**Comment by adigujjar** [comment]
@dpa99c  any help

**Comment by dpa99c** [comment]
Use the `IOS_FIREBASE_SDK_VERSION` and `IOS_GOOGLE_TAG_MANAGER_VERSION` [plugin variables](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#plugin-variables) to align the Firebase SDK version required by this plugin with that required by AdMob plugin.
