### ISSUE TITLE
Build error IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by loancarre** [dpa99c/cordova-plugin-firebasex#834]
hello,

I'am sorry but i cant build an ios app with firebasex, i have an error that tell me: " iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.0.99." and this cause failed build
i search a solutions in issues but i dont find one, can you help me please ?

Thanks

<img width="584" alt="Capture d’écran 2023-10-03 à 10 13 13" src="https://github.com/dpa99c/cordova-plugin-firebasex/assets/33637992/c194210b-dda4-4aa8-a72f-94848191fead">

**Comment by AdrGeorgescu** [comment]
I have the same issue after updating to macos Sonoma, Xcode 15. I am using cordova 7.0.1
I created a basic react app and added the `cordova-plugin-firebasex` plugin. 

I followed all the instruction from this issue: https://github.com/dpa99c/cordova-plugin-firebasex/issues/830#issuecomment-1725189302 but it didn't help.

`pod install` returns the following error:
```
[!] CocoaPods could not find compatible versions for pod "FirebaseAnalytics":
  In snapshot (Podfile.lock):
    FirebaseAnalytics (< 11.0, = 10.10.0, >= 9.0, ~> 10.10.0)

  In Podfile:
    Firebase/Core (= 10.15.0) was resolved to 10.15.0, which depends on
      FirebaseAnalytics (~> 10.15.0)

Specs satisfying the `FirebaseAnalytics (< 11.0, = 10.10.0, >= 9.0, ~> 10.10.0), FirebaseAnalytics (~> 10.15.0)` dependency were found, but they required a higher minimum deployment target.
```

I updated the `platform :ios, '16.0'` in my `Podfile` (also in the `config.xml` - cordova). I tried all values from 10 to 17.

Same error with the `cordova-plugin-firebasex-test` project.

**Comment by bvcoskun** [comment]
I added this to my Podfile maybe it would help:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
	      target.build_configurations.each do |config|
		      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
	      end
    end
end
```

**Comment by dpa99c** [comment]
Please try to build the [example project](https://github.com/dpa99c/cordova-plugin-firebasex).

If you are able to reproduce the issue in the example project, please open a new issue and fill out the issue template in full, including steps to reproduce in the example project and details of test devices used to reproduce the issue.
