### ISSUE TITLE
IOS_FIREBASE_SDK_VERSION flag is ignored

### ISSUE THREAD

**Issue by AdrGeorgescu** [dpa99c/cordova-plugin-firebasex#838]
**Current behavior:**

The `IOS_FIREBASE_SDK_VERSION` flag is ignored because the Firebase pod names were updated in this PR: https://github.com/dpa99c/cordova-plugin-firebasex/pull/811/files 
but the `firebasePodRegex` was not updated in the `/scripts/ios/helpers.js` file.

IMPORTANT: the source code from npmjs.com (https://www.npmjs.com/package/cordova-plugin-firebasex?activeTab=code) is different from the source code on github, even tho they are the same version: `6.1.0`

NOTE: using the command below:
```cordova plugin add cordova-plugin-firebasex --variable IOS_FIREBASE_SDK_VERSION=10.15.0```
will work because it will use the code from npmjs.com where the pod names are not updated yet.

**Expected behavior:**

The `IOS_FIREBASE_SDK_VERSION` flag should update the pods versions.

**Comment by bvcoskun** [comment]
Yes, I have the same issue. Podfile.lock still has 10.10.0 and i get "pod install" error during add platform. 

```
[!] CocoaPods could not find compatible versions for pod "FirebaseInstallations":
  In snapshot (Podfile.lock):
    FirebaseInstallations (= 10.10.0, ~> 10.0, ~> 10.10.0)
  In Podfile:
    Firebase/Installations (= 10.15.0) was resolved to 10.15.0, which depends on
      FirebaseInstallations (~> 10.15.0)
    Firebase/Messaging (= 10.15.0) was resolved to 10.15.0, which depends on
      FirebaseMessaging (~> 10.15.0) was resolved to 10.15.0, which depends on
        FirebaseInstallations (~> 10.0)
Specs satisfying the `FirebaseInstallations (= 10.10.0, ~> 10.0, ~> 10.10.0), FirebaseInstallations (~> 10.0), FirebaseInstallations (~> 10.15.0)` dependency were found, but they required a higher minimum deployment target.
```
