### ISSUE TITLE
[FR][IOS] Impementation of initiateOnDeviceConversionMeasurement method

### ISSUE THREAD

**Issue by SaintNK** [dpa99c/cordova-plugin-firebasex#843]
Hello! Is it possible to proxy initiateOnDeviceConversionMeasurement() method of the FirebaseAnalytics to the javascript part in this plugin?
It will greatly help to measure conversion of marketing campaigns on iOS devices
Documentation - https://firebase.google.com/docs/tutorials/ads-ios-on-device-measurement/step-3#objective-c

**Comment by dpa99c** [comment]
Implemented and released in v16.3.0
