### ISSUE TITLE
@dpa99c @peterdsp

### ISSUE THREAD

**Issue by Pbonmars-20031006** [dpa99c/cordova-plugin-firebasex#845]
@dpa99c @peterdsp 

Yes `pod repo update` is working, But if anyone is using Flutter please update the Firebase library in the `pubspec.yml` file first then it works.

hiya, I'm using Flutter, in that case, to which version should I update the firebase in pubspec.yaml file

_Originally posted by @jay-benzatine in https://github.com/dpa99c/cordova-plugin-firebasex/issues/830#issuecomment-1727340622_

**Comment by jay-benzatine** [comment]
@Pbonmars-20031006 Hello,

I have used this Firebase version in my project. Please try it and let me know it's working or not?


```
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_performance: ^0.9.2+5
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5
  firebase_remote_config: ^4.2.5
```

**Comment by dpa99c** [comment]
Closing as Flutter is not a supported build environment for this plugin
