### ISSUE TITLE
ios: missing FirebaseAnalytics pod

### ISSUE THREAD

**Issue by jkorrek** [dpa99c/cordova-plugin-firebasex#847]
**Current behavior:**

After updating to version 16.2.0, the iOS build fails with a compile error ["Module 'FirebaseAnalytics' not found"](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L8).

I think this is related to the switch to the Firebase product pods (https://github.com/dpa99c/cordova-plugin-firebasex/pull/811).
I guess the Analytics package was in inherit dependency previously and now, after switching to the product pods, is no longer included automatically.

Adding an explicit dependency to the podfile for "FirebaseAnalytics" fixes the issues.

**Comment by dpa99c** [comment]
Resolved by #848
