### ISSUE TITLE
Re: Update your apps to the latest Firebase Cloud Messaging APIs and SDKs

### ISSUE THREAD

**Issue by hitestmail** [dpa99c/cordova-plugin-firebasex#849]
# Feature request

- Recently we got an email from the Firebase about their deprecating APIs.
- I am using cordova-plugin-firebasex in my app to send push notifications from both iOS and Android.
- They are stating below two points that we are using from deprecating SDK.
<html>
<body>
<blockquote type="cite" style="color: rgb(34, 34, 34); font-family: Arial, Helvetica, sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div dir="ltr"><div style="background-color: rgb(245, 245, 245);"><div style="padding: 10px 0px;">
Your recent usage of impacted APIs/features: Server Keys<br/>Your recent usage of impacted APIs/features: Legacy HTTP protocol
--

</div></div></div></blockquote>
</body>
</html>
- Can we please get an update about this as soon as possible.

Thank you,

**Comment by dpa99c** [comment]
Server Keys are managed in the Firebase console and nothing to do with this plugin:
https://firebase.google.com/docs/cloud-messaging/auth-server#migrate-legacy-server-keys


Legacy HTTP protocol relates to how you are sending messages from your server to the Firebase Cloud Messaging service - again nothing to do with this plugin:
https://firebase.google.com/docs/cloud-messaging/http-server-ref

On a side note, although the plugin by default pins recent version of Firebase SDK components when installed, you can override this with plugin variables to install the very latest Firebase SDKs if you so wish:
https://github.com/dpa99c/cordova-plugin-firebasex#plugin-variables
