### ISSUE TITLE
Not supported for latest rxjs

### ISSUE THREAD

**Issue by Tilakraj0308** [dpa99c/cordova-plugin-firebasex#854]
Just wanted to be sure, is it only supported for rxjs version 5.5.0 and 6.5.0 ?

**Comment by dpa99c** [comment]
You have not filled out the issue template so have provided insufficient information therefore this issue will be closed as invalid.

Please follow the [documented steps](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#reporting-a-bug-or-problem) for reporting an issue.

If you are able to reproduce the issue in the example project, please open a new issue and fill out the issue template in full, including steps to reproduce in the example project and details of test devices used to reproduce the issue.
