### ISSUE TITLE
Not able to receive push notification with Cordova firebasex plugin Android 12 & 13

### ISSUE THREAD

**Issue by sw-tt-vidhithakkar** [dpa99c/cordova-plugin-firebasex#855]
Hello,

I am getting logs of platformApplicationDisabled as shown in attached screenshot and never fires onMessageReceived event 
![tmp_599359a6-4994-44f2-aa8d-e34758147c08](https://github.com/dpa99c/cordova-plugin-firebasex/assets/78071400/c41cde0d-45cc-48f5-9ba4-6491532bc7d3)
notification.

I am using below libraries.
Cordova - 11
Android - 12
cordova-plugin-firebasex - 16.3.0

Please let me know if anyone have any information on this.

**Comment by dpa99c** [comment]
You have not filled out the issue template so have provided insufficient information therefore this issue will be closed as invalid.

Please follow the [documented steps](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#reporting-a-bug-or-problem) including:
- Build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test), use its [built-in FCM client](https://github.com/dpa99c/cordova-plugin-firebasex-test?tab=readme-ov-file#testing-cloud-messaging) to test Cloud Messaging.
- Check existing issues, for example https://github.com/dpa99c/cordova-plugin-firebasex/issues/851: some non-Google Android devices don't receive notifications when the app is closed.

If you are able to reproduce the issue in the example project, please open a new issue and fill out the issue template in full, including steps to reproduce in the example project and details of test devices used to reproduce the issue.
