### ISSUE TITLE
Is it still usable with cordova 8 and v4.x ?

### ISSUE THREAD

**Issue by globules-io** [dpa99c/cordova-plugin-firebasex#86]
Looking for build the latest available version for Cordova 8 so was thinking about forking then rebasing on a v4.x tag. Been trying the v4.0.1 which works fine on Android but not on iOS.
Would v4.10 work? Initial test did not work on Android but maybe we did something wrong..
Thanks. Cordova 8.1.2 + iOS5.0.0

**Comment by dpa99c** [comment]
v4 contains many bugs which have been fixed in the latest version.
I recommend updating to `cordova@9` and using the latest version - older versions are not supported.

**Comment by globules-io** [comment]
Ok thanks, will upgrade...
