### ISSUE TITLE
Cannot read properties of  null (reading '1')

### ISSUE THREAD

**Issue by danemco** [dpa99c/cordova-plugin-firebasex#868]
# Bug report

**CHECKLIST**
- [X] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [X] I confirm this is a suspected bug or issue that will affect other users

- [X] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [X] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [X] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

After upgrading to cordova-plugin-firebasex version 16.4.0, I get this error after running `cordova prepare ios`:

`Cannot read properties of null (reading '1')`

Here's the output with the `--verbose` flag turned on:

```
Prepared iOS project successfully
Executing script found in plugin cordova-plugin-firebasex for hook "after_prepare": plugins/cordova-plugin-firebasex/scripts/after_prepare.js
cordova-plugin-firebasex: Preparing Firebase on iOS
Cannot read properties of null (reading '1')
TypeError: Cannot read properties of null (reading '1')
    at Object.applyPodsPostInstall (/Users/dan/dev/members.ldslifecoaches.com/app/plugins/cordova-plugin-firebasex/scripts/ios/helper.js:226:84)
    at module.exports (/Users/dan/dev/members.ldslifecoaches.com/app/plugins/cordova-plugin-firebasex/scripts/after_prepare.js:157:34)
    at runScriptViaModuleLoader (/Users/dan/dev/members.ldslifecoaches.com/app/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/Users/dan/dev/members.ldslifecoaches.com/app/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /Users/dan/dev/members.ldslifecoaches.com/app/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40
```

I'm using Cordova version 12 but with cordova-ios 6.2.0 for this project. I can verify that this same problem exists on cordova-ios 7.0.0.

**Comment by danemco** [comment]
No, but I ignore the error and it seems to build anyway. Perhaps that's not
a good idea...

**Comment by dylanfpaul** [comment]
having the exact same issue with both cordova-io@6 and cordova-ios@7. I am also using cordova v 12.

**Comment by dylanfpaul** [comment]
@danemco what was your deployment target set to for ios in config.xml? Like what is the exact string? I am pretty sure there is an outstanding issue that inolves using a deployment target that doesn't have two numbers. For instance, my deployment target used to be "17" and after switching it to "17.0" I have gotten past this error.

**Comment by danemco** [comment]
I don't see a "deployment target" value in my config.xml. Do you mean my
app version?
