### ISSUE TITLE
setConsent method implementation

### ISSUE THREAD

**Issue by dgnovo** [dpa99c/cordova-plugin-firebasex#873]
Hi @dpa99c ,
we're using your plugin on our cordova / ionic app to implement firebase analytics, but we noticed that is missing the setConsent method implementation. Will you implement this feature in the future?
Thanks in advance for any response.

**Comment by pinguluk** [comment]
I've implemented the changes myself https://github.com/pinguluk/cordova-plugin-firebasex/tree/develop, but I couldn't get the iOS to work for some reason yet
