### ISSUE TITLE
Inquiry About Addition of Google Analytics Consent Options for Ad Personalization and User Data

### ISSUE THREAD

**Issue by bialek-e-file** [dpa99c/cordova-plugin-firebasex#875]
I am reaching out to inquire about a potential enhancement to the Firebasex that could significantly benefit users who rely on Google Analytics.

As you know, with the increasing importance of privacy and data protection, managing user consents for cookies and data collection has become a crucial aspect of website management. Google Analytics offers options for ad personalization (ad_personalization) and access to user data (ad_user_data), which are essential for delivering a tailored advertising experience while adhering to privacy regulations.

Ad Personalization Consent (ad_personalization): This would allow users to opt-in or out of personalized advertising delivered by Google Analytics.

User Data Access Consent (ad_user_data): This would give users the option to control whether their data can be used by Google Analytics for advertising purposes.

Could you please share if there are any plans to incorporate these specific consent options into Firebasex? If so, do you have an estimated timeline for when these features might be available?

**Comment by bialek-e-file** [comment]
Thanks, this is what I needed

**Comment by dpa99c** [comment]
Resolved by release of `cordova-plugin-firebasex@16.5.0`
