### ISSUE TITLE
[FEATURE] Method to get users FCM registered info and subscribed topics

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#88]
# Feature request
FCM allows for querying a token/deviceID to see which topics it is currently subscribed to.  I am doing this from my server now using `php-fcm` but would like to have this feature in the app itself.  

- A descriptive title 
   deviceInfo - retrieve users current registered info about their token ID.

- A description of the problem you're trying to solve, including why you think this is a problem
Trying to have the client app update FCM directly versus having to pass everything to a backend server to process and update FCM on behalf of that user.

- An overview of the suggested solution
Adding:  
     `window.FirebasePlugin.deviceInfo(function(data) {  ...   }`

     `data` =
```
(
    [applicationVersion] => 0.2.86
    [connectDate] => 2019-07-24
    [application] => com.myapp
    [scope] => *
    [authorizedEntity] => 215687698299
    [rel] => Array
        (
            [topics] => Array
                (
                    [C1001_5] => Array
                        (
                            [addDate] => 2019-08-07
                        )

                    [C1001_5_34] => Array
                        (
                            [addDate] => 2019-08-07
                        )

                    [C1001] => Array
                        (
                            [addDate] => 2019-08-07
                        )

                    [appRegister] => Array
                        (
                            [addDate] => 2019-07-24
                        )
                )
        )
    [connectionType] => WIFI
    [platform] => IOS

```
- Use case: why should this be implemented?
One use case example is for when a users token/deviceID has changed - let the app pull all the current subscriptions for the old ID, unsubscribe the old ID from all the topics, and then subscribe the new ID to all the same topics.

- If the feature changes current behavior, reasons why your solution is better
Server side version of this: https://php-fcm.readthedocs.io/en/latest/device.html

**Comment by dpa99c** [comment]
Good idea - will add to TODO list
