### ISSUE TITLE
Update iOS Firebase SDK component version to v10.23.0, fixes crash on startup

### ISSUE THREAD

**Issue by ben-kn-app** [dpa99c/cordova-plugin-firebasex#880]
# Bug report

**Current behavior:**

There is a known ios-sdk-firebase bug see [Github Issue Build with Xcode 15.3, run on iOS 17.4, 100% crash on launch: pb_enc_bool EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)](https://github.com/firebase/firebase-ios-sdk/issues/12457) which is solved by the official firebase ios sdk in version 10.23.0 

Could this plugin be updated to use this new firebase ios sdk component? 

**Expected behavior:**

crash on launch: pb_enc_bool 

**Steps to reproduce:**

Follow the steps in the above github issue

**Comment by ben-kn-app** [comment]
This would also fix issue https://github.com/dpa99c/cordova-plugin-firebasex/issues/860

**Comment by ben-kn-app** [comment]
There is already an open PR that bumps the ios firebase sdk to 10.22.0, which already addresses FirebaseSessions crash on startup https://github.com/dpa99c/cordova-plugin-firebasex/pull/878

**Comment by haziqali-2019** [comment]
any idea why setting "IOS_FIREBASE_SDK_VERSION": "10.23.0" in package.json gives an error in build? According to documentation, this should update firebase sdk. Manually updating plugin.xml seems to work.

**Comment by pinguluk** [comment]
> any idea why setting "IOS_FIREBASE_SDK_VERSION": "10.23.0" in package.json gives an error in build? According to documentation, this should update firebase sdk. Manually updating plugin.xml seems to work.

[_The following Cordova plugin variables are supported by the plugin. Note that these must be set at plugin installation time. If you wish to change plugin variables, you'll need to uninstall the plugin and reinstall it with the new variable values._](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#plugin-variables)

**Comment by roundlakedan** [comment]
Just wanted to echo that I was able to fix this by going into ~/plugins/cordova-plugin-firebasex/plugins.xml and manually incrementing the version to the latest for the Firebase-related plugins. Testing seems to indicate this works fine - no more crashing on startup and push notifications seem to send without any other amendments necessary.
<img width="960" alt="Screenshot 2024-04-16 at 5 53 54 AM" src="https://github.com/dpa99c/cordova-plugin-firebasex/assets/22779234/76cd8a52-a42e-4f7d-b809-623277b47434">

**Comment by dpa99c** [comment]
Resolved by release of `cordova-plugin-firebasex@16.5.0`

**Comment by dFelinger** [comment]
For those who still has problem with 16.5.0 and adhoc release build, just add empty .swift file in the root of your project.

Solution found here: https://github.com/nanopb/nanopb/issues/949#issuecomment-2018207748
