### ISSUE TITLE
Build failed on cordova 7.1

### ISSUE THREAD

**Issue by sjouljian** [dpa99c/cordova-plugin-firebasex#899]
Im using latest version of the plugin in cordova, while building on ios im getting the following error:

**[!] CocoaPods could not find compatible versions for pod "FirebaseInAppMessaging":
  In Podfile:
    FirebaseInAppMessaging (= 11.2.0-beta)

Specs satisfying the `FirebaseInAppMessaging (= 11.2.0-beta)` dependency were found, but they required a higher minimum deployment target.**

please suggest.

**Comment by dpa99c** [comment]
`cordova-plugin-firebasex@17` by default pins Firebase iOS SDK v11 which increases the minimum iOS deployment target to 13.0
so you'll need to set this in your `config.xml`:

```
    <platform name="ios">
    	<preference name="deployment-target" value="13.0" /> 
    </platform>
```

**Comment by dpa99c** [comment]
then remove/re-add the ios platform: 
`cordova platform rm ios && cordova platform add ios && cordova prepare ios`

**Comment by sjouljian** [comment]
> `cordova-plugin-firebasex@17` by default pins Firebase iOS SDK v11 which increases the minimum iOS deployment target to 13.0 so you'll need to set this in your `config.xml`:
> 
> ```
>     <platform name="ios">
>     	<preference name="deployment-target" value="13.0" /> 
>     </platform>
> ```

i did this already but still not working. note that i have cordova project but i build it remotely using Ionic AppFlow.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-firebasex?tab=readme-ov-file#remote-cloud-build), this plugin will not work in remote cloud build environments like Ionic AppFlow because they don't execute the Cordova hook scripts that are essential for this plugin to function.
If you wish to use this plugin, you will need to develop and build your application in a local build environment

**Comment by sjouljian** [comment]
weird. Ive been using it for years and it was working normally. Im only having the problem now with the latest version (v17).

**Comment by dpa99c** [comment]
you can play about with the settings but I can't support your efforts because the development environment is not under your control. maybe try asking on the Ionic forums?
