### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by aaadipop** [dpa99c/cordova-plugin-firebasex#903]
# Bug report

**CHECKLIST**
- [ x ] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ ] I confirm this is a suspected bug or issue that will affect other users

- [ x ] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) 

- [ x ] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ ] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

first screenshot is the output from `ionic cordova build ios` run from cli and the second one is the build output from xcode,
same error is present in my project and in the `cordova-plugin-firebasex-test` project

**Steps to reproduce:**
I cloned the example project, run `npm i`, `cordova platform add ios` and `cordova run ios` and ended up with the bellow error ( screens )

I have a fresh XCode install and I have only one simulator, for IOS 18.1, should I get an older one? ( I'm a bit out of space for doing that :) )

**Screenshots**
<img width="1592" alt="Capture d’écran 2024-11-01 à 10 27 14" src="https://github.com/user-attachments/assets/019a850e-b434-4c56-afb5-b5bfd9cbbbd1">
<img width="1215" alt="Capture d’écran 2024-11-01 à 10 27 54" src="https://github.com/user-attachments/assets/89eaf848-2a2d-4a30-afcb-ff5ed970b546">

**Environment information**

- Cordova CLI version 
	- `cordova -v` : 11.1.0
- Cordova platform version
	- `cordova platform ls`:
	```
        Installed platforms:
          ios 7.1.1
        Available platforms:
          android ^10.1.1
          browser ^6.0.0
          electron ^3.0.0
          osx ^6.0.0 (deprecated)
        ```

- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_iOS build issue:_
- Node JS version
    - `node -v` : v20.18.0
- XCode version: Version 16.1 (16B40)

**Comment by dpa99c** [comment]
Looks like you need to update Cocoapods to the latest version:
https://github.com/firebase/firebase-ios-sdk/issues/13996

**Comment by aaadipop** [comment]
yep, updated cocoapods from `1.16.1` to `1.16.2` and `cordova-plugin-firebasex` from `^17.0.0` to `^18.0.3` and works good with xCode `16.1`
