### ISSUE TITLE
Fabric failed to download settings error

### ISSUE THREAD

**Issue by rolinger** [dpa99c/cordova-plugin-firebasex#91]
Researching this issue in my Xcode Console:

`[Fabric] failed to download settings Error Domain=FABNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=21db289........745ce, content_type=application/json; charset=utf-8}`

And found some articles regarding it.  I use Fabric keyID for a Cordova-twitter plugin, but it seems this Fabric error might be related to Firebase. Is this something you have dealt with before?  Maybe about enabling FCM Crashlytics in FCM Console?

Found this thread related to it but not certain the direction I need to go.   
https://stackoverflow.com/questions/50269731/fabric-failed-to-download-settings-error-domain-fabnetworkerror-code-5

**Comment by rolinger** [comment]
I resolved the issue.  For anyone who comes across this issue here is what I did to resolve it.

1. Login to Fabric and link Fabric io app to Firebase project - if you don't have a Fabric account/app setup you will need to get one setup and then link it to your Firebase project (the linking can be done from within Fabric project management itself)
2. Ensure your Xcode project has your Fabric key referenced properly. In Xcode project go to Build Phases and under `Crashlytics` add your api key and secret to the run script
```
    Shell:  /bin/sh
         1. "${PODS_ROOT}/Fabric/run" 0a138288_API_KEY_9a2b5090bc0 5e58b8d03ac_FABRIC_SECRET_KEY_552d08350fe8
```

Adding Firebase/Pods only adds the script line: `"${PODS_ROOT}/Fabric/run"` - it doesn't add your keys/secret - you must do this manually.  I already had a key added to my project for a twitter plugin and thought that was sufficient (only needing to reference it once)...but it turns out the two are unrelated and you must add them to your project here for Crashlytics/Firebase to work (AFTER you link your Fabric project to your Firebase project)

3. in your projects pList file, add the Fabric key:	
```
        <key>Fabric</key>
	<dict>
		<key>APIKey</key>
		<string>0a138288_API_KEY_9a2b5090bc0</string>
		<key>Kits</key>
		<array>
			<dict>
				<key>KitInfo</key>
				<dict/>
				<key>KitName</key>
				<string>Crashlytics</string>
			</dict>
		</array>
	</dict>
```

**Comment by tsimbalar** [comment]
Thanks @rolinger for the detailed report and workaround. 

Is there anyway we could have this working without human intervention and "just work" from a fresh `git clone` ? 

I guess the initial `Fabric` plugin does something like that 🤔

**Comment by tsimbalar** [comment]
Not quite certain, but it looks like combining : 

- the hook that is present in the original _Fabric Crashlytics plugin_ so that we pass the Fabric API Key like in https://github.com/sarriaroman/FabricPlugin/blob/master/hooks/lib/ios-helper.js to the `run` script would help 
- adding the necessary key in info plist like https://github.com/sarriaroman/FabricPlugin/blob/9363a290e071ccd262da9d718aaf5a10a284e144/plugin.xml#L53-L81

could do the trick

**Comment by rolinger** [comment]
@tsimbalar - well, I think the plugin needs to have a variable to add or not to add Fabric to the Firebasex build.   Since Firebase Crashlytics can be used on its own OR linked/pulled from Fabric the installer should have options to choose which is your installation.   Here are some scenarios that would need to be evaluated during plugin install:
```
1. Users not using Fabric or Crashlytics - 
    * Do not install Fabric Firebasex crashlytics
    * google-services file has no keys for crashlytics, there for not installed.
2. Users only using Fabric
   * do not install Firebasex crashlytics
    * google-services file has no keys for crashlytics, there for not installed.
3. Users only using Crashlytics
    * Fabric not installed
    * crashlytic keys in google-services file, it will be installed.
4. Users who linked Fabric to Crashlytics
   * install Fabric with `cordova plugin add cordova-plugin-firebasex --FabricKey=asdfasdfasdf --FabricSecret=123412341234`
    * crashlytic keys in google-services file, it will be installed.
    * Frabric/Crashlytics linked together.
```

I think something like this would help eliminate app compile errors and issues
