### ISSUE TITLE
onMessageReceived not working when in foreground

### ISSUE THREAD

**Issue by michelsondan** [dpa99c/cordova-plugin-firebasex#92]

**Comment by dpa99c** [comment]
Please build and run the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) which validates and illustrates the plugin functionality.
You can use its built-in FCM v1 API client to send test notification messages and assert that `onMessageReceived` works properly when the app is in the foreground on both iOS & Android

**Comment by michelsondan** [comment]
I am sending with firebase console! why is it not working ?

![image](https://user-images.githubusercontent.com/22793811/63101697-41141680-bf82-11e9-95fc-73ed0a39540b.png)

![image](https://user-images.githubusercontent.com/22793811/63101829-8c2e2980-bf82-11e9-90a3-d6c37156f88f.png)

**Comment by dpa99c** [comment]
What is not working? That `onMessageReceived()` is not being called while the app is in the foreground or that a foreground notification is not being displayed when you expected it to be?

**Comment by michelsondan** [comment]
First,  thank you!
onMessageReceived is not being called while app is in foreground.

**Comment by dpa99c** [comment]
I would suggest building and running the example project app - change the package ID to the same as your own app so you can use the same Firebase config - and repeat the test.

**Comment by michelsondan** [comment]
I look on project, I don't see that it is an example that show how to use cordova-plugin-firebasex. I think it is not clear.

**Comment by dpa99c** [comment]
The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) is a Cordova app project which acts as a test harness for functional validator for `cordova-plugin-firebasex` as well as a code example of how the plugin is to be used.
The majority of interaction with the JS API of the plugin is in [index.js](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/www/js/index.js)

**Comment by michelsondan** [comment]
I am using the old version of corova-plugin-firebbase with no problem! I know how to use it.
Can it be, that in the new version, onMessageReceived not called in foreground, because I have not created a new channel ? again, in background it is working great!

**Comment by dpa99c** [comment]
Just added a couple of screencaptures of the example project to the README demonstrating receipt of notifications in both background and foreground:
https://github.com/dpa99c/cordova-plugin-firebasex/#cloud-messaging

The example app was built with v6.0.6 of the plugin to make the recordings.

**Comment by michelsondan** [comment]
I have tested the test example, and it is working good. 
Still can't find what I am doing wrong. I am Comparing your code to my code, can't find the problem. 
Still background message are ok, **foreground message are **not ok**.**
I am using quasar framework, maybe that?
 I am adding screen capture of my package and AndroidManifest. 

Please help. Thank you.

![image](https://user-images.githubusercontent.com/22793811/63222683-9edb7500-c1b3-11e9-86f9-4ae95abedccd.png)

![image](https://user-images.githubusercontent.com/22793811/63222727-07c2ed00-c1b4-11e9-8746-850139cb45d1.png)

**Comment by michelsondan** [comment]
I found the reason ..... 
I think that you should fix it -
the AndroidManifest is not updating from plugin.xml with this code:
`		<config-file target="AndroidManifest.xml" parent="application">
			<service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />
			<service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
				<intent-filter>
					<action android:name="com.google.firebase.MESSAGING_EVENT"/>
				</intent-filter>
			</service>
			<receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver"/>
			<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />
			<meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/>
		</config-file>
`
**so to fix that, I added this code in config.xml file that located in the root of cordova project.**

**Comment by michielcrabbe96** [comment]
@dpa99c I'm having the same problem as @michelsondan. The onMessageReceived callback is not  being called when the app is in foreground on Android. In all other cases it works sublime 👌.

This xml code of @michelsondan does seem to fix the issue.

> I found the reason .....
> I think that you should fix it -
> the AndroidManifest is not updating from plugin.xml with this code:
> ` <config-file target="AndroidManifest.xml" parent="application"> <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" /> <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService"> <intent-filter> <action android:name="com.google.firebase.MESSAGING_EVENT"/> </intent-filter> </service> <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver"/> <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" /> <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/> </config-file> `
> **so to fix that, I added this code in config.xml file that located in the root of cordova project.**

**Comment by dpa99c** [comment]
@michielcrabbe96 have you added the `notification_foreground` key to the notification payload as [outlined here](https://github.com/dpa99c/cordova-plugin-firebasex#android-foreground-notifications)?

Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app and using its built-in [FCM API client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to sent the pre-defined messages such as [notification.json](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json)

**Comment by michielcrabbe96** [comment]
> @michielcrabbe96 have you added the `notification_foreground` key to the notification payload as [outlined here](https://github.com/dpa99c/cordova-plugin-firebasex#android-foreground-notifications)?
> 
> Please try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) app and using its built-in [FCM API client](https://github.com/dpa99c/cordova-plugin-firebasex-test#messaging-client) to sent the pre-defined messages such as [notification.json](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json)

No, I did not specify the `notification_foreground` key. But as the documentation says, this key is just to show a notification while the app is in the foreground. If I interpreted this correctly?

The problem is just that `onMessageReceived` does not get called when the app is in the foreground. @michelsondan fix did solve this problem tho. But now I'm just wondering if it's possible to include the fix in this repo? 😃

**Comment by dpa99c** [comment]
The relevant `<config-file>` block is [defined in the `plugin.xml` of this plugin](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/plugin.xml#L37) and it's the responsibility of Cordova to translate that into the `AndroidManifest.xml`.

Note that there is a [bug in Cordova](https://github.com/apache/cordova-android/issues/809) where placing any `<config-file>` block in `config.xml` will cause Cordova to fail to add conflicting `<config-file>` blocks from `plugin.xml` (including this one). AFAIK that fix has not made it into a Cordova release yet so until the next version of `cordova` CLI is released, there's a workaround which I mention in the above issue.

**Comment by fascox** [comment]
The same thing happens to me. The call **onMessageReceived()** doesn't work when the app is in foreground or even in the background when tapping the system notification. in Xcode console I can see the notification message but next i get 
```
 FirebasePlugin[native] LOG: willPresentNotification: foreground notification alert=YES, badge=NO, sound=NO
 FirebasePlugin[native]: willPresentNotification: foreground notification
```

Sample Typescript code in Ionic 5

```
 this.firebase.onMessageReceived()
      .subscribe(msg => {
        if (this.platform.is('ios')) {
          console.log('ios message received: ', msg.aps.alert);
          this.toastService.showAlert(msg.aps.alert);
        } else {
          console.log('android message received: ', msg.body);
          this.toastService.showAlert(msg.body);
        }
      });
```
