### ISSUE TITLE
iOS - cordova-plugin-local-notifications compatibility

### ISSUE THREAD

**Issue by fgarcia5** [dpa99c/cordova-plugin-firebasex#95]
# Bug report

**Current behavior:**
This plugin works correctly. I have the problem when adding cordova-plugin-local-notifications (https://github.com/katzer/cordova-plugin-local-notifications), after adding it the "onMessageReceived" event does not fire.
If the application is in the background, the notification is received but when touching it "onNotification" does not fire. When the App is in foreground, it seems that the push do not arrive because the event in question is not triggered.

**Expected behavior:**
Necesito que convivan ambos plugins debido que debo enviar notificaciones locales y desde el servidor. Con cordova-plugin-firebase ambos funcionaban perfectamente.

**Environment information**

- Cordova CLI version 
	- `cordova -v` 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- `cordova platform ls` ios 5.0.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
        cordova-plugin-firebasex 6.0.7 "Google Firebase Plugin"
        cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"

_iOS build issue:_
- Node JS version
    - `node -v`10.10.0
    -  `npm -v`6.10.3
- XCode version 10.3

**Other information:**
I will publish the compatibility issue with the other plugin, but I turn here first because it seems more updated and because with cordova-plugin-firebase I did not have this problem.

Anyone used both plugins and managed to make them work?

Thanks in advance, regards.

**Comment by fgarcia5** [comment]
I implemented this branch of the plugin: https://github.com/Steffaan/cordova-plugin-local-notifications
The local notifications and push firebase function worked correctly.

**Comment by golyo** [comment]
This fork not working with cordova-plugin-firebasex 10.0.0 and upper

**Comment by mauliklogicalwings** [comment]
Hello
@fgarcia5 @dpa99c 
We are using  https://github.com/Steffaan/cordova-plugin-local-notifications(0.9.3)  and cordova-plugin-firebasex(13.0.0-cli) plugins in our cordova project. when iOS app in foreground and sent local notification, it throw error message
 
FirebasePlugin[native]: willPresentNotification: foreground notification not set

can you please help us to solve this?
Thanks

**Comment by Maho38** [comment]
Hello,

are there any updates for the problem? I also want to use both - local notifications and the firbeasex plugin.
Can anybody help me?

Thank you!

**Comment by marcostomazini** [comment]
> Hello,
> 
> are there any updates for the problem? I also want to use both - local notifications and the firbeasex plugin. Can anybody help me?
> 
> Thank you!

resolved in
https://github.com/dpa99c/cordova-plugin-firebasex/pull/573
