### ISSUE TITLE
App Breaks On Resume After First onMessageReceived

### ISSUE THREAD

**Issue by Abdulrahmanh95** [dpa99c/cordova-plugin-firebasex#97]
Hi,

After receiving & tapping the first notification and openening it, I click on home button (pause the app) so it's working in the background.

But when I resume it from the opened applications list, the app crashes and closes immediately!

However, resuming the application without tapping the first notification works fine.

Any ideas please?

**Comment by dpa99c** [comment]
Please try building & running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to eliminate the cause of issue being in your own code or another plugin.

If you are able to reproduce the issue in the example project, please complete the issue template to provide full details of the issue included crash details in the native console log, affected platform/version, etc.

**Comment by dpa99c** [comment]
Closed due to no response
