### ISSUE TITLE
verifyPhoneNumber Error on Android

### ISSUE THREAD

**Issue by atoyansk** [dpa99c/cordova-plugin-firebasex#98]
# Bug report

**Current behavior:**

When calling verifyPhoneNumber in Ionic Lab (Android), displays this error on console:
Cannot read property 'verifyPhoneNumber' of undefined

**Expected behavior:**
The SMS code should be sent.

**Steps to reproduce:**

1. Installed the plugin ionic cordova plugins add cordova-plugin-firebasex
2. Call verifyPhoneNumber (var window not declared)
3. Error is displayed

**Environment information**
Ionic:

   ionic (Ionic CLI)  : 4.12.0
   Ionic Framework    : ionic-angular 3.9.3
   @ionic/app-scripts : 3.2.1

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 8.0.0, browser 5.0.4
   Cordova Plugins       : 
- cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
- 	cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
- 	cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
- 	cordova-plugin-browsersync 0.1.7 "cordova-plugin-browsersync"
- 	cordova-plugin-camera 4.0.3 "Camera"
- 	cordova-plugin-device 2.0.3 "Device"
- 	cordova-plugin-file 6.0.1 "File"
- 	cordova-plugin-firebasex 6.0.6 "Google Firebase Plugin"
- 	cordova-plugin-geolocation 4.0.2 "Geolocation"
- 	cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
- 	cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
- 	cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
- 	cordova-plugin-splashscreen 5.0.2 "Splashscreen"
- 	cordova-plugin-statusbar 2.4.3 "StatusBar"
- 	cordova-plugin-whitelist 1.3.4 "Whitelist"
- 	cordova-sqlite-storage 3.2.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
- 	cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
- 	cordova-support-google-services 1.3.1 "cordova-support-google-services"

System:

   Android SDK Tools : 26.1.1
   NodeJS            : v10.15.1
   npm               : 2.15.12
   OS                : Windows 10
        

**Related code:**
```
let tell= "+972" + ddd + phoneNumber;
(<any>window).FirebasePlugin.verifyPhoneNumber(tell, 60, (credential) => {
       alert("SMS sent!");
      this.verificationId = credential.verificationId;
   }, (error) => {
      console.error(error);
      alert(error);
      });
```

**Console output**
<details>
<summary>ERROR TypeError: Cannot read property 'verifyPhoneNumber' of undefined</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**
It's an Ionic 3 app, not tested on iOS yet (only on Android for now).

**Comment by dpa99c** [comment]
Ionic Lab is a browser emulation of the Android environment and as such Cordova plugins will not work with it. Please build and run the Cordova Android platform to produce a native Android app in order to test the functionality of this plugin.
